### ISSUE TITLE
[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由, 拒绝服务. 请登录OpenAI查看详情 https://platform.openai.com/signup[Bug]: 

### ISSUE THREAD

**Issue by Ryancheng236** [binary-husky/gpt_academic#1000]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

显示余额不足 这个应该怎么办呢

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/124876352/a4055b9c-64c8-4ce3-9099-35ea25408554)

**Comment by sjoeycookie** [comment]
我也遇见了同样的问题，想问一下您解决了吗

**Comment by shuyanCoding** [comment]
> 我也遇见了同样的问题，想问一下您解决了吗

**Comment by Cstardust** [comment]
请问解决了吗
