### ISSUE TITLE
[Bug]: 阿里云语音识别配置后无法使用

### ISSUE THREAD

**Issue by ZhangChunXian** [binary-husky/gpt_academic#1002]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

操作系统: Ubuntu 18.04
在配置好阿里云语音识别的appkey, accessky, secret后, 网站内的语音识别按键正常, 点击开始录制, 但是发出什么声音都没有输出.

### Screen Shot | 有帮助的截图

在录制音频的过程中, 不断输出以下报错
![001b0c41a0130975a25606908cb174c3](https://github.com/binary-husky/gpt_academic/assets/68273796/0349177d-d0fd-49bb-9d6b-f4abe809ddf1)

**Comment by ZhangChunXian** [comment]
不好意思,我自己看了一下, 截图里的报错, 好像和音频没有关系, 这是另外两个报错截图, 与ffmpeg有关
![0e879f0ec42b344c748e1d81a419bbca](https://github.com/binary-husky/gpt_academic/assets/68273796/70e3f914-935f-46dc-8aaa-caf8336a5311)
![b3818a0723b42534d05016151373b5b2](https://github.com/binary-husky/gpt_academic/assets/68273796/ece09536-8453-441d-a768-d6889b4be03b)

**Comment by binary-husky** [comment]
群里是你对吧😄第一个uuid的问题是初始化代码没执行？建议看看浏览器F12报错信息

第二个我猜是gradio或其相关的牵连依赖有关系
