### ISSUE TITLE
[Bug]: 二转api设置问题

### ISSUE THREAD

**Issue by fattank** [binary-husky/gpt_academic#1003]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我计划使用二转api的服务，在coonfig.py 按照要求设置如下：
API_KEY = "sk-UOnzh
API_URL_REDIRECT = {"https://aigptx.top/v1/"}
是不是我设置有问题？就是连不通。
但使用openai的可以，一连就通。openai这里什么都不写：
API_URL_REDIRECT = {}
请问我设置有错误吗？
谢谢

### Screen Shot | 有帮助的截图

无

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

无

**Comment by binary-husky** [comment]
API_URL_REDIRECT 格式不正确

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97

**Comment by bkzy333** [comment]
> https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97

但是在docker-compose.yaml中无法用json格式进行配置，docker-compose的环境变量仅支持纯文本格式。该如何改动呢？
以下代码会报错提示【API_URL_REDIRECT必须是字符串、数字、布尔值或 null。】
`    environment:
      API_KEY: 'sk-RQ1232134l,sk-Y435656x'
      API_URL_REDIRECT:{"https://api.openai.com/v1/chat/completions":"https://xxxx.yyyy.zzzz/v1/chat/completions"}
`
于是我改成以下代码，运行docker-compose up的时候没有报错，但环境变量API_URL_REDIRECT没有改动为第三方url
`services:
  gpt_academic_nolocalllms:
    environment:
      API_URL_REDIRECT: "https://api.openai.com/v1/chat/completions,https://api.chatanywhere.com.cn"
`
