### ISSUE TITLE
[Feature]: 有没有记录token的功能

### ISSUE THREAD

**Issue by fattank** [binary-husky/gpt_academic#1004]
### Class | 类型

程序主体

### Feature Request | 功能请求

由于这学术gpt多线程，还循环。花钱像流水，一会儿几刀就没了，而且还要借给被人用。所以非常希望有一个功能可以记录用了多少token，自少心里有数。
或者这个功能已经有了，我没发现。
又或者可以在哪个py里加一段代码，记录在日志里，该问题用了多少token。
非常感谢。

**Comment by binary-husky** [comment]
目前没有此功能，这种徒增焦虑的功能，我一直不愿意加

**Comment by fattank** [comment]
好吧，焦虑不是立刻有，就是看账单的时候有。
