### ISSUE TITLE
[Feature]: 能在提交button旁设置小按钮，点击可选择是否携带历史信息

### ISSUE THREAD

**Issue by logiccao** [binary-husky/gpt_academic#1006]
### Class | 类型

None

### Feature Request | 功能请求

能在提交button旁设置小按钮，点击可选择是否携带历史信息

可以像：https://github.com/Chanzhaoyu/chatgpt-web
中的
<img width="1204" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/35301893/cfc4052a-4893-40e5-bc78-3a5719227c62">

**Comment by binary-husky** [comment]
👍
