### ISSUE TITLE
[Feature]: 支持onnx模型

### ISSUE THREAD

**Issue by ValeriaWong** [binary-husky/gpt_academic#1008]
### Class | 类型

None

### Feature Request | 功能请求

- [x] chatglm-6B_onnx  纯CPU推理，最多仅需8GB内存
- [ ] pangu_alpha_onnx 纯cpu推理，4~5GB内存，推理速度极快，但对比现有模型如 百川-13B 生成效果欠佳

**Comment by binary-husky** [comment]
嗯嗯
