### ISSUE TITLE
Enhancement : 添加zotero接口

### ISSUE THREAD

**Issue by ValeriaWong** [binary-husky/gpt_academic#101]
如题，希望可以添加zotero接口，联动；

- [x] 在读文章写摘要.py 中添加支持pdf格式
- [ ] 增加多个文章片段之间的观点对比，文献综述等功能

根据现有drop文件利用zipfile或tarfile进行extract的实践来看（zipfile会出现中文乱码），可选方案有
- 对zotero的storage文件夹进行遍历后找到指定的pdf文件进行压缩后手动拖到界面的选项；
- 也有为zotero单独写一个py文件的选项

**Comment by binary-husky** [comment]
3Q

**Comment by ValeriaWong** [comment]
在使用pdf中发现批量总结pdf脚本有如下可优化的点：

- [ ] 调用api，支持图像pdf、公式的ocr
- [ ] prompt可优化，借鉴仓库chatpaper
- [ ] 可添加批量翻译pdf的功能

有一些未想到解决方案的困难如下：
-  某些图像pdf在页面左部及顶部的排版内容属于无效信息，有时会影响内容输出，此前实践是将其进行裁剪后再进行ocr识别，但裁剪的尺度并不能放之四海皆准
