### ISSUE TITLE
[Bug]:4.0 json解析不合常规 

### ISSUE THREAD

**Issue by JacksonTang99** [binary-husky/gpt_academic#1011]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

3.5 可以用
4.0 json解析不合常规，异常data

### Screen Shot | 有帮助的截图

![_`YZT I@KE1FH}I N2} ILB](https://github.com/binary-husky/gpt_academic/assets/128497189/927102ef-e54f-416c-a952-0220e22cee26)
![RF {_B1CL48G}{0VD}HB~BX](https://github.com/binary-husky/gpt_academic/assets/128497189/a003325b-d832-4aac-84b4-87fcd01088c5)
![TN@TU%L}4AZWLOA7OJPHSK8](https://github.com/binary-husky/gpt_academic/assets/128497189/e5dc41e7-8295-4fb3-b348-199b27a8877a)

**Comment by binary-husky** [comment]
非官方源

**Comment by binary-husky** [comment]
什么中间商

**Comment by JacksonTang99** [comment]
是第三方的，在tb买的，有没有官方源推荐啊，tb都是第三方，国内小白很受伤/(ㄒoㄒ)/~~

**Comment by binary-husky** [comment]
小白的话可以One API、api2d、OpenAI-SB，这些都可以按量购买

**Comment by binary-husky** [comment]
价格比较贵，但好在用多少买多少，没坑

**Comment by JacksonTang99** [comment]
好的，谢谢
