### ISSUE TITLE
[Feature]: 是否支持导入翻译术语表功能？

### ISSUE THREAD

**Issue by fzyj99** [binary-husky/gpt_academic#1015]
### Class | 类型

其他

### Feature Request | 功能请求

您好，请问您这边在翻译时，能否导入术语表？因为chatgpt对一些专业术语，尤其是法律术语不太敏感，翻译的较差。请问是否可以向Deepl一样，根据本地提供的术语表来翻译呢？

**Comment by binary-husky** [comment]
试试写在system prompt中？
