### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Harintton** [binary-husky/gpt_academic#1017]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

首先我是个小白，安装完全是按照规定的安装步骤来的。我使用Anaconda Powershell Prompt安装最新的requirements.txt，文件中包含了gradio 3.32.2版本，但是最后一步运行main.py时，出现了ModuleNotFoundError: No module named 'gradio'，请教一下现在应该如何解决这个问题。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/141337052/c4804253-5618-4ee3-ba7a-d3e9bf89d1ca)
![image](https://github.com/binary-husky/gpt_academic/assets/141337052/8887b6ac-cbce-4d57-8279-be14481893f6)

**Comment by binary-husky** [comment]
多个python冲突
