### ISSUE TITLE
[Feature]: 支持自定义chatglm模型位置

### ISSUE THREAD

**Issue by xy3xy3** [binary-husky/gpt_academic#1023]
### Class | 类型

大语言模型

### Feature Request | 功能请求

运行main.py需要重新下载模型
但是我已经下载到了其他目录 希望加个变量可以直接修改模型目录 如果目录有模型就不用重新下载

**Comment by xy3xy3** [comment]
已经知道如何自定义了：路径request_llm\bridge_chatglm.py
_model_name_改成绝对路径即可

**Comment by huitang96** [comment]
> 已经知道如何自定义了：路径request_llm\bridge_chatglm.py _model_name_改成绝对路径即可

在chatglm3中好像不行，我将权重下载到一个文件，修改了_model_name_，并没有反应，可以协助解决吗
