### ISSUE TITLE
[Bug]: 多线程翻译pdf有大段漏翻

### ISSUE THREAD

**Issue by vegetex** [binary-husky/gpt_academic#1027]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

感觉pdf翻译的截断位置有点不合理，在截图提供的例子里非常明显，而且试了很多次都只能翻译到这里。用引用文献39的位置做了简单标记。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/141477904/1ed3182c-41c9-49d9-8740-97e11cf7d933)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

https://doi.org/10.1364/AO.53.000748

**Comment by binary-husky** [comment]
谢谢反馈

**Comment by binary-husky** [comment]
支持借助GROBID实现PDF高精度翻译
 https://github.com/binary-husky/gpt_academic/commit/ec76d3dcc4c5b8dc514e25a6305f9ff0828623dd
