### ISSUE TITLE
[Feature]: 隐藏用户输入记录，只保留ai回答内容

### ISSUE THREAD

**Issue by runcheng-yang** [binary-husky/gpt_academic#1028]
### Class | 类型

程序主体

### Feature Request | 功能请求

您好，很感谢提供一个这么好用的工具。
想请教一下，应该对什么内容进行调整，可以使得聊天记录页面只显示ai回答的内容，不显示用户输入的记录和预置的提示词模板

**Comment by binary-husky** [comment]
这个有点麻烦，https://github.com/binary-husky/gpt_academic/blob/71c692dcefc8ff647f6fc1a5ecffe30ea7efef56/toolbox.py#L396，改这个函数

**Comment by runcheng-yang** [comment]
十分感谢，我去试着修改一下。
不过在等待期间我找了另一种办法：【还存在一些不稳定&应该是只能修改gpt接口的回复】
修改 bridge_chatgpt的输出返回，让页面始终显示我需要的回复语，并隐藏用户输入的内容
![屏幕截图 2023-08-13 085118](https://github.com/binary-husky/gpt_academic/assets/83591156/0dd32f31-c06d-48de-8970-6e6aadc4bc3d)

**Comment by runcheng-yang** [comment]
十分感谢，我去试着修改一下。
不过在等待期间我找了另一种办法：【还存在一些不稳定&应该是只能修改gpt接口的回复】
修改 bridge_chatgpt的输出返回，让页面始终显示我需要的回复语，并隐藏用户输入的内容
![屏幕截图 2023-08-13 085118](https://github.com/binary-husky/gpt_academic/assets/83591156/e1ee98aa-a402-498b-a7be-bb5eaeb1f262)
