### ISSUE TITLE
代理出错

### ISSUE THREAD

**Issue by yang1111-gif** [binary-husky/gpt_academic#1029]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

我的代码是在服务器上跑的，clash是下载在笔记本上的，也就是windows系统，然后我在电脑上连接服务器跑代码。这是我的流程。
现在问题是，我配置代理的时候，一直出错，我用这个地址也出不行：
![image](https://github.com/binary-husky/gpt_academic/assets/71382201/3f98d4e9-e04f-4ed1-9d3e-9ff86070b4f9)
![image](https://github.com/binary-husky/gpt_academic/assets/71382201/9b60befe-f41f-486d-b295-901eb181172a)

然后我改成服务器的Ip和端口号，如下：
![image](https://github.com/binary-husky/gpt_academic/assets/71382201/2c2f5b56-1e0d-439f-a406-5b1e8926dae0)
ye'bu'xin也不行，请问我该怎么改？请大佬指教，谢谢。

### Screen Shot | 有帮助的截图

1

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

1

**Comment by binary-husky** [comment]
代理运行的地方不对

**Comment by yang1111-gif** [comment]
> 代理运行的地方不对

大佬请问下，我这种情况的代理运行在哪？我在本地跑，用代理，流程都是通的，放在服务器就出现上面的问题了。请指教，谢谢。
