### ISSUE TITLE
[Bug]: 希望更新hugging face平台代码

### ISSUE THREAD

**Issue by B3nDan** [binary-husky/gpt_academic#1030]
### Installation Method | 安装方法与平台

Huggingface

### Version | 版本

Others | 非最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

hugging face上的版本不支持设置API_URL_REDIRECT = {}参数
而github上的版本已经支持

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/129975925/984ab4f4-6c2e-4034-bb9d-7b0e26dc02d2)
![image](https://github.com/binary-husky/gpt_academic/assets/129975925/90ddcd40-37ac-48c7-a212-5a7334980499)

**Comment by binary-husky** [comment]
已更新
