### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by XXZDYKW** [binary-husky/gpt_academic#1031]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

按照要求安装后，运行 python main.py，报错 AttributeError: module 'os' has no attribute 'statvfs'

### Screen Shot | 有帮助的截图

![捕获](https://github.com/binary-husky/gpt_academic/assets/47839014/0b85f7a1-eea5-47e5-80dc-73362a8c51a7)

**Comment by binary-husky** [comment]
一键安装脚本亦正常工作
