### ISSUE TITLE
[Bug]: 我把服务部署在HK环境下，从大陆访问，总会卡在这个js加载的地方

### ISSUE THREAD

**Issue by caohangabc** [binary-husky/gpt_academic#1033]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

我把服务部署在HK环境下，从大陆本地访问，总会卡在这个js加载的地方，无法进入主页

### Screen Shot | 有帮助的截图

<img width="1196" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/35301893/b7d381b4-f4ff-4a0c-9a5f-ab84d36f8cf2">

**Comment by caohangabc** [comment]
这个api请求超时， 导致页面卡在loading2分钟
https://gradio-space-api-fetcher-v2.hf.space/api

**Comment by zpp800** [comment]
就是说我也有这个问题

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/77268c13-e09b-4e23-821c-c44efd240c2d)
换一下浏览环境？

**Comment by zpp800** [comment]
> ![图像](https://user-images.githubusercontent.com/96192199/260205799-77268c13-e09b-4e23-821c-c44efd240c2d.png) 换一下浏览环境？

好像不是浏览环境的问题吧？

**Comment by zpp800** [comment]
> ![图像](https://user-images.githubusercontent.com/96192199/260205799-77268c13-e09b-4e23-821c-c44efd240c2d.png) 换一下浏览环境？

应该是那个gradio版本问题，不稳定，

**Comment by caohangabc** [comment]
我解决了这个问题，确实是gradio的问题， 得找到了对应的js文件，禁止了超时的那个请求

1. 找到index-c7d10e24.js， 在python的包目录：site-packages/gradio/templates/frontend/assets/index-c7d10e24.js
2.将js文件中的: fetch("https://gradio-space-api-fetcher-v2.hf.space/api",{method:"POST",body:JSON.stringify({serialize:!1,config:JSON.stringify(b)}),headers:q})
替换成：fetch(`${b.root}/info`,{headers:q})

**Comment by binary-husky** [comment]
> > ![图像](https://user-images.githubusercontent.com/96192199/260205799-77268c13-e09b-4e23-821c-c44efd240c2d.png) 换一下浏览环境？
> 
> 应该是那个gradio版本问题，不稳定，

用的是项目内置gradio的版本吗？还是下载的新版？

**Comment by caohangabc** [comment]
> > > ![图像](https://user-images.githubusercontent.com/96192199/260205799-77268c13-e09b-4e23-821c-c44efd240c2d.png) 换一下浏览环境？
> > 
> > 
> > 应该是那个gradio版本问题，不稳定，
> 
> 用的是项目内置gradio的版本吗？还是下载的新版？

我用的是项目 requirements.txt 中gradio的版本

**Comment by zpp800** [comment]
&nbsp;python的包目录&nbsp; &nbsp;我找不见呀&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;site-packages/gradio/templates/frontend/assets/index-c7d10e24.js



找到的这两个打开也查不到&nbsp;fetch("https://gradio-space-api-fetcher-v2.hf.space/api",{method:"POST",body:JSON.stringify({serialize:!1,config:JSON.stringify(b)}),headers:q})这个


大佬教教我



寒夕
***@***.***







                       
原始邮件
                       
                     

发件人："caohangabc"< ***@***.*** &gt;;

发件时间：2023/8/12 18:24

收件人："binary-husky/gpt_academic"< ***@***.*** &gt;;

抄送人："zpp"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [binary-husky/gpt_academic] [Bug]: 我把服务部署在HK环境下，从大陆访问，总会卡在这个js加载的地方 (Issue #1033)




 
我解决了这个问题，确实是gradio的问题， 得找到了对应的js文件，禁止了超时的那个请求
 
找到index-c7d10e24.js， 在python的包目录：site-packages/gradio/templates/frontend/assets/index-c7d10e24.js
 2.将js文件中的: fetch("https://gradio-space-api-fetcher-v2.hf.space/api",{method:"POST",body:JSON.stringify({serialize:!1,config:JSON.stringify(b)}),headers:q})
 替换成：fetch(${b.root}/info,{headers:q})

**Comment by zpp800** [comment]
终于找到了，替换了之后就成这样了&nbsp; info 401&nbsp; &nbsp; 不过不会卡住，访问速度变快了，我就喜欢较真的感觉。哈哈哈！ 感谢大佬



寒夕
***@***.***







                       
原始邮件
                       
                     

发件人："caohangabc"< ***@***.*** &gt;;

发件时间：2023/8/12 18:24

收件人："binary-husky/gpt_academic"< ***@***.*** &gt;;

抄送人："zpp"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [binary-husky/gpt_academic] [Bug]: 我把服务部署在HK环境下，从大陆访问，总会卡在这个js加载的地方 (Issue #1033)




 
我解决了这个问题，确实是gradio的问题， 得找到了对应的js文件，禁止了超时的那个请求
  
找到index-c7d10e24.js， 在python的包目录：site-packages/gradio/templates/frontend/assets/index-c7d10e24.js
 2.将js文件中的: fetch("https://gradio-space-api-fetcher-v2.hf.space/api",{method:"POST",body:JSON.stringify({serialize:!1,config:JSON.stringify(b)}),headers:q})
 替换成：fetch(${b.root}/info,{headers:q})
