### ISSUE TITLE
[Feature]: 希望加入百度文心千帆的api

### ISSUE THREAD

**Issue by xy3xy3** [binary-husky/gpt_academic#1035]
### Class | 类型

None

### Feature Request | 功能请求

API文档地址：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Nlks5zkzu
api价格：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Blfmc9dlf
目前使用一些模型是免费的：https://cloud.baidu.com/doc/WENXINWORKSHOP/s/2lktec9ey
<html>
<body>

模型名称 | 描述
-- | --
Linly-Chinese-LLaMA-2-7B | 由深圳大学CV研究所Linly项目进行中文增强训练的7b参数版本
Llama-2-7b-chat | Llama-2-7b-chat是高性能原生开源版本
Linly-Chinese-LLaMA-2-13B | 由深圳大学CV研究所Linly项目进行中文增强训练的13b参数版本
Llama-2-13b-chat | Llama-2-13b-chat是性能与效果均衡的原生开源版本
Llama-2-70b-chat | Llama-2-70b-chat是高精度效果的原生开源版本
ChatGLM2-6B | 智谱AI与清华KEG实验室发布的中英双语对话模型
RWKV-4-World | 由香港大学物理系校友彭博研发并开源，结合了Transformer与RNN的优点，具备优秀的推理性能与效果
OpenLLaMA-7B | 在Meta AI研发的Llama模型基础上，OpenBuddy进行调优，涵盖了更广泛的词汇、通用字符与token嵌入，具备与Llama相当的性能与推理效果
Falcon-7B | 由TII研发、在用精选语料库增强的1500B token上进行训练
Dolly-12B | 由Databricks训练的指令遵循大语言模型
MPT-7B | 一种短格式指令遵循模型，由MosaicML研发，基于MPT-7B模型在Databricks Dolly-15k、HH-RLHF数据集上调优的版本，采用经过修改的仅使用解码器的transformer架构

</body>
</html>模型名称	描述
[Linly-Chinese-LLaMA-2-7B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/qlkqu3j29)	由深圳大学CV研究所Linly项目进行中文增强训练的7b参数版本
[Llama-2-7b-chat](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Rlki1zlai)	Llama-2-7b-chat是高性能原生开源版本
[Linly-Chinese-LLaMA-2-13B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/ulkqu7kvl)	由深圳大学CV研究所Linly项目进行中文增强训练的13b参数版本
[Llama-2-13b-chat](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/2lki2us1e)	Llama-2-13b-chat是性能与效果均衡的原生开源版本
[Llama-2-70b-chat](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/8lkjfhiyt)	Llama-2-70b-chat是高精度效果的原生开源版本
[ChatGLM2-6B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/ilkqu9pib)	智谱AI与清华KEG实验室发布的中英双语对话模型
[RWKV-4-World](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/plkque69d)	由香港大学物理系校友彭博研发并开源，结合了Transformer与RNN的优点，具备优秀的推理性能与效果
[OpenLLaMA-7B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Ylkquk74n)	在Meta AI研发的Llama模型基础上，OpenBuddy进行调优，涵盖了更广泛的词汇、通用字符与token嵌入，具备与Llama相当的性能与推理效果
[Falcon-7B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/nlkqulm5g)	由TII研发、在用精选语料库增强的1500B token上进行训练
[Dolly-12B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/clkquqy0d)	由Databricks训练的指令遵循大语言模型
[MPT-7B](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/2lkqurg0f)	一种短格式指令遵循模型，由MosaicML研发，基于MPT-7B模型在Databricks Dolly-15k、HH-RLHF数据集上调优的版本，采用经过修改的仅使用解码器的transformer架构

**Comment by binary-husky** [comment]
这个好啊，适合国内用

**Comment by for3ever3** [comment]
> 这个好啊，适合国内用
速度爆肝出来，大牛

**Comment by CNZedChou** [comment]
> 这个好啊，适合国内用

科大讯飞星火认知大模型最近也在搞API测试。免费发放1年有效的1000000token（大概就是18块的额度）。

[星火认知大模型Web文档](https://www.xfyun.cn/doc/spark/Web.html)
[API测试申请入口](https://www.xfyun.cn/solutions/xinghuoAPI)

**Comment by binary-husky** [comment]
> > 这个好啊，适合国内用
> 
> 科大讯飞星火认知大模型最近也在搞API测试。免费发放1年有效的1000000token（大概就是18块的额度）。
> 
> [星火认知大模型Web文档](https://www.xfyun.cn/doc/spark/Web.html) [API测试申请入口](https://www.xfyun.cn/solutions/xinghuoAPI)

星火已经接入了

**Comment by binary-husky** [comment]
@xy3xy3 @CNZedChou @for3ever3 @HougeLangley [百度文心千帆的api]已接入
