### ISSUE TITLE
[Bug]: 配置了key不能shi用很奇怪

### ISSUE THREAD

**Issue by wxyhgk** [binary-husky/gpt_academic#1037]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

我配置了第三方key，可是说我没有配置key很奇怪，

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/37659181/330c3f55-e120-418f-b2dd-e45323875199)

![image](https://github.com/binary-husky/gpt_academic/assets/37659181/6e892476-fb6d-4476-be40-39c060ca471e)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

![image](https://github.com/binary-husky/gpt_academic/assets/37659181/35aa2532-1ff9-4e1b-8b2b-90257cbe9cc6)

**Comment by wcgXi** [comment]
我用的3.5官方的API key 也是不行

**Comment by binary-husky** [comment]
看wiki 
https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97
