### ISSUE TITLE
[Bug]: NotOpenSSLWarning

### ISSUE THREAD

**Issue by grothen** [binary-husky/gpt_academic#1039]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Others | 非最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

“/Users/xxx/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020”
其他好像没有报错，但是界面一直处在queue 1/1 | xxx s的状态

### Screen Shot | 有帮助的截图

![CleanShot 2023-08-13 at 21 10 03@2x](https://github.com/binary-husky/gpt_academic/assets/3252576/fe294400-67b3-40bd-9389-713be8b42f1f)

**Comment by grothen** [comment]
还有一个warning：
“None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
”

**Comment by binary-husky** [comment]
> 还有一个warning： “None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used. ”

这个警告忽略即可

**Comment by binary-husky** [comment]
安装过程遇到什么readme里面没写的特殊情况吗？一键安装脚本是否尝试过？

**Comment by grothen** [comment]
我是换了电脑，原来电脑一点问题没有，新电脑就不行😂我试试一键安装
