### ISSUE TITLE
[Bug]: 使用第三方API KEY返回跟openai的一模一样，但是由于已经流式输出，在界面上解析不了，只能用没有界面的正常输出

### ISSUE THREAD

**Issue by williamzhao95** [binary-husky/gpt_academic#1041]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用第三方API KEY返回跟openai的一模一样，但是由于已经流式输出，在界面上解析不了，只能用没有界面的正常输出，错误显示为JSON解析不符合常规，终端显示已返回结果

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/18749483/8a891821-5493-44b4-b3dc-e3e61eafb4d3)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

![image](https://github.com/binary-husky/gpt_academic/assets/18749483/8bb3e484-9866-44fd-91f9-a6ccd838aee7)
![image](https://github.com/binary-husky/gpt_academic/assets/18749483/e1715037-ee26-4266-9596-294813a4038c)

**Comment by williamzhao95** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/18749483/4eaa367d-58cf-4801-8886-78df0937753b)

**Comment by binary-husky** [comment]
哪个第三方呀？

**Comment by binary-husky** [comment]
？

**Comment by williamzhao95** [comment]
就是别人封装的类openai的api，返回的直接是流式的，nogui的函数就可以很好的解析，调用多线程的都可以正常运行，界面的predict就显示解析错误

**Comment by williamzhao95** [comment]
> 


就是别人封装的类openai的api，返回的直接是流式的，nogui的函数就可以很好的解析，调用多线程的都可以正常运行，界面的predict就显示解析错误

**Comment by binary-husky** [comment]
不告诉哦哪个第三方，我也没法解决呀

**Comment by williamzhao95** [comment]
https://gptgod.online/api/v1/chat/completions，这个用多线程的是正常的，可能返回的时候一下子全返回了

**Comment by williamzhao95** [comment]
> 

[https://gptgod.online/api/v1/chat/completions，这个用多线程的是正常的，可能返回的时候一下子全返回了](https://gptgod.online/api/v1/chat/completions%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%94%A8%E5%A4%9A%E7%BA%BF%E7%A8%8B%E7%9A%84%E6%98%AF%E6%AD%A3%E5%B8%B8%E7%9A%84%EF%BC%8C%E5%8F%AF%E8%83%BD%E8%BF%94%E5%9B%9E%E7%9A%84%E6%97%B6%E5%80%99%E4%B8%80%E4%B8%8B%E5%AD%90%E5%85%A8%E8%BF%94%E5%9B%9E%E4%BA%86)

**Comment by Kiyliy** [comment]
现在大多数用的都是one-api的第三方

**Comment by Kiyliy** [comment]
我找到一个解决办法了()
status_text = f"finish_reason: {chunkjson['choices'][0].get('finish_reason', 'null')}"
改成这样就好了 , 检测不到这个finish_reason, 那就自动返回null

**Comment by binary-husky** [comment]
> finish_reason

谢谢，代码已修改

**Comment by williamzhao95** [comment]
已解决
