### ISSUE TITLE
[Bug]: 讯飞星火的配置项没加入config,不知道怎么写,也不能选择

### ISSUE THREAD

**Issue by maxadc** [binary-husky/gpt_academic#1043]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

如题

### Screen Shot | 有帮助的截图

-

**Comment by binary-husky** [comment]
把  LLM_MODEL = 'spark' 即可
本项目中所有的配置都列举在config一个文件中，不会放到其他地方

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/a7ced9e4-6f81-4a0f-ae07-5fb0d05f621b)

**Comment by breadabo** [comment]
我配置了“spark”，也配置了对应的api key，但是选择讯飞模型后，提问似乎无法正常得到反馈信息。
![QQ截图20230818124047](https://github.com/binary-husky/gpt_academic/assets/62640339/a6380277-f31d-41f4-817b-95f9d1e09394)

**Comment by breadabo** [comment]
问题解决。原来光创建应用还不行，还要单独发工单申请到API测试资格才可以。不过现在的问题是网页默认调用的似乎是星火大模型V1.5，不知道怎样设置才能改成调用V2.0

**Comment by binary-husky** [comment]
在线大模型配置关联关系示意图
│
├── "gpt-3.5-turbo" 等openai模型
│   ├── API_KEY
│   ├── CUSTOM_API_KEY_PATTERN（不常用）
│   ├── API_ORG（不常用）
│   └── API_URL_REDIRECT（不常用）
│
├── "azure-gpt-3.5" 等azure模型
│   ├── API_KEY
│   ├── AZURE_ENDPOINT
│   ├── AZURE_API_KEY
│   ├── AZURE_ENGINE
│   └── API_URL_REDIRECT
│
├── "spark" 星火认知大模型
│   ├── XFYUN_APPID
│   ├── XFYUN_API_SECRET
│   └── XFYUN_API_KEY
│
├── "claude-1-100k" 等claude模型
│   └── ANTHROPIC_API_KEY
│
├── "stack-claude"
│   ├── SLACK_CLAUDE_BOT_ID
│   └── SLACK_CLAUDE_USER_TOKEN
│
├── "qianfan" 百度千帆大模型库
│   ├── BAIDU_CLOUD_QIANFAN_MODEL
│   ├── BAIDU_CLOUD_API_KEY
│   └── BAIDU_CLOUD_SECRET_KEY
│
├── "newbing" Newbing接口不再稳定，不推荐使用
    ├── NEWBING_STYLE
    └── NEWBING_COOKIES

**Comment by applepieiris** [comment]
> 我配置了“spark”，也配置了对应的api key，但是选择讯飞模型后，提问似乎无法正常得到反馈信息。 ![QQ截图20230818124047](https://user-images.githubusercontent.com/62640339/261502315-a6380277-f31d-41f4-817b-95f9d1e09394.jpg)

我也是
