### ISSUE TITLE
[Bug]: 无法卸载，在控制面板的卸载应用中找不到该软件！Unable to uninstall

### ISSUE THREAD

**Issue by oykang** [binary-husky/gpt_academic#1044]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

the software cannot be found in the Uninstall application in the Control Panel!

### Screen Shot | 有帮助的截图

the software cannot be found in the Uninstall application in the Control Panel!

**Comment by binary-husky** [comment]
把文件夹删除即可

**Comment by yingzhige00** [comment]
> 把文件夹删除即可

但是，删除之后我的C盘莫名奇妙的少了些空间，这个程序在C盘中做了什么
