### ISSUE TITLE
[Bug]: Arxiv论文精细翻译结果中，最为关键的转化PDF编译失败。

### ISSUE THREAD

**Issue by solthx** [binary-husky/gpt_academic#1045]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

[2023-08-16-17-46-59-2023-08-16-17-46-58-result.zip](https://github.com/binary-husky/gpt_academic/files/12358081/2023-08-16-17-46-59-2023-08-16-17-46-58-result.zip)

提示：虽然PDF生成失败了, 但请查收结果（压缩包）, 内含已经翻译的Tex文档, 也是可读的, 您可以到Github Issue区, 用该压缩包+对话历史存档进行反馈 ...

### Screen Shot | 有帮助的截图

<img width="1772" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/27994326/ca02f8db-5851-4b12-80c6-d2e3298d20d1">
<img width="1724" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/27994326/0d7e6c65-ec76-4f74-9a1f-56d99ffb8713">

**Comment by binary-husky** [comment]
你系统缺字体 !pdfTeX error: pdflatex (file simkai.ttf): cannot open TrueType font file for reading

**Comment by binary-husky** [comment]
simkai是楷体吧？建议换个电脑，字体问题不容易解决
