### ISSUE TITLE
[Bug]: 在线联网功能无法正常运行

### ISSUE THREAD

**Issue by flashszn** [binary-husky/gpt_academic#1049]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在线联网功能无法正常运行，我尝试了在线联网功能，我发现它们并不会去搜索。
我尝试打印了中间history 的值，发现是空值[]。
# ------------- < 第1步：爬取搜索引擎的结果 > -------------
    from toolbox import get_conf
    proxies, = get_conf('proxies')
    urls = google(txt, proxies)
    history = []
    print(history )

    # ------------- < 第2步：依次访问网页 > -------------
    max_search_result = 10   # 最多收纳多少个网页的结果
    for index, url in enumerate(urls[:max_search_result]):
        res = scrape_text(url['link'], proxies)
        history.extend([f"第{index}份搜索结果：", res])
        chatbot.append([f"第{index}份搜索结果：", res[:500]+"......"])
        yield from update_ui(chatbot=chatbot, history=history) # 刷新界面 # 由于请求gpt需要一段时间，我们先及时地做一次界面更新

### Screen Shot | 有帮助的截图

![bug](https://github.com/binary-husky/gpt_academic/assets/105858279/4c65f9c1-5340-43b0-9639-5f358676794a)

**Comment by dalerxli** [comment]
您好！您的邮件已收到，谢谢。

**Comment by binary-husky** [comment]
是否配置了代理呢？

**Comment by flashszn** [comment]
> 是否配置了代理呢？

配置了

**Comment by flashszn** [comment]
> 是否配置了代理呢？

我尝试打印了中间的过程，发现：
for index, url in enumerate(urls[:max_search_result]):
这个循环根本不会被进行

**Comment by flashszn** [comment]
问题已经解决，问题的原因是因为我使用的代理可能被谷歌列入了反爬黑名单，在更换代理后，联网功能可以正常使用。
