### ISSUE TITLE
论文优化只能一段一段复制进去吗？ 不支持word文档直接上传上去一次性优化吗？

### ISSUE THREAD

**Issue by xuedafei** [binary-husky/gpt_academic#105]

**Comment by xuedafei** [comment]
复制字数多了，还会显示文本太长处理不了，我知道这是chatgpt的问题。但是一段一段复制进去，chatgpt就不能全局理解后给出优化了，它只能一块一块的优化吧，这样优化感觉不靠谱啊

**Comment by binary-husky** [comment]
Any suggestion?

**Comment by xuedafei** [comment]
> 
用户上传整个文件后，不能用程序把文件拆分，分段调用api吗？然后再整体吐出优化后的结果、优化原因之类的。
这样才是一键优化

**Comment by xuedafei** [comment]
> Any suggestion?
用户上传整个文件后，不能用程序把文件拆分，分段调用api吗？然后再整体吐出优化后的结果、优化原因之类的。
这样才是一键优化

**Comment by xuedafei** [comment]
> Any suggestion?

用户上传整个文件后，不能用程序把文件拆分，分段调用api吗？然后再整体吐出优化后的结果、优化原因之类的。
这样才是一键优化

**Comment by LYP857** [comment]
他写论文都靠谱，引用文章都搜不到的，害，鸡肋

**Comment by LYP857** [comment]
他写文章都不靠谱的，引用文章都不靠谱，引用文章找不到的，这个要是写论文，为什么不直接去chatgpt问就好了，有啥区别吗，还省事，没必要
