### ISSUE TITLE
[Bug]: 报错exceed  current quota但在官网可正常提问，查询账户仍有余额，更换其他账号的API key也不行

### ISSUE THREAD

**Issue by aquens** [binary-husky/gpt_academic#1052]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

报错You exceeded your current quota, please check your plan and billing details
之前都能正常使用，gptac报错后去官网也能正常提问，查询发现账户仍有余额。更换了另一个账号的API key也不行

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/115077064/b087758c-af37-4863-a15b-6dac1f0aa29f)

**Comment by binary-husky** [comment]
这个就是没有余额，很清晰

另外你是不是api key配置没生效？

**Comment by LongruiDong** [comment]
> ### Installation Method | 安装方法与平台
> Pip Install (I ignored requirements.txt)
> 
> ### Version | 版本
> Latest | 最新版
> 
> ### OS | 操作系统
> Windows
> 
> ### Describe the bug | 简述
> 报错You exceeded your current quota, please check your plan and billing details 之前都能正常使用，gptac报错后去官网也能正常提问，查询发现账户仍有余额。更换了另一个账号的API key也不行
> 
> ### Screen Shot | 有帮助的截图
> ![image](https://user-images.githubusercontent.com/115077064/262249885-b087758c-af37-4863-a15b-6dac1f0aa29f.png)
> 
> ### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）
> _No response_

遇到同样的问题 你解决了吗

**Comment by aquens** [comment]
大概确实是余额不够了，没有做什么操作，过了一个月又好了。（但是此前官网查询有余额且也仍然能正常使用）
