### ISSUE TITLE
[Feature]: 希望接入one-api这个项目

### ISSUE THREAD

**Issue by flashszn** [binary-husky/gpt_academic#1054]
### Class | 类型

程序主体

### Feature Request | 功能请求

希望模型请求直接通过one-api这个项目来代理。

one-api是一个api整合项目，通过这个项目的反代理，可以像使用gpt系列的/v1/completion接口一样调用国内的大模型，仅仅需要更改一下模型名字。

项目地址：https://github.com/songquanpeng/one-api

因而，仅仅在chatcompletion这个类中加入one-api项目支持的国内模型即可以调用国内大模型。

这样每次更新新的模型就不需要写新的请求函数了，直接增加one-api所对应的模型名字即可

**Comment by binary-husky** [comment]
早就支持了，修改一下API_URL_REDIRECT就行
