### ISSUE TITLE
[Feature]: 星火大模型V2.0怎么调用

### ISSUE THREAD

**Issue by for3ever3** [binary-husky/gpt_academic#1057]
### Class | 类型

大语言模型

### Feature Request | 功能请求

在同一个应用里，我发现1.5和2.0的服务接口认证信息ID等等信息都是一样的，
如1.5的APPID为
ee***
APISecret
Njg3Z*********************************
APIKey
93ffb*********************************

2.0的也是一样的，默认是调用1.5的模型，扣的也是1.5的token，2.0的token没扣，请问怎么去选择调用2.0的模型呢

**Comment by CNZedChou** [comment]
好像只要改接口地址和domain参数？
> ws(s)://spark-api.xf-yun.com/v2.1/chat
> 星火大模型V2请求地址，对应的domain参数为generalv2

**Comment by binary-husky** [comment]
可以直接用v2取代v1吗

**Comment by CNZedChou** [comment]
在[星火认知大模型Web文档](https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)里，写修改这两项可以使用v2
我改了**接口地址** 和 参数中的**domain改为generalv2**，就可以使用。
[com_sparkapi.py-接口地址](https://github.com/binary-husky/gpt_academic/blob/19bd0c35ed05e6f99c8e3c0a8c994b1385341cae/request_llm/com_sparkapi.py#L65)、[com_sparkapi.py-domain参数]( https://github.com/binary-husky/gpt_academic/blob/19bd0c35ed05e6f99c8e3c0a8c994b1385341cae/request_llm/com_sparkapi.py#L170C34-L170C34)

**Comment by for3ever3** [comment]
> 在[星火认知大模型Web文档](https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)里，写修改这两项可以使用v2 我改了**接口地址** 和 参数中的**domain改为generalv2**，就可以使用。 [com_sparkapi.py-接口地址](https://github.com/binary-husky/gpt_academic/blob/19bd0c35ed05e6f99c8e3c0a8c994b1385341cae/request_llm/com_sparkapi.py#L65)、[com_sparkapi.py-domain参数](https://github.com/binary-husky/gpt_academic/blob/19bd0c35ed05e6f99c8e3c0a8c994b1385341cae/request_llm/com_sparkapi.py#L170C34-L170C34)
成功调用

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/116b7ce12fa90b1488fe5cde3773b9b96eb46873

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/d547073e-7f70-411d-beb4-a7af2fb37dcd)
LLM_MODEL = sparkv2

**Comment by applepieiris** [comment]
有哪位大佬知道我用的官网给的代码，运行test.py报错，根本跑不了。

`error: Handshake status 403 Forbidden -+-+- {'date': 'Fri, 08 Sep 2023 05:27:55 GMT', 'content-type': 'application/json; charset=utf-8', 'connection': 'keep-alive', 'content-length': '114', 'server': 'kong/1.3.0'} -+-+- b'{"message":"HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication"}'`

**Comment by zdevc** [comment]
> 有哪位大佬知道我用的官网给的代码，运行test.py报错，根本跑不了。
> 
> `error: Handshake status 403 Forbidden -+-+- {'date': 'Fri, 08 Sep 2023 05:27:55 GMT', 'content-type': 'application/json; charset=utf-8', 'connection': 'keep-alive', 'content-length': '114', 'server': 'kong/1.3.0'} -+-+- b'{"message":"HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication"}'`

你的本地时间有问题，和星火大模型的服务器相差5分钟就会报错
在你本地同步一下当前时间，比如linux下执行：
sudo /usr/sbin/ntpdate -u cn.pool.ntp.org
