### ISSUE TITLE
[Bug]: 使用python main.py运行时对话会吞掉最前面的第一个汉字或者单词

### ISSUE THREAD

**Issue by KenlesVime** [binary-husky/gpt_academic#1063]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

很奇怪，使用python main.py运行时对话会吞掉最前面的第一个汉字或者单词，使用docker-compose部署则不会

### Screen Shot | 有帮助的截图

https://i.postimg.cc/fRyYhwWB/023f141f381e63f9a12e766cae5766f.png

**Comment by binary-husky** [comment]
第三方api的问题，最新代码已修复

**Comment by KenlesVime** [comment]
没有使用git clone，直接下载最新代码的zip包传到服务器运行，已解决
