### ISSUE TITLE
[Bug]: 很抱歉，但我没有办法访问或解析私人上传的文件。有其他什么我可以帮助你的吗？

### ISSUE THREAD

**Issue by freedomspiritJohn** [binary-husky/gpt_academic#1064]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在demo网站复制空间后上传了个PDF文件，然后显示不能读取这个文件

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/129288685/23c78ccb-e636-4c5d-818d-8faafbe07414)

**Comment by binary-husky** [comment]
读readme
