### ISSUE TITLE
[Bug]: Linux, PDF生成失败

### ISSUE THREAD

**Issue by Dr-Joseph-Zhou** [binary-husky/gpt_academic#1065]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

PDF生成失败，本地上传再次失效。可能是本地latex部署不成功？或缺失字体？

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/66234152/3bc126b0-23e8-4af7-93ee-8e4be7bad323)
![image](https://github.com/binary-husky/gpt_academic/assets/66234152/8c0a4e81-9a1e-41ee-8d26-4e9d4d919be6)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

[2023-08-28-22-13-17-2023-08-28-22-13-16-result.zip](https://github.com/binary-husky/gpt_academic/files/12454861/2023-08-28-22-13-17-2023-08-28-22-13-16-result.zip)

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/6d5d5b61-cb12-4a1b-b70d-4ad2c66ba7d3)

**Comment by binary-husky** [comment]
大概率是缺字体，先close了，有需要在重新open吧
