### ISSUE TITLE
[Bug]: json 解析错误

### ISSUE THREAD

**Issue by VectorZhao** [binary-husky/gpt_academic#1066]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

今天看着支持了更精确的pdf翻译功能，于是便更新了镜像。配置了GROBID_URLS，HUGGINGFACE_ACCESS_TOKEN，更新结束后试用一下，翻译效果翻倍。然后之后聊天就一直出现json异常的错误。搜了一下issue，是非正规渠道的api引起的。

但是我目前配置的是azure的模型。配置了如下参数：
```
AZURE_ENDPOINT = "https://你亲手写的api名称.openai.azure.com/"
AZURE_API_KEY = "填入azure openai api的密钥"    # 建议直接在API_KEY处填写，该选项即将被弃用
AZURE_ENGINE = "填入你亲手写的部署名"            # 读 docs\use_azure.md
```
已经用了很长时间，从未出现过问题。

### Screen Shot | 有帮助的截图

<img width="1475" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/16644993/154e033a-95c4-46d7-a5ad-5077d86bce30">

**Comment by binary-husky** [comment]
之前一个兼容修正出了问题

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/2fa3d47887aebd1121d4b61d4a25b1780a0c5957
请确认是否得到修复

**Comment by VectorZhao** [comment]
镜像编译完成后测试

**Comment by binary-husky** [comment]
我测试了一下azure，应该已经修复了
