### ISSUE TITLE
[Bug]: 导入软件依赖失败。使用该模块需要额外依赖，安装方法pip install --upgrade pymupdf。

### ISSUE THREAD

**Issue by waifry** [binary-husky/gpt_academic#1067]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

使用pdf功能时候出现：导入软件依赖失败。使用该模块需要额外依赖，安装方法pip install --upgrade pymupdf。
word功能正常，其他都正常
只有这个pymupdf会提示导入软件依赖失败
我得系统可能有多个Python
默认使用的事conda, 切换到gpt设定的虚拟环境导入安装requirements.txt的库，并且库连接的是阿里的资源。

系统有安装conda 在base python和虚拟Python上都尝试过
pip list
***********
PyMuPDF                   1.23.1
PyMuPDFb                  1.23.0
***********

-------------------------------------------------------------------------------
(gpt) ➜  gpt_academic git:(master) ✗ file $(which python)                      
/Users/**/opt/anaconda3/envs/gpt/bin/python: Mach-O 64-bit executable arm64

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/143472756/8028006e-f30c-460a-a594-5bdcabe351e6)
<img width="605" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/143472756/4d3a46e7-c904-4706-b523-76805d53fa26">

**Comment by binary-husky** [comment]
`python -m pip install xxx`
