### ISSUE TITLE
[Feature]: docker和docker-compose部署支持azure-gpt-3.5

### ISSUE THREAD

**Issue by freechw** [binary-husky/gpt_academic#1068]
### Class | 类型

其他

### Feature Request | 功能请求

目前使用docker-compose部署，好像还不能支持azure-gpt-3.5，希望能增加此功能。
此外，docker部署支持数据持久化就更好了。

**Comment by binary-husky** [comment]
数据持久化应该是docker容器管理者要做的事，和项目本身关系似乎不大
