### ISSUE TITLE
“Json解析不合常规 405 Not Allowed”请问怎么解决

### ISSUE THREAD

**Issue by Gaowkang** [binary-husky/gpt_academic#107]
![image](https://user-images.githubusercontent.com/111952602/228554131-774b47d6-4ecf-4d93-b9f1-132b9008c923.png)

**Comment by ShiXiangnan** [comment]
我这也是相同的问题……难搞哦

**Comment by Fenglinyu** [comment]
一样的问题，不知道升级成plus能解决不

**Comment by Fenglinyu** [comment]
Json解析不合常规 “error”: { “message”: “You exceeded your current quota, please check your plan and billing details.”, “type”: “insufficient_quota”, “param”: null, “code”: null }}

**Comment by FightingFranky** [comment]
一样的问题，提示没有额度了...

**Comment by superfeimao** [comment]
同样的问题。Json解析不合常规 “error”: { “message”: “You exceeded your current quota, please check your plan and billing details.”, “type”: “insufficient_quota”, “param”: null, “code”: null }}


有没有成功解决了呀？换个账号？还是换个key，还是要升级plus啥的？有解决方法的话可以回我下吗，折腾好久了啊

**Comment by Fenglinyu** [comment]
不清楚，我打算先绑个visa卡试试，估计是没有免费的token了

**Comment by superfeimao** [comment]
大家可以换一个有余额的账号，我换了账号已经解决了。

**Comment by xzm123456** [comment]
> > 不清楚，我打算先绑个visa卡试试，估计是没有免费的token了
> 
> 解决了 ，就是没有免费的token！

兄弟，问一下plus，有token限制吗？

**Comment by superfeimao** [comment]
> > > 不清楚，我打算先绑个visa卡试试，估计是没有免费的token了
> > 
> > 
> > 解决了 ，就是没有免费的token！
> 
> 兄弟，问一下plus，有token限制吗？

（API调用计费方式，总消耗=提问消耗+答案消耗）
价格：$0.00200/1K tokens
1K tokens 大约750个英文单词，375个汉字

**Comment by xzm123456** [comment]
> > > > 不清楚，我打算先绑个visa卡试试，估计是没有免费的token了
> > > 
> > > 
> > > 解决了 ，就是没有免费的token！
> > 
> > 
> > 兄弟，问一下plus，有token限制吗？
> 
> （API调用计费方式，总消耗=提问消耗+答案消耗） 价格：$0.00200/1K tokens 1K tokens 大约750个英文单词，375个汉字
可以，兄弟很给力。再问一下，这个项目用起来怎么样

**Comment by superfeimao** [comment]
> 



> > > > > 不清楚，我打算先绑个visa卡试试，估计是没有免费的token了
> > > > 
> > > > 
> > > > 解决了 ，就是没有免费的token！
> > > 
> > > 
> > > 兄弟，问一下plus，有token限制吗？
> > 
> > 
> > （API调用计费方式，总消耗=提问消耗+答案消耗） 价格：$0.00200/1K tokens 1K tokens 大约750个英文单词，375个汉字
> > 可以，兄弟很给力。再问一下，这个项目用起来怎么样

我不知道咋用... 用不明白啊！

**Comment by superfeimao** [comment]
> > 用不明白啊！
> 
> ？？项目没有运行起来？不应该啊

运行起来了哈哈哈，就是不懂“正确使用方法”

**Comment by xzm123456** [comment]
> 

可以的，我还在找便宜的VISA卡0.0，哭了

**Comment by ShiXiangnan** [comment]
> > > > 用不明白啊！
> > > 
> > > 
> > > ？？项目没有运行起来？不应该啊
> > 
> > 
> > 运行起来了哈哈哈，就是不懂“正确使用方法”
> 
> 可以的，我还在找便宜的VISA卡0.0，哭了

找个国外的好兄弟登你的号帮你充一下就行了

**Comment by xzm123456** [comment]
> 

看到你消息就在想0.0

**Comment by xzm123456** [comment]
> > > > > 用不明白啊！
> > > > 
> > > > 
> > > > ？？项目没有运行起来？不应该啊
> > > 
> > > 
> > > 运行起来了哈哈哈，就是不懂“正确使用方法”
> > 
> > 
> > 可以的，我还在找便宜的VISA卡0.0，哭了
> 
> 找个国外的好兄弟登你的号帮你充一下就行了

在想了，在想了0.0

**Comment by nikeaddidaslining** [comment]
换别的账号也可以，他有免费额度上限5美金，达到就得换一个，在自己账户的usage可以看使用情况

**Comment by ShiXiangnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ShiXiangnan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
