### ISSUE TITLE
[Bug]: huggingface中部署无法启用账户密码功能

### ISSUE THREAD

**Issue by YuanJ2003** [binary-husky/gpt_academic#1073]
### Installation Method | 安装方法与平台

Huggingface

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

在config.py中设置好了账户密码，格式正确，但重新构建后仍然是进入直接使用

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/105262243/1a39005b-d33e-4eff-b4a8-15a9c46d2d5d)

**Comment by binary-husky** [comment]
到底是huggingface还是docker呀？

**Comment by binary-husky** [comment]
建议先本地部署进行调试

**Comment by YuanJ2003** [comment]
本地调试一切正常，，就是直接复制了您的huggingface空间，然后在config.py里配置的

**Comment by binary-husky** [comment]
哦 我知道了
app.py 和 main.py 不一样，app.py在github上没有，其中


```
demo.queue(concurrency_count=CONCURRENT_COUNT).launch(server_name="0.0.0.0", share=False, favicon_path="docs/logo.png", blocked_paths=["config.py","config_private.py","docker-compose.yml","Dockerfile"])
 ```

没加username，请把github上的代码迁移过去即可
