### ISSUE TITLE
[Feature]: 集成讯飞火星大模型V2.0

### ISSUE THREAD

**Issue by pangafu** [binary-husky/gpt_academic#1075]
### Class | 类型

大语言模型

### Feature Request | 功能请求

当前集成的是火星1.5，能否把火星2.0也集成进去？

![image](https://github.com/binary-husky/gpt_academic/assets/10149168/543d13fc-8f37-40b6-a2c7-3def09e40c3d)

**Comment by binary-husky** [comment]
了解一个讯飞2.0相比1.5需要额外申请吗

**Comment by pangafu** [comment]
好像不需要，我这边申请了直接1.5和2.0都有了


binary-husky ***@***.***> 于2023年8月31日周四 11:45写道：

**Comment by BAp3r** [comment]
我在config.py里填好了api的id和秘钥，但是web端这里看不到spark之类的字眼，有大佬能帮我解答一下吗
![image](https://github.com/binary-husky/gpt_academic/assets/87560912/472c3cd5-b8cb-4591-874e-1631902f2a0f)

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/116b7ce12fa90b1488fe5cde3773b9b96eb46873

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/c79ccb9a-6cd8-4ffb-aac3-253e38c1a756)
