### ISSUE TITLE
Request timeout. Network error. Please check proxy settings in config.py.

### ISSUE THREAD

**Issue by zlyszx** [binary-husky/gpt_academic#1078]
![image](https://github.com/binary-husky/gpt_academic/assets/74173496/23509502-cd26-43bd-8a66-a95d1b086f5a)
![image](https://github.com/binary-husky/gpt_academic/assets/74173496/f8c8dd4e-2394-456f-b31d-feb83960f32b)
![image](https://github.com/binary-husky/gpt_academic/assets/74173496/9f21c623-fc37-41ff-9407-5a40536568b8)
![image](https://github.com/binary-husky/gpt_academic/assets/74173496/24704c16-981e-42e0-b117-4a27ee98ac91)

请问这是什么原因呢？

**Comment by binary-husky** [comment]
#1
