### ISSUE TITLE
[Bug]: 版本更新后，出现No such file or directory: 'themes/default.css' 

### ISSUE THREAD

**Issue by xjtubmeboy** [binary-husky/gpt_academic#1080]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

版本更新后，出现No such file or directory: 'themes/default.css' 

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/37238928/6b479b47-ad9d-4820-91e5-8715f877ca38)

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/23c0a880-0a92-4a12-b40a-eeaa929817c0)
