### ISSUE TITLE
[Bug]: 我在我的设备上PDF总是编译失败

### ISSUE THREAD

**Issue by DrZhang1208** [binary-husky/gpt_academic#1081]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

Ubuntu 20.04.6 LTS
我是通过sudo apt-get install texlive-full安装的latex
每次使用论文翻译都是最后一部不能编译pdf
由于最为关键的转化PDF编译失败, 将根据报错信息修正tex源文件并重试, 当前报错的latex代码处于第[-1]行 ...

### Screen Shot | 有帮助的截图

![图片](https://github.com/binary-husky/gpt_academic/assets/97793620/95cd2177-ae0a-4e26-acac-0cfa14fc7c66)
![图片](https://github.com/binary-husky/gpt_academic/assets/97793620/f808c598-f97a-4142-b506-d8506b5f1a0f)

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Latex%E7%9B%B8%E5%85%B3%E6%8F%92%E4%BB%B6%EF%BC%88arxiv%E6%96%87%E7%AB%A0%E7%BF%BB%E8%AF%91%EF%BC%89

**Comment by binary-husky** [comment]
ubuntu没有安装中文字体

**Comment by DrZhang1208** [comment]
感谢大佬，docker确实方便很多
