### ISSUE TITLE
[Feature]: 关于New Bing AI接入的求助

### ISSUE THREAD

**Issue by M1Garand12138** [binary-husky/gpt_academic#1091]
### Class | 类型 

关于New Bing AI接入的求助

### Feature Request | 功能请求 关于New Bing AI接入的求助

请问这程序支持New Bing AI的接入吗？如果能的话，要怎么做？

**Comment by binary-husky** [comment]
你好 目前newbing的接入不再维护了 因为替代方案很多

**Comment by M1Garand12138** [comment]
但我目前只有New Bing的能接入，GPT接入的话我担心因为访问过多被机场拉黑






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月10日(星期天) 下午3:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/gpt_academic] [Feature]: 关于New Bing AI接入的求助 (Issue #1091)





 
你好 目前newbing的接入不再维护了 因为替代方案很多

**Comment by binary-husky** [comment]
可以使用第三方代理服务比如openai-sb，api2d，ohmygpt等等，他们自带代理服务，可以作为过渡
