### ISSUE TITLE
[Bug]: 总结PDF文档的bug

### ISSUE THREAD

**Issue by RikkaLzw** [binary-husky/gpt_academic#1094]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Traceback (most recent call last):
  File ".\toolbox.py", line 137, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\批量总结PDF文档.py", line 149, in 批量总结PDF文档
    yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File ".\crazy_functions\批量总结PDF文档.py", line 16, in 解析PDF
    file_content, page_one = read_and_clean_pdf_text(file_name) # （尝试）按照章节切割PDF
  File ".\crazy_functions\crazy_utils.py", line 476, in read_and_clean_pdf_text
    main_fsize = max(fsize_statiscs, key=fsize_statiscs.get)
ValueError: max() arg is an empty sequence
进行最后总结出现该报错

### Screen Shot | 有帮助的截图

![QQ截图20230910154219](https://github.com/binary-husky/gpt_academic/assets/128763841/04bdbbbe-e953-4255-a239-e121566e9065)
![QQ截图20230910154303](https://github.com/binary-husky/gpt_academic/assets/128763841/861a764a-41b8-4ebd-aa80-ce5eb0c519bb)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

[论文汇总.zip](https://github.com/binary-husky/gpt_academic/files/12567739/default.zip)

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/52c0bf0f-0409-4bcf-aa5d-2b2f38d46f85)
2020.pdf这个文件无法打开（WPS office）

**Comment by binary-husky** [comment]
修正报错讯息 

https://github.com/binary-husky/gpt_academic/commit/28d777a96bfb92f86267797c5e2e6bc6ba0b7ae7

**Comment by RikkaLzw** [comment]
> ![image](https://user-images.githubusercontent.com/96192199/266825217-52c0bf0f-0409-4bcf-aa5d-2b2f38d46f85.png) 2020.pdf这个文件无法打开（WPS office）

谢谢谢谢，真的抱歉，我没检查
