### ISSUE TITLE
[Bug]: TypeError: compile_latex_with_timeout() missing 1 required positional argument: 'cwd'

### ISSUE THREAD

**Issue by RikkaLzw** [binary-husky/gpt_academic#1097]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Traceback (most recent call last):
  File ".\toolbox.py", line 137, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Latex输出PDF结果.py", line 199, in Latex英文纠错加PDF对比
    success = yield from 编译Latex(chatbot, history, main_file_original='merge', main_file_modified='merge_proofread_en',
  File ".\crazy_functions\latex_fns\latex_actions.py", line 366, in 编译Latex
    ok = compile_latex_with_timeout(f'latexdiff --encoding=utf8 --append-safecmd=subfile {work_folder_original}/{main_file_original}.tex  {work_folder_modified}/{main_file_modified}.tex --flatten > {work_folder}/merge_diff.tex')
TypeError: compile_latex_with_timeout() missing 1 required positional argument: 'cwd'

### Screen Shot | 有帮助的截图

![QQ截图20230911145248](https://github.com/binary-husky/gpt_academic/assets/128763841/d3524ed1-8d08-49b4-942a-9ed9e05b1209)
![QQ截图20230911145315](https://github.com/binary-husky/gpt_academic/assets/128763841/b2879d08-5ab6-417c-bef8-0d7494348e28)

**Comment by binary-husky** [comment]
是修改了一部分代码吧，`--append-safecmd=subfile` 是？

**Comment by RikkaLzw** [comment]
> 

这个是原本就有的。我只加了后面那个参数cwd，其余问题不大就是没有高亮

**Comment by binary-husky** [comment]
嗯？但我们源代码里确实没有呀，你是在哪clone的？

**Comment by RikkaLzw** [comment]
> 嗯？但我们源代码里确实没有呀，你是在哪clone的？

**Comment by RikkaLzw** [comment]
> 嗯？但我们源代码里确实没有呀，你是在哪clone的？
crazy_functions/latex_fns/latex_actions.py  366行

**Comment by binary-husky** [comment]
不好意思，确实如您所说，我检查一下

**Comment by binary-husky** [comment]
不好意思，确实如您所说，我检查一下

**Comment by binary-husky** [comment]
已修复，非常感谢！！
https://github.com/binary-husky/gpt_academic/commit/c4c64659276a6fe185977e34537f041d5383e1fb

**Comment by binary-husky** [comment]
对啦，目前prompt可能不是很讲究，欢迎提PR

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/a081ec9c-a5b4-4f72-80e8-c6c88bc9cc10)

**Comment by RikkaLzw** [comment]
> 对啦，目前prompt可能不是很讲究，欢迎提PR
> 
> ![image](https://user-images.githubusercontent.com/96192199/267308492-a081ec9c-a5b4-4f72-80e8-c6c88bc9cc10.png)

好的
