### ISSUE TITLE
[Bug]: UnboundLocalError: cannot access local variable 'knowledge_archive_interface' where it is not associated with a value

### ISSUE THREAD

**Issue by shiliu2023** [binary-husky/gpt_academic#1099]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

知识库问答的时候报错：

Traceback (most recent call last):
  File "./toolbox.py", line 137, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File "./crazy_functions/Langchain知识库.py", line 90, in 读取知识库作答
    kai = knowledge_archive_interface()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'knowledge_archive_interface' where it is not associated with a value

### Screen Shot | 有帮助的截图

Traceback (most recent call last):
  File "./toolbox.py", line 137, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File "./crazy_functions/Langchain知识库.py", line 90, in 读取知识库作答
    kai = knowledge_archive_interface()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'knowledge_archive_interface' where it is not associated with a value

**Comment by binary-husky** [comment]
已修复：

https://github.com/binary-husky/gpt_academic/commit/4b5f13bff26c2412078a4af550dc265fa37201df
