### ISSUE TITLE
[Bug]: 精准翻译PDF论文插件-基于GROBID

### ISSUE THREAD

**Issue by doubletree6** [binary-husky/gpt_academic#1103]
### Installation Method | 安装方法与平台

Huggingface

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

精准翻译论文pdf文档时，第一步翻译没有问题，但进行多线程操作后必定会产生Connection errored out的问题，从而终止翻译。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/108912608/71364d6a-c6bb-4736-bc4d-ce2234876022)

**Comment by doubletree6** [comment]
试验了几个页数较少的文章（2-3页），多线程6个以内，未出现上述问题。

**Comment by binary-husky** [comment]
版本迭代到3.52，试试更新后的代码？
