### ISSUE TITLE
[Bug]: WARNING:root:No GPU found. Conversion on CPU is very slow.

### ISSUE THREAD

**Issue by w1033775433** [binary-husky/gpt_academic#1104]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

WARNING:root:No GPU found. Conversion on CPU is very slow.
使用VScode，显卡3060

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/117188760/ea982b10-4062-4141-9f49-8382ce8e542a)

**Comment by binary-husky** [comment]
cn特色网络问题
