### ISSUE TITLE
[Feature]: 接入gpt4free的接口

### ISSUE THREAD

**Issue by Giancarlo-Ma** [binary-husky/gpt_academic#1108]
### Class | 类型

程序主体

### Feature Request | 功能请求

现在大部分都是依赖自助申请api key,时间和金钱成本较高，但是gpt4free有很多开放的免费接口源，是否可以考虑集成

**Comment by binary-husky** [comment]
您好，考虑到维护难度，我们不会再主动集成逆向工程的接口

**Comment by Giancarlo-Ma** [comment]
这个就是集成一个gpt4free的package就好了，你们没空的话，我有时间看看怎么弄一下吧

**Comment by Giancarlo-Ma** [comment]
> 您好，考虑到维护难度，我们不会再主动集成逆向工程的接口

这个就是集成一个gpt4free的package就好了，你们没空的话，我有时间看看怎么弄一下吧

**Comment by daihuiao** [comment]
有进展吗
