### ISSUE TITLE
[Bug]: 为什么pdf翻译到一半就戛然而止了，所有线程都不动了？

### ISSUE THREAD

**Issue by LucasXin1** [binary-husky/gpt_academic#1109]
### Installation Method | 安装方法与平台

Huggingface

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我用的是网页版

### Screen Shot | 有帮助的截图

![微信截图_20230915184946](https://github.com/binary-husky/gpt_academic/assets/105917817/a0d8706d-0d90-4ba7-8494-ac03718ec752)

**Comment by binary-husky** [comment]
请稍等一会，等到结果输出后，取回报错即可

**Comment by binary-husky** [comment]
另外插件功能不建议用网页版，运算负荷太大了
