### ISSUE TITLE
[Feature]: 请问怎么配置讯飞星火V2.0

### ISSUE THREAD

**Issue by daoyeshan** [binary-husky/gpt_academic#1112]
### Class | 类型

大语言模型

### Feature Request | 功能请求

请问怎么配置讯飞星火V2.0,跟配置ChatGPT有什么区别？
我在config.py将USE_PROXY 改回False，LLM_MODEL 改为 "sparkv2" ，并设置了讯飞的API_KEY等信息，最后运行“python main.py”
结果显示“当前模型：gpt-3.5-turbo”，说明我的配置还是不对的，请问应该怎么修改？
还有就是，huggingface中的gpt-academic能否支持讯飞星火V2.0？如果支持的话，是跟ChatGPT一样直接输入XFYUN_API_KEY吗？
谢谢！

USE_PROXY = False
LLM_MODEL = "sparkv2"

XFYUN_APPID = "95xxxx53"
XFYUN_API_SECRET = "ZDQxxxxxxxxxxRkM2I1"
XFYUN_API_KEY = "7fb517xxxxx017"

**Comment by binary-husky** [comment]
你好，配置问题看wiki即可~
