### ISSUE TITLE
[Bug]: 不能加载Newbing组件

### ISSUE THREAD

**Issue by ZhuJap** [binary-husky/gpt_academic#1116]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

clash代理 端口7890
Newbing cookies 正常配置
首次你好就出现报错！

### Screen Shot | 有帮助的截图

![屏幕截图 2023-09-19 190848](https://github.com/binary-husky/gpt_academic/assets/92317850/d2b9dffa-975f-424e-89d3-c2c0a0e1ad02)

**Comment by binary-husky** [comment]
Newbing组件不再维护
