### ISSUE TITLE
[Bug]: 配置了第三方api，前两天用的好好的，今天怎么也连不上，用其他工具能连上

### ISSUE THREAD

**Issue by RexLeeGrey** [binary-husky/gpt_academic#1119]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

显示
Something went wrong
Connection errored out.

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/125941057/8d58ffb3-2c5e-43e9-a7bf-18c64081c6e2)
![image](https://github.com/binary-husky/gpt_academic/assets/125941057/45b3132e-b573-49d0-8a5b-b4f2f68780ef)
![image](https://github.com/binary-husky/gpt_academic/assets/125941057/ccebd27d-edb9-4864-81f4-e778936dbca0)

**Comment by binary-husky** [comment]
看一下终端的traceback？

**Comment by binary-husky** [comment]
浏览器代理关掉试试，似乎是简单的网络问题

**Comment by RexLeeGrey** [comment]
很奇怪，换了个浏览器就好了
