### ISSUE TITLE
[Feature]: 希望能够增加azure openai gpt4 的模型选项

### ISSUE THREAD

**Issue by fangconquerord** [binary-husky/gpt_academic#1120]
### Class | 类型

程序主体

### Feature Request | 功能请求

RT

**Comment by binary-husky** [comment]
方便加QQ提供下测试endpoint吗，我的azure刚到期了 QQ 505030475

**Comment by fangconquerord** [comment]
加你了

**Comment by liuyangedu** [comment]
同意

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/e24f077b68e38b679e5ca25853ea2c402f074ea3

已添加，3.54版本之后入主分支

**Comment by Sefank** [comment]
希望azure gpt4和azure gpt3.5可以共存（需要不同的engine值）
