### ISSUE TITLE
[Bug]: 近期针对pdf的任务频繁出错

### ISSUE THREAD

**Issue by Wanbi1** [binary-husky/gpt_academic#1125]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

最近在使用“批量总结pdf”以及“精准翻译pdf”任务时频繁出现一部分任务无法顺利进行的情况，如图。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/110647344/435c85c5-1d77-45ef-88ee-de86b73343da)

**Comment by binary-husky** [comment]
traceback 显示你的代理有问题
