### ISSUE TITLE
[Feature]: 希望能加入解析matlab code的功能

### ISSUE THREAD

**Issue by 12Wayne-Peng** [binary-husky/gpt_academic#1127]
### Class | 类型

函数插件

### Feature Request | 功能请求

隨著MATLAB在工程和科學領域的廣泛應用，對MATLAB代碼的解析和理解變得越來越重要。這不僅僅是為了節省開發者的時間，還有助於快速找出代碼中的問題和進行優化。因此，我們誠摯地請求貴公司考慮開發一個功能，讓使用者能夠「一鍵解析MATLAB代碼」。這樣的功能將大大提升使用者的工作效率，並使得代碼的檢查和優化變得更加直觀。

**Comment by binary-husky** [comment]
已加

https://github.com/binary-husky/gpt_academic/commit/8d4cb057387108d1fe85504cc66d949a6ee2e320
