### ISSUE TITLE
每次运行时端口总是随机的，如何固定呢？

### ISSUE THREAD

**Issue by Cz1544252489** [binary-husky/gpt_academic#1128]
# 我搜了一些相关问题，发现似乎和我这个问题不太一样，如果有一样的请踢我。

## 我是在一台美国VPS上运行的，加入了API key后修改了一点配置，就是proxy代理这里，但是没有任何左右，即便我将False也改成了True。

![image](https://github.com/binary-husky/gpt_academic/assets/64407693/220083cf-9a26-48be-81b4-5989da6907d8)

**Comment by binary-husky** [comment]
config.py往下翻

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/wiki/%E9%A1%B9%E7%9B%AE%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/1d10b2f3-8f74-4c0e-86df-bf72bd2420df)

**Comment by Cz1544252489** [comment]
好的好的，非常非常感谢您及时的回复。^o^
