### ISSUE TITLE
[Feature]: 解析文件类的插件出错

### ISSUE THREAD

**Issue by ArborealSky** [binary-husky/gpt_academic#1133]
### Class | 类型

函数插件

### Feature Request | 功能请求

如图，已经安装了rarfile插件，但是程序无法正确接收文件，会报错让安装rarfile。目前正在使用GPT3.5的key，请问是我的使用方法不正确，还是需要使用其他的模型才能处理项目或者pdf文件？请问您有关于使用这类插件的教程吗？

（不知道图片能否加载出来）
<img width="1093" alt="屏幕截图 2023-09-28 174217" src="https://github.com/binary-husky/gpt_academic/assets/96411281/965657e9-94de-42bc-b520-1f6dcd698db4">

**Comment by binary-husky** [comment]
多个python冲突
