### ISSUE TITLE
不能自动导入config.py中的key

### ISSUE THREAD

**Issue by sw8207** [binary-husky/gpt_academic#1139]
![image](https://github.com/binary-husky/gpt_academic/assets/52055472/34e55058-63b7-42ee-a107-1b958f951083)

如上图所示，使用chatgpt3.5时，在config.py填了apikey，但不能识别，重新在输入窗口输入同样的key，就可以了。

**Comment by binary-husky** [comment]
配置未生效一定是因为被覆盖了，详见wiki
