### ISSUE TITLE
[Feature]: 精准翻译能否手动限制并发数或者请求间隔？open ai限制了key的并发数量

### ISSUE THREAD

**Issue by JamieJustTang** [binary-husky/gpt_academic#1140]
### Class | 类型

函数插件

### Feature Request | 功能请求

<img width="591" alt="截屏2023-10-01 13 00 26" src="https://github.com/binary-husky/gpt_academic/assets/61746949/e456f5e2-8d52-43a4-a045-fb81f4b6d78a">

出现这类报错问题。手动限制并发数的话应该就可以解决。

**Comment by binary-husky** [comment]
已经有这种配置了，见wiki，或者config.py
