### ISSUE TITLE
[Bug]: arxiv下载翻译后编译失败

### ISSUE THREAD

**Issue by wumingshiwjh** [binary-husky/gpt_academic#1141]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

[2023-10-01-15-43-37-2023-10-01-15-43-36-result.zip](https://github.com/binary-husky/gpt_academic/files/12776657/2023-10-01-15-43-37-2023-10-01-15-43-36-result.zip)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/146599606/2fdcf0ce-614e-4750-8397-5fce72d8f897)

**Comment by binary-husky** [comment]
根据报错信息，你电脑上缺少字体（黑体）
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/f5434d94-4846-470a-bfe7-e462e03584c8)

**Comment by binary-husky** [comment]
建议使用docker运行

**Comment by wumingshiwjh** [comment]
感谢大佬，确实是字体的问题，我一开始是确认了mac的字体册里有黑体的。但是好像mac的字体适配不是很好，要把它复制到tex文件的路径下才行
