### ISSUE TITLE
[Bug]: 程序启动报错

### ISSUE THREAD

**Issue by XizanLiu** [binary-husky/gpt_academic#1142]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

启动时有以下报错，求解决方法：

Traceback (most recent call last):
  File "/Users/xizanliu/chatgpt_academic/main.py", line 206, in <module>
    main()
  File "/Users/xizanliu/chatgpt_academic/main.py", line 54, in main
    with gr.Blocks(title="ChatGPT 学术优化", theme=set_theme, analytics_enabled=False, css=advanced_css) as demo:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gradio/blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gradio/blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gradio_client/serializing.py", line 43, in input_api_info
    types = api_info.get("serialized_input", [api_info["info"]["type"]] * 2)  # type: ignore
                                              ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'


### Screen Shot | 有帮助的截图

<img width="569" alt="Screenshot 2023-10-01 at 10 12 49" src="https://github.com/binary-husky/gpt_academic/assets/68432787/748d13d1-c163-49ac-86af-2ff66d3fed8c">


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by binary-husky** [comment]
确定使用了requirements.txt吗

**Comment by XizanLiu** [comment]
确定的 有按照步骤安装的

**Comment by XizanLiu** [comment]
> 确定使用了requirements.txt吗

确定的 有按照步骤安装

**Comment by binary-husky** [comment]
我试试能不能复现。

运行`pip install gradio_client==0.1.4`可否修复问题呢

**Comment by XizanLiu** [comment]
已修复 感谢！
