### ISSUE TITLE
[Feature]: 增加账户机制自动读取不同的config

### ISSUE THREAD

**Issue by PeterZaipinai** [binary-husky/gpt_academic#1144]
### Class | 类型

程序主体

### Feature Request | 功能请求

希望增加一个账号机制，我想做一个平台给朋友们共享，但是GPT4翻译论文开销很大，每次单独键入不同的计费key也麻烦，能不能程序前置一个账户选择，不同账户读不同的config文件呢？

**Comment by lknife** [comment]
赞同，我也有这个需求
