### ISSUE TITLE
[Bug]: 使用ChatGLM2-6b, AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

### ISSUE THREAD

**Issue by lang-H** [binary-husky/gpt_academic#1146]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用的python3.11.6+cuda11.8+torch2.0.1，硬件是内存32g+4060ti 16g，无论是用cpu还是显卡，INT4还是不量话，跑都是一样的报错，ChatGLM2测试过可以正常运行的。
python3.10.7也试了还是不行
下面红色框起来的是报错行

### Screen Shot | 有帮助的截图

![5360a8ca3e29702e0da5633309c019a2](https://github.com/binary-husky/gpt_academic/assets/74520172/5940d777-9b18-41a9-a036-f402d6fc737b)
![75aca09b276e5fad45762b604ed601ed](https://github.com/binary-husky/gpt_academic/assets/74520172/69b296d4-bfcc-4014-ae41-d4ab99154c5f)
![e17b5891564c9e01687b8c8ee1b8241a](https://github.com/binary-husky/gpt_academic/assets/74520172/5d769265-f8bc-4a76-bdfd-6fb3567810ed)
![effc8629cc2bd773ddf0382fd6a3eb4a](https://github.com/binary-husky/gpt_academic/assets/74520172/1eeb7324-fa17-4620-beca-6a42383fa86f)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

正在执行一些模块的预热...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
Running on local URL:  http://0.0.0.0:57339
chatglm2-6b-int4
 [PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。 
Process GetGLMHandle-1:
Traceback (most recent call last):
  File "e:\GPT\gpt_academic\request_llm\bridge_chatglm.py", line 53, in run
    self.chatglm_tokenizer = AutoTokenizer.from_pretrained(_model_name_, trust_remote_code=True)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GPT\gpt_academic\gptacademi\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\GPT\gpt_academic\gptacademi\Lib\site-packages\transformers\tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\GPT\gpt_academic\gptacademi\Lib\site-packages\transformers\tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lang/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\tokenization_chatglm.py", line 69, in __init__
    super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=False, **kwargs)
  File "E:\GPT\gpt_academic\gptacademi\Lib\site-packages\transformers\tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "E:\GPT\gpt_academic\gptacademi\Lib\site-packages\transformers\tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\lang/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\tokenization_chatglm.py", line 112, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
                                                            ^^^^^^^^^^^^^^^
  File "C:\Users\lang/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\tokenization_chatglm.py", line 108, in vocab_size
    return self.tokenizer.n_words
           ^^^^^^^^^^^^^^
AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lang\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "e:\GPT\gpt_academic\request_llm\bridge_chatglm.py", line 66, in run
    raise RuntimeError("不能正常加载ChatGLM的参数！")
RuntimeError: 不能正常加载ChatGLM的参数！

**Comment by Ellinia511** [comment]
同样的问题

**Comment by lang-H** [comment]
pip安装transformers==4.30.2后解决，据说4.33.1也可以

**Comment by Ellinia511** [comment]
> pip安装transformers==4.30.2后解决，据说4.33.1也可以

您好，请问在哪里看到的解决方案呢，我好像找解决步骤的时候安装过这个还没解决，不过报错是完全一样的

**Comment by lang-H** [comment]
> > pip安装transformers==4.30.2后解决，据说4.33.1也可以
> 
> 您好，请问在哪里看到的解决方案呢，我好像找解决步骤的时候安装过这个还没解决，不过报错是完全一样的

我在群里问了，有大佬回复的

**Comment by Ellinia511** [comment]
感谢回复，我尝试了一下还是报错了，可以请问您是什么交流群吗？





------------------ 原始邮件 ------------------
From: lang-H ***@***.***&gt;
发送时间: 10/06/2023, 10:06
To: 576053010 ***@***.***&gt;
Subject: Re: [binary-husky/gpt_academic] [Bug]: 使用ChatGLM2-6b, AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer' (Issue #1146)





   
pip安装transformers==4.30.2后解决，据说4.33.1也可以
  
您好，请问在哪里看到的解决方案呢，我好像找解决步骤的时候安装过这个还没解决，不过报错是完全一样的
  
我在群里问了，有大佬回复的

**Comment by lang-H** [comment]
> 感谢回复，我尝试了一下还是报错了，可以请问您是什么交流群吗？
> […](#)
> ------------------ 原始邮件 ------------------ From: lang-H ***@***.***&gt; 发送时间: 10/06/2023, 10:06 To: 576053010 ***@***.***&gt; Subject: Re: [binary-husky/gpt_academic] [Bug]: 使用ChatGLM2-6b, AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer' (Issue #1146) pip安装transformers==4.30.2后解决，据说4.33.1也可以 您好，请问在哪里看到的解决方案呢，我好像找解决步骤的时候安装过这个还没解决，不过报错是完全一样的 我在群里问了，有大佬回复的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

就是GitHub工程里的那个群号

**Comment by Ellinia511** [comment]
> > 感谢回复，我尝试了一下还是报错了，可以请问您是什么交流群吗？
> > […](#)
> > ------------------ 原始邮件 ------------------ From: lang-H _**@**_._**> 发送时间: 10/06/2023, 10:06 To: 576053010 _**@**_.**_> Subject: Re: [binary-husky/gpt_academic] [Bug]: 使用ChatGLM2-6b, AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer' (Issue #1146) pip安装transformers==4.30.2后解决，据说4.33.1也可以 您好，请问在哪里看到的解决方案呢，我好像找解决步骤的时候安装过这个还没解决，不过报错是完全一样的 我在群里问了，有大佬回复的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 就是GitHub工程里的那个群号

感谢！
