### ISSUE TITLE
[Bug]: 翻译arxiv文档报错，无论本地自己搭建还是官方在线均报错

### ISSUE THREAD

**Issue by ddkk3000** [binary-husky/gpt_academic#1147]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

官方在线版报错代码如下：

> Local Message] 实验性函数调用出错:
> 
> Traceback (most recent call last):
>   File "./toolbox.py", line 165, in decorated
>     yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
>   File "./crazy_functions/Latex输出PDF结果.py", line 249, in Latex翻译中文并重新编译PDF
>     txt, arxiv_id = yield from arxiv_download(chatbot, history, txt)
>   File "./crazy_functions/Latex输出PDF结果.py", line 141, in arxiv_download
>     extract_archive(file_path=dst, dest_dir=extract_dst)
>   File "./toolbox.py", line 507, in extract_archive
>     with tarfile.open(file_path, 'r:*') as tarobj:
>   File "/usr/lib/python3.8/tarfile.py", line 1608, in open
>     raise ReadError("file could not be opened successfully")
> tarfile.ReadError: file could not be opened successfully
>  
> 当前代理可用性:
> 
> 代理配置 socks5h://localhost:7890, 代理所在地：Japan

本地搭建版报错代码如下：

> [Local Message] 实验性函数调用出错:
> 
> Traceback (most recent call last):
>   File ".\toolbox.py", line 150, in decorated
>     yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
>   File ".\crazy_functions\Latex输出PDF结果.py", line 250, in Latex翻译中文并重新编译PDF
>     txt, arxiv_id = yield from arxiv_download(chatbot, history, txt, allow_cache)
>   File ".\crazy_functions\Latex输出PDF结果.py", line 139, in arxiv_download
>     extract_archive(file_path=dst, dest_dir=extract_dst)
>   File ".\toolbox.py", line 461, in extract_archive
>     with tarfile.open(file_path, 'r:*') as tarobj:
>   File "D:\academic-gpt\installer_files\env\lib\tarfile.py", line 1811, in open
>     raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
> tarfile.ReadError: file could not be opened successfully:
> - method gz: ReadError('invalid header')
> - method bz2: ReadError('not a bzip2 file')
> - method xz: ReadError('not an lzma file')
> - method tar: ReadError('invalid header')
>  
> 当前代理可用性:
> 
> 代理配置 socks5h://127.0.0.1:12341, 代理所在地：Hong Kong - Cloudflare, Inc.

所翻译的arxiv文档的地址为：https://arxiv.org/abs/2112.10551

### Screen Shot | 有帮助的截图

![msedge_HmO7O9M6OT](https://github.com/binary-husky/gpt_academic/assets/10786234/51e6ff95-9b95-47cd-b671-322aa1808389)

**Comment by binary-husky** [comment]
这个文章的源代码，https://arxiv.org/format/2112.10551，我手动尝试也无法打开，不知道它是什么格式

**Comment by ddkk3000** [comment]
啊？其他的文件也有类似错误。


例如，


https://arxiv.org/abs/2012.01007


这不是一个特例。

----------




--------------原始邮件--------------
发件人："binary-husky ***@***.***&gt;;
发送时间：2023年10月6日(星期五) 中午11:10
收件人："binary-husky/gpt_academic" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [binary-husky/gpt_academic] [Bug]: 翻译arxiv文档报错，无论本地自己搭建还是官方在线均报错 (Issue #1147)
-----------------------------------

 

 
这个文章的源代码，https://arxiv.org/format/2112.10551，我手动尝试也无法打开，不知道它是什么格式

**Comment by ddkk3000** [comment]
> 这个文章的源代码，https://arxiv.org/format/2112.10551 ，我手动尝试也无法打开，不知道它是什么格式

我访问的源码可以打开。要不您再看看？

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/f3c64038-17d6-4822-914c-10059fd8f28f)

**Comment by binary-husky** [comment]
搞了半天它是tex文件啊，这样
1. 把它重命名为2112.10551.tex
2. 拖进文件上传区
3. 直接点击arxiv精细翻译插件

**Comment by binary-husky** [comment]
[2023-10-06-04-21-06-comparison.pdf](https://github.com/binary-husky/gpt_academic/files/12826872/2023-10-06-04-21-06-comparison.pdf)

**Comment by ddkk3000** [comment]
啊？不好意思，我用的是winrar.

----------




--------------原始邮件--------------
发件人："binary-husky ***@***.***&gt;;
发送时间：2023年10月6日(星期五) 中午12:19
收件人："binary-husky/gpt_academic" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [binary-husky/gpt_academic] [Bug]: 翻译arxiv文档报错，无论本地自己搭建还是官方在线均报错 (Issue #1147)
-----------------------------------

**Comment by ddkk3000** [comment]
谢谢，明白了

----------




--------------原始邮件--------------
发件人："binary-husky ***@***.***&gt;;
发送时间：2023年10月6日(星期五) 中午12:21
收件人："binary-husky/gpt_academic" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [binary-husky/gpt_academic] [Bug]: 翻译arxiv文档报错，无论本地自己搭建还是官方在线均报错 (Issue #1147)
-----------------------------------

 

 
搞了半天它是tex文件啊，这样
  
把它重命名为2112.10551.tex
 
拖进文件上传区
 
直接点击arxiv精细翻译插件

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/197287fc303119bf71caf9b3f72280cab08da749

提交了一个patch
