### ISSUE TITLE
[Bug]: 直接上传tex文件然后使用arxiv精准翻译（使用本地latex那个插件也不行），仍然报错

### ISSUE THREAD

**Issue by ddkk3000** [binary-husky/gpt_academic#1148]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

相关问题是：https://github.com/binary-husky/gpt_academic/issues/1147

本地和在线的报错如下（均尝试直接翻译tex的插件与arxiv插件）：

>Traceback (most recent call last):
  File ".\toolbox.py", line 150, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Latex输出PDF结果.py", line 282, in Latex翻译中文并重新编译PDF
    yield from Latex精细分解与转化(file_manifest, project_folder, llm_kwargs, plugin_kwargs,
  File ".\crazy_functions\latex_fns\latex_actions.py", line 211, in Latex精细分解与转化
    maintex = find_main_tex_file(file_manifest, mode)
  File ".\crazy_functions\latex_fns\latex_toolbox.py", line 247, in find_main_tex_file
    raise RuntimeError('无法找到一个主Tex文件（包含documentclass关键字）')
RuntimeError: 无法找到一个主Tex文件（包含documentclass关键字）

> Traceback (most recent call last):
  File "./toolbox.py", line 165, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File "./crazy_functions/Latex输出PDF结果.py", line 276, in Latex翻译中文并重新编译PDF
    project_folder = move_project(project_folder, arxiv_id)
  File "./crazy_functions/Latex输出PDF结果.py", line 81, in move_project
    shutil.copytree(src=project_folder, dst=new_workfolder)
  File "/usr/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: 'private_upload/2023-10-06-04-49-44'

tex文件在附件中。下载自：https://arxiv.org/format/2012.01007
[2012.01007.zip](https://github.com/binary-husky/gpt_academic/files/12827041/2012.01007.zip)

### Screen Shot | 有帮助的截图

![Uploading msedge_5j3mF9r4CN.png…]()

**Comment by TonyHuang0711** [comment]
看起来是文件上传失败 点重置➡️刷新 重新传文件试试

**Comment by ddkk3000** [comment]
本地和远程都不行，不是上传失败的问题。

----------




--------------原始邮件--------------
发件人："Yuki ***@***.***&gt;;
发送时间：2023年10月6日(星期五) 下午2:57
收件人："binary-husky/gpt_academic" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [binary-husky/gpt_academic] [Bug]: 直接上传tex文件然后使用arxiv精准翻译（使用本地latex那个插件也不行），仍然报错 (Issue #1148)
-----------------------------------

 

 
看起来是文件上传失败 点重置➡️刷新 重新传文件试试

**Comment by TonyHuang0711** [comment]
浏览器控制台有没有显示报错？
* 如果你在本地运行 去检查你的private_upload文件夹下面有没有你的文件

2023年10月6日 08:49，ddkk3000 ***@***.***> 写道：


本地和远程都不行，不是上传失败的问题。

----------




--------------原始邮件--------------
发件人："Yuki ***@***.***&gt;;
发送时间：2023年10月6日(星期五) 下午2:57
收件人："binary-husky/gpt_academic" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [binary-husky/gpt_academic] [Bug]: 直接上传tex文件然后使用arxiv精准翻译（使用本地latex那个插件也不行），仍然报错 (Issue #1148)
-----------------------------------




看起来是文件上传失败 点重置➡️刷新 重新传文件试试

**Comment by ddkk3000** [comment]
再次确定有这个文件，依然无效

----------




--------------原始邮件--------------
发件人："Yuki ***@***.***&gt;;
发送时间：2023年10月6日(星期五) 下午3:53
收件人："binary-husky/gpt_academic" ***@***.***&gt;;
抄送："ddkk3000 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [binary-husky/gpt_academic] [Bug]: 直接上传tex文件然后使用arxiv精准翻译（使用本地latex那个插件也不行），仍然报错 (Issue #1148)
-----------------------------------

 

 浏览器控制台有没有显示报错？ 
 * 如果你在本地运行 去检查你的private_upload文件夹下面有没有你的文件 
 
 2023年10月6日 08:49，ddkk3000 ***@***.***&gt; 写道： 
 
 
 本地和远程都不行，不是上传失败的问题。 
 
 ---------- 
 
 
 
 
 --------------原始邮件-------------- 
 发件人："Yuki ***@***.***&amp;gt;; 
 发送时间：2023年10月6日(星期五) 下午2:57 
 收件人："binary-husky/gpt_academic" ***@***.***&amp;gt;; 
 抄送："ddkk3000 ***@***.***&amp;gt;;"Author ***@***.***&amp;gt;; 
 主题：Re: [binary-husky/gpt_academic] [Bug]: 直接上传tex文件然后使用arxiv精准翻译（使用本地latex那个插件也不行），仍然报错 (Issue #1148) 
 ----------------------------------- 
 
 
 
 
 看起来是文件上传失败 点重置➡️刷新 重新传文件试试

**Comment by binary-husky** [comment]
我都试过了，明明是可以的：
https://github.com/binary-husky/gpt_academic/issues/1147
