### ISSUE TITLE
[Bug]: 调用openai模型，前台结果未显示完，提示something went wrong  Connection erroe

### ISSUE THREAD

**Issue by comeonwzh520** [binary-husky/gpt_academic#1150]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

调用openai模型，前台结果未显示完，提示something went wrong  Connection erroe
后台没有报错

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/21006059/d694889b-a4cc-4a49-8fcc-c2411c54cd34)
![image](https://github.com/binary-husky/gpt_academic/assets/21006059/13dc23b2-bd88-4268-8f60-4874db88bd59)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

询问的内容是“将rectangle为(3, 2)拼到6x4的长方形中，rectangle可以旋转，计算出最大利用率的方案，并计算出来拼了多少个rectangle，使用Python语言如何实现”

**Comment by binary-husky** [comment]
已知：
 部分浏览器插件干扰前端运行
