### ISSUE TITLE
[Bug]: 虚空终端难以使用本地文件进行会话

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [binary-husky/gpt_academic#1155]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

![image](https://github.com/binary-husky/gpt_academic/assets/62531937/856faa74-8538-42d0-9acd-e20914d1047c)
如图,当我首先点击虚空终端,再上传pdf后(并把输入框中自动填入的"private_upload\default\2023-10-09-16-47-29\基于超像素特征表示的图像前景背景分割算法_薛萍.pdf"路径删除),输入图中prompt,gpt却判断为无文件输入(此前我也尝试过先上传文件,再点击虚空终端,是可以成功上传文件的,但是我不太明白两者先后为何有区别,并且我在指导文本中看到推荐先点虚空终端的做法)

### Screen Shot | 有帮助的截图

如上图

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

log中未找到具体细节
![image](https://github.com/binary-husky/gpt_academic/assets/62531937/1c68af58-b346-4923-8941-13a008456cf3)

**Comment by binary-husky** [comment]
您好 虚空终端目前的功能是调度插件 还没有处理复合指令的能力
