### ISSUE TITLE
[Feature]: gpt_academic能用来写文献综述吗

### ISSUE THREAD

**Issue by daoyeshan** [binary-husky/gpt_academic#1156]
### Class | 类型

None

### Feature Request | 功能请求

在B站看到一个软件，可以根据在WOS下载的文献资料信息，将每篇文章精简为一两句话的小段落，类似文献综述的，感觉这样比较方便快速筛选论文。不知道pt_academic能否加入类似功能

**Comment by philyhb** [comment]
这种就是批量总结文献，后续应该可以在此功能下优化下输入形式。

**Comment by daoyeshan** [comment]
对的，就是这种批量总结



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月02日 21:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [binary-husky/gpt_academic] [Feature]: gpt_academic能用来写文献综述吗 (Issue #1156) |

这种就是批量总结文献，后续应该可以在此功能下优化下输入形式。
