### ISSUE TITLE
[Bug]: 返回报错

### ISSUE THREAD

**Issue by RexLeeGrey** [binary-husky/gpt_academic#1161]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 210, in predict
    gpt_replying_buffer = gpt_replying_buffer + chunkjson['choices'][0]["delta"]["content"]
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'content'

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/125941057/0a6724e1-d7c0-47d2-ab3e-4787abc48de6)


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by binary-husky** [comment]
fixed
