### ISSUE TITLE
[Bug]: 尝试执行Latex指令失败。Latex没有安装, 或者不在环境变量PATH中。安装方法https://tug.org/texlive/。报错信息

### ISSUE THREAD

**Issue by JavaZeroo** [binary-husky/gpt_academic#1165]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

使用Docker-compose配置4，网页版不能使用latex精细翻译。

### Screen Shot | 有帮助的截图

尝试执行Latex指令失败。Latex没有安装, 或者不在环境变量PATH中。安装方法https://tug.org/texlive/。报错信息

Traceback (most recent call last):
  File "./crazy_functions/Latex输出PDF结果.py", line 239, in Latex翻译中文并重新编译PDF
    subprocess.Popen(['pdflatex', '-version'])
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pdflatex'

 
![image](https://github.com/binary-husky/gpt_academic/assets/71128095/70f38d82-27b0-4df2-8d23-abba63a703e6)

**Comment by binary-husky** [comment]
正在验证该问题，目前，您可以临时使用方案零

**Comment by JavaZeroo** [comment]
感谢

**Comment by sudathesis** [comment]
这个问题貌似还是存在

**Comment by DolorousFitzgerald** [comment]
用latex -v检查之后是有的，执行也还是这个样子

**Comment by ForgetThatNight** [comment]
怎么解决这个问题，第三方依赖太多了好多bug

**Comment by freemank1224** [comment]
+1 还没解决吗？我也遇到了

**Comment by zhaojingxin123** [comment]
我也是同样的问题

**Comment by zhaojingxin123** [comment]
> 正在验证该问题，目前，您可以临时使用方案零

我也遇到这个问题了，解决了吗？怎么整呀？
