### ISSUE TITLE
[Bug]: GROBID服务不可用，请检查config中的GROBID_URL。作为替代，现在将执行效果稍差的旧版代码。

### ISSUE THREAD

**Issue by BigBMonster** [binary-husky/gpt_academic#1166]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

精准翻译pdf时出现以下提示：
GROBID服务不可用，请检查config中的GROBID_URL。作为替代，现在将执行效果稍差的旧版代码。

config文件中内容如下：
GROBID_URLS = [
    "https://qingxu98-grobid.hf.space", "https://qingxu98-grobid2.hf.space", "https://qingxu98-grobid3.hf.space",
    "https://shaocongma-grobid.hf.space", "https://FBR123-grobid.hf.space", "https://yeku-grobid.hf.space",
]

### Screen Shot | 有帮助的截图

![bad3516ba2cefd3252f3097c437ca21](https://github.com/binary-husky/gpt_academic/assets/110216829/40e5e320-8a51-4d5b-904d-7fb02565193e)
![7d3ec63319dffdee48f2c8204762dbb](https://github.com/binary-husky/gpt_academic/assets/110216829/bb2b6963-2985-4c7c-939f-e1bcbe8bc47f)

**Comment by BigBMonster** [comment]
突然就可以用了  有点玄学

**Comment by daoyeshan** [comment]
> 突然就可以用了 有点玄学
是的

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/673faf8cefea374aae564132119444aa777ff049
