### ISSUE TITLE
代理和api都配置成功，未自动跳出网页，输入url后报错，无法进入网页。

### ISSUE THREAD

**Issue by Jaakko3311** [binary-husky/gpt_academic#1169]
![微信图片_20231014100933](https://github.com/binary-husky/gpt_academic/assets/147489683/6c1d2d74-bdb8-4871-b8d2-c24242b5fac5)
![微信图片_20231014100933](https://github.com/binary-husky/gpt_academic/assets/147489683/63f065f8-db77-4fc8-9e88-7eecef98b0cf)

**Comment by Jaakko3311** [comment]
![微信图片_20231014101039](https://github.com/binary-husky/gpt_academic/assets/147489683/7dc75446-a286-40c0-8700-cd81b0f59205)

**Comment by binary-husky** [comment]
新版本应该已经修复了，请确认？
