### ISSUE TITLE
[Feature]: 希望可以添加能够一次性翻译多篇ArXiv论文的功能。

### ISSUE THREAD

**Issue by ZijianShao** [binary-husky/gpt_academic#1171]
### Class | 类型

函数插件

### Feature Request | 功能请求

非常感谢您做的工具！
希望可以添加能够一次性翻译多篇ArXiv论文的功能。实现一次性输入多个论文号，自动批量翻译论文。

**Comment by binary-husky** [comment]
我们有CLI调用的方法
