### ISSUE TITLE
[Bug]: Docker部署方案四 Latex环境报错

### ISSUE THREAD

**Issue by zhiqing0205** [binary-husky/gpt_academic#1175]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

FileNotFoundError: [Errno 2] No such file or directory: 'pdflatex'

### Screen Shot | 有帮助的截图

![](https://img.ziuch.top/i/2023/10/18/8dgqyy-2.webp)

**Comment by binary-husky** [comment]
this patch should make it work:

https://github.com/binary-husky/gpt_academic/commit/20e3eee6e7a4a382645c7f4cd31177afd6116fff

**Comment by pcx-pcx** [comment]
可修改为：subprocess.Popen(['pdflatex','-version'],shell=True)
