### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TangKLSUSTC** [binary-husky/gpt_academic#1177]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

chatGLM模型无法加载，报“NameError: name '_C' is not defined”的错误
一键安装脚本安装的环境和依赖项，使用脚本提示的“pip install -r request_llm/requirements_chatglm.txt”后出现此错误
chatglm依赖项是使用“.\installer_files\env\python.exe”环境安装的

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/48979603/bd02ced8-347f-4884-85fb-87fa451bc79f)

**Comment by binary-husky** [comment]
https://github.com/pytorch/pytorch/issues/1633

我不能复现？需要多方确认该问题

**Comment by binary-husky** [comment]
其他人碰到这个情况麻烦reopen一下
