### ISSUE TITLE
报错求助

### ISSUE THREAD

**Issue by dylan-strive** [binary-husky/gpt_academic#1180]
[Local Message] 异常

Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 196, in predict
    chunk = next(stream_response)
            ^^^^^^^^^^^^^^^^^^^^^
StopIteration
 
read-only
以上报错怎么解决，有小伙伴知道吗

**Comment by binary-husky** [comment]
信息不足

**Comment by dylan-strive** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/115934680/696fa490-2a9f-4f37-8f53-117ff6a8e883)
- 查看对应的报错内容，对应于bridge_chatgpt.py中代码行196。
- 是否是因为使用的非openai官网API 
- 如果是，有小伙伴知道有哪些途径可以购买官方API 
谢谢！

**Comment by binary-husky** [comment]
提供一下前后端的完整截图

**Comment by dylan-strive** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/115934680/d21117ad-7098-4156-a676-ac629e016c6c)
![image](https://github.com/binary-husky/gpt_academic/assets/115934680/cb0d01f2-c73b-4683-b4fe-1b3424389518)
![屏幕截图 2023-10-18 190512](https://github.com/binary-husky/gpt_academic/assets/115934680/5b8d3561-076f-403b-9664-8574900f2f42)
![image](https://github.com/binary-husky/gpt_academic/assets/115934680/21503c8d-2cd8-4d64-bd4c-f6fdeee48f69)
- 上图为配置的API的url

**Comment by binary-husky** [comment]
API的url是错的，v1/chat/completions也要对应上
