### ISSUE TITLE
分享一个huggingface的dockerfile的部署方法，感觉还可以，可以直接同步最新代码

### ISSUE THREAD

**Issue by xqx121** [binary-husky/gpt_academic#1183]
<html>
<body>

--
  | FROM python:3.8
  |  
  | # 安装 git
  | RUN apt-get update && apt-get install -y git
  |  
  | # 克隆仓库
  | RUN git clone https://github.com/binary-husky/gpt_academic.git
  |  
  | # 切换到子目录
  | WORKDIR /gpt_academic
  |  
  | # 创建缓存目录和日志目录
  | RUN mkdir  /.cache && chmod 777  /.cache
  | RUN mkdir /gpt_academic/gpt_log && chmod 777 /gpt_academic/gpt_log
  |  
  | # 为 'private_upload' 创建目录并设置权限
  | RUN mkdir /gpt_academic/private_upload && chmod 777 /gpt_academic/private_upload
  |  
  | # 安装依赖包
  | RUN pip install -r requirements.txt
  | RUN pip install --upgrade nougat-ocr tiktoken
  |  
  | # 将MPLCONFIGDIR环境变量设置为可写的目录
  | ENV MPLCONFIGDIR=/gpt_academic/.matplotlib
  |  
  | # 创建MPLCONFIGDIR目录
  | RUN mkdir $MPLCONFIGDIR && chmod 777 $MPLCONFIGDIR
  |  
  | # 非必要步骤，用于预热模块
  | RUN python3  -c 'from check_proxy import warm_up_modules; warm_up_modules()'
  |  
  | ENV WEB_PORT=7860
  |  
  | # 启动
  | CMD ["python3", "-u", "main.py"]

</body

</html>
![image](https://github.com/binary-husky/gpt_academic/assets/78908927/b159c78c-e088-4316-b76e-49337d4a5edb)

**Comment by xqx121** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/78908927/077b80bf-9987-47af-ae1b-624a1b748e24)

**Comment by RikkaLzw** [comment]
> --   | FROM python:3.8   |     | # 安装 git   | RUN apt-get update && apt-get install -y git   |     | # 克隆仓库   | RUN git clone https://github.com/binary-husky/gpt_academic.git   |     | # 切换到子目录   | WORKDIR /gpt_academic   |     | # 创建缓存目录和日志目录   | RUN mkdir /.cache && chmod 777 /.cache   | RUN mkdir /gpt_academic/gpt_log && chmod 777 /gpt_academic/gpt_log   |     | # 为 'private_upload' 创建目录并设置权限   | RUN mkdir /gpt_academic/private_upload && chmod 777 /gpt_academic/private_upload   |     | # 安装依赖包   | RUN pip install -r requirements.txt   | RUN pip install --upgrade nougat-ocr tiktoken   |     | # 将MPLCONFIGDIR环境变量设置为可写的目录   | ENV MPLCONFIGDIR=/gpt_academic/.matplotlib   |     | # 创建MPLCONFIGDIR目录   | RUN mkdir $MPLCONFIGDIR && chmod 777 $MPLCONFIGDIR   |     | # 非必要步骤，用于预热模块   | RUN python3 -c 'from check_proxy import warm_up_modules; warm_up_modules()'   |     | ENV WEB_PORT=7860   |     | # 启动   | CMD ["python3", "-u", "main.py"]
> 
> ![image](https://github.com/binary-husky/gpt_academic/assets/78908927/b159c78c-e088-4316-b76e-49337d4a5edb)

一直building

**Comment by RikkaLzw** [comment]
> --   | FROM python:3.8   |     | # 安装 git   | RUN apt-get update && apt-get install -y git   |     | # 克隆仓库   | RUN git clone https://github.com/binary-husky/gpt_academic.git   |     | # 切换到子目录   | WORKDIR /gpt_academic   |     | # 创建缓存目录和日志目录   | RUN mkdir /.cache && chmod 777 /.cache   | RUN mkdir /gpt_academic/gpt_log && chmod 777 /gpt_academic/gpt_log   |     | # 为 'private_upload' 创建目录并设置权限   | RUN mkdir /gpt_academic/private_upload && chmod 777 /gpt_academic/private_upload   |     | # 安装依赖包   | RUN pip install -r requirements.txt   | RUN pip install --upgrade nougat-ocr tiktoken   |     | # 将MPLCONFIGDIR环境变量设置为可写的目录   | ENV MPLCONFIGDIR=/gpt_academic/.matplotlib   |     | # 创建MPLCONFIGDIR目录   | RUN mkdir $MPLCONFIGDIR && chmod 777 $MPLCONFIGDIR   |     | # 非必要步骤，用于预热模块   | RUN python3 -c 'from check_proxy import warm_up_modules; warm_up_modules()'   |     | ENV WEB_PORT=7860   |     | # 启动   | CMD ["python3", "-u", "main.py"]
> 
> ![image](https://github.com/binary-husky/gpt_academic/assets/78908927/b159c78c-e088-4316-b76e-49337d4a5edb)

![image](https://github.com/binary-husky/gpt_academic/assets/128763841/78515f65-cbbc-4ae6-b6fb-92fb562f115e)

**Comment by BDTA-zky** [comment]
请问怎么改成自己的中转接口啊

**Comment by xqx121** [comment]
设置一下环境变量应该可以吧，ENV API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://reverse-proxy-url/v1/chat/completions"}
