### ISSUE TITLE
[Bug]:  路径拼接错误，导致无法访问文件而停止服务

### ISSUE THREAD

**Issue by znsoftm** [binary-husky/gpt_academic#1185]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

目前最新版本，2023.11.21

### OS | 操作系统
Windows 
Please choose | 请选择

### Describe the bug | 简述

 C:\\Users\\ma139/arxiv_cache/2310.10631\\workfolder\\sections/appendix\\qualitative

如上，在win平台下，路径拼接有unix也有win风格，导致程序无法访问本地文件

建议处理方法： 改为os.sep作为分隔符

重现方法：翻译 arxiv文档： 2310.10631

### Screen Shot | 有帮助的截图
![L2@$ROP0B}@AOR @1DCB(1I](https://github.com/binary-husky/gpt_academic/assets/15354249/916959cb-080a-4358-ac79-708539833e00)

![E63(H8)FE1S39V7D~G0 QMA](https://github.com/binary-husky/gpt_academic/assets/15354249/0c6ed085-5c64-44c2-b4b5-2397a19cf177)

**Comment by znsoftm** [comment]
linux /windows 平台都不工作。

**Comment by binary-husky** [comment]
很遗憾，这个问题和路径拼接错误无关，作者使用了一个很奇怪的input命令，input了一个目录，移除相关代码后，调用本地latex翻译插件即可

**Comment by binary-husky** [comment]
我标记一个这个issue以待后续处理

**Comment by binary-husky** [comment]
以下是经过翻译的pdf，由于几个油尽灯枯的api key干扰，有部分文本没有翻译

[2023-10-21-15-46-16-comparison.pdf](https://github.com/binary-husky/gpt_academic/files/13061137/2023-10-21-15-46-16-comparison.pdf)

**Comment by znsoftm** [comment]
在本地测试通过。
