### ISSUE TITLE
[Bug]: [Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

### ISSUE THREAD

**Issue by Cominder** [binary-husky/gpt_academic#1186]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

clash, 全局代理，无法连接

### Screen Shot | 有帮助的截图

<img width="986" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/19499571/6998b521-121e-480a-8185-b2fc8e6cf7c5">
<img width="759" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/19499571/645deeef-4feb-4543-8c97-2fccc00261f2">
<img width="444" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/19499571/95832e48-29fb-4a02-aeae-432bf2f2f8c3">

**Comment by binary-husky** [comment]
#1

**Comment by Cominder** [comment]
<img width="979" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/19499571/a097039f-f7e6-4ca4-880a-a37dd3da9582">
<img width="723" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/19499571/2e5c87fa-b7cf-4a0b-837a-35ff14018eee">

**Comment by SISTMrL** [comment]
@Cominder 你好我也是mac + clash，也是出现跟你一样的问题，请问你是如何解决的
