### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jj023721** [binary-husky/gpt_academic#1191]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

[Local Message] 不能加载Newbing组件。

Traceback (most recent call last):
  File ".\request_llm\bridge_newbingfree.py", line 140, in run
    self.newbing_model = NewbingChatbot(proxy=self.proxies_https, cookies=cookies)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\request_llm\edge_gpt_free.py", line 631, in __init__
    self.chat_hub: _ChatHub = _ChatHub(
                              ^^^^^^^^^
  File ".\request_llm\edge_gpt_free.py", line 430, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/89644056/9fb287f4-6338-47ea-ae71-ad13c62b38cc)


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by binary-husky** [comment]
Newbing不再受到支持

**Comment by jj023721** [comment]
你好，这里是蒋永梁，你的邮件已收到！
