### ISSUE TITLE
[Bug]: 文心一言配置完毕后报错

### ISSUE THREAD

**Issue by shiliu2023** [binary-husky/gpt_academic#1196]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

  File "/root/gpt_academic/request_llm/bridge_qianfan.py", line 109, in generate_from_baidu_qianfan
    incoming = dec['result']
               ~~~^^^^^^^^^^
KeyError: 'result'

### Screen Shot | 有帮助的截图

  File "/root/gpt_academic/request_llm/bridge_qianfan.py", line 109, in generate_from_baidu_qianfan
    incoming = dec['result']
               ~~~^^^^^^^^^^
KeyError: 'result'

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by binary-husky** [comment]
详细描述下config中的相关配置？
