### ISSUE TITLE
[Bug]: json解析不合常规

### ISSUE THREAD

**Issue by raywang2018** [binary-husky/gpt_academic#1203]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

部署完成后在输入区输入问题提交后，会出现Json异常，405 Not Allowed的错误

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/37130471/b01ebbf0-93a6-4604-90d1-3fe4bf00319d)

**Comment by raywang2018** [comment]
运行界面的报错
![image](https://github.com/binary-husky/gpt_academic/assets/37130471/84f6f231-652e-4966-92bf-e2f3b45b7abf)

**Comment by binary-husky** [comment]
盲猜是自定义url写错了

**Comment by raywang2018** [comment]
> 盲猜是自定义url写错了

谢谢大佬！应该是这个问题。
