### ISSUE TITLE
[Bug]: Arxiv论文精细翻译在长论文中，会出现较大部分页面没有翻译

### ISSUE THREAD

**Issue by Curisan** [binary-husky/gpt_academic#1207]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

Arxiv论文精细翻译插件翻译llama2论文时，前十几页页有翻译，后面几乎没有翻译（试了两次，第一次从20页后无翻译，第二次从17页后无翻译，但是到37页后又有三四页翻译）
输入为llama2 arxiv 链接： https://arxiv.org/abs/2307.09288

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/22990773/513298bd-f8e0-4db9-953e-5a6cb77d7189)

**Comment by binary-husky** [comment]
有可能是论文的一部分本身是pdf的，作者没有提供tex源码。您可以尝试在高级参数输入区输入`--no-cache`再试一次，如果结果依旧，则很可能是这种情况

**Comment by Curisan** [comment]
仔细看了下源代码和latex文件，是代码中没有处理include标签造成的，凡是有include标签的，都不会去翻译

**Comment by Curisan** [comment]
@binary-husky
