### ISSUE TITLE
第三方key不是32位数字

### ISSUE THREAD

**Issue by dfmjndm** [binary-husky/gpt_academic#1209]
### Class | 类型

None

### Feature Request | 功能请求

第三方key用的是sk-123这种格式
由于位数不是32位所以报了
您提供的api-key不满足要求，不包含任何可用于gpt-4的api-key。您可能选择了错误的模型或请求源。

我需要注释哪部分代码取消这个检测

**Comment by binary-husky** [comment]
见wiki

**Comment by dfmjndm** [comment]
> 见wiki

如果您是指 #170 的话我已经看过了，我的目录中没有config_private.py
而且KEY 就是 sk-536 ，只有6个字符没有51个字符
