### ISSUE TITLE
[Bug]: docker-compose.yaml中无法用json格式进行配置环境变量API_URL_REDIRECT

### ISSUE THREAD

**Issue by bkzy333** [binary-husky/gpt_academic#1211]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

在docker-compose.yaml中无法用json格式进行配置，docker-compose的环境变量仅支持纯文本格式。该如何改动环境变量API_URL_REDIRECT呢？
以下代码会报错提示【API_URL_REDIRECT必须是字符串、数字、布尔值或 null。】
environment:
API_KEY: 'sk-RQ1232134l,sk-Y435656x'
API_URL_REDIRECT:{"https://api.openai.com/v1/chat/completions":"https://xxxx.yyyy.zzzz/v1/chat/completions"}(https://api.openai.com/v1/chat/completions%22:%22https://xxxx.yyyy.zzzz/v1/chat/completions%22%7D)

于是我改成以下代码，运行docker-compose up的时候没有报错，但环境变量API_URL_REDIRECT没有改动为第三方url
environment:
API_KEY: 'sk-RQ1232134l,sk-Y435656x'
API_URL_REDIRECT: "https://api.openai.com/v1/chat/completions,https://api.chatanywhere.com.cn"
和
 API_URL_REDIRECT: "https://api.chatanywhere.com.cn"

### Screen Shot | 有帮助的截图

返回的错误日志
`gpt-3.5-turbo : 1 : 你好，你是什么模型？ ..........
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
sock = connection.create_connection(
File "/gpt/toolbox.py", line 88, in decorated
yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
File "/gpt/request_llm/bridge_all.py", line 568, in predict
yield from method(inputs, llm_kwargs, *args, **kwargs)
File "/gpt/request_llm/bridge_chatgpt.py", line 187, in predict
if retry > MAX_RETRY: raise TimeoutError
`

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

页面返回的信息：[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

**Comment by binary-husky** [comment]
加个单引号，参考
![Uploading image.png…]()

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/1b5d5079-c7f0-43c4-a955-347803fcc38b)
