### ISSUE TITLE
[Bug]: 选择了gpt-4模型，但是问答显示还是用的gpt-3

### ISSUE THREAD

**Issue by Alexzandera14** [binary-husky/gpt_academic#1214]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

选择了gpt-4的模型，但是问答过程显示还是gpt-3
我的账号是chatgpt Plus版本，可以使用gpt-4

### Screen Shot | 有帮助的截图

![0be803fc107ea76267b92a7d19ecb37](https://github.com/binary-husky/gpt_academic/assets/149370760/b2c759a9-43d2-4861-9843-611af8038d05)

**Comment by binary-husky** [comment]
正常，gpt4就是这样的。改一下prompt就好了，以下是GPT4的官方prompt: 

```
You are ChatGPT, a large language model trained by OpenAI, based on the GPT-4 architecture.
Knowledge cutoff: 2022-01
Current date: 2023-10-xx
```

**Comment by Alexzandera14** [comment]
![d2b77cebd58f343185b380730b5a36f](https://github.com/binary-husky/gpt_academic/assets/149370760/6a6b9fc4-4859-485c-b0cd-3b7b495167cc)
您的意思是不是，虽然我问他是什么模型的时候他回答自己是gpt-3，但实际上模型已经切换到gpt-4了？因为我选了gpt4模型之后，问他一些2022年的问题，他就说自己是gpt3，只更新到2020年~
