### ISSUE TITLE
[Bug]: chatglm不能使用，缺少nvrtc-builtins64_121.dll文件

### ISSUE THREAD

**Issue by luolundashu** [binary-husky/gpt_academic#1216]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

报错如下
 query_layer = apply_rotary_pos_emb(query_layer, rotary_pos_emb)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: nvrtc: error: failed to open nvrtc-builtins64_121.dll.
  Make sure that nvrtc-builtins64_121.dll is installed correctly.
  
应该是缺少nvrtc-builtins64_121.dll这个文件

### Screen Shot | 有帮助的截图

无

**Comment by binary-husky** [comment]
本地模型建议在linux+docker上使用

**Comment by swjtu510** [comment]
我也是遇到同样的问题，请问该怎么解决呢

**Comment by luolundashu** [comment]
没解决，用gpt去了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月4日(星期一) 晚上7:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/gpt_academic] [Bug]: chatglm不能使用，缺少nvrtc-builtins64_121.dll文件 (Issue #1216)





 
我也是遇到同样的问题，请问该怎么解决呢

**Comment by E-chain** [comment]
我也碰到了这个问题，后来发现是pytorch和cuda版本不匹配导致的，缺少nvrtc-builtins64_121是因为需要12.1版本的cuda，但我装了12.3，回退版本之后解决啦
