### ISSUE TITLE
[Bug]: 本地latex论文精细翻译结果中，最为关键的转化PDF编译失败

### ISSUE THREAD

**Issue by Administor123** [binary-husky/gpt_academic#1218]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

翻译完之后出现了如下问题：

正在编译PDF文档
编译已经开始。当前工作路径为gpt_log\default\shared/2023-10-31-14-29-28，如果程序停顿5分钟以上，请直接去该路径下取回翻译结果，或者重启之后再度尝试 ...

正在编译PDF文档
由于最为关键的转化PDF编译失败, 将根据报错信息修正tex源文件并重试, 当前报错的latex代码处于第[-1]行 ...

失败了
虽然PDF生成失败了, 但请查收结果（压缩包）, 内含已经翻译的Tex文档, 您可以到Github Issue区, 用该压缩包进行反馈。如系统是Linux，请检查系统字体（见Github wiki） ...

报告如何远程获取？
报告已经添加到右侧“文件上传区”（可能处于折叠状态），请查收。
[gpt_log\default\shared\2023-10-31-14-53-11-2023-10-31-14-53-10-result.zip](http://localhost:10149/file=F:/PycharmProject/chat_academy/gpt_log/default/shared/2023-10-31-14-53-11-2023-10-31-14-53-10-result.zip)
[gpt_log\default\shared\2023-10-31-14-51-23-2023-10-31-14-51-23.trans.html](http://localhost:10149/file=F:/PycharmProject/chat_academy/gpt_log/default/shared/2023-10-31-14-51-23-2023-10-31-14-51-23.trans.html)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/86997302/2e69a803-40e8-4aac-a513-96fddedc753e)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

无

**Comment by Administor123** [comment]
请问这个问题好解决吗

**Comment by binary-husky** [comment]
检查下压缩包里面的日志，看看是不是字体错误。

**Comment by quduoduo** [comment]
我用GPT翻译成功了，用星火API v2.0失败了，供参考。

**Comment by HIT-ZY** [comment]
请问怎么检查是不是字体错误
