### ISSUE TITLE
主题NoCrypt/Miku无法选用

### ISSUE THREAD

**Issue by Meetzyj** [binary-husky/gpt_academic#1229]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

不管是在设置里还是在ui里切换主题NoCrypt/Miku均会报错

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/109496347/5d91391c-8c9a-4361-906c-9b99cccbe86e)
![image](https://github.com/binary-husky/gpt_academic/assets/109496347/8267cbe9-1a12-49f2-a4eb-b272a374244a)

**Comment by binary-husky** [comment]
配置来自hf的主题，必须需要配置代理（HF被gfw封了）
