### ISSUE TITLE
Enhancement: Add more programming language support

### ISSUE THREAD

**Issue by QGrain** [binary-husky/gpt_academic#123]
Hi, thanks for your great job!

However, `chatgpt_academic` currently only support parsing python or C/C++ programs. **Could you please add more programming language support?**

I've briefly read the feature-related code [解析项目源代码.py](https://github.com/binary-husky/chatgpt_academic/blob/master/crazy_functions/%E8%A7%A3%E6%9E%90%E9%A1%B9%E7%9B%AE%E6%BA%90%E4%BB%A3%E7%A0%81.py). It seems to just categorize the projects (Python and C/C++ Only) according to the file extension and then distribute them to the `function 解析源代码()` for parsing. Therefore, it should be feasible and simple to add support for go, rust, java, js, shell, and more languages.

In more detail, an **adaptive** project parsing class could be built for projects with different languages. If possible, I'd like to help to implement this feature and make a PR.

**Comment by adrianzzk** [comment]
im looking forward to it bro

**Comment by binary-husky** [comment]
welcome any functional plugin PR，

additionally some minor [advance](https://github.com/binary-husky/chatgpt_academic/wiki/%5B%E5%A4%87%E5%BF%98%E5%BD%95%5D-%E5%87%BD%E6%95%B0%E6%8F%92%E4%BB%B6PR%E7%9A%84%E5%B0%8F%E5%B0%8F%E5%BB%BA%E8%AE%AE%EF%BC%88%E4%B8%BA%E4%BA%86merge%E6%97%B6%E5%B0%91%E6%8E%89%E5%A4%B4%E5%8F%91%E2%80%A6%E2%80%A6%EF%BC%89) for help us merge quickly (but don't worry, we will also take care of it after pr):
