### ISSUE TITLE
[Bug]: spark

### ISSUE THREAD

**Issue by advancfa** [binary-husky/gpt_academic#1230]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

spark如何配置我将，我将XFYUN_APPID, XFYUN_API_KEY, XFYUN_API_SECRET配置好后出现了错误{'header': {'code': 11200, 'message': 'AppIdNoAuthError:(12:17:04.432) tokens.total', 'sid': 'cht000b5e72@dx18b988c77afb81b540', 'status': 2}}

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/147598606/fc949d84-9542-4850-9295-486ebbd41fe6)

**Comment by binary-husky** [comment]
请询问讯飞官方
