### ISSUE TITLE
[Feature]: 希望改善溢出处理行为

### ISSUE THREAD

**Issue by samxiaowastaken** [binary-husky/gpt_academic#1232]
### Class | 类型

程序主体

### Feature Request | 功能请求

我在进行PDF精确翻译时发现部分特殊论文在作者人数很多的时候会出现GPT3.5-4k token溢出的情况。在部分极端情况下不能预测剩余token数量，截断文本不成功，会再次翻译作者列表导致溢出并进入死循环，直到达到尝试次数。实测6篇选自中科院TOP期刊的论文中，有2篇出现了该问题。

体现如下：
<img width="783" alt="c0d7cf589e481c4cd4143d49b88d469" src="https://github.com/binary-husky/gpt_academic/assets/76235458/c3aff32c-8d4a-4220-88cd-2042d14fc6a0">

在批量翻译pdf的时候因为文字量很大，开支会不小。使用token上限小的3.5会省下一半的钱，尤其是在一些上下文关系不明显的文章中，使用小token模型更加经济。

我看到pull requests中有一个增加自动切换模型的功能，该功能在需要节约成本的情况下会很有帮助，并且省下溢出重试的时间。希望可以考虑加入自动切换模型的功能，并且在设置中提供溢出行为选项，例如：切换模型、自动截断、手动截断、暂停/停止任务的开关。

**Comment by binary-husky** [comment]
把参考文献中的作者当成论文作者

**Comment by samxiaowastaken** [comment]
额，我看到openAI刚刚发布了新的API模型，3.5turbo的速度变快了很多，并且用比原来4k更低的价格可以用到16k模型了，希望可以尽快更新一下

**Comment by samxiaowastaken** [comment]
16K似乎挺难溢出的（）应该可以缓解该问题

**Comment by binary-husky** [comment]
最新的版本截断了author列表，可以缓解该问题
