### ISSUE TITLE
[Bug]: 页大小非4KB或16KB时使用精准翻译PDF（NOUGAT）报错闪退

### ISSUE THREAD

**Issue by hb5813** [binary-husky/gpt_academic#1235]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

在arm-v8a架构CPU，linux的页大小为64KB的环境下，使用精准翻译PDF（NOUGAT）功能将产生报错，并闪退。

### Screen Shot | 有帮助的截图

报错信息为：
[FATAL:partition_root.cc(958)] Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14)). 
#00 0xfffba2a52900  (/home/opc/.local/lib/python3.11/site-packages/pypdfium2_raw/libpdfium.so+0x3c2900)
#01 0xfffba2a5b090  (/home/opc/.local/lib/python3.11/site-packages/pypdfium2_raw/libpdfium.so+0x3cb090)
#02 0xfffba2a55ffc  (/home/opc/.local/lib/python3.11/site-packages/pypdfium2_raw/libpdfium.so+0x3c5ffc)
#03 0xfffba28e23d0  (/home/opc/.local/lib/python3.11/site-packages/pypdfium2_raw/libpdfium.so+0x2523d0)
#04 0xfffba2a02898  (/home/opc/.local/lib/python3.11/site-packages/pypdfium2_raw/libpdfium.so+0x372898)
#05 0xfffbf72750bc  (/usr/lib64/libffi.so.6.0.2+0x50bc)
#06 0xfffbf72759e8  (/usr/lib64/libffi.so.6.0.2+0x59e8)
#07 0xfffbf72b33c8  (/usr/lib64/python3.11/lib-dynload/_ctypes.cpython-311-aarch64-linux-gnu.so+0x133c8)
#08 0xfffbf72b3ed8  (/usr/lib64/python3.11/lib-dynload/_ctypes.cpython-311-aarch64-linux-gnu.so+0x13ed8)
#09 0xfffc027bf1a4  (/usr/lib64/libpython3.11.so.1.0+0x1df1a4)
#10 0xfffc0275edac  (/usr/lib64/libpython3.11.so.1.0+0x17edac)
#11 0xfffc02877008  (/usr/lib64/libpython3.11.so.1.0+0x297008)
#12 0xfffc0287c94c  (/usr/lib64/libpython3.11.so.1.0+0x29c94c)
#13 0xfffc027835d0  (/usr/lib64/libpython3.11.so.1.0+0x1a35d0)
#14 0xfffc027821f0  (/usr/lib64/libpython3.11.so.1.0+0x1a21f0)
#15 0xfffc0276316c  (/usr/lib64/libpython3.11.so.1.0+0x18316c)
#16 0xfffc027f7104  (/usr/lib64/libpython3.11.so.1.0+0x217104)
#17 0xfffc027c5e28  (/usr/lib64/libpython3.11.so.1.0+0x1e5e28)
#18 0xfffc02824588  (/usr/lib64/libpython3.11.so.1.0+0x244588)
#19 0xfffc0276fb7c  (/usr/lib64/libpython3.11.so.1.0+0x18fb7c)
#20 0xfffc02765a0c  (/usr/lib64/libpython3.11.so.1.0+0x185a0c)
#21 0xfffc02877008  (/usr/lib64/libpython3.11.so.1.0+0x297008)
#22 0xfffc0287c94c  (/usr/lib64/libpython3.11.so.1.0+0x29c94c)
#23 0xfffc027835d0  (/usr/lib64/libpython3.11.so.1.0+0x1a35d0)
#24 0xfffc027821f0  (/usr/lib64/libpython3.11.so.1.0+0x1a21f0)
#25 0xfffc0276316c  (/usr/lib64/libpython3.11.so.1.0+0x18316c)
#26 0xfffc027f7104  (/usr/lib64/libpython3.11.so.1.0+0x217104)
#27 0xfffc027c5e28  (/usr/lib64/libpython3.11.so.1.0+0x1e5e28)
#28 0xfffc02824588  (/usr/lib64/libpython3.11.so.1.0+0x244588)
#29 0xfffc0276fb7c  (/usr/lib64/libpython3.11.so.1.0+0x18fb7c)
#30 0xfffc02765a0c  (/usr/lib64/libpython3.11.so.1.0+0x185a0c)
#31 0xfffc02877008  (/usr/lib64/libpython3.11.so.1.0+0x297008)
Trace/breakpoint trap (core dumped)

**Comment by binary-husky** [comment]
这个是nougat的报错，本项目似乎无从解决，建议去nougat那边反馈一下？
