### ISSUE TITLE
requirments.txt[Bug]: 

### ISSUE THREAD

**Issue by zougang123** [binary-husky/gpt_academic#1236]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Windows

### Describe the bug | 简述

![image](https://github.com/binary-husky/gpt_academic/assets/105329638/70d81092-1232-43db-8c95-6ec5372bc116)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/105329638/546cd810-1ded-4e32-bcfd-a9ecc5daf2d5)

**Comment by zougang123** [comment]
请问这个是什么原因，怎么解决？

**Comment by zougang123** [comment]
家人们，谁懂啊

**Comment by binary-husky** [comment]
先cd
