### ISSUE TITLE
[Feature]: 新增对于OpenAI图像对话模型的支持

### ISSUE THREAD

**Issue by samxiaowastaken** [binary-husky/gpt_academic#1239]
### Class | 类型

大语言模型

### Feature Request | 功能请求

我注意到OpenAI还发布了一个支持图像输入的语言模型，这个模型在网页版PLUS订阅的表现很不错，可以识别图表和手写并给出解释，应该对于解释论文中的图表很有用，是否会考虑加入对于图像模型的支持？

顺便，我刚刚PR了一下OpenAI刚刚发布的新的模型，包含新的GPT3.5turbo（16k）以及GPT4turbo，希望通过一下。

**Comment by binary-husky** [comment]
PR已通过，GPT4V正在整合

**Comment by binary-husky** [comment]
已支持
