### ISSUE TITLE
[Feature]: Local model

### ISSUE THREAD

**Issue by rosx27** [binary-husky/gpt_academic#1243]
### Class | 类型

大语言模型

### Feature Request | 功能请求

Maybe i haven't thoroughly tested the program yet but I can't seem to find an option to use local LLM running on text-generation webui with --openai flag.

If this is already implemented, please point me to where should i input the local URL of text-generation webui.

Also, since autogen is included in this package, can we have a multi local LLM config fo this? e.g.: similar to autogen's OAI_CONFIG_LIST
```
[
    {
        "name": "creative",
	"model": "CodeLlama Instruct",
        "api_key": "NULL",
        "api_base": "http://localhost:1234/v1"
    },
    {
        "name": "analytic",
	"model": "Phined CodeLlama Python",
        "api_key": "NULL",
        "api_base": "http://localhost:5001/v1"
    }
]
```

based on above config, I'm using LM Studio and text-generation webui.

**Comment by binary-husky** [comment]
Hi, this project support text-generation webui in previous version, but we have not been able to follow the latest updates of TGUI ...

The implemenation of AutoGen is **still in progress**, soon we will release it, we are working on two ends:
- implementing gpt-academic interface to AutoGen resp
- implementing AutoGen as GPT-Academic plugin

Thank you for asking!
