### ISSUE TITLE
[Bug]: 梯子为ssr如何配置网络地址？

### ISSUE THREAD

**Issue by Wanbi1** [binary-husky/gpt_academic#1249]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

最近更换了梯子，现在使用ssr，不知道如何调整协议？

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/110647344/664f1765-73cb-45be-af31-8f9f08e7cbc7)
![image](https://github.com/binary-husky/gpt_academic/assets/110647344/1ddb6930-b42d-498d-a371-7d4d58ed423f)

**Comment by Wanbi1** [comment]
问题已解决，请管理员删除此issue

**Comment by binary-husky** [comment]
#1
