### ISSUE TITLE
[Bug]: 对接one api后报错

### ISSUE THREAD

**Issue by itq5** [binary-husky/gpt_academic#1250]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

对接one api后报错后执行报错
![image](https://github.com/binary-husky/gpt_academic/assets/42521985/db70aee0-3abc-42e5-9dc0-8eb17b4ce3eb)
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.*****.com/"}

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/42521985/db70aee0-3abc-42e5-9dc0-8eb17b4ce3eb)

**Comment by binary-husky** [comment]
API_URL_REDIRECT 填写的格式不对
