### ISSUE TITLE
[Feature]: Provides multiple versions of GPT

### ISSUE THREAD

**Issue by Lyther** [binary-husky/gpt_academic#1251]
### Class | 类型

大语言模型

### Feature Request | 功能请求

The OpenAI has a list of all the GPT models, some of them are awesome.

For example, `gpt-4-1106-preview` now has a 128,000 tokens context width, which is about 128K text input. GPT3 also has a 16K version called `gpt-3.5-turbo-16k`. I highly recommend adding new models to the GPT Academic.

**Comment by binary-husky** [comment]
yes we have just updated our model list !
