### ISSUE TITLE
arXiv 精细翻译出来还是英文[Bug]: 

### ISSUE THREAD

**Issue by sun-i** [binary-husky/gpt_academic#1253]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

arXiv 精细翻译出来还是英文

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/111034439/ee319c11-344e-4846-9481-67ab409d2895)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

arXiv id: 1709.00643

**Comment by binary-husky** [comment]
有些文章latex语法非常特殊，请尝试nougat翻译即可
