### ISSUE TITLE
[Bug]: sess接口的api-key无法使用

### ISSUE THREAD

**Issue by david-666-maker** [binary-husky/gpt_academic#1254]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

之前sk接口的api过期了，新的api是sess接口，可以查询到当前还有充足额度，但无法使用

### Screen Shot | 有帮助的截图

<img width="695" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/61860921/e623e23b-425d-4a26-823c-b34eba85ffec">

**Comment by Biocxifu** [comment]
今天也碰到了，刚拿到的key是session key，现在sess好像还不支持

**Comment by binary-husky** [comment]
如果是
API_KEY = "sess-wg61ZafYHpNz7FFwIH7HGZlbVqUVaeV5tatHCWpl"
这样的APIKEY

可以通过修改CUSTOM_API_KEY_PATTERN实现兼容
CUSTOM_API_KEY_PATTERN = r"sess-[a-zA-Z0-9]{40}"

**Comment by binary-husky** [comment]
@david-666-maker @Biocxifu

**Comment by Biocxifu** [comment]
> @david-666-maker @Biocxifu

感谢

**Comment by Biocxifu** [comment]
> 如果是 API_KEY = "sess-wg61ZafYHpNz7FFwIH7HGZlbVqUVaeV5tatHCWpl" 这样的APIKEY
> 
> 可以通过修改CUSTOM_API_KEY_PATTERN实现兼容 CUSTOM_API_KEY_PATTERN = r"sess-[a-zA-Z0-9]{40}"

请问这个参数CUSTOM_API_KEY_PATTERN在哪个文件？

**Comment by david-666-maker** [comment]
> > 如果是 API_KEY = "sess-wg61ZafYHpNz7FFwIH7HGZlbVqUVaeV5tatHCWpl" 这样的APIKEY
> > 可以通过修改CUSTOM_API_KEY_PATTERN实现兼容 CUSTOM_API_KEY_PATTERN = r"sess-[a-zA-Z0-9]{40}"
> 
> 请问这个参数CUSTOM_API_KEY_PATTERN在哪个文件里面？

就在config文件里
