### ISSUE TITLE
[Feature]: 请问支持转发的openai代理比如openkey吗

### ISSUE THREAD

**Issue by grothen** [binary-husky/gpt_academic#1258]
### Class | 类型

None

### Feature Request | 功能请求

我设置了
`API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": https://openkey.cloud}
`
目前的问题是似乎无法识别为openaikey，显示为
`[API_KEY] 您的 API_KEY 不满足任何一种已知的密钥格式`
我令toolbox.py中的is_openai_api_key(key)函数总是返回true后显示了这个
<img width="734" alt="CleanShot 2023-11-11 at 21 54 05@2x" src="https://github.com/binary-husky/gpt_academic/assets/3252576/539a6c8d-a87f-4bce-8ea9-ac0e71051795">

P.S.
这个服务的key的形式大约为sk-数字/大小写字母{48}

**Comment by binary-husky** [comment]
API_URL_REDIRECT 格式不正确

**Comment by grothen** [comment]
自问自答一下
`API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": https://openkey.cloud}`需要改成
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://openkey.cloud/v1/chat/completions"}
