### ISSUE TITLE
[Bug]: 网络无法连接到chatgpt

### ISSUE THREAD

**Issue by adrianzzk** [binary-husky/gpt_academic#1260]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

通过自动升级功能update到3.59版本，运行发现无法访问网络，提示检查端口。根据以往经验，无需更改config。
同时还提示我AZURE_ENDPOINT这个变量的相关内容出错，将变量名里的内容删除后提示我无法访问
回滚至3.57版本，可以正常使用。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/96020706/4f712c38-7e1e-444b-999a-4b1b7b5ee324)
![image](https://github.com/binary-husky/gpt_academic/assets/96020706/eeedd15f-01ff-4eec-a3d8-842c064eec22)

**Comment by binary-husky** [comment]
已经紧急修复
https://github.com/binary-husky/gpt_academic/commit/69f37df356889f22c8fdfebdb580cf9815a6a79d
