### ISSUE TITLE
[Bug]: Chuanhu-Small-and-Beautiful主题存在bug

### ISSUE THREAD

**Issue by adrianzzk** [binary-husky/gpt_academic#1264]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

config设置```Chuanhu-Small-and-Beautiful```主题后发现，在浏览器界面更改其他主题后会保留该主题格式，其他主题遇到此类情况则不会。
另外，我发现```NoCrypt/Miku```主题不支持对代码高亮，是主题的原因吗？我还挺喜欢这个主题的，但看代码没有高亮有点难受

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/96020706/a782b230-9492-417f-9b7e-7aff6a00c546)
![image](https://github.com/binary-husky/gpt_academic/assets/96020706/41a22f97-0664-487b-ad35-803a79103c14)

**Comment by binary-husky** [comment]
`NoCrypt/Miku`是HF社区主题，`Chuanhu-Small-and-Beautiful`来自@Keldos 大佬

**Comment by binary-husky** [comment]
NoCrypt/Miku是HF社区主题，Chuanhu-Small-and-Beautiful来自[@Keldos ](https://github.com/Keldos-Li)大佬

**Comment by binary-husky** [comment]
这个倒不是bug，仅仅是 Chuanhu-Small-and-Beautiful 涉及的css比较条目比较多。所以目前建议需要动态切换则将default作为初始主题；不需要动态切换，把 Chuanhu-Small-and-Beautiful 作为初始主题

**Comment by adrianzzk** [comment]
好的，了解了，3q
