### ISSUE TITLE
[Bug]: qianfan无法正常使用 有人遇到下面这种情况吗

### ISSUE THREAD

**Issue by ggGAObin** [binary-husky/gpt_academic#1265]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

看下图

### Screen Shot | 有帮助的截图

![微信截图_20231113203304](https://github.com/binary-husky/gpt_academic/assets/135831464/45d82541-4570-45d8-8f54-833f31762f08)
![2684a630a515b518bc8e5e5c22ba0ec](https://github.com/binary-husky/gpt_academic/assets/135831464/6a2ad839-5f21-4358-b997-4ec4bc637224)

**Comment by binary-husky** [comment]
关代理软件 + 浏览器隐私模式

**Comment by ggGAObin** [comment]
thanks
