### ISSUE TITLE
[Feature]: config文件配置咨询

### ISSUE THREAD

**Issue by for3ever3** [binary-husky/gpt_academic#1266]
### Class | 类型

其他

### Feature Request | 功能请求

在
```
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://ai-20231112.fakeopen.com/v1/chat/completions"}
```
中，除上述例子，我想添加多个非官方的接口地址，我应该怎么写配置

在
```# 自定义API KEY格式
CUSTOM_API_KEY_PATTERN = 
```
中，我想添加多个API_KEY格式，我试过”apikey“,"apikey"不能运行，["apikey", "apikey"]不能运行
我该怎么去撰写多个apikey格式，达到支持多个不同非官方apikey的目的

**Comment by binary-husky** [comment]
这个不支持，非官方接口选个最好的就行了，多个非官方代理是不是多少显得有点邪门了。

一定要弄的话可以把这些接口用one-api统合下。

**Comment by for3ever3** [comment]
> 这个不支持，非官方接口选个最好的就行了，多个非官方代理是不是多少显得有点邪门了。
> 
> 一定要弄的话可以把这些接口用one-api统合下。

OK，谢谢，我忘了还有oneapi了
