### ISSUE TITLE
[Bug]: api key相关

### ISSUE THREAD

**Issue by eqfwrg424535** [binary-husky/gpt_academic#1267]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

不太明白这个API的运行机制 我在网上购买了一个API Key把它放到config.py里之后，能够正常启动，但是测试总是报错，我设置了

> API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.onechat.fun/chat"}
 其中 “https://api.onechat.fun/chat” 是第三方给的链接，结果出现如下错误：
Traceback (most recent call last):
  File ".\request_llms\bridge_chatgpt.py", line 242, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(chunkjson['choices'][0]["delta"]) == 0):
                                                 ~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

### Screen Shot | 有帮助的截图

[
![微信截图_20231114022038](https://github.com/binary-husky/gpt_academic/assets/48349602/0fbae289-0dad-46f2-9a7a-4a3f5070e1d2)
](url)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by binary-husky** [comment]
API_URL_REDIRECT 格式不正确
