### ISSUE TITLE
[Feature]: 不通过代理和gui，使用chatgpt

### ISSUE THREAD

**Issue by bing0037** [binary-husky/gpt_academic#1269]
### Class | 类型

程序主体

### Feature Request | 功能请求

# 现状&问题：
之前一直使用的是v2rayN，曾经本项目的代码也是能愉快地运行的。
但是，最近不知道是不是“学”网的问题，能“上网”，但是运行程序`python main.py`，要么报错“网络错误”，要不报错openai请求SSL报错。按照[#1]调试了好几天，都没成功，放弃了。。。
我用过[pythonanywhere](https://www.pythonanywhere.com/)，服务器看起来是在美国，省去了“科学”的烦恼，用openai的api，没有问题。

# 请求：
能不能把基本的功能，变成没有GUI的形式，直接代码操作，省去了“上网”问题带来的烦恼，，，
其实，我经常用的也就是论文翻译，方便我快速调研文献，感谢作者这么好的项目，让我看论文速度提升N倍，现在突然用不了了，上瘾了总是难戒。。。

感谢感谢！

**Comment by bing0037** [comment]
使用check_proxy.py，一会显示在hong kong, 一会在us, 一会又查询超时，代理可能无效，，，实在是崩溃了。。。

**Comment by bing0037** [comment]
抱歉，手欠一不小心点成close了。。。

使用check_proxy.py检查，一会显示在hongkong，一会在us，一会又查询超时，代理可能无效，崩溃了。。。

**Comment by binary-husky** [comment]
https://github.com/binary-husky/void-terminal

The CLI & python API for the well-known project gpt_academic

这个项目是我们官方的，但功能尚不完善，有任何问题欢迎issue或者qq联系
