### ISSUE TITLE
网络一直报错。。不知道到底该怎么配置了

### ISSUE THREAD

**Issue by SYZ622** [binary-husky/gpt_academic#1283]
![image](https://github.com/binary-husky/gpt_academic/assets/113154375/b10d290c-1424-4c62-86fd-c5daa005f3ce)
我用的是v2rayn，
![image](https://github.com/binary-husky/gpt_academic/assets/113154375/199f467d-1151-49d3-862a-1cceda5506b4)
希望能帮我看一下这样配置是否错误？我运行后一直报错。
![image](https://github.com/binary-husky/gpt_academic/assets/113154375/bed3a8b2-dd65-46d3-b110-41d62cfa2521)

**Comment by binary-husky** [comment]
#1

**Comment by SYZ622** [comment]
@binary-husky 感谢您的回复，但是我看过这个了，也按照上述操作进行了，仍然显示网络错误。
