### ISSUE TITLE
[Feature]: 为什么在海外proxy的代理状态还是出错？

### ISSUE THREAD

**Issue by KirakiraZLY** [binary-husky/gpt_academic#1289]
### Class | 类型

None

### Feature Request | 功能请求

大概就是如下面所示，我USE_PROXY = False没有修改，希望得到解答，谢谢。
`
PS D:\gpt_academic> python check_proxy.py
 [PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。 
代理配置 无, 代理所在地：Denmark
`

**Comment by binary-husky** [comment]
只是个提醒而已，不是报错

**Comment by KirakiraZLY** [comment]
但是当我运行后，在输入区输入内容，得到的反馈是
`
[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。
`
