### ISSUE TITLE
[Bug]:配置academic，安装 内置Gradio及其他依赖项，到这就卡住了：Building wheel for tiktoken (pyproject.toml) ... \

### ISSUE THREAD

**Issue by daoyeshan** [binary-husky/gpt_academic#1291]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

配置academic，安装 内置Gradio及其他依赖项，到这就卡住了：Building wheel for tiktoken (pyproject.toml) ... \
之前配置的时候直接就OK了，现在一直不行。网上找了一些方法都不行，请问该怎么解决啊

### Screen Shot | 有帮助的截图

![22](https://github.com/binary-husky/gpt_academic/assets/58663392/446c18f4-51ba-4887-93ff-eeac0e643bd3)

**Comment by binary-husky** [comment]
请用一键安装脚本试试，依然有问题请重开issue

**Comment by daoyeshan** [comment]
我安装visual stidio2022以后，发现就可以了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年11月17日 14:49 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [binary-husky/gpt_academic] [Bug]:配置academic，安装 内置Gradio及其他依赖项，到这就卡住了：Building wheel for tiktoken (pyproject.toml) ... \ (Issue #1291) |

请用一键安装脚本试试，依然有问题请重开issue
