### ISSUE TITLE
gpt4实际上是gpt3的api[Bug]: 

### ISSUE THREAD

**Issue by XianronZhang** [binary-husky/gpt_academic#1298]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

切换到GPT4环境，发现还是在用GPT3

### Screen Shot | 有帮助的截图

![屏幕截图 2023-11-18 174915](https://github.com/binary-husky/gpt_academic/assets/30207023/e3d2f911-b7c1-4e63-8ca9-715b411e532c)

**Comment by binary-husky** [comment]
https://community.openai.com/t/gpt-4-through-api-says-its-gpt-3/286881
