### ISSUE TITLE
[Bug]:  'Row' object has no attribute 'style'

### ISSUE THREAD

**Issue by AGoldenbread** [binary-husky/gpt_academic#1300]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

 'Row' object has no attribute 'style'

### Screen Shot | 有帮助的截图

代理所在地：未知，IP查询频率受限
Traceback (most recent call last):
  File "D:\google\chatgpt_academic-master\main.py", line 54, in <module>
    with gr_L1():
         ^^^^^^^
  File "D:\google\chatgpt_academic-master\main.py", line 44, in <lambda>
    gr_L1 = lambda: gr.Row().style()
                    ^^^^^^^^^^^^^^
AttributeError: 'Row' object has no attribute 'style'

**Comment by AGoldenbread** [comment]
AttributeError: 'Row' object has no attribute 'style'

**Comment by binary-husky** [comment]
删改代码了？

**Comment by AGoldenbread** [comment]
> 删改代码了？

已经解决啦，没有删改代码，用visual studio code重做了一遍就好啦(◕ᴗ◕✿)
