### ISSUE TITLE
[Feature]: 报错了怎么办

### ISSUE THREAD

**Issue by Jackielcl** [binary-husky/gpt_academic#1302]
### Class | 类型

None

### Feature Request | 功能请求

Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 220, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(chunkjson['choices'][0]["delta"]) == 0):
                                                 ~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by binary-husky** [comment]
QQ上提供一下config样本
