### ISSUE TITLE
[Bug]: 使用知云API仍提示缺少key

### ISSUE THREAD

**Issue by RSNRG** [binary-husky/gpt_academic#1304]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

由于之前买了知云他家的第三方API，所以想试试能不能用，咨询客服后告知利用docker部署在虚拟机中是可以的，Windows本机部署没试过。而我在本机部署后，修改了API_KEY、CUSTOM_API_KEY_PATTERN、API_URL_REDIRECT这三步后打开仍然提示无有效API

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/113892394/c95aba87-9840-4827-9d11-7866e66b3eaa)
![微信图片_20231120091649](https://github.com/binary-husky/gpt_academic/assets/113892394/dec0c2cc-f620-4503-bc4c-832f7c9e5f42)

**Comment by RSNRG** [comment]
![03d3fcccfdedd2596c1f8cce40c1dc9](https://github.com/binary-husky/gpt_academic/assets/113892394/41c9863e-8f68-493f-86d2-66244efed93d)
这样直接修改解析格式可解决

**Comment by binary-husky** [comment]
配置没生效，详情见wiki

**Comment by RSNRG** [comment]
con

> 配置没生效，详情见wiki

config和config private都修改了，不知道怎么改，wiki里面的环境变量适合Windows吗，是高级系统设置中的环境变量吗，不是计算机专业的，不了解乌班图
