### ISSUE TITLE
我在解析一个c++项目代码时显示OpenAI绑定信用卡可解除频率限制，我必须得绑定信用卡吗

### ISSUE THREAD

**Issue by GJH1223** [binary-husky/gpt_academic#1305]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我在解析一个c++项目代码时显示OpenAI绑定信用卡可解除频率限制

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/72844984/e52fc4cd-5af9-477e-a3fd-1300554cb398)

**Comment by binary-husky** [comment]
填写多个api key也行
