### ISSUE TITLE
[Bug]: 使用DALLE画图失败

### ISSUE THREAD

**Issue by adrianzzk** [binary-husky/gpt_academic#1306]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

无论使用DALLE2或3都会报这个错，但事实上是可以访问的。
后来我觉得是模型的问题，接连换了几个，发现只有用gpt-3.5-turbo，DALLE2才可以生成，但也只是成功了一次。
不知道这是为什么

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/96020706/f0c60ccc-ef27-449a-83b4-b9ddb86714fd)

**Comment by binary-husky** [comment]
图中的报错是分辨率不正确，试试1024x1024 ?

**Comment by adrianzzk** [comment]
好的，明天测试一下，但是按理说默认不应该会生成吗？我前几次默认参数也没成功，我明天多测试几次

**Comment by binary-husky** [comment]
如果还有问题可以再把issue打开
