### ISSUE TITLE
[Bug]: No module named 'gradio.floating'

### ISSUE THREAD

**Issue by Daydream0929** [binary-husky/gpt_academic#1307]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

Python3.11与gradio库不兼容
报错：ModuleNotFoundError: No module named 'gradio.floating'

### Screen Shot | 有帮助的截图

<img width="1411" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/61659904/f63e0589-5925-4617-ba57-ed0aaf8a11a1">

**Comment by Daydream0929** [comment]
将python版本将为3.9就没有错误了，不知道其他版本还有没有错误

**Comment by binary-husky** [comment]
python 3.11 也是支持的，可能你依赖没装对
