### ISSUE TITLE
[Bug]: 有额度，但是提示没额度，请问这个要怎么处理呢？？

### ISSUE THREAD

**Issue by Aleix-Chen** [binary-husky/gpt_academic#1309]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由, 拒绝服务. 请登录OpenAI查看详情 https://platform.openai.com/signup

### Screen Shot | 有帮助的截图

<img width="1007" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/58615825/587e6f81-88c5-4461-8277-cc16c1a41476">

**Comment by binary-husky** [comment]
提示没额度，那就是没额度

**Comment by Aleix-Chen** [comment]
搞错了，是过期了

**Comment by ossphil** [comment]
我新生成的API也是没有额度的提示
