### ISSUE TITLE
[Feature]: 不同的GPT模型使用指定不同的API。

### ISSUE THREAD

**Issue by what-name-can** [binary-husky/gpt_academic#1311]
### Class | 类型

None

### Feature Request | 功能请求

我有多个chaptgpt账号的Key 但是只有一个Key可以使用GPT4。
我的问题是如何操作可以在请求GPT4模型时使用支持GPT4的那一个Key，请求GPT3.5模型使用其他不支持GPT4的Key。

**Comment by binary-husky** [comment]
支持GPT4的key通常也支持3.5

一定要弄这种特殊的要求的话，自己改`select_api_key`函数吧
