### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by Gg1324563708** [binary-husky/gpt_academic#1320]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

安装了'gradio'，但一直报错

### Screen Shot | 有帮助的截图

![Uploading 848a59bbcef79e276a833c4d7028baf.png…]()

**Comment by binary-husky** [comment]
请阅读readme的headline

**Comment by Gg1324563708** [comment]
![Uploading 1.png…]()
