### ISSUE TITLE
[Bug]: zhipuai

### ISSUE THREAD

**Issue by hsjlyj** [binary-husky/gpt_academic#1321]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

zhipuai无法使用

### Screen Shot | 有帮助的截图

![屏幕截图 2023-11-23 170927](https://github.com/binary-husky/gpt_academic/assets/51742502/eaa374f8-b413-42e4-a441-428c268225d2)
![屏幕截图 2023-11-23 171011](https://github.com/binary-husky/gpt_academic/assets/51742502/c465c5d7-ee23-4fb3-b3cd-d82cdd7e88b2)

**Comment by binary-husky** [comment]
安装 pip install zhipuai
