### ISSUE TITLE
[Bug]: 精准翻译pdf使用不了gpt4

### ISSUE THREAD

**Issue by forever-lwy** [binary-husky/gpt_academic#1322]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

您好，每次使用gpt4系列的模型翻译就会在翻译摘要的部分报错，后面的多线程也会全部失败，但换成3.5就能用，key用的同一个

### Screen Shot | 有帮助的截图

[Local Message] 警告，在执行过程中遭遇问题, Traceback：

Traceback (most recent call last):
  File ".\crazy_functions\crazy_utils.py", line 84, in _req_gpt
    result = predict_no_ui_long_connection(
  File ".\request_llms\bridge_all.py", line 610, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
  File ".\request_llms\bridge_chatgpt.py", line 117, in predict_no_ui_long_connection
    json_data = json.loads(chunk.lstrip('data:'))['choices'][0]
IndexError: list index out of range

**Comment by binary-husky** [comment]
应该是第三方接口？可以加我qq505030475提供一下配置，测试一下

**Comment by forever-lwy** [comment]
发现是这个我这个key的问题了，换一个就可以了，谢谢了。

**Comment by dalerxli** [comment]
您好！您的邮件已收到，谢谢。

**Comment by RikkaLzw** [comment]
我也遇上这个问题用gpt4 1106，问答是正常的，但是用来理解pdf的时候就出现这个了

**Comment by RikkaLzw** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/128763841/f8b7cb32-6da9-4860-b9c3-86baf24e9cba)
很纳闷
