### ISSUE TITLE
[Bug]: pdf编译失败

### ISSUE THREAD

**Issue by GStarmin** [binary-husky/gpt_academic#1323]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

最后编译pdf阶段编译失败

打开压缩包查看日志显示

```
pdfTeX warning: pdflatex.exe (file pdftex.map): cannot open font map file
{UGBK.sfd}{Unicode.sfd}) [1
```

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/51370056/0ffb2bba-3381-48cf-9684-47fc302f1c12)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

[2023-11-23-22-09-00-result.zip](https://github.com/binary-husky/gpt_academic/files/13451149/2023-11-23-22-09-00-result.zip)

**Comment by binary-husky** [comment]
系统字体有问题，建议使用docker
