### ISSUE TITLE
[Bug]: Latex项目编译pdf错误

### ISSUE THREAD

**Issue by hellosuer** [binary-husky/gpt_academic#1325]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在上传Latex项目翻译完成后，转化pdf编译失败，包括之前好多次axvir论文也是pdf编译失败，目前尚未编译成功过

### Screen Shot | 有帮助的截图

![d024d093e935015735fe47b95664ba6](https://github.com/binary-husky/gpt_academic/assets/110160797/125d4a3f-b0b9-44e5-81a2-47307a2d0688)
[2023-11-23-10-28-05-result.zip](https://github.com/binary-husky/gpt_academic/files/13454238/2023-11-23-10-28-05-result.zip)

**Comment by binary-husky** [comment]
检查一下系统字体
建议使用docker部署
