### ISSUE TITLE
代理所在地查询超时，代理可能无效

### ISSUE THREAD

**Issue by Thomas-ZhiZhi** [binary-husky/gpt_academic#1326]
![image](https://github.com/binary-husky/gpt_academic/assets/151315882/128c930d-534d-41a0-8887-87f49a9205b2)
按照教程配置后运行程序，显示如图。代理未通过。请教如何做

**Comment by 1241788183** [comment]
我也是这样==求教

**Comment by magicCJ** [comment]
用项目启动可以，使用Docker-compose就会这样。不知道为啥

**Comment by binary-husky** [comment]
duplicate of #1 
可以测一下代理是否干净，openai可能会屏蔽一些飞机场

**Comment by vincenteliang** [comment]
> 用项目启动可以，使用Docker-compose就会这样。不知道为啥

我也是一样的问题，请问解决了吗

**Comment by vincenteliang** [comment]
> duplicate of #1 #1 的副本 可以测一下代理是否干净，openai可能会屏蔽一些飞机场

Python使用是没问题的，但是用docker就不行

**Comment by vincenteliang** [comment]
解决了，在docker-compose文件中关闭代理，然后在docker desktop软件中设置
![a761b6edb53d2dc5f858a394d1f0a28](https://github.com/binary-husky/gpt_academic/assets/33492609/884ab2f5-1039-4259-9ef2-24c2ecbca02d)

**Comment by SoDebug** [comment]
> 解决了，在docker-compose文件中关闭代理，然后在docker desktop软件中设置 ![a761b6edb53d2dc5f858a394d1f0a28](https://private-user-images.githubusercontent.com/33492609/293825628-884ab2f5-1039-4259-9ef2-24c2ecbca02d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MjYxMTAsIm5iZiI6MTcxNzQyNTgxMCwicGF0aCI6Ii8zMzQ5MjYwOS8yOTM4MjU2MjgtODg0YWIyZjUtMTAzOS00MjU5LTllZjItMjRjMmVjYmNhMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE0NDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMDVmZWM5YTQ3OTAxZTYzOWMxNTdkYzYxMTg1YWU3MmVlYjFkYWQxMWMzZjRjMDg2M2U3OWNjZmIzZDg1NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5M-wirGFKfqT6V00DNbN5xofmd8UURKx6RasJX6-rMg)

正确的解决方式

**Comment by HUGOSAMA1121** [comment]
> 解决了，在docker-compose文件中关闭代理，然后在docker desktop软件中设置 ![a761b6edb53d2dc5f858a394d1f0a28](https://private-user-images.githubusercontent.com/33492609/293825628-884ab2f5-1039-4259-9ef2-24c2ecbca02d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDkwMTksIm5iZiI6MTcxOTA0ODcxOSwicGF0aCI6Ii8zMzQ5MjYwOS8yOTM4MjU2MjgtODg0YWIyZjUtMTAzOS00MjU5LTllZjItMjRjMmVjYmNhMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA5MzE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYzUzOWUyOTg2ZjBlZTYyZTkyYTEyNzYyYjcwOWQ3ZWM3NzJlN2FiOTNiY2Y4MWU1YjliOTNjZWZhYzliMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4CM63lgjOF84ogiUJTnEnClr7S5WhBAXZjfpZ2gOvt0)

您好，请问我也是clash，地址一样，使用docker桌面端，openai可以进入，但是localhost的界面进不去，您知道如何解决吗？
![image](https://github.com/binary-husky/gpt_academic/assets/68230594/7016b120-ba11-4ad0-90ff-08d2415a41dc)
