### ISSUE TITLE
运行后没有图形化界面

### ISSUE THREAD

**Issue by Dreamlover11111** [binary-husky/gpt_academic#1331]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

没有图形化界面

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/129772379/686b7fe3-6c09-46ca-9c7f-6ea16f72e8ae)
![image](https://github.com/binary-husky/gpt_academic/assets/129772379/9a5977ae-4d83-446d-9106-e00c4b1f5ef6)

**Comment by binary-husky** [comment]
安装方法？

**Comment by Dreamlover11111** [comment]
> 安装方法？

我是download压缩包然后用pycharm打开的

**Comment by binary-husky** [comment]
请用一键安装方式尝试一下，看看能否复现该bug呢？

**Comment by binary-husky** [comment]
一键安装方式
https://github.com/binary-husky/gpt_academic/releases
