### ISSUE TITLE
[Bug]: runtime error when duplicating huggingface space 

### ISSUE THREAD

**Issue by doubletree6** [binary-husky/gpt_academic#1332]
### Installation Method | 安装方法与平台

Huggingface

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

error output when building docker app on hugging face. this may caused by file missing or gradio version unmatch?

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/108912608/f4b267b7-4c0c-428a-ae05-0bc18199e811)

**Comment by binary-husky** [comment]
I recreated hf space yesterday, and have not yet notice this problem, please reopen this issue if same thing happen again
