### ISSUE TITLE
[Feature]:安装后如何更新 

### ISSUE THREAD

**Issue by lixiaoyaol** [binary-husky/gpt_academic#1333]
### Class | 类型

None

### Feature Request | 功能请求

麻烦问一下，我在本地安装的版本为3.55，运行python main.py时提示：“更新可用，输入Y+回车更新”。可是我输入Y+回车提示更新失败，请问如何直接更新版本？

**Comment by lixiaoyaol** [comment]
> git pull

尝试了，git pull出现 `fatal: unable to access 'https://github.com/binary-husky/gpt_academic.git/': Recv failure: Connection was reset` 错误，不起作用，我使用git clone 是可以正常使用的

**Comment by binary-husky** [comment]
直接下载代码覆盖原有程序即可，没有什么花里胡哨的升级技巧
