### ISSUE TITLE
[Feature]: pdf解析方式疑问

### ISSUE THREAD

**Issue by hby96** [binary-husky/gpt_academic#1339]
### Class | 类型

程序主体

### Feature Request | 功能请求

作者您好，麻烦问一下，为什么翻译pdf时用了scipdf去解析pdf文件，理解pdf内容时又用了自写的解析函数去解析pdf文件？

为什么要对pdf文件采用不同的解析方式呢？如此设计的初衷是什么？两者在使用效果上有什么区别吗？

**Comment by binary-husky** [comment]
自写的解析快，scipdf解析效果好但是慢
