### ISSUE TITLE
[Feature]: 是否可以加载指定目录下下载好的模型？

### ISSUE THREAD

**Issue by maxadc** [binary-husky/gpt_academic#1340]
### Class | 类型

None

### Feature Request | 功能请求

由于众所周知的huggingface.co访问困难的原因。在线下载模型有点困难。我会使用第三方镜像或者迅雷，或者其他人转发等方式从其他源下载模型镜像。目录合适和AutoModel.from_pretrained自己直接下载管理的格式也不相同。没法覆盖或者替换。是否可以在配置中用参数指定路径的方式指定目录加载本地模型！！！

**Comment by binary-husky** [comment]
可以，但需要修改一下源代码里面的路径。可以加群沟通一下

**Comment by ZH-007** [comment]
修改了源代码路径仍然无法加载本地的权重参数。
举例：D:/LLM_MODEL/chatglm36b中包含权重参数，在bridge_chatglm3.py文件中load_model_and_tokenizer()方法下的模型路径修改为上述路径。打开网页端选择chatglm3后运行，仍然需要下载权重参数。请问如何解决？

**Comment by lrh000** [comment]
> 修改了源代码路径仍然无法加载本地的权重参数。 举例：D:/LLM_MODEL/chatglm36b中包含权重参数，在bridge_chatglm3.py文件中load_model_and_tokenizer()方法下的模型路径修改为上述路径。打开网页端选择chatglm3后运行，仍然需要下载权重参数。请问如何解决？

一样的问题，请问你解决了吗
