### ISSUE TITLE
[Feature]: 支持gpt4free

### ISSUE THREAD

**Issue by 2catycm** [binary-husky/gpt_academic#1345]
### Class | 类型

大语言模型

### Feature Request | 功能请求

目前使用newbing模型GPT_ACADEMIC会显示无法使用newbing。
据我所知，目前有了新的替代方案，即使用 https://github.com/xtekky/gpt4free 这个开源项目。这个开源项目有多个渠道可以获得bing或者其他gpt4模型，只需要调用简单的api。因此希望GPT_ACADEMIC可以支持。

**Comment by binary-husky** [comment]
我们不会官方维护任何逆向工程的代码了，维护压力太大，不过您有兴趣可以帮助接入
