### ISSUE TITLE
[Feature]: 调整界面中的函数插件顺序

### ISSUE THREAD

**Issue by Monsoon007** [binary-husky/gpt_academic#1351]
### Class | 类型

函数插件

### Feature Request | 功能请求

我尝试修改了crazy_functional.py中的插件代码顺序，并重启了应用，但似乎不起效果

**Comment by binary-husky** [comment]
“我尝试修改了crazy_functional.py中的插件代码顺序” 这个操作是正确的，你是不是改错文件了，或者用的docker？
