### ISSUE TITLE
[Bug]: openAI拒绝服务

### ISSUE THREAD

**Issue by csy021031** [binary-husky/gpt_academic#1354]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

采用了一次就出现这个报错是什么原因呢？ 我用的GPT3.5模型不是免费的吗？哭了
[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由, 拒绝服务. 请登录OpenAI查看详情 https://platform.openai.com/signup

### Screen Shot | 有帮助的截图

![YYUNWB{Z74G8~LQ @8U6T%X](https://github.com/binary-husky/gpt_academic/assets/135625652/a06bbefe-5727-41e2-ac1a-7198fbea1816)
![BRN_(MNTEW4Q 3%9XXSSFYH](https://github.com/binary-husky/gpt_academic/assets/135625652/9a14e626-67a9-4b3c-8d95-3e6c2a71e563)

**Comment by binary-husky** [comment]
不是免费的，市面上有几毛钱的apikey，可以找找

**Comment by csy021031** [comment]
好的好的，谢谢author！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月4日(星期一) 下午3:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/gpt_academic] [Bug]: openAI拒绝服务 (Issue #1354)





 
不是免费的，市面上有几毛钱的apikey，可以找找

**Comment by zhangdulin** [comment]
请问在哪找的apikey:gpt-3.5-turbo-16k和 gpt-4-turbo
