### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 708978499** [binary-husky/gpt_academic#1360]
### Installation Method | 安装方法与平台

Docker（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用精准翻译PDF时报错

### Screen Shot | 有帮助的截图

[Local Message] 警告，在执行过程中遭遇问题, Traceback：

Traceback (most recent call last):
  File "./crazy_functions/crazy_utils.py", line 84, in _req_gpt
    result = predict_no_ui_long_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_all.py", line 635, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_chatgpt.py", line 115, in predict_no_ui_long_connection
    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{"error":{"message":"Insufficient balance","type":null,"status":402}}

**Comment by binary-husky** [comment]
报错信息已经很明确了呀
