### ISSUE TITLE
文件无法上传

### ISSUE THREAD

**Issue by Unstoppable45** [binary-husky/gpt_academic#1361]
文件传不上去，一直在uploading......
![屏幕截图 2023-12-05 213518](https://github.com/binary-husky/gpt_academic/assets/137591027/2e90599c-b326-4133-b849-f8eb007849f7)

**Comment by Unstoppable45** [comment]
gradio3.32.6——>3.25.0，main.py无法运行，修改main.py中gradio版本报错更多了

**Comment by binary-husky** [comment]
换个文件试试（别用云文件）

**Comment by formoree** [comment]
同样的问题
