### ISSUE TITLE
[Bug]: Huggingface Proxy Network error

### ISSUE THREAD

**Issue by doubletree6** [binary-husky/gpt_academic#1362]
### Installation Method | 安装方法与平台

Huggingface

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Proxy error when using API2D api

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/108912608/61a52bba-58c4-4320-8c8f-b54609854475)

**Comment by binary-husky** [comment]
api2d usually do not require proxy

**Comment by doubletree6** [comment]
That's right. you touched the key point. because API2D does not need a proxy, so the config for proxy is False in my config.py. but the issue remains for no reason. I tried the API2D api-key in your demo, and the bug persists. please check the demo you created and try to apply an API2d key if possible. I am starting to wonder if there is a problem with API2D's services.
