### ISSUE TITLE
GPT账户被封了

### ISSUE THREAD

**Issue by Unstoppable45** [binary-husky/gpt_academic#1365]
昨天刚试用了一会儿，今天被封号了
![屏幕截图 2023-12-06 204505](https://github.com/binary-husky/gpt_academic/assets/137591027/9b9413f3-bc7a-4814-86ac-6e33d0ed6857)
不知道是什么原因，重新注册了一个，不敢调用API了.......

**Comment by binary-husky** [comment]
与项目无关

**Comment by binary-husky** [comment]
听过outlook邮箱还有一些其他邮箱容易被封
