### ISSUE TITLE
[Bug]:  No module named 'gradio'

### ISSUE THREAD

**Issue by Tzy123-space** [binary-husky/gpt_academic#1368]
### Installation Method | 安装方法与平台

Docker（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

No module named 'gradio'，在其他问题下有人指出有txt，但是我并没有发现没有可供查询的txt文件

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/148780861/55efe877-e5c3-485e-afff-8be47d024ba2)

**Comment by binary-husky** [comment]
读readme
