### ISSUE TITLE
[Feature]: 在构建知识库的时候C盘直接没空间了，希望能够说明向量数据库存在哪里，以及可以指明修改向量数据库和文本向量化模型的存储位置

### ISSUE THREAD

**Issue by WenxuanZhao** [binary-husky/gpt_academic#1371]
### Class | 类型

函数插件

### Feature Request | 功能请求

![image](https://github.com/binary-husky/gpt_academic/assets/30493911/2d5481da-0b11-4826-bc16-7ad89c9ec020)
h救救孩子

**Comment by binary-husky** [comment]
关闭重复issue #1372
