### ISSUE TITLE
[Feature]: 请问使用第三方API调用DALLE插件需要单独设置API_REDIRECT吗？

### ISSUE THREAD

**Issue by hjnnjh** [binary-husky/gpt_academic#1375]
### Class | 类型

函数插件

### Feature Request | 功能请求

我试了一下好像不给DALLE设置API_REDIRECT也可以，Chat的已经设置了。

**Comment by hjnnjh** [comment]
第三方API有提供专门的image接口，是不是调用api2d系列模型可以redirect到第三方API的image接口啊？

**Comment by hjnnjh** [comment]
对了，目前就是gpt开头的模型是可以正常用于生成图片的，但是api2d系列的模型用不了。

**Comment by binary-husky** [comment]
dalle2应该是适用于api2d的

**Comment by hjnnjh** [comment]
> dalle2应该是适用于api2d的

好的，现在用着正常我就不管了，dalle2和3都是正常的。
