### ISSUE TITLE
[Bug]: Docker img 'gpt_academic_full_capability' get TypeError when using ChatGLM3

### ISSUE THREAD

**Issue by pengtb** [binary-husky/gpt_academic#1379]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

The container raised a `TypeError` when initializing ChatGLM3. It seems that lower down the version of protobuf may solve this problem?

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/39072131/0c49f12a-6bd9-482e-9b79-3beec29dab69)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

All settings were left default.

**Comment by binary-husky** [comment]
Thank you for reporting this problem, I have been investigating this issue, but have not verify a feasible solution.

Some package upgrade might causing this problem

**Comment by binary-husky** [comment]
We need some help regarding this issue

**Comment by binary-husky** [comment]
this patch might help https://github.com/binary-husky/gpt_academic/commit/107944f5b72d7351fe64478dbf2c20a0b70a0b1d
