### ISSUE TITLE
[BUG]:Json异常<!doctype html>[Bug]: 

### ISSUE THREAD

**Issue by Supermarket-you** [binary-husky/gpt_academic#1383]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

Traceback (most recent call last):
  File "./request_llms/bridge_chatgpt.py", line 242, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(chunkjson['choices'][0]["delta"]) == 0):
                                                 ~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

### Screen Shot | 有帮助的截图

<img width="715" alt="截屏2023-12-13 10 33 07" src="https://github.com/binary-husky/gpt_academic/assets/105334291/0d69251a-70b8-4382-8277-0c9bddb8e784">
<img width="208" alt="截屏2023-12-13 10 33 16" src="https://github.com/binary-husky/gpt_academic/assets/105334291/81f74fcc-f6ef-4711-b61f-13250c629fae">


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by binary-husky** [comment]
配置错误，详见wiki

**Comment by RickWithDreams** [comment]
怎么解决的啊，遇到同样的问题

**Comment by zhyuxin** [comment]
我也是遇到了这个问题，如果有解决方法，万望回复

**Comment by zhyuxin** [comment]
> 我也是遇到了这个问题，如果有解决方法，万望回复

我找到了解决方案
# 重新URL重新定向，实现更换API_URL的作用（高危设置! 常规情况下不要修改! 通过修改此设置，您将把您的API-KEY和对话隐私完全暴露给您设定的中间人！）
# 格式: API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "在这里填写重定向的api.openai.com的URL"} 
# 举例: API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://reverse-proxy-url/v1/chat/completions"}
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"https://你的api/v1/chat/completions"}
