### ISSUE TITLE
[Bug]: 使用第三方接入点的API(自建的one-api)报错

### ISSUE THREAD

**Issue by Nothingness-Void** [binary-husky/gpt_academic#1387]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

配置完第三方接入点之后，有返回值但是报错

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/55913486/ec83c7ad-6e5e-47e2-a353-f4e4ba85dce8)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

gpt_academic-gpt_academic_nolocalllms-1  |  gpt-4 : 0 : 你好 ..........
gpt_academic-gpt_academic_nolocalllms-1  | data: {"choices":[{"index":0,"delta":{"content":null,"role":"assistant"}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"你","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"好","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"！","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"有","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"什","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"么","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"可以","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"帮","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"助","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"你","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"的","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"呢","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"index":0,"delta":{"content":"？","role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: {"choices":[{"finish_reason":"stop","index":0,"delta":{"content":null,"role":null}}],"created":1702550226,"id":"chatcmpl-8VdNSKKwMzhzIOCNQQULqLMuV3EEQ"}data: [DONE]

**Comment by binary-husky** [comment]
官方的不会出现content:null的情况
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/dce397f9-c165-46f1-92d9-4b19f1fc18f5)

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/36e19d520282506ab6c0b9dfcec300515b48146b

**Comment by Geniucker** [comment]
但是貌似`predict`函数里对第三方api的支持没有应用到`predict_no_ui_long_connection`里，所以翻译pdf等功能还是用不了
