### ISSUE TITLE
[Bug]:为什么代理配置正确，还是无法使用呢 

### ISSUE THREAD

**Issue by zwsxzy** [binary-husky/gpt_academic#1390]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

为什么代理配置正确，还是无法使用呢 

### Screen Shot | 有帮助的截图

![屏幕截图 2023-12-15 134928](https://github.com/binary-husky/gpt_academic/assets/48172853/bdde31d2-3649-46f6-b214-dc92ed96424e)
![屏幕截图 2023-12-15 135011](https://github.com/binary-husky/gpt_academic/assets/48172853/8a43fddd-c28c-4410-bcc1-08558cb1beab)

**Comment by binary-husky** [comment]
看一下#1
