### ISSUE TITLE
[Bug]: 尝试上传zip文件进行批量pdf总结，但extract_archive解压不完整，导致FileNotFoundError

### ISSUE THREAD

**Issue by HuajiFruits** [binary-husky/gpt_academic#1391]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

尝试上传zip文件进行批量pdf总结，但extract_archive解压不完整，导致FileNotFoundError。上传的zip文件含有23个pdf，但对应的.extract文件夹中仅有17个pdf。
一些尝试（挣扎QAQ）：
1. 本来使用的是之前使用chatpaper时配置的conda环境，现在尝试了按readme.md的指引重新设置，并下载使用最新的github clone。未能解决问题。

2. 尝试过从toolbox中复制出extract_archive函数中解压zip文件的部分，单独运行：
import zipfile
with zipfile.ZipFile(file_path, 'r') as zipobj:
            zipobj.extractall(path=dest_dir)
            print("Successfully extracted zip archive to {}".format(dest_dir))
 结果：使用gptac_venv环境，单独运行时可以正常解压出23份PDF。

3.尝试使用rar,安装了rarfile库，并将winrar的文件夹和可执行文件均添加进了系统变量。在GPT学术优化页面中显示：
解压失败! 需要安装pip install rarfile来解压rar文件。建议：使用zip压缩格式。
单独提取toolbox中extract_archive函数解压rar文件的部分，去除try，发现并不是没有导入rarfile，而是：
发生异常: BadRarFile
Failed the read enough data: req=1048576 got=52
根据搜索到的解决方法，尝试过下载安装unrar.exe，以及修改rarfile.py的HACK_SIZE_LIMIT参数，均报一样的错。暂时放弃。
 
 请问这个问题如何解决？希望大佬能提供一些帮助。

### Screen Shot | 有帮助的截图

![图片](https://github.com/binary-husky/gpt_academic/assets/65650408/8376e81d-e3ae-4c93-a30a-fc3f686175ac)
这是运行时cmd页面的截图。
![图片](https://github.com/binary-husky/gpt_academic/assets/65650408/3c0a71d2-072a-40ba-9117-62f4dde65ada)
这是GPT学术优化的对应报错页面。
![图片](https://github.com/binary-husky/gpt_academic/assets/65650408/c91ffb20-fe22-409d-bb9b-9dc3df47b767)
这是GPT学术优化自动提取出的文件夹。
![图片](https://github.com/binary-husky/gpt_academic/assets/65650408/61763587-1a67-4ea8-9545-0fb6c761e652)
这是上传的zip文件。
![图片](https://github.com/binary-husky/gpt_academic/assets/65650408/45c3342e-3630-47c2-9f76-736bc76933e5)
这是单独运行extract_archive中提取zip的脚本得到的结果，是能正常解压出来的，之前在想是不是中文变成乱码的问题，但是我把文件名中中文“科研通”三个字删掉也是一样的。

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Anaconda\envs\gptac_venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gpt_academic-master\gpt_academic-master\toolbox.py", line 692, in on_file_uploaded
    upload_msg += extract_archive(file_path=this_file_path, dest_dir=this_file_path+'.extract')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\gpt_academic-master\gpt_academic-master\toolbox.py", line 491, in extract_archive
    zipobj.extractall(path=dest_dir)
  File "D:\Anaconda\envs\gptac_venv\Lib\zipfile.py", line 1681, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "D:\Anaconda\envs\gptac_venv\Lib\zipfile.py", line 1735, in _extract_member
    open(targetpath, "wb") as target:
    ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'private_upload\\default_user\\2023-12-15-17-17-43\\Heat Expose2.zip.extract\\Urban ecological land and natural-anthropogenic environment interactively drive surface urban heat island_ An urban agglomeratio(-ablesci.com).pdf'

**Comment by binary-husky** [comment]
你这windows文件名不能太长

**Comment by HuajiFruits** [comment]
感谢，确实是这样的，将过长的文件名改短就可以了，非常感谢XD
