### ISSUE TITLE
[Bug]: 无法生成图片

### ISSUE THREAD

**Issue by LiangzhengChou** [binary-husky/gpt_academic#1394]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

![image](https://github.com/binary-husky/gpt_academic/assets/113409054/06730879-c7d0-4d79-b977-211ec4b2f7a8)
您好在这里的图片生成的设置哪里出了问题呢？
我在config.py里设置的是opnai的key
它提示您提供的api-key不满足要求，不包含任何可用于api2d-gpt-3.5-turbo-16k的api-key。您可能选择了错误的模型或请求源。

### Screen Shot | 有帮助的截图

<img width="816" alt="1702653257430" src="https://github.com/binary-husky/gpt_academic/assets/113409054/98e72872-03d8-4895-bdbf-a7a0e2b1d7d1">

**Comment by binary-husky** [comment]
把模型切换到 gpt-*
