### ISSUE TITLE
[Bug]: 远程部署无法连接

### ISSUE THREAD

**Issue by Lacroixx97** [binary-husky/gpt_academic#1395]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

你好，我将项目部署在办公室自建的linux服务器上，服务端未设置防火墙，在按照
https://github.com/binary-husky/gpt_academic/issues/386
的提示修改完main.py后，在客户端输入url:port后并不能成功登录，请问最新版本是否对远程使用做了什么代码修改导致无法远程使用？谢谢

### Screen Shot | 有帮助的截图

![1](https://github.com/binary-husky/gpt_academic/assets/94316673/6ff10387-2fa0-4b60-9fd2-4dff25705c02)
![2](https://github.com/binary-husky/gpt_academic/assets/94316673/04b3459e-9b4c-4593-ad22-fd091bb23d46)

**Comment by binary-yuki** [comment]
请排除以下环境因素：

- “服务端未设置防火墙”指的是...? 系统防火墙呢（类似ubuntu的ufw)

建议操作
：
- 建议服务端内部curl一下查看是否正常
- 请参考(wiki)[https://github.com/binary-husky/gpt_academic/wiki/%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9C%E7%A8%8B%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97]

如可以麻烦提供更多材料样本 暂时无法复现该issue

**Comment by binary-husky** [comment]
我看到打印的信息一切正常。但我建议把main.py修改回去吧。

这个就是要么ip地址不对，要么端口被屏蔽了。

**Comment by Lacroixx97** [comment]
> 我看到打印的信息一切正常。 但我建议把main.py修改回去吧。
> 
> 这个就是要么ip地址不对，要么端口被屏蔽了。

了解了大大，感谢拨冗回复！

**Comment by Lacroixx97** [comment]
已解决，所有使用Chrome系浏览器的用户注意（包括Edge），浏览器默认会屏蔽部分端口，解决方法为端口改为随机或避开屏蔽端口，详见https://developer.aliyun.com/article/627084
