### ISSUE TITLE
[Feature]: 如何在同一机器上部署多个服务

### ISSUE THREAD

**Issue by Cz1544252489** [binary-husky/gpt_academic#1402]
### Class | 类型

程序主体

### Feature Request | 功能请求

是否可以在同一机器上部署两个独立的服务，将一个域名的两个端口，或者多个域名分别指向不同的功能。因为虽然现在功能的确非常强大，但是还是喜欢可以有更加个性化的效果，比如给普通朋友提供免费3.5服务，更加关系好的提供4.0的服务。

**Comment by binary-husky** [comment]
完全没问题，改一下WEB_PORT就行了
