### ISSUE TITLE
[Bug]: 我运行不起来

### ISSUE THREAD

**Issue by Nixizfan** [binary-husky/gpt_academic#1403]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

一个晚上过后打不开了。。。虽然之前打得开但是网址没配好

### Screen Shot | 有帮助的截图

Traceback (most recent call last):
  File "D:\gpt_academic-master\main.py", line 407, in <module>
    main()
  File "D:\gpt_academic-master\main.py", line 17, in main
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

这个是报错

**Comment by Nixizfan** [comment]
大佬们救救孩子吧

**Comment by Cz1544252489** [comment]
No module named 'gradio'   应该是环境没有配置好吧，这个gradio作为设置密码的包没有安装。

**Comment by Nixizfan** [comment]
请问一下应该是啥出现了问题怎么配置呢

**Comment by binary-husky** [comment]
应该是电脑上有多个python，冲突了

**Comment by Nixizfan** [comment]
已解决
