### ISSUE TITLE
[Bug]: docker-compose-3.6.4版使用sparkv3模型出错

### ISSUE THREAD

**Issue by sclxzy** [binary-husky/gpt_academic#1409]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

使用sparkv3模型无法使用：如，精准翻译pdf,批量总结pdf，均会出错，总结出来的结果为错误代码，望修复

### Screen Shot | 有帮助的截图

![1703315986188](https://github.com/binary-husky/gpt_academic/assets/132804931/e1ccbcaa-c47d-42c6-9779-a991ff48f79e)
![1703316048905](https://github.com/binary-husky/gpt_academic/assets/132804931/b6b8e841-d530-4d58-909f-e199a5f25550)
![1703316068457](https://github.com/binary-husky/gpt_academic/assets/132804931/be94fb2f-90f9-4cd5-ab09-d6f683fe0cbe)

**Comment by binary-husky** [comment]
已修复 https://github.com/binary-husky/gpt_academic/pull/1410
