### ISSUE TITLE
界面提交时Error及解决办法

### ISSUE THREAD

**Issue by Misaka89535** [binary-husky/gpt_academic#141]
![图片](https://user-images.githubusercontent.com/90268558/228734412-3a2a02b1-bb06-45c5-a1ef-61292254c3b3.png)
从昨天晚上开始试了很久，在这个界面一直报错如下：TypeError: entry_points() got an unexpected keyword argument  'group'
（类似#88 的问题）
多次尝试改代理无果，后面查询发现可能是Markdown的版本不兼容（3.4.3）导致的，需要换用Markdown3.3.4的版本。
解决办法：首先卸载原有的Markdown，代码如下：
`pip uninstall Markdown`
再安装Markdown==3.3.4版本：
`pip install Markdown==3.3.4`
![图片](https://user-images.githubusercontent.com/90268558/228736568-c03db86b-8671-45d8-97de-567e8b07fb82.png)
似乎可以运行了（但目前又出现了#126 提到的问题），可能与账号有关？
参考：[https://blog.csdn.net/qq_35438053/article/details/127436656](url)

**Comment by Misaka89535** [comment]
> ![图片](https://user-images.githubusercontent.com/90268558/228734412-3a2a02b1-bb06-45c5-a1ef-61292254c3b3.png) 从昨天晚上开始试了很久，在这个界面一直报错如下：TypeError: entry_points() got an unexpected keyword argument 'group' （类似#88 的问题） 多次尝试改代理无果，后面查询发现可能是Markdown的版本不兼容（3.4.3）导致的，需要换用Markdown3.3.4的版本。 解决办法：首先卸载原有的Markdown，代码如下： `pip uninstall Markdown` 再安装Markdown==3.3.4版本： `pip install Markdown==3.3.4` ![图片](https://user-images.githubusercontent.com/90268558/228736568-c03db86b-8671-45d8-97de-567e8b07fb82.png) 似乎可以运行了（但目前又出现了#126 提到的问题），可能与账号有关？ 参考：[https://blog.csdn.net/qq_35438053/article/details/127436656](url)

问题解决了，重新注册了一个账号后能够正常使用了。出现类似问题的朋友可以检查一下自己账号。
![图片](https://user-images.githubusercontent.com/90268558/228743481-793223aa-2f10-477d-a0a0-1ef2d2dddcf2.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/228746633-684fc9aa-5453-4451-8638-bf715b8904e8.png)

确实有个markdown版本红了，可能碰巧装上那个版本了。
话说你用的啥pip源，让大家避避坑？

**Comment by Misaka89535** [comment]
> ![image](https://user-images.githubusercontent.com/96192199/228746633-684fc9aa-5453-4451-8638-bf715b8904e8.png)
> 
> 确实有个markdown版本红了，可能碰巧装上那个版本了。 话说你用的啥pip源，让大家避避坑？

我原来用的清华镜像，现在换成官方的，不过markdown之前会装上新版本可能只是因为我最近碰巧重装了系统

**Comment by Abigail61** [comment]
有用，解决了 感谢

**Comment by binary-husky** [comment]
> > ![image](https://user-images.githubusercontent.com/96192199/228746633-684fc9aa-5453-4451-8638-bf715b8904e8.png)
> > 确实有个markdown版本红了，可能碰巧装上那个版本了。 话说你用的啥pip源，让大家避避坑？
> 
> 我原来用的清华镜像，现在换成官方的，不过markdown之前会装上新版本可能只是因为我最近碰巧重装了系统

又是清华镜像的受害者，吐血，他们宕机了吗
