### ISSUE TITLE
[Feature]: 关于DALLE-3画图的修改

### ISSUE THREAD

**Issue by fattank** [binary-husky/gpt_academic#1414]
### Class | 类型

函数插件

### Feature Request | 功能请求

请教一下：
1、如果使用DALLE-3生成的图像不太满意，但还行，希望在原有基础之上修改怎么办？
2、部署到UBuntu上使用，如何让他可以在后台运行，保持持续运行，我使用python main.py & 命令就是启动不成功，但是在终端使用python main.py是能成功打开访问的。
3、如果想把项目打包到exe用 pyinstaller失败。目的是想用在不同的计算机上，有没有办法，请指导一下。

**Comment by binary-husky** [comment]
1、dalle3没有这个能力
2、输入tmux，然后python main.py，然后ctrl + b退出
3、不可以打包成exe，但我们有一键安装脚本，把它在u盘安装就行
