### ISSUE TITLE
[Bug]: windows一键安装脚本会重复下载miniconda

### ISSUE THREAD

**Issue by wanghaisheng** [binary-husky/gpt_academic#1417]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

由于我这台上已经安装过了miniconda，vscode，但运行安装脚本，仍然会下载

不能检测吗

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/2363295/0d149358-61dd-4ad3-8205-1fc5b562ad82)

**Comment by binary-husky** [comment]
换个路径试试

**Comment by wanghaisheng** [comment]
@binary-husky 是压缩包换个路径 ？
可能是我今天没有解压对
