### ISSUE TITLE
[Feature]: 提供免费的academic gpt的功能，无需付费，开箱即用。

### ISSUE THREAD

**Issue by DaifukuAc** [binary-husky/gpt_academic#1418]
### Class | 类型

None

### Feature Request | 功能请求

academic.daifuku.asia。无偿提供api支持，无需付费，开箱即用，支持openai全系列模型。
由api.daifuku.asai提供支持。

**Comment by caesarliuli** [comment]
[Uploading Canonical BAF complex activity shapes the enhancer landscape that licenses CD8+ T cell effector and memory fates.pdf…]()
