### ISSUE TITLE
[Feature]: 请问如何配置火山大模型skylark2

### ISSUE THREAD

**Issue by Leekinxun** [binary-husky/gpt_academic#1428]
### Class | 类型

大语言模型

### Feature Request | 功能请求

如需添加火山大模型skylark2,应该如何修改predict_no_ui_long_connection函数和predict函数，以及对应的com_xxx.py脚本

**Comment by Leekinxun** [comment]
我已经成功接入了，如果需要帮助可以@我发相关py脚本

**Comment by binary-husky** [comment]
@Leekinxun 
您好，如果可以的话欢迎发布pull request；
或者加入github页面的qq群直接发我也可以

**Comment by Leekinxun** [comment]
> @Leekinxun 您好，如果可以的话欢迎发布pull request； 或者加入github页面的qq群直接发我也可以

已经发送加群申请，谢谢
