### ISSUE TITLE
[Bug]: 能够正常对话，但是无法使用插件函数

### ISSUE THREAD

**Issue by 19zhs19** [binary-husky/gpt_academic#1430]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

这个是报告
[2023-12-27-19-21-20grobid.json](https://github.com/binary-husky/gpt_academic/files/13792258/2023-12-27-19-21-20grobid.json)
有相同的是重装了pip库，但是并没有说重装哪个，将其运行命令复制下来都符合要求

### Screen Shot | 有帮助的截图

![292724664-5f28d4f4-42b7-44fa-a975-38bf606db5ae](https://github.com/binary-husky/gpt_academic/assets/138569812/bf6938d6-4b2c-4e7d-9c02-7ee07776b13f)

**Comment by binary-husky** [comment]
网络不好，重启几次，让tiktoken成功加载

**Comment by 19zhs19** [comment]
> 网络不好，重启几次，让tiktoken成功加载

可是已经试过好多次了都是这样
