### ISSUE TITLE
[Bug]: 最近的几个新版本都无法自动更新

### ISSUE THREAD

**Issue by MrGongqi** [binary-husky/gpt_academic#1433]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Others | 非最新版

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

你好，我从3.62更新到3.64，无法自动更新，，，不知道是什么原因，都必须重新下载脚本重新安装，，如下面的图可见，运行中出现是否一键更新提示，但是会马上跳过，导致无法选择，，，

### Screen Shot | 有帮助的截图

![144924d8ad412e23b24d30b089dc585](https://github.com/binary-husky/gpt_academic/assets/49467246/8b54274f-a21d-4562-8071-cf9bb1ebe9ab)

**Comment by binary-husky** [comment]
Y+回车就行，不用管其他的

**Comment by EinXin** [comment]
> Y+回车就行，不用管其他的，打印的消息不影响您Y+回车的

![微信图片_20240120161421](https://github.com/binary-husky/gpt_academic/assets/128442688/66fa1d6e-cda4-466c-860e-f83d5642ceb6)
请问大佬这个怎么解决？按Y+回车仍然没有更新
