### ISSUE TITLE
[Feature]: 请增加对openkey的支持

### ISSUE THREAD

**Issue by grothen** [binary-husky/gpt_academic#1436]
### Class | 类型

程序主体

### Feature Request | 功能请求

目前有一个key的池子的服务openkey，他们提供一个仿照openai的key，通过他们的服务会访问一个池子内的openai的key，从而避免购买单一帐号会被ban的问题。但是因为该key的格式略有不同，目前的gpt_academic会有一些冲突，比如提交时会有
“检测到： OpenAI Key 1 个, Azure Key 0 个, API2D Key 0 个”的提示。请增加对他们的官方支持（https://openkey.cloud）。

**Comment by grothen** [comment]
似乎问题是“提交”和基础功能按键没有正常输出命令，我目前的修改是
![CleanShot 2023-12-31 at 20 49 41](https://github.com/binary-husky/gpt_academic/assets/3252576/3b43ba5e-8445-4064-bd4b-384260803499)
bug的现象是
![CleanShot 2023-12-31 at 20 51 04](https://github.com/binary-husky/gpt_academic/assets/3252576/b9318a2b-4ba7-43ae-8797-5a43a63c6f49)

**Comment by grothen** [comment]
不好意思，是我画蛇添足，经测试只要private_config正确设置就没有问题

**Comment by binary-husky** [comment]
没有更多问题我先close一下
