### ISSUE TITLE
[Bug]: 无法调用本地GROBID

### ISSUE THREAD

**Issue by SuperMaxine** [binary-husky/gpt_academic#1446]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在精准翻译pdf功能中，我通过docker搭建了本地的GROBID服务，在`127.0.0.1:8070`开放了本地端口，在浏览器可以访问Web端，使用其官方文档的`curl -v --form input=@./thefile.pdf localhost:8070/api/processFulltextDocument`测试命令也已经可以成功解析pdf文件了，但是我将`http://127.0.0.1:8070`加入config.py的`GROBID_URLS`并注释掉其他地址后，会显示“GROBID服务不可用，请检查config中的GROBID_URL。作为替代，现在将执行效果稍差的旧版代码。”

我个人猜测可能是通信没有成功建立，但是我也尝试了关闭proxy以及本机上所有可能的代理程序，都没有改善这个问题，所以想请教一下还有可能是哪里的问题。

### Screen Shot | 有帮助的截图

我尝试了图中所有地址，都获得了相同的结果：
![image](https://github.com/binary-husky/gpt_academic/assets/32979328/b5d5d94c-c8a2-4853-94a3-90d498d55526)
![image](https://github.com/binary-husky/gpt_academic/assets/32979328/2db3d6e4-65a2-4aba-a87f-8fd39b10a876)

**Comment by binary-husky** [comment]
docker 端口的问题：
- gpt-academic 是否同样使用 docker 部署？如果是，就稍微有点麻烦，尤其是在windows下
- "http://127.0.0.1:8070" 这个是正确的，删除其他试一试
-

**Comment by SuperMaxine** [comment]
> docker 端口的问题：
> 
> * gpt-academic 是否同样使用 docker 部署？如果是，就稍微有点麻烦，尤其是在windows下
> * "http://127.0.0.1:8070" 这个是正确的，删除其他试一试

谢谢回复，我的gpt_academic是源码clone到windows宿主机上通过conda单独管理环境并运行的。看您回复后我尝试了一下在不开启proxy时，只保留一个"http://127.0.0.1:8070/"地址，成功调用到本地的GROBID了。之前可能单独设这个地址的时候还没关proxy，我又确认了下开启proxy后确实连接不上了。问题解决了，十分感谢🙏
