### ISSUE TITLE
[Bug]: bridge_chatgpt 的 predict对第三方api的支持貌似没有完全应用到 predict_no_ui_long_connection 里，导致批量翻译pdf的功能无法使用

### ISSUE THREAD

**Issue by Geniucker** [binary-husky/gpt_academic#1447]
### Installation Method | 安装方法与平台

Docker-Compose（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

这两个函数里面的立即看起来不一样，写法也不太一样，在 `predict_no_ui_long_connection` 里面 has_role赋值完就没用过，虽然直接用 if "role" in delta 判断了，但是和predict里的判断逻辑不太一样

### Screen Shot | 有帮助的截图

上面是`predict`，下面是`predict_no_ui_long_connection`。前者是先判断has_content，后者是先has_role，所以`predict_no_ui_long_connection`在同时has_content和has_role的情况下就不会返回东西了
<img width="635" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/61449208/b1ffc176-a126-474c-b923-848a806ccb08">
<img width="611" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/61449208/22c6ad6d-0232-4382-b265-0c974da817bc">

**Comment by Geniucker** [comment]
is_head_of_stream也没有在`predict_no_ui_long_connection`里处理

**Comment by AI2Inventor** [comment]
> is_head_of_stream也没有在`predict_no_ui_long_connection`里处理

我也是这个问题，貌似现在也没更新
