### ISSUE TITLE
[Feature]: docker arm support 

### ISSUE THREAD

**Issue by jackeyzzz12138** [binary-husky/gpt_academic#1448]
### Class | 类型

其他

### Feature Request | 功能请求

最近使用方案4的docker镜像发现没有arm版本，重新用 [ubuntu-arm](https://hub.docker.com/layers/library/ubuntu/latest/images/sha256-ba545858745d6307f0d1064d0d25365466f78d02f866cf4efb9e1326a4c196ca?context=explore) 为基座系统制作了arm支持的docker镜像在我的[fork仓库](https://github.com/jackeyzzz12138/gpt_academic/pkgs/container/gpt_academic_with_latex_arm)中，目前自测使用latex相关的功能没有问题，不知道还有没有其他bug，如果可以的话也希望能够PR到原项目。

P.S.
**构建镜像时没有找到ctex的arm安装方式，所以没有安装ctex，不知道是否有其他影响？**

**Comment by binary-husky** [comment]
非常感谢，一直以来arm都没精力关注，我把这个issue链接到wiki上，后面有空了再处理

**Comment by jackeyzzz12138** [comment]
由于GitHub仓库名称更新，以前的package不再更新，新的镜像名称为
```
docker pull ghcr.io/jackeyzzz12138/gpt_academic_arm_with_latex_arm:arm
```
