### ISSUE TITLE
[Bug]: 关于在config.py文件中配置好KEY以及URL，使用中转站，但是却显示API_KEY报错的坑

### ISSUE THREAD

**Issue by August-L-J** [binary-husky/gpt_academic#1454]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

事情的经过是这样的，买了个中转站，主要是用api_key，用别的插件api_key都可以跑通，但是却发现用gpt_academic的时候，总是会报错
我确信API_KEY以及API_URL_REDIRECT都配置好了，但是之后运行main.py文件就是报错
![前端_报错](https://github.com/binary-husky/gpt_academic/assets/75567677/c2c346d8-08de-4c47-9182-2f130b1aeeb2)
跟我说，错误的API秘钥，随后我看了下终端跑出的结果
![debug](https://github.com/binary-husky/gpt_academic/assets/75567677/a86e6374-c278-495c-965a-038e5966e8f4)
我发现我的api_key会被自动修正成另一个，我在想是不是这个原因导致找不到KEY而报错的

随后，我将config.py文件中的API_KEY这样设置  API_KEY=""
同时，之前设置的  API_URL_REDIRECT  不用修改，因为我打算从前端把API_KEY给传进去，结果就可以辣~！
![成功](https://github.com/binary-husky/gpt_academic/assets/75567677/e5b7652c-7ba4-4db6-8d27-17483f71ad06)

希望大家不要踩这个坑，开发看见的话来修修bug呗，因为真的搞了好久。。。

### Screen Shot | 有帮助的截图

见```Describe the bug```

**Comment by binary-husky** [comment]
不是BUG！你环境变量里面有脏东西
