### ISSUE TITLE
[Bug]: Arxiv论文精细翻译（输入arxivID）[需Latex]在编译PDF文档时报错

### ISSUE THREAD

**Issue by August-L-J** [binary-husky/gpt_academic#1456]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我的arxivID是对的，确实有下载完整tex文件，结果就是报错

![8IS%X7A 6X0MOI_@8%F{347](https://github.com/binary-husky/gpt_academic/assets/75567677/15edbe0e-866d-49bb-8783-4c9deddc46e0)

![L{W6D`W4RJ YB0DRR5YM_4S](https://github.com/binary-husky/gpt_academic/assets/75567677/de907b75-43f9-4f66-bc7b-d816d4897a0d)

![T{OXXLT(0(U9X26VN7B S9A](https://github.com/binary-husky/gpt_academic/assets/75567677/b620ad5c-b31f-4d07-b0e8-b41ec3e89841)

![72BWBS%4)GYG9_N 0M4UZDL](https://github.com/binary-husky/gpt_academic/assets/75567677/ef1244fb-e32e-4065-8073-e6e174f38dd8)

资料
[[Bug] Arxiv论文精细翻译（输入arxivID）[需Latex]在编译PDF文档时报错.zip](https://github.com/binary-husky/gpt_academic/files/13850719/Bug.Arxiv.arxivID.Latex.PDF.zip)

### Screen Shot | 有帮助的截图

RT

**Comment by August-L-J** [comment]
### 另外再提一个坑（可能是），就是下载好LaTeX后，要配置好LaTeX的系统环境变量，如果代码报错，说LaTeX环境变量没配好，那么就去找```LaTeX输出PDF结果.py```文件里面用Ctrl+f（我的是pycharm）总之搜索关键字找到```subprocess.Popen(['pdflatex', '-version'])```的代码，然后修改成```subprocess.Popen(['pdflatex电脑路径，例如：C:\\texlive\\2023\\bin\\windows\\pdflatex', '-version'])```
即可使用与LaTeX相关的功能：）

**Comment by binary-husky** [comment]
我打开了你上传的压缩包，直接就可以生成pdf，没有出现任何问题。

**Comment by binary-husky** [comment]
可能系统字体有问题

**Comment by HIT-ZY** [comment]
确实

**Comment by macqueen09** [comment]
> 可能系统字体有问题

@binary-husky  那平时windows用这没出现字体问题，这里出现字体问题，是应该如何解决呢？

**Comment by macqueen09** [comment]
https://web.ugreen.cloud/web/#/share/51fa24f909cb4194840786eb59333354 提取码：VNT6
是zip包

同样问题， 是一篇比较新的 https://arxiv.org/abs/2401.06209 的论文 Eyes Wide Shut? Exploring the Visual Shortcomings of Multimodal LLMs
