### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by alongGS** [binary-husky/gpt_academic#1461]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

python main.py 报错

### Screen Shot | 有帮助的截图

![8924d41e-2858-4d1c-9ee4-d0b0b6605c16](https://github.com/binary-husky/gpt_academic/assets/22184082/6ca6e86f-df0f-46f3-937f-4710e5b37b0a)

**Comment by binary-husky** [comment]
python版本有问题？试试一键安装脚本
