### ISSUE TITLE
请增加支持copilot-gpt4-service

### ISSUE THREAD

**Issue by Luo-hongyi** [binary-husky/gpt_academic#1463]
### Class | 类型

程序主体

### Feature Request | 功能请求

见 https://github.com/aaamoon/copilot-gpt4-service

对于已买Github copilot的人来说，可以剩下一笔了

**Comment by binary-husky** [comment]
直接就可以接入

**Comment by Luo-hongyi** [comment]
docker方式可以吗？

**Comment by SuperMaxine** [comment]
> 直接就可以接入

开发者您好，这个好像还真是没法直接接入，我尝试了大概一周吧，目前确定[copilot-gpt4-service](https://github.com/aaamoon/copilot-gpt4-service)项目配置正常的前提下（用其他第三方gpt客户端如ChatGPT Next Web、OpenAI Translator可以正常使用），在本项目的docker-compose文件里修改了以下内容，并且没有启用PROXY：

```yaml
      API_KEY:                  '  ghu_...'
      CUSTOM_API_KEY_PATTERN:   'ghu_[a-zA-Z0-9]{36}'
      API_URL_REDIRECT:         '{"https://api.openai.com/v1/chat/completions":"http://172.19.0.2:8080/v1/chat/completions"}'
```

但现在只有在输入框直接对话的时候可以获得回复，而且模型似乎存在调用错误的问题，[copilot-gpt4-service](https://github.com/aaamoon/copilot-gpt4-service)项目支持gpt-4和gpt-3.5-turbo两种模型，但在本项目的webui对话中，无论选用哪个模型，返回结果都会自称gpt3，也就是说没有成功设置模型（触发了copilot的fallback设置，收到了gpt-3.5-turbo的回复）。另外，在所有其他插件函数中，都无法收到任何回复。经过我在两个项目之间的观察，其他的gpt客户端在成功与copilot-gpt4-service项目互动时，在每次请求前都会发送一次OPTIONS请求，如下图所示：

![image](https://github.com/binary-husky/gpt_academic/assets/32979328/7c486233-400f-47b2-8d8f-cc0b231cc0c9)

![image](https://github.com/binary-husky/gpt_academic/assets/32979328/c8ea1b3f-672e-4611-85cd-ea27275d1a17)

但是gpt_academic与其交互时，只有一个POST请求

![image](https://github.com/binary-husky/gpt_academic/assets/32979328/5514d1ca-1937-443d-a5cd-1d7b03b0483a)

![image](https://github.com/binary-husky/gpt_academic/assets/32979328/fb97e27f-3067-4867-a056-e61c27a38219)

在调用其他功能函数时也是如此

![image](https://github.com/binary-husky/gpt_academic/assets/32979328/bc9cf6c2-a68e-4905-9b14-c51eadcd7b44)

![image](https://github.com/binary-husky/gpt_academic/assets/32979328/d4721529-b92d-4b37-b31a-c3adaa347631)

有时在大量的请求中还会出现一些报错：

![image](https://github.com/binary-husky/gpt_academic/assets/32979328/2b5218b6-b16c-4eca-80d1-75a040f52c55)

从时间上来看，我认为请求其实发送出去了并且得到了处理（返回时间通常为一分多钟），但是不知为何功能函数没有成功收集到结果，导致最终如文档翻译等功能函数输出结果全部为空。

为了排除其他干扰（如copilot-gpt4-service项目中有人反应较多的请求跨域问题），我也试着将docker-compose文件中自定义的子网地址`172.19.0.2`换成`gateway.docker.internal`、除了docker部署，我也尝试了本地python部署的方式，填入了和本地其他gpt客户端完全一致的地址（127.0.0.1:8080）。但所有尝试都表现出了同样的表现，即请求成功发出但功能函数收不到回复。

如果可以的话，希望请您抽空解答一下本项目中的直接对话、功能函数以及其他GPT客户端项目在OpenAI API调用上有什么区别，有什么可能导致上述问题的原因，如果您能提供一些思路的话，我觉得我会更有希望解决上述的问题并将解决方案分享给本项目的其他用户。十分感谢。

**Comment by Geniucker** [comment]
@SuperMaxine 可能是这个问题有关，不过本质上还是其和官方API行为不同 https://github.com/binary-husky/gpt_academic/issues/1447

By the way，已经在这个项目解决了问题 https://github.com/Geniucker/CoGPT ，你可以先试试这个，之后我会给 copilot-gpt4-service 提 PR 修
