### ISSUE TITLE
[Feature]: [Local Message] Reduce the length

### ISSUE THREAD

**Issue by wangnanwy** [binary-husky/gpt_academic#1470]
### Class | 类型

None

### Feature Request | 功能请求

使用GPT-3.5TURBO 的API  ，贵软件项目中的PDF理解功能，当连续使用以后出现以下提示，是怎么会是？
![Uploading gpt.jpg…]()

**Comment by binary-husky** [comment]
只是个警告，重试即可

**Comment by wangnanwy** [comment]
已经收到您的来件！！
