### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Emanon008** [binary-husky/gpt_academic#1471]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

翻译的时候反复出现 报错Something went wrong
Connection errored out.

### Screen Shot | 有帮助的截图

<img width="514" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/88377084/f1282f24-46a0-4122-b667-7841188737e7">

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

（zhe vge

**Comment by binary-husky** [comment]
尝试 `pip install https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.7-py3-none-any.whl`
