### ISSUE TITLE
[Bug]: ArxivID检索问题——使用docker-compose up部署方案4

### ISSUE THREAD

**Issue by sudathesis** [binary-husky/gpt_academic#1474]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

#### 功能测试

使用 https://arxiv.org/abs/2112.10003 进行测试”一键下载arxiv论文并进行翻译摘要“函数插件时可以正常运行
输入参数为2112.10003

<img width="804" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/104356577/f84af553-5dbc-4f5d-800d-be71e4227380">

再进行“Arxiv论文精细翻译（输入arxivID）”测试时也可以正常运行

<img width="797" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/104356577/978f9203-d4de-49ba-a59a-b9c0061db449">

#### 功能运用
但是对于下面这类文章，以 https://arxiv.org/abs/hep-ex/0105031 为例，输入参数根据函数定义中需要调用的输入，应该为hep-ex/0105031

以下是”一键下载arxiv论文并进行翻译摘要“的输出结果

<img width="806" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/104356577/f46251ef-9017-47f1-b329-d64d470c498c">

接着测试“Arxiv论文精细翻译（输入arxivID）”函数插件

<img width="819" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/104356577/a093953a-8d96-4505-808a-a7d80aa13f0a">

### Screen Shot | 有帮助的截图

使用docker-compose up部署方案4

**Comment by binary-husky** [comment]
这种您可以手动下载tar文件 -> 文件上传 -> arxiv 翻译

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/2c60362d-753a-479b-963f-a6cac92afac0)

**Comment by sudathesis** [comment]
如果需要全文翻译的确可以通过下载源文件进行翻译，但如果用“一键下载arxiv论文并进行翻译摘要”翻译摘要就比较麻烦了
