### ISSUE TITLE
局域网连接总是报connection errored out

### ISSUE THREAD

**Issue by M41698K** [binary-husky/gpt_academic#148]
局域网连接总是报something went wrong，public url又没有问题，有解决办法吗？

**Comment by panxiang126** [comment]
这个issues后面有讨论 #23

**Comment by M41698K** [comment]
> 这个issues后面有讨论 #23

谢谢，是设置用户和密码，局域网ip访问才出错，docker方式，当时后面的ngnix方式没太看明白，ip访问不需要设置ngnix吧。如果不设置用户名和密码访问，一切正常，可以详细说一下解决办法吗

**Comment by panxiang126** [comment]
我的情况和你的一样，设置了用户名和密码登录，即本机使用ip登录也会遇到 “connection errored out” 问题，关掉用户名和密码登录就一切都正常了。他们的讨论是反代转发的问题，需要在nginx中修改配置文件，但是我用的是clash，不知道怎么操作。

**Comment by M41698K** [comment]
> 在main.py中也直接设置用户名和密码可行吗？

**Comment by panxiang126** [comment]
那不是一样的嘛
