### ISSUE TITLE
[Bug]: 最新的pip包zhipuai会导致依赖冲突

### ISSUE THREAD

**Issue by Menghuan1918** [binary-husky/gpt_academic#1481]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

最新的zhipuai包依赖需要pydantic>=2.5.2,与现有的版本1.10.11冲突

### Screen Shot | 有帮助的截图

![图片](https://github.com/binary-husky/gpt_academic/assets/122662527/7338e985-305c-4885-a7b4-c8192c0b0615)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

临时解决方法:
pip install zhipuai==1.0.7
安装旧版本zhipuai进行使用

**Comment by binary-husky** [comment]
目前已经支持pydantic v2 了
