### ISSUE TITLE
[Bug]: WARNING:root:No GPU found. Conversion on CPU is very slow.

### ISSUE THREAD

**Issue by lisanyao** [binary-husky/gpt_academic#1482]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用PDF精翻插件时，提示没有找到GPU，但是电脑有GPU

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/100399931/e6cbf3d9-0b3d-4bde-8b3f-792a53ab257a)

**Comment by lisanyao** [comment]
(run) D:\my\myGitHub\gpt_academic-version3.64-1>python
Python 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.is_available())
False
这个插件是使用pytorch框架来和GPU通信的吗？
是不是需要单独安装pytorch？

**Comment by lisanyao** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/100399931/81e87e99-7aa9-449d-ae71-b66c8535f077)
这个插件是使用pytorch框架来和GPU通信的吗？
是不是需要单独安装pytorch？

**Comment by August-L-J** [comment]
真巧，我也遇到一样的问题，等到最后，PDF精翻还会报错

**Comment by binary-husky** [comment]
需要安装带cuda的pytorch
