### ISSUE TITLE
[Bug]: 非官方的api-key如何调用

### ISSUE THREAD

**Issue by ifhjl** [binary-husky/gpt_academic#1483]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

如题所说，由于没有外国行用卡，我所使用的是其他渠道得到的api_key，是可以调用的，需要加入一行openai.api_base = "https://api.openai-sb.com/v1"。请问是否可以使用呢？

### Screen Shot | 有帮助的截图

无

**Comment by binary-husky** [comment]
看看wiki啊
