### ISSUE TITLE
[Feature]: 能否全部打包为一个独立的exe运行包运行呢？

### ISSUE THREAD

**Issue by pccai** [binary-husky/gpt_academic#1487]
### Class | 类型

None

### Feature Request | 功能请求

个人电脑上允许，具备一定联网能力。

**Comment by pccai** [comment]
OK，我理解就是把下载好的文件夹整体打包，启动bat。py文件不需要编译发布成exe吗？
tks

**Comment by binary-husky** [comment]
项目中有些脚本是动态加载的，所以目前不能用现有的工具打包成exe
