### ISSUE TITLE
[Bug]: 干净的windows 10环境，允许一键安装脚本后，启动询问多个GPT模型报错

### ISSUE THREAD

**Issue by pccai** [binary-husky/gpt_academic#1488]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

ImportError: This modeling file requires the following packages that were not found in your environment: sentencepiece. Run `pip install sentencepiece`

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/2232794/623bfd64-fc03-404e-84b3-b905902f1a76)

**Comment by binary-husky** [comment]
Run pip install sentencepiece
