### ISSUE TITLE
[Feature]:  能否支持接入最新的GLM4 的API？

### ISSUE THREAD

**Issue by catherine-lisa** [binary-husky/gpt_academic#1490]
### Class | 类型

None

### Feature Request | 功能请求

智谱清言的GLM4 于1.16发布，目前可否添加支持其对应的API接入？

**Comment by GengKanghua** [comment]
已经可以用了，docker部署，`ZHIPUAI_MODEL:            '    glm-4  '` [即可。]，其他模型编码可以参考该网页(https://open.bigmodel.cn/dev/howuse/model)

**Comment by binary-husky** [comment]
> 已经可以用了，docker部署，`ZHIPUAI_MODEL: ' glm-4 '` 即可。 其他模型编码可以参考该网页(https://open.bigmodel.cn/dev/howuse/model)

已经是默认选项了
