### ISSUE TITLE
[Bug]: 挂载目录

### ISSUE THREAD

**Issue by lizkefan** [binary-husky/gpt_academic#1493]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

之前一直使用的宝塔，宝塔容器管理有一个`目录`按钮，点击后可以进入容器目录内修改相关文件。

最近换到了1panel，一时间不知道怎么可视化修改项目文件了。

`version: '3'
services:
  gpt_academic_nolocalllms:
    image: ghcr.io/binary-husky/gpt_academic_nolocal:master
    restart: always
    **volumes:
      - /path/to/local/directory:/gpt**
    environment:
      # 请查阅 `config.py` 以查看所有的配置信息
`

重新up -d以后，目录内没有任何文件，也一直在重启中。

项目日志
`
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
python3: can't open file '/gpt/main.py': [Errno 2] No such file or directory
`

### Screen Shot | 有帮助的截图

none

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

none

**Comment by lizkefan** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/115395219/81f0f0ad-65bd-4aef-a8e0-468a8902f6b8)

**Comment by binary-husky** [comment]
抱歉，这个和项目没有关系，不能归类为项目【BUG】

**Comment by luojiyin1987** [comment]
@lizkefan  请提供你的 docker compose 文件内容， 大概率是 command 有问题
```yaml
command: >
      bash -c "python3 -u main.py"
````
