### ISSUE TITLE
[Bug]: Autogen多智能终端体执行出错

### ISSUE THREAD

**Issue by dongla-danzeng** [binary-husky/gpt_academic#1496]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

在执行多智能终端时出现“TypeError: string indices must be integers, not 'str'”，根据之前的bug经验是感觉需要开启proxy，但是个人服务器是国外的，所以并没有开启，其提供解决帮助

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/72214248/28893c74-7903-4ea4-b828-1696487a839f)

**Comment by binary-husky** [comment]
this issue is cause by newer autogen version, anyway, solve by https://github.com/binary-husky/gpt_academic/commit/a6fdc493b7351a2722ed3accc7ef82fb73a8f844

**Comment by binary-husky** [comment]
thank you for discovering and reporting this issue, 
and would you mind join dev QQ group 610599535?
