### ISSUE TITLE
有没有完全部署成功的大神出个详细的部署步骤呀？Windows 有截图，跪求

### ISSUE THREAD

**Issue by Jeffy995** [binary-husky/gpt_academic#150]
Windows安装部署
基本环：安装anaconda
1.下载项目 CMD
选择路径
git clone https://github.com/binary-husky/chatgpt_academic.git
cd chatgpt_academic
我们建议将config.py复制为config_private.py并将后者用作个性化配置文件以避免config.py中的变更影响你的使用或不小心将包含你的OpenAI API KEY的config.py提交至本项目。
cp config.py config_private.py
2.创建虚拟环境 python 3.11
conda create -n chatgpt python=3.11.0 #新建环境、
3.进入项目下载路径
例如 cd  G:\python\Program\chatgpt_academic
4.启动虚拟环境
conda activate chatgpt
5. 安装 gradio>=3.23
（1）到https://pypi.org/project/gradio/ 下载whl版本
（2）pip install  G:\python\Program\chatgpt_academic\gradio-3.23.0-py3-none-any.whl
6.配置其他环境
（1）打开requirements.txt，注释掉gradio，然后保存
（2）运行 python -m pip install -r requirements.txt
7.启动代理
8. 配置config_private.py
（1）添加API_KEY
（2）修改USE_PROXY = Ture
（3）修改proxies
在浏览器输入: https://ipapi.co/json/
浏览器上右键->检查->网络->ctrl+r
打开json，将远程地址修改到proxies = { "http": "104.26.9.44:443", "https": "104.26.9.44:443", }
9.启动程序
python main.py

**Comment by Goudandaner** [comment]
B站好像有的。

**Comment by Jeffy995** [comment]
Windows安装部署
基本环：安装anaconda
1.下载项目 CMD
选择路径
git clone https://github.com/binary-husky/chatgpt_academic.git
cd chatgpt_academic
我们建议将config.py复制为config_private.py并将后者用作个性化配置文件以避免config.py中的变更影响你的使用或不小心将包含你的OpenAI API KEY的config.py提交至本项目。
cp config.py config_private.py
2.创建虚拟环境 python 3.11
conda create -n chatgpt python=3.11.0 #新建环境、
3.进入项目下载路径
例如 cd  G:\python\Program\chatgpt_academic
4.启动虚拟环境
conda activate chatgpt
5. 安装 gradio>=3.23
（1）到https://pypi.org/project/gradio/ 下载whl版本
（2）pip install  G:\python\Program\chatgpt_academic\gradio-3.23.0-py3-none-any.whl
6.配置其他环境
（1）打开requirements.txt，注释掉gradio，然后保存
（2）运行 python -m pip install -r requirements.txt
7.启动代理
8. 配置config_private.py
（1）添加API_KEY
（2）修改USE_PROXY = Ture
（3）修改proxies
在浏览器输入: https://ipapi.co/json/
浏览器上右键->检查->网络->ctrl+r
打开json，将远程地址修改到proxies = { "http": "104.26.9.44:443", "https": "104.26.9.44:443", }
9.启动程序
python main.py

**Comment by binary-husky** [comment]
代理的问题也可以看 #1
