### ISSUE TITLE
[Bug]: 第三方API-KEY以及API_URL_REDIRECT重定向地址设置好后，交互页面依旧Error：You can find your API key at https://platform.openai.com/account/api-keys

### ISSUE THREAD

**Issue by LuoFanA595** [binary-husky/gpt_academic#1501]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

部署方法使用Docker-Compose

我的docker-compose.yml文件内容仅保留了【方案一】区域的信息。

API_KEY 填写的是第三方的转发KEY
服务器是海外的，USE_PROXY参数改为False

其余信息均为更改

config.py文件内容修改项如下：
API_KEY与docker-compose.yml同步

转发API修改，以下转发地址经过测试 是可以使用的。
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"https://www.wushuangai.com/v1/chat/completions"}

其余内容均未更改。

但执行 docker-compose up 去到页面输入内容后报错如下：

'''Json异常 “error”: { “message”: “Incorrect API key provided: sk-ExsOP***************************************9858. You can find your API key at https://platform.openai.com/account/api-keys.”, “type”: “invalid_request_error”, “param”: null, “code”: “invalid_api_key” }}'''

页面回复：[Local Message] Incorrect API key. OpenAI以提供了不正确的API_KEY为由, 拒绝服务. 请登录OpenAI查看详情 https://platform.openai.com/signup

转发API映射已经设置好了。不知道是什么原因。。。。。请有经验的朋友麻烦看一下

### Screen Shot | 有帮助的截图

<img width="1204" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/83820267/5cf55932-7b31-42c9-a9bb-4e12e8e9f445">
<img width="1365" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/83820267/9beb79c8-a434-4fd0-815c-b5e4a2964048">
<img width="2201" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/83820267/7591efbc-b7d0-493b-9be2-f55b0b29d34c">

**Comment by binary-husky** [comment]
请**只使用一种**配置方法，把所有配置都移动到 docker-compose.yml 中

**Comment by JingsenZhang** [comment]
Json解析异常 “error”: { “message”: “Incorrect API key provided: sk-rHEqG***************************************Rroo. You can find your API key at https://platform.openai.com/account/api-keys.”, “type”: “invalid_request_error”, “param”: null, “code”: “invalid_api_key” }}

[Local Message] Incorrect API key. OpenAI以提供了不正确的API_KEY为由, 拒绝服务. 请登录OpenAI查看详情 https://platform.openai.com/signup

你好，我遇到了同样的问题（API_URL_REDIRECT设置无误）

**Comment by xiegangao** [comment]
解决了吗，佬
