### ISSUE TITLE
[Bug]: 找不到文件

### ISSUE THREAD

**Issue by mct1223** [binary-husky/gpt_academic#1505]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

上传文件后，想要使用函数插件，但是老是显示找不到文件

### Screen Shot | 有帮助的截图

![屏幕截图 2024-01-23 170228](https://github.com/binary-husky/gpt_academic/assets/140930504/c52697a5-d76d-4629-ab7b-26cb471101cd)

**Comment by binary-husky** [comment]
上传的文件类型不对
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/c7e0299e-fad2-400c-8f7a-ade410d608c1)

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/09ed45e4-40be-4550-abe8-4f26a55c6689)
