### ISSUE TITLE
[Bug]: 翻译pdf时，无法进行翻译，且内容不对应

### ISSUE THREAD

**Issue by mct1223** [binary-husky/gpt_academic#1508]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

翻译pdf时，无法进行翻译，且内容不对应

### Screen Shot | 有帮助的截图

![屏幕截图 2024-01-24 175519](https://github.com/binary-husky/gpt_academic/assets/140930504/04e15822-7d3d-4507-a095-8873288e7d9c)
![屏幕截图 2024-01-24 175538](https://github.com/binary-husky/gpt_academic/assets/140930504/7eb8b296-9d69-43f3-a731-5976c16ec09c)
![屏幕截图 2024-01-24 175557](https://github.com/binary-husky/gpt_academic/assets/140930504/3e95a9b6-27ff-47f9-a6ef-8b5f157c5dd5)
![屏幕截图 2024-01-24 175629](https://github.com/binary-husky/gpt_academic/assets/140930504/5c572509-874c-46ec-9b0a-28bf913c74fa)

**Comment by binary-husky** [comment]
Grobid不能处理某些PDF，比如扫描版，或者有字符混淆加密的PDF
