### ISSUE TITLE
[Feature]: 能不能添加BASE_URL (optional) Default: https://api.openai.com  Examples: http://your-openai-proxy.com  Override openai api request base url.

### ISSUE THREAD

**Issue by zhanghxiao** [binary-husky/gpt_academic#1509]
### Class | 类型

None

### Feature Request | 功能请求
能不能添加
BASE_URL (optional)
Default: https://api.openai.com

Examples: http://your-openai-proxy.com

Override openai api request base url.

**Comment by binary-husky** [comment]
看wiki啊
