### ISSUE TITLE
Arxiv论文精细翻译（输入arxivID)这个插件，调用出错请求完善，谢谢！

### ISSUE THREAD

**Issue by alleniver** [binary-husky/gpt_academic#1510]
### Class | 类型

其他

### Feature Request | 功能请求

使用插件[Arxiv论文精细翻译（输入arxivID)这个插件，输入2401.11708这个ID后翻译会出现下面错误，试过其他文件都是正常的。用这个文章ID调用其类似的那个翻译综述的插件是正常的。
还有我有个问题，在使用其他的插件翻译，比如牛轧糖或其他精翻插件，翻译的结果都是markdown的对照格式的，要怎么让能把它翻译成单中文文本，并且编译到PDF格式，就像"[Arxiv论文精细翻译（输入arxivID)"这个插件得到的结果那样，我要怎么操作？
麻烦告知一下，谢谢！

Traceback (most recent call last):
  File ".\toolbox.py", line 185, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Latex输出PDF结果.py", line 253, in Latex翻译中文并重新编译PDF
    txt, arxiv_id = yield from arxiv_download(chatbot, history, txt, allow_cache)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\crazy_functions\Latex输出PDF结果.py", line 143, in arxiv_download
    extract_archive(file_path=dst, dest_dir=extract_dst)
  File ".\toolbox.py", line 341, in extract_archive
    with tarfile.open(file_path, "r:*") as tarobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\envs\gptac_venv\Lib\tarfile.py", line 1811, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('truncated header')

**Comment by quduoduo** [comment]
File "C:\Users\XXXX\Documents\OneKeyInstallerForWindowsAndMacOS\installer_files\env\lib\tarfile.py", line 1811, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('truncated header')
今天使用出现这个错误，之前没有类似错误

**Comment by quduoduo** [comment]
同样是部分文章存在该问题，如2310.14414
