### ISSUE TITLE
[Bug]: Model gpt-4 does not exist. 模型不存在

### ISSUE THREAD

**Issue by prousty** [binary-husky/gpt_academic#1512]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

网络成功配置
APIkey导入成功
购买了gpt-4，网页版gpt-4正常使用
但是在学术优化3.7.1里显示”[Local Message] Model gpt-4 does not exist. 模型不存在, 或者您没有获得体验资格.“
是选错模型了么？

### Screen Shot | 有帮助的截图

![1706197004937](https://github.com/binary-husky/gpt_academic/assets/8150241/575c6ddb-aecd-4239-9d40-58c6ab6ea120)

**Comment by binary-husky** [comment]
字面意思
