### ISSUE TITLE
[Bug]: zhipuai在frontier分支上llm_kwargs["llm_model"]参数设置错误

### ISSUE THREAD

**Issue by Menghuan1918** [binary-husky/gpt_academic#1524]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

在[这个提交](https://github.com/binary-husky/gpt_academic/commit/16a58238854ede2727d1c2bc20d9128e1ad1f48e)中
```
    if llm_kwargs["llm_model"] == "zhipuai":
        llm_kwargs["llm_model"] = zhipuai_default_model
```
zhipuai_default_model值为glm-4,但是在model_info中对应的zhipuai只有zhipuai的参数,这会导致调用model_info出错

在windows和linux下均会出错

### Screen Shot | 有帮助的截图

![图片](https://github.com/binary-husky/gpt_academic/assets/122662527/2856b60e-41a9-41b6-953b-f33f5fb08352)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

pdf翻译相关插件都会出错

**Comment by binary-husky** [comment]
修好了！~
