### ISSUE TITLE
[Bug]: 实时语音对话不工作，查看日志报错 ModuleNotFoundError: No module named 'webrtcvad'

### ISSUE THREAD

**Issue by Qm-jmz** [binary-husky/gpt_academic#1532]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

使用dockers compose file最后一个方案进行部署，麦克风已能正常工作，但调用阿里云时似乎存在问题，并没有实现语音识别。前端表现如下：
![image](https://github.com/binary-husky/gpt_academic/assets/50917637/5d3a606c-6119-4a47-86fc-182bf7dfa115)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/50917637/2d7ec5fa-0783-45be-8f42-963dfd58b774)
![image](https://github.com/binary-husky/gpt_academic/assets/50917637/c80495a2-583a-4f2c-81c7-112b7344d2a0)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

[ENV_VAR] 尝试加载ALIYUN_APPKEY，默认值： --> 修正值：略
 [ENV_VAR] 成功读取环境变量ALIYUN_APPKEY
[ENV_VAR] 尝试加载ALIYUN_TOKEN，默认值： --> 修正值：
 [ENV_VAR] 成功读取环境变量ALIYUN_TOKEN
[ENV_VAR] 尝试加载ALIYUN_ACCESSKEY，默认值： --> 修正值：略
 [ENV_VAR] 成功读取环境变量ALIYUN_ACCESSKEY
[ENV_VAR] 尝试加载ALIYUN_SECRET，默认值： --> 修正值：略
 [ENV_VAR] 成功读取环境变量ALIYUN_SECRET
b'{"ErrMsg":"","Token":{"UserId":"略","Id":"略","ExpireTime":略}}'
token = 略
expireTime = 略
Exception in thread Thread-3 (audio_convertion_thread):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/gpt/crazy_functions/live_audio/aliyunASR.py", line 178, in audio_convertion_thread
    import webrtcvad
ModuleNotFoundError: No module named 'webrtcvad'

**Comment by Qm-jmz** [comment]
怀疑是否镜像中缺少webrtcvad依赖

**Comment by Qm-jmz** [comment]
通过在容器的终端中通过 pip install webrtcvad 手动安装该库，目前已可以正常工作。

**Comment by binary-husky** [comment]
> 怀疑是否镜像中缺少webrtcvad依赖

的确如此，感谢提醒，已加
