### ISSUE TITLE
[Feature]: 接入模型yshs

### ISSUE THREAD

**Issue by MengDanzz** [binary-husky/gpt_academic#1534]
### Class | 类型

大语言模型

### Feature Request | 功能请求

该语言模型示例： https://pypi.org/project/yshs/

**Comment by MengDanzz** [comment]
是一家chatgpt代理机构，提供自己的token，但无法直接作为 openai token

**Comment by binary-husky** [comment]
第三方API‐KEY接入指南
https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97

非常抱歉，我们目前精力有限，只能专注于符合openai标准接口的第三方api接入，以及自主研发新生大模型的接入
