### ISSUE TITLE
[Bug]: 怎么更改成本地，如何安装GROBID本地服务。

### ISSUE THREAD

**Issue by kongsam3** [binary-husky/gpt_academic#1536]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

正在连接GROBID服务，请稍候: https://qingxu98-grobid8.hf.space 如果等待时间过长，请修改config中的GROBID_URL，可修改成本地GROBID服务。

### Screen Shot | 有帮助的截图

/

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

/

**Comment by binary-husky** [comment]
请参考 https://github.com/kermitt2/grobid
用docker部署即可，需要对docker有一定的前置知识储备
