### ISSUE TITLE
是否考虑用Electron框架封装为桌面应用

### ISSUE THREAD

**Issue by m2kar** [binary-husky/gpt_academic#154]
作者你好，

这个工具看起来功能非常强大，但对非计算机背景的用户来说，部署使用尚有难度，请问是否考虑封装为更加统一的桌面应用，实现跨平台的使用。

技术栈可以参考使用Electron框架，对跨平台的使用很友好。

**Comment by m2kar** [comment]
如作者有计划推出，本人可以助一臂之力 😁

**Comment by AllenXiao95** [comment]
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/18730237/229012940-9bb2eea1-8d4d-4abe-8b8b-27a85072d54a.png">
你说的是这种么? 我可以提供技术支持, 目前在做入口拆分, 支持工具docker启动或者url启动

**Comment by m2kar** [comment]
是这个，期待大佬早日完工

**Comment by binary-husky** [comment]
大佬们好 @m2kar @AllenXiao95 ，

这个Electron确实不是我熟悉的东西，

但是这个项目是属于大家的，

如果有这种改进我们会尽可能配合

**Comment by binary-husky** [comment]
Duplicate桌面安装包  #157

**Comment by AllenXiao95** [comment]
上两周比较忙, 项目地址: https://github.com/AllenXiao95/chatgpt_academic_desktop
我这用electron封装了下, 目前支持 配置化启动docker和url启动 两种方式, 配置信息第一次输入后会存在用户本地, 欢迎试用
