### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SimoNgwujsudhw** [binary-husky/gpt_academic#1550]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

在jupyter notebook插件调用的时候报错，报错显示PaperFileGroup没有get_token_num方法，我把这个方法加上去了不知道对不对（加上去似乎是可以正常运行了

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/134476447/49f06429-04e9-45dd-b976-7e37e34263ae)

**Comment by SimoNgwujsudhw** [comment]
我把gettoken函数定义放到PaperFileGroup外以后似乎显示的更对一点

**Comment by SimoNgwujsudhw** [comment]
[GPT-Academic-2024-02-12-14-01-30.md](https://github.com/binary-husky/gpt_academic/files/14235492/GPT-Academic-2024-02-12-14-01-30.md)
最后结果大概是这样

**Comment by binary-husky** [comment]
非常感谢反馈，修复如下
https://github.com/binary-husky/gpt_academic/commit/b9b1e12dc90b2b13b0e8dd6425aa843a164af94d
