### ISSUE TITLE
[Bug]: docker安装版本适配spark api报错

### ISSUE THREAD

**Issue by Fred-supre** [binary-husky/gpt_academic#1554]
### Installation Method | 安装方法与平台

Docker-Compose（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

在mac本地使用conda安装方式，适配spark api可以正常运行。但是通过docker compose方式安装之后通过spark api会出现报错，不过千帆api则可以正常使用

### Screen Shot | 有帮助的截图

<img width="1423" alt="Snipaste_2024-02-14_21-12-27" src="https://github.com/binary-husky/gpt_academic/assets/57496712/a1672606-c4ce-4328-a05a-b1d311cc26bd">

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

gpt_academic_nolocalllms-1  | error: Connection to remote host was lost.
gpt_academic_nolocalllms-1  | Exception ignored in thread started by: <function SparkRequestInstance.create_blocking_request.<locals>.run at 0x2aaaf7fdfa60>
gpt_academic_nolocalllms-1  | Traceback (most recent call last):
gpt_academic_nolocalllms-1  |   File "/gpt/request_llms/com_sparkapi.py", line 113, in run
gpt_academic_nolocalllms-1  |     ws.send(data)
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/websocket/_app.py", line 284, in send
gpt_academic_nolocalllms-1  |     raise WebSocketConnectionClosedException("Connection is already closed.")
gpt_academic_nolocalllms-1  | websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
gpt_academic_nolocalllms-1  | Traceback (most recent call last):
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 422, in run_predict
gpt_academic_nolocalllms-1  |     output = await app.get_blocks().process_api(
gpt_academic_nolocalllms-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1323, in process_api
gpt_academic_nolocalllms-1  |     result = await self.call_function(
gpt_academic_nolocalllms-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1067, in call_function
gpt_academic_nolocalllms-1  |     prediction = await utils.async_iteration(iterator)
gpt_academic_nolocalllms-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 336, in async_iteration
gpt_academic_nolocalllms-1  |     return await iterator.__anext__()
gpt_academic_nolocalllms-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 329, in __anext__
gpt_academic_nolocalllms-1  |     return await anyio.to_thread.run_sync(
gpt_academic_nolocalllms-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
gpt_academic_nolocalllms-1  |     return await get_async_backend().run_sync_in_worker_thread(
gpt_academic_nolocalllms-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
gpt_academic_nolocalllms-1  |     return await future
gpt_academic_nolocalllms-1  |            ^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
gpt_academic_nolocalllms-1  |     result = context.run(func, *args)
gpt_academic_nolocalllms-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/usr/local/lib/python3.11/site-packages/gradio/utils.py", line 312, in run_sync_iterator_async
gpt_academic_nolocalllms-1  |     return next(iterator)
gpt_academic_nolocalllms-1  |            ^^^^^^^^^^^^^^
gpt_academic_nolocalllms-1  |   File "/gpt/toolbox.py", line 115, in decorated
gpt_academic_nolocalllms-1  |     yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
gpt_academic_nolocalllms-1  |   File "/gpt/request_llms/bridge_all.py", line 765, in predict
gpt_academic_nolocalllms-1  |     yield from method(inputs, llm_kwargs, *args, **kwargs)
gpt_academic_nolocalllms-1  |   File "/gpt/request_llms/bridge_spark.py", line 60, in predict
gpt_academic_nolocalllms-1  |     if response == f"[Local Message] 等待{model_name}响应中 ...":
gpt_academic_nolocalllms-1  |        ^^^^^^^^
gpt_academic_nolocalllms-1  | UnboundLocalError: cannot access local variable 'response' where it is not associated with a value

**Comment by binary-husky** [comment]
我修复了response的问题：https://github.com/binary-husky/gpt_academic/commit/e359fff0405c4cb865b809b4ecfc0a95a54d2512

但是具体到这个问题的话，大概是星火的key失效导致的

**Comment by Fred-supre** [comment]
> 我修复了response的问题：[e359fff](https://github.com/binary-husky/gpt_academic/commit/e359fff0405c4cb865b809b4ecfc0a95a54d2512)
> 
> 但是具体到这个问题的话，大概是星火的key失效导致的

重新尝试之后还是会报错，但是报错信息变成了：“error: Connection to remote host was lost.”
我比较疑惑为啥本地运行没问题，但是docker容器运行会出问题，如果是key有问题理论上本地运行的版本也会报错呀

**Comment by binary-husky** [comment]
> > 我修复了response的问题：[e359fff](https://github.com/binary-husky/gpt_academic/commit/e359fff0405c4cb865b809b4ecfc0a95a54d2512)
> > 但是具体到这个问题的话，大概是星火的key失效导致的
> 
> 重新尝试之后还是会报错，但是报错信息变成了：“error: Connection to remote host was lost.” 我比较疑惑为啥本地运行没问题，但是docker容器运行会出问题，如果是key有问题理论上本地运行的版本也会报错呀

会不会因为配置格式有点问题呢？
