### ISSUE TITLE
[Bug]: 运行时界面显示不正常

### ISSUE THREAD

**Issue by pengbin2023** [binary-husky/gpt_academic#1556]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

python 3.9.8 安装后，后台显示正常，但界面显示不正常，后台显示如下：
WARNING: You are using pip version 21.2.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\86133\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
PS D:\ai\gpt_academic> python main.py
 [PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
代理配置 无, 代理所在地：China - Chinanet
 [API_KEY] 本项目现已支持OpenAI和Azure的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,azure-key3"
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。
 [API_KEY] 您的 API_KEY 不满足任何一种已知的密钥格式，请在config文件中修改API密钥之后再运行。
如果浏览器没有自动打开，请复制并转到以下URL：
        「暗色主题已启用（支持动态切换主题）」: http://localhost:57343
Running on local URL:  http://0.0.0.0:57343
正在执行一些模块的预热 ...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/153375149/c369bc9f-87a8-4f19-984a-97c2b79541c4)
![image](https://github.com/binary-husky/gpt_academic/assets/153375149/b62cdbfc-066d-43ac-b6d8-4a3016039ecc)

**Comment by pengbin2023** [comment]
将样式改成 亮色模式 DARK_MODE = False后，如下
![image](https://github.com/binary-husky/gpt_academic/assets/153375149/cacb16fc-5983-4d4e-a0a8-e7097da32e92)

**Comment by binary-husky** [comment]
浏览器按F12，有任何报错吗

**Comment by binary-husky** [comment]
另外更换浏览器有用吗
