### ISSUE TITLE
[Bug]: Gemini-Pro本地发起请求的时间似乎异常

### ISSUE THREAD

**Issue by wl223600** [binary-husky/gpt_academic#1559]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

在GPT-Academic使用Gemini-Pro模型的响应速度似乎与通过```curl```直接调用有较大差距，有时需等待1分钟才能收到来自Gemini的回复。
初步分析考虑为在本地端发起请求所花费的时间过长。
复现步骤：

1. 在自己可控制的服务器上搭建nginx服务，同时配置一个正常网页和指向Gemini API的反向代理。
2. 修改```request_llms\com_google.py```内的```self.url_gemini```。
3. **同时**操作，通过浏览器向网页发起请求（或curl发起会话）；同时GPT-Academic内向Gemini-Pro模型发起会话。
4. 查看服务器端nginx日志。

### Screen Shot | 有帮助的截图

（暂无，最直观的表现为点击“提交”按钮后平均1分钟后才有相应，其他模型如gpt/qianfan/qwen系列无此问题）

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）
备注：GPT-Academic部署于国内Debian 12机器上，未启用代理。远程服务器位于国外。

##### 可通过如下命令手动发起请求。
````
curl https://<自定义域名或generativelanguage.googleapis.com>/v1beta/models/gemini-pro:streamGenerateContent?key=[API_key，可于Google AI Studio免费申请] \
        -H 'Content-Type: application/json' \
        --no-buffer \
        -d '{ "contents":[{"parts":[{"text": "<替换成你想要的内容>"}]}]}' \
        2> /dev/null | grep "text"
````
##### 查看nginx日志。
````
# log位置根据个人配置不同可能会有变化。
cat /var/log/nginx/access.log
````

###### GPT-Academic
````[已隐藏IP:GPT-Academic] - - [16/Feb/2024:22:03:51 -????] "POST /v1beta/models/gemini-pro:streamGenerateContent?key=[已隐藏API_key] HTTP/2.0" 200 1333 "-" "python-requests/2.28.1"````
###### 浏览器
````[已隐藏IP:Chrome] - - [16/Feb/2024:22:02:36 -????] "GET / HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36"````

###### GPT-Academic
````[已隐藏IP] - - [16/Feb/2024:23:58:35 -????] "POST /v1beta/models/gemini-pro:streamGenerateContent?key=[已隐藏API_key] HTTP/2.0" 200 1120 "-" "python-requests/2.28.1"````
###### CURL(on windows 11)
````[已隐藏IP] - - [16/Feb/2024:23:57:39 -????] "POST /v1beta/models/gemini-pro:streamGenerateContent?key=[已隐藏API_key] HTTP/2.0" 200 779 "-" "curl/8.4.0"````

#### 思考
上述症状是否可以提示点击GPT-Academic内的"提交"按钮很长一段时间后，才向Gemini API提出了````POST````请求？

非程序员，上述bug汇报如有问题请见谅。

**Comment by binary-husky** [comment]
与 #1546 重复，合并处理
