### ISSUE TITLE
[Bug]: Add an image to use models/gemini-pro-vision, or switch your model to a text model.

### ISSUE THREAD

**Issue by jun0wanan** [binary-husky/gpt_academic#1563]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

我用gemini-vision-pro的时候，只输入text会报上述错误，是因为必须图文吗？多模态模型不能只输入text？

### Screen Shot | 有帮助的截图

无

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

无

**Comment by binary-husky** [comment]
嗯目前似乎需要图文，目前vision模型都不太实用
