### ISSUE TITLE
[Bug]:  PDF翻译中文并重新编译PDF TypeError: report_exception() missing 1 required positional argument: 'b'

### ISSUE THREAD

**Issue by danfouer** [binary-husky/gpt_academic#1564]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

[Local Message] 插件调用出错:

Traceback (most recent call last):
  File ".\toolbox.py", line 191, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File ".\crazy_functions\Latex输出PDF.py", line 437, in PDF翻译中文并重新编译PDF
    report_exception(chatbot, history, a=f"请配置 MATHPIX_APPID 和 MATHPIX_APPKEY")
TypeError: report_exception() missing 1 required positional argument: 'b'

 

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/4875770/1ab29003-bdb9-4728-868b-98ef1635afe6)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023)
kpathsea version 6.3.5
Copyright 2023 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.39; using libpng 1.6.39
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04

**Comment by binary-husky** [comment]
修复啦

https://github.com/binary-husky/gpt_academic/commit/b72289bfb05605ce3dfd127cf3bf9592897a9edf

另外你还需要配置 MATHPIX_APPID 和 MATHPIX_APPKEY
