### ISSUE TITLE
整个GPT-Academic程序能否支持全英语环境，包括插件，以及提问和回复？

### ISSUE THREAD

**Issue by huskier** [binary-husky/gpt_academic#1573]
你好，想问下整个GPT-Academic程序能否支持全英语环境，包括插件，以及提问和回复？

**Comment by binary-yuki** [comment]
详见[multi-language.py](https://github.com/binary-husky/gpt_academic/blob/master/multi_language.py)

**Comment by huskier** [comment]
Thank you.
Best regards.
