### ISSUE TITLE
[Feature]: 能否使用simpletex的api来代替Mathpix使用？

### ISSUE THREAD

**Issue by yinjiashu** [binary-husky/gpt_academic#1575]
### Class | 类型

None

### Feature Request | 功能请求

目前暂时不好免费申请mathpix的ocrapi，上网上找了一下发现好像多有人推荐用simpletex代替mathpix使用，现在我看了一下也开始开放api公测了，请问我们这个项目的脚本能不能使用这个api呢？或者有没有什么自己更改代码使用simpletex的api呢？
附开放平台api文档https://simpletex.cn/api_doc

**Comment by binary-husky** [comment]
mathpix的ocr不是只识别公式，还会转化成tex，所以目前还不行

**Comment by CNZedChou** [comment]
申请mathpix api需要一次性付费20$
