### ISSUE TITLE
[Bug]: 第三方API-KEY不满足要求

### ISSUE THREAD

**Issue by lipc20052006** [binary-husky/gpt_academic#1576]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

用了API2D的KEY，参照[第三方API‐KEY接入指南](https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)做了设置，key可以成功导入
![image](https://github.com/binary-husky/gpt_academic/assets/8895184/dfd5b2db-5567-40bd-b326-8db775241217)

但使用的时候报错，
![image](https://github.com/binary-husky/gpt_academic/assets/8895184/b47ef2aa-f98f-4b30-adc5-ae8e74d2c714)

“您提供的api-key不满足要求，不包含任何可用于gpt-3.5-turbo-16k的api-key。您可能选择了错误的模型或请求源。”，“您提供的api-key不满足要求，不包含任何可用于gpt-3.5-turbo的api-key。您可能选择了错误的模型或请求源。”
不知道哪里不对，请指点

### Screen Shot | 有帮助的截图

![ongfig](https://github.com/binary-husky/gpt_academic/assets/8895184/1e4927f0-1d32-4dbc-9518-d888bf59a9e8)

**Comment by binary-husky** [comment]
无法复现
请检查配置是否生效

**Comment by lisch7** [comment]
同样的问题，API2D的key无法使用

**Comment by WanZunGe** [comment]
同样的问题，请问楼主解决了吗

**Comment by MasteLeo** [comment]
我也遇到了

**Comment by lisch7** [comment]
@MasteLeo @WanZunGe @lipc20052006 @binary-husky 插楼回答一下这个问题，在AVAIL_LLM_MODELS和LLM_MODEL这里把api2d的模型加上就能用了，如图：
![image](https://github.com/user-attachments/assets/da463b82-5c5c-4ca2-bf07-423bcc930040)

**Comment by MasteLeo** [comment]
您好，您的邮件已收到，我会尽快查看，谢谢。
