### ISSUE TITLE
[Feature]: 是否考虑增加星火V3.5的支持？

### ISSUE THREAD

**Issue by wangxiancao** [binary-husky/gpt_academic#1580]
### Class | 类型

大语言模型

### Feature Request | 功能请求

是否我没找到，但是现在的模型已经更新到V3.5，是否能更新这个部分。
不然只能返回这个error ：“请求错误: 11200, {'header': {'code': 11200, 'message': 'AppIdNoAuthError:(13:26:52.549) tokens.total', 'sid': 'cht000bfbb6@dx18de3e15784b8f2550', 'status': 2}}”

<img width="600" alt="spark" src="https://github.com/binary-husky/gpt_academic/assets/67248894/f5e89c68-d4fc-4c6d-b5a1-9bb8a5dbd095">

**Comment by binary-husky** [comment]
我记得已经更新了呀
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/f94d5074-9915-4841-bb4f-b8d51f83a065)

**Comment by binary-husky** [comment]
有什么问题吗？

**Comment by wangxiancao** [comment]
更新本地库后已经成功使用，config.py里没有sparkv3.5的选项，我自己按照格式写了一个
