### ISSUE TITLE
[Feature]: chatgpt-0125

### ISSUE THREAD

**Issue by pure-maple** [binary-husky/gpt_academic#1590]
### Class | 类型

大语言模型

### Feature Request | 功能请求

建议支持chatgpt最新0125版本模型调用

**Comment by binary-husky** [comment]
请验证这个PR是否有效

https://github.com/binary-husky/gpt_academic/pull/1594

**Comment by awwaawwa** [comment]
> 请验证这个 PR 是否有效
> 
> #1594
根据 [OpenAI Models](https://platform.openai.com/docs/models/gpt-3-5-turbo)，max token应该是16,385 tokens吧。

**Comment by binary-husky** [comment]
> > 请验证这个 PR 是否有效
> > #1594
> > 根据 [OpenAI Models](https://platform.openai.com/docs/models/gpt-3-5-turbo)，max token应该是16,385 tokens吧。

是的，我再修改一下

**Comment by binary-husky** [comment]
PR修改到https://github.com/binary-husky/gpt_academic/pull/1598
把max token 修改了
