### ISSUE TITLE
[Feature]: 支持月之暗面的 api

### ISSUE THREAD

**Issue by ohjunk2001** [binary-husky/gpt_academic#1593]
### Class | 类型

大语言模型

### Feature Request | 功能请求

月之暗面的 api 后续会不会考虑支持？

**Comment by binary-husky** [comment]
已经在弄了

**Comment by Kilig947** [comment]
https://github.com/binary-husky/gpt_academic/pull/1597

done

**Comment by somehotnail** [comment]
填写了月之暗面的api之后，如何切换模型呢？

**Comment by Kilig947** [comment]
> 填写了月之暗面的api之后，如何切换模型呢？

择任意模型填入AVAIL_LLM_MODELS
 
"moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"

![image](https://github.com/binary-husky/gpt_academic/assets/46100050/315c3d83-9e48-4ed4-b347-2ff15a4021f1)

**Comment by Kilig947** [comment]
> > 填写了月之暗面的api之后，如何切换模型呢？
> 
> 择任意模型填入AVAIL_LLM_MODELS
> 
> "moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"
> 
> ![image](https://private-user-images.githubusercontent.com/46100050/309967927-315c3d83-9e48-4ed4-b347-2ff15a4021f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDgwNTMsIm5iZiI6MTcwOTYwNzc1MywicGF0aCI6Ii80NjEwMDA1MC8zMDk5Njc5MjctMzE1YzNkODMtOWU0OC00ZWQ0LWIzNDctMmZmMTVhNDAyMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDAzMDIzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZjM2YzFhYjk3OGM5MGMwZTAyYmI3ODAyYzI2OGY3ZWQ3MzU0ODBkMTRkZjQwMGIzYzBjNjE1OTdiNmIxOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZymqzWJIJtHTvVrsZAU3Epd1n-d1gSEfM6jpnHRnnZY)

忘记在config.py 增加可用模型了，已pr https://github.com/binary-husky/gpt_academic/pull/1603

**Comment by somehotnail** [comment]
感谢

**Comment by binary-husky** [comment]
done
