### ISSUE TITLE
有微信吗 我弄不好[Bug]: 

### ISSUE THREAD

**Issue by Hrendeo** [binary-husky/gpt_academic#1595]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

有微信吗 我弄不好

### Screen Shot | 有帮助的截图

有微信吗 我弄不好

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

有微信吗 我弄不好

**Comment by binary-husky** [comment]
readme主页有群

**Comment by Hrendeo** [comment]
没啊  没看到微信呀  我微信是z1793130902
