### ISSUE TITLE
[Feature]:可否批量添加自定义兼容openai api 的自定义模型名称？

### ISSUE THREAD

**Issue by zhanghxiao** [binary-husky/gpt_academic#1601]
### Class | 类型

大语言模型

### Feature Request | 功能请求

可否批量添加自定义兼容openai api 的自定义模型名称？只在原基础上添加openai的模型，代理地址与自定义apikey依旧不变，如果可以请问应该在哪修改？

**Comment by binary-husky** [comment]
[第三方API‐KEY接入指南](https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)

**Comment by binary-husky** [comment]
[适配RWKV Runner](https://github.com/binary-husky/gpt_academic/wiki/%E9%80%82%E9%85%8DRWKV-Runner)
