### ISSUE TITLE
vercel部署

### ISSUE THREAD

**Issue by GH-wudi** [binary-husky/gpt_academic#161]
可否增加vercel部署选项，这样就可以在不用挂代理的情况下进行访问？

**Comment by binary-husky** [comment]
抱歉我不太懂vercel是什么，能解释下吗

**Comment by nxtjdc** [comment]
> 抱歉我不太懂vercel是什么，能解释下吗

也求一个vercel部署，具体可以参开这个：
https://github.com/Yidadaa/ChatGPT-Next-Web

**Comment by GH-wudi** [comment]
> 抱歉我不太懂vercel是什么，能解释下吗

他是一个托管平台，应该可以理解为一个服务器，一般用来部署前端，但也支持原生Python或者flask服务，最主要的是免费，可在国内合法访问。另外非常喜欢此项目，希望可以做点贡献。

**Comment by binary-husky** [comment]
> > 抱歉我不太懂vercel是什么，能解释下吗
> 
> 他是一个托管平台，应该可以理解为一个服务器，一般用来部署前端，但也支持原生Python或者flask服务，最主要的是免费，可在国内合法访问。另外非常喜欢此项目，希望可以做点贡献。

非常感谢，好像值得一试。
不过作为一个刚给腾讯云冲过钱的vps用户，我有点稍微疑惑，它免费的话岂不是会亏钱吗，毕竟一个简单的vps一个月都需要几十块钱呢。

**Comment by mrhblfx** [comment]
同求, netlify和vercel两个类似, 都有免费的服务

**Comment by binary-husky** [comment]
最近尝试了很多次，很遗憾，vercel的容量太小，都无法放得下gradio依赖

**Comment by GH-wudi** [comment]
> 最近尝试了很多次，很遗憾，vercel的容量太小，都无法放得下gradio依赖

非常感谢您的努力，Hugging Face上部署也非常方便滴
