### ISSUE TITLE
[Feature]: 你好，可以向gpts一样，prompt不展示出来吗？

### ISSUE THREAD

**Issue by 1165715111** [binary-husky/gpt_academic#1610]
### Class | 类型

None

**Comment by binary-husky** [comment]
可以，改这行

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/b3c6f909-385d-46cb-b39b-1cbdff2b3752)

**Comment by 1165715111** [comment]
好的，谢谢

**Comment by 1165715111** [comment]
大佬，不行，不加上Prefix、Suffix，按钮就没有效果了
