### ISSUE TITLE
[Bug]: Arxiv论文精细翻译(输入ArxivID)，这个功能无法翻译最新的Arxiv论文，无法得到结果PDF。

### ISSUE THREAD

**Issue by alleniver** [binary-husky/gpt_academic#1614]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

https://arxiv.org/abs/2403.03206
这篇文章我通过Arxiv的编号翻译好像最后打包成PDF的时候无法打包。麻烦查看一下是什么问题？
(翻译后的压缩包太大传不上来)，麻烦你们使用"Arxiv论文精细翻译(输入ArxivID)"这个功能尝试一下谢谢。

### Screen Shot | 有帮助的截图

<img width="383" alt="0ac49949d4b6f681304a9493a4e4316" src="https://github.com/binary-husky/gpt_academic/assets/6006650/bd0adbc9-da58-4733-805a-a7790a141d9c">

<img width="392" alt="83e282ec5e7cd51001e34038dd3baed" src="https://github.com/binary-husky/gpt_academic/assets/6006650/95669317-fa70-4a26-a2f1-0196a529c1e9">

**Comment by HIT-ZY** [comment]
其实不是字体的原因，我有仔细研究过这块，其实就是生成的tex文件有问题，不符合tex语法，可以在tex修改后自己手动编译，然后接着编译即可

**Comment by macqueen09** [comment]
> 其实不是字体的原因，我有仔细研究过这块，其实就是生成的tex文件有问题，不符合tex语法，可以在tex修改后自己手动编译，然后接着编译即可

@HIT-ZY  那怎么定位到是哪个tex文件，呀，  latex小白，一来不知道如何定位，删改后  通过什么工具再手动编译下呢？
Thanks

**Comment by macqueen09** [comment]
https://web.ugreen.cloud/web/#/share/51fa24f909cb4194840786eb59333354 提取码：VNT6
是zip包

同样问题， 是一篇比较新的 https://arxiv.org/abs/2401.06209  的论文   Eyes Wide Shut? Exploring the Visual Shortcomings of Multimodal LLMs

**Comment by macqueen09** [comment]
问题解决了。 看了log里提到字体问题


Package: MULEenc 2021/10/16 4.8.5
) (C:\Program Files\MiKTeX\tex/latex/cjk\CJK.enc
File: CJK.enc 2021/10/16 4.8.5
Now handling font encoding C00 ...
... no UTF-8 mapping file for font encoding C00


问了chatGPT 说是 MiKtex的字体需要更新，打开软件  点击更新，更新所有后，再试试就好了

**Comment by FHL000** [comment]
> https://web.ugreen.cloud/web/#/share/51fa24f909cb4194840786eb59333354 提取码：VNT6 是zip包
> 
> 同样问题， 是一篇比较新的 https://arxiv.org/abs/2401.06209 的论文 Eyes Wide Shut? Exploring the Visual Shortcomings of Multimodal LLMs

分享过期了，能重新分享一下吗谢谢！

**Comment by FHL000** [comment]
@macqueen09
