### ISSUE TITLE
[Bug]: 腾讯云服务器上用`docker-compose up`的方式部署无法配置代理

### ISSUE THREAD

**Issue by hjnnjh** [binary-husky/gpt_academic#1622]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

我修改了`docker-compose up`中与代理有关的配置，设置了`{"http": "http://127.0.0.1:7890", "https": "http://127.0.0.1:7890"}`，走的是clash的7890端口，clash配置的systemd服务，是正常的，但是用不了需要代理才能访问的接口。在Mac上都不用配置代理就能访问宿主机的网络，linux上不知道咋回事，在`docker-compose .yml`中配置7890端口转发以及通过`config.json`文件为container添加代理这些方法我都试过了，都没用，不想折腾了（为了这事今晚代码都没写成），看看有没有跟我遇到相同问题并解决的人，舅舅！报错截图如下。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/37699150/a2bef111-e688-412b-b241-74805ccee887)

**Comment by hjnnjh** [comment]
突然想起我还有azure的额度，实在解决不了就转战azure了 :(

**Comment by hjnnjh** [comment]
主要是claude 3用不了，我检查了报错的代码，好像是anthropic的api没给proxy参数？

**Comment by binary-yuki** [comment]
Error code: 403 就是有相应 -应该和 APIKEY 有关系而不是代理 403 - permission_error: Your API key does not have permission to use the specified resource. 能否检查一下你的 APIKEY 是否有误

**Comment by hjnnjh** [comment]
> Error code: 403 就是有响应 -应该和 APIKEY 有关系而不是代理 403 - permission_error: Your API key does not have permission to use the specified resource. 能否检查一下你的 APIKEY 是否有误

我检查看看，可能是API写错了

**Comment by hjnnjh** [comment]
> Error code: 403 就是有响应 -应该和 APIKEY 有关系而不是代理 403 - permission_error: Your API key does not have permission to use the specified resource. 能否检查一下你的 APIKEY 是否有误

我知道了，API没写错，我需要改一下clash的节点，分流规则写的有问题
