### ISSUE TITLE
[Bug]: Cannot open document for: /v1/chat/completions

### ISSUE THREAD

**Issue by ATentropy** [binary-husky/gpt_academic#1629]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

key使用了项目[copilot-gpt4-service](https://github.com/aaamoon/copilot-gpt4-service) 
修改了config_private.py中的重定向（图1）
成功运行main.py，输入后返回异常（图2）
重定向url中，localhost换成127.0.0.1也不行
尝试了隔壁[Nextchat](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web)，完美运行（图3），所以key应该没问题

### Screen Shot | 有帮助的截图

![屏幕截图 2024-03-14 210207](https://github.com/binary-husky/gpt_academic/assets/56159205/1a236e2f-6d0b-422b-89ed-5bb65197e1b1)
![image](https://github.com/binary-husky/gpt_academic/assets/56159205/06be414d-d8b5-4c34-9d38-e618698a3bc7)
![image](https://github.com/binary-husky/gpt_academic/assets/56159205/e21184f3-4e26-4792-8d73-c309dda92dca)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

![image](https://github.com/binary-husky/gpt_academic/assets/56159205/9c8fdb6e-728d-486b-b6dd-032554a77a5d)

**Comment by binary-husky** [comment]
我无法复现这个问题，接入coplilot没出现任何问题……

```
API_KEY = 'sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
LLM_MODEL = "gpt-4"
API_URL_REDIRECT = {
    "https://api.openai.com/v1/chat/completions": "http://127.0.0.1:8080/v1/chat/completions"
}
```

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/wiki/%E6%8E%A5%E5%85%A5copilot%E2%80%90gpt4%E2%80%90service

**Comment by ATentropy** [comment]
知道为什么了，8080端口被占的原因，已解决。但不知道为什么隔壁没问题：）
