### ISSUE TITLE
[Bug]: 非OpenAI官方接口返回了错误

### ISSUE THREAD

**Issue by My-Rabbit** [binary-husky/gpt_academic#1630]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

非OpenAI官方接口返回了错误:{“error”:{“message”:" (request id: 2024031413125765546472283356075)",“type”:“upstream_error”,“param”:“500”,“code”:“bad_response_status_code”}}

### Screen Shot | 有帮助的截图

![屏幕截图 2024-03-14 212222](https://github.com/binary-husky/gpt_academic/assets/56757074/5bc03192-6f12-4d83-b08b-650e7aee0458)

**Comment by My-Rabbit** [comment]
在海外使用时报错

**Comment by binary-yuki** [comment]
oneapi报错 你用的是第三方 api？ 请联系 api 提供商 非项目错误

**Comment by binary-husky** [comment]
对，这个与项目无关

**Comment by Ryan-Lou** [comment]
![1b26b7fcc856b2cdb21f962d61e80cd](https://github.com/binary-husky/gpt_academic/assets/54530803/8953aee3-745c-40ff-9b81-fc2c84c31379)
这个也和项目无关吗

**Comment by binary-yuki** [comment]
@Ryan-Lou 建议检查一下配置的redirect_url(如果用的是第三方)

**Comment by My-Rabbit** [comment]
谢谢！
