### ISSUE TITLE
cladue3是否能够同样支持自定义api

### ISSUE THREAD

**Issue by bioone** [binary-husky/gpt_academic#1634]
### Class | 类型

大语言模型

**Comment by wl223600** [comment]
Claude系列实测已经支持自定义API。
原api地址为```https://api.anthropic.com```，根据类似OpenAI API的替换方法在配置文件中写入对Claude API的自定义配置即可。Claude 3 Opus高峰期可能会触发限制，sonnet还好。
倒是目前moonshot似乎还没发现自定义API的支持。可能是写新功能的时候还没注意到这点，可以理解。

**Comment by binary-husky** [comment]
现在可以啦，修改 API_URL_REDIRECT 即可
API_URL_ = {
"https://api.anthropic.com": "https://xxx.yyy.zzz.com"
}

**Comment by binary-husky** [comment]
> Claude系列实测已经支持自定义API。 原api地址为`https://api.anthropic.com`，根据类似OpenAI API的替换方法在配置文件中写入对Claude API的自定义配置即可。Claude 3 Opus高峰期可能会触发限制，sonnet还好。 倒是目前moonshot似乎还没发现自定义API的支持。可能是写新功能的时候还没注意到这点，可以理解。

在PR https://github.com/binary-husky/gpt_academic/pull/1641 中，Claude API从"https://api.anthropic.com"变成"https://api.anthropic.com/v1/messages"
