### ISSUE TITLE
[Bug]: Linux云服务器上使用docker部署无法使用claude 3

### ISSUE THREAD

**Issue by hjnnjh** [binary-husky/gpt_academic#1636]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

1. 主要的报错信息为`gpt-academic-gpt_academic_nolocalllms-1 | anthropic.PermissionDeniedError: Error code: 403 - {'error': {'type': 'forbidden', 'message': 'Request not allowed'}}`；
2. 服务器是腾讯云轻量应用服务器，系统是 `Ubuntu 20.04`，有公网IP，配置了`Clash`并且正常，容器网络是`host`模式，在容器内部`curl -I https://api.anthropic.com`正常，同时`Clash Log`有记录（见下图），但通过公网IP:Port访问本项目的WebUI然后提交就会报错，同时我注意到这个过程`Clash Log`并没有记录，然而在我自己的MacBook上，一切正常，API KEY确定没有错误，因为跟我在MacBook上用的一个API KEY，代理也是一个，流量转发规则一样；
3. 目前我尝试了以下解决方案：
   - 在`docker-compose.yml`文件中添加`proxies`相关配置——无效；
   - 配置`iptables`的`nat`，让通过公网IP端口的请求转发到`127.0.0.1`——无效；

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/37699150/072bdcc4-42fc-418d-90dd-0dfc9d0dbf1e)

**Comment by Menghuan1918** [comment]
现在应该没问题了吧..?

**Comment by hjnnjh** [comment]
> 现在应该没问题了吧..?

还没试，我的Claude api没钱了。。。

**Comment by hjnnjh** [comment]
> 现在应该没问题了吧..?

没问题了，刚刚试了下。

**Comment by endNone** [comment]
怀疑是api问题
