### ISSUE TITLE
[Bug]: 使用grobid+智谱大模型时会报错

### ISSUE THREAD

**Issue by NeverOccurs** [binary-husky/gpt_academic#1640]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述
使用grobid切分后调用glm翻译PDF文档时会报错。
zhipuai.core._errors.APIRequestFailedError: Error code: 400, with error text {"error":{"code":"1214","message":"messages[4]:content和tool_calls 字段不能同时为空"}}

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/96693590/72233f55-9598-4a1c-9cc1-86ae17f6bd4f)

**Comment by binary-husky** [comment]
修复https://github.com/binary-husky/gpt_academic/commit/67ad04137206ba202ea537644826ec60dcc11451
