### ISSUE TITLE
[Bug]: Docker 部署无法访问

### ISSUE THREAD

**Issue by Lufffya** [binary-husky/gpt_academic#1644]
### Installation Method | 安装方法与平台

Docker-Compose（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

![image](https://github.com/binary-husky/gpt_academic/assets/49063302/924b7438-907b-492b-b629-063d8df169e4)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/49063302/1e357f71-789b-46e1-b31b-549164c2cdfb)

使用以上脚本运行后，通过 http://localhost:22304 访问不了（本地环境有全局的科学上网，但不代理局域网）

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/bb1e0eb2-133b-43a5-9355-25a54bbbc419)

**Comment by binary-husky** [comment]
换一种端口映射方式
