### ISSUE TITLE
[Bug]: 为什么模型选择GPT-4，问它还是回复是GPT-3呢？

### ISSUE THREAD

**Issue by ldddddddl** [binary-husky/gpt_academic#1649]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

config和网页端都是选择gpt4，但是一问还是3，这是什么原因？我在platform.openai.com后台创建的api给了所有的权限，还是这样子。

### Screen Shot | 有帮助的截图

![图片1](https://github.com/binary-husky/gpt_academic/assets/49769934/842644bc-1f20-45e8-96b8-0e9a11ad8176)

**Comment by qifeng2233** [comment]
gpt4沿用的gpt3的数据训练的，所以在gpt4的知识库里认为自己是gpt3.5
