### ISSUE TITLE
[Bug]: 询问多个GPT模型时出现报错

### ISSUE THREAD

**Issue by Nextstrain9000** [binary-husky/gpt_academic#1660]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

询问多个GPT模型时出现以下报错

`Traceback (most recent call last):
  File "./crazy_functions/crazy_utils.py", line 84, in _req_gpt
    result = predict_no_ui_long_connection(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./request_llms/bridge_all.py", line 874, in predict_no_ui_long_connection
    return_string_collect.append( f"【{str(models[i])} 说】: <font color=\"{colors[i]}\"> {future.result()} </font>" )
                                                                            ~~~~~~^^^
IndexError: list index out of range`

### Screen Shot | 有帮助的截图

<img width="635" alt="搜狗截图20240328112910" src="https://github.com/binary-husky/gpt_academic/assets/140483081/37c2fd60-7bb3-4c0c-901c-5b3d3fda568a">
<img width="527" alt="搜狗截图20240328113116" src="https://github.com/binary-husky/gpt_academic/assets/140483081/bd073520-ac53-4539-b419-570097560e85">


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

我的docker compose文件

[docker-compose.zip](https://github.com/binary-husky/gpt_academic/files/14783622/docker-compose.zip)

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/216d4374e7ce9eb84a6a33c24c8b826b69785478

**Comment by binary-husky** [comment]
已经修复，请试试看？

**Comment by Nextstrain9000** [comment]
感谢！
