### ISSUE TITLE
[Bug]: 无法安装环境

### ISSUE THREAD

**Issue by JoHnNy3799** [binary-husky/gpt_academic#1664]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

两周前仍可正常运行，网络代理配置等也没有发生改变，现在再次运行时出现如图情况，更换代理和安装方式后仍无法解决问题

### Screen Shot | 有帮助的截图

![{E851428F-1182-48bd-ABEB-EDD1752644E1}](https://github.com/binary-husky/gpt_academic/assets/150353918/62ce161c-0c63-49f4-bc03-197ed4bb9984)

**Comment by chaoyu1999** [comment]
我也一样

**Comment by RezaFeng** [comment]
一样，gradio的链接貌似挂了

**Comment by RezaFeng** [comment]
把requirement.txt中的第一行gradio链接改为https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.7-py3-none-any.whl，然后重新安装运行就可以了

**Comment by DUnionCY** [comment]
> 把requirement.txt中的第一行gradio链接改为[https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.7-py3-none-any .whl，然后重新安装运行就可以了](https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.7-py3-none-any.whl%EF%BC%8C%E7%84%B6%E5%90%8E%E9%87%8D%E6%96%B0%E5%AE%89%E8%A3%85%E8%BF%90%E8%A1%8C%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86)

感谢已解决

**Comment by DUnionCY** [comment]
\gpt_academic下的requirement.txt中的
https://public.agent-matrix.com/publish/gradio-3.32.8-py3-none-any.whl
替换为
https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.7-py3-none-any.whl

**Comment by DUnionCY** [comment]
\gpt_academic下的requirement.txt中的
https://public.agent-matrix.com/publish/gradio-3.32.8-py3-none-any.whl
替换为
https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.8-py3-none-any.whl

**Comment by JoHnNy3799** [comment]
> \gpt_academic下的requirement.txt中的 https://public.agent-matrix.com/publish/gradio-3.32.8-py3-none-any.whl 替换为 https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.8-py3-none-any.whl

已解决，感谢
