### ISSUE TITLE
requirement中的gradio链接无法访问了

### ISSUE THREAD

**Issue by RezaFeng** [binary-husky/gpt_academic#1666]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

requirement中的gradio链接无法访问了，不管是开代理还是不开代理，https://public.agent-matrix.com/publish/gradio-3.32.8-py3-none-any.whl。
会提示
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='public.agent-matrix.com', port=443): Max retries exceeded with url: /publish/gradio-3.32.8-py3-none-any.whl (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)')))

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/18794642/da067aa0-22c9-46bc-ba76-6da9d943c812)

**Comment by mengcius** [comment]
Same

**Comment by JusticeGL** [comment]
same issue, can't access

**Comment by DUnionCY** [comment]
\gpt_academic下的requirement.txt中的
https://public.agent-matrix.com/publish/gradio-3.32.8-py3-none-any.whl
替换为
https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.7-py3-none-any.whl

**Comment by DUnionCY** [comment]
\gpt_academic下的requirement.txt中的
https://public.agent-matrix.com/publish/gradio-3.32.8-py3-none-any.whl
替换为
https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.8-py3-none-any.whl

**Comment by CereSae** [comment]
> \gpt_academic下的requirement.txt中的 https://public.agent-matrix.com/publish/gradio-3.32.8-py3-none-any.whl 替换为 https://fastly.jsdelivr.net/gh/binary-husky/gradio-fix@gpt-academic/release/gradio-3.32.8-py3-none-any.whl

success, Tx

**Comment by binary-husky** [comment]
刚才服务器嘎了，现在已经恢复
