### ISSUE TITLE
[Bug]: 显示选择的模型是GPT-4，实际运行的是GPT-3

### ISSUE THREAD

**Issue by Evanhooyee** [binary-husky/gpt_academic#1669]
### Installation Method | 安装方法与平台

Docker（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

模型选择是gpt-4，但实际运行的是gpt-3

### Screen Shot | 有帮助的截图

![1711957668316](https://github.com/binary-husky/gpt_academic/assets/55730879/cd899c6e-27b9-49d5-92f7-a815ddc3afd2)

**Comment by adrianzzk** [comment]
我记得好像有人说过，gpt4是在3的基础上训练的，所以他自我认知还是3

**Comment by whzlatan** [comment]
如果是购买的中转的api,可能被卖家坑了

**Comment by Evanhooyee** [comment]
> 我记得好像有人说过，gpt4是在3的基础上训练的，所以他自我认知还是3

同样的问题我也问了网页的GPT-4，它的回答就是GPT-4

**Comment by Evanhooyee** [comment]
> 如果是购买的中转的api,可能被卖家坑了

没有中转，我自己的账号生成的api

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/67e53817-7630-4c18-9cf4-d265212cb682)
