### ISSUE TITLE
设置密码后遇到Connection errored out

### ISSUE THREAD

**Issue by ikashana** [binary-husky/gpt_academic#167]
不设密码正常使用，设置密码后gradio.live域名是正常可以登录可以正常使用的，但是用路由器用Socat做端口转发使用公网域名端口访问变成了能登陆，但是功能均Connection errored out...请教如何解决这个。

**Comment by binary-husky** [comment]
和websocket有关

**Comment by ikashana** [comment]
> 和websocket相关

稍微折腾了一下还是不是太会配置socat的websocket_(:з)∠)_
