### ISSUE TITLE
[Bug]: OpenAI以账户额度不足为由，拒绝服务

### ISSUE THREAD

**Issue by Zhuo-ruishuang** [binary-husky/gpt_academic#1670]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

第一次安装中科院学术优化chatGPT，结果显示OpenAI以账户额度不足为由，拒绝服务，怎么解决啊~~~是不是多加几个API啊

### Screen Shot | 有帮助的截图

![捕获](https://github.com/binary-husky/gpt_academic/assets/59915470/9f22f8ae-588e-4852-810a-da287018d301)

**Comment by wangxiancao** [comment]
字面意思，免费额度现在不能用api，要加钱
