### ISSUE TITLE
![捕获](https://github.com/binary-husky/gpt_academic/assets/76040541/3d060e72-6f3e-4f7f-b6b3-c167c04e4fff)

### ISSUE THREAD

**Issue by yilangcheng** [binary-husky/gpt_academic#1674]
![捕获](https://github.com/binary-husky/gpt_academic/assets/76040541/3d060e72-6f3e-4f7f-b6b3-c167c04e4fff)
大佬们，求教啊！我这里提示API秘钥的问题，然后我到openAI官网生成一个API秘钥，然后最后运行时又提示说账户额度不足，怎么回事啊？

_Originally posted by @xiaoshazhu2001 in https://github.com/binary-husky/gpt_academic/issues/1#issuecomment-1879832370_

**Comment by binary-husky** [comment]
问题与项目无关，找openai呀
