### ISSUE TITLE
[Feature]: 允许用户在配置文件中指定默认Top-p和Temperture

### ISSUE THREAD

**Issue by wl223600** [binary-husky/gpt_academic#1676]
### Class | 类型

大语言模型

### Feature Request | 功能请求

Hello,
```Top-p```和```Temperture```可能会影响模型在部分任务下的性能。目前这两个参数可以通过UI指定（默认值为1）。
是否有计划在日后允许用户在```config.py```内预先指定这两个参数的默认值呢（但同时仍允许在UI内调整当前窗口的```Top-p```和```Temperture```数值）？
Reference
[GPT-4 API相应示例](https://community.openai.com/t/cheat-sheet-mastering-temperature-and-top-p-in-chatgpt-api/172683)

**Comment by binary-husky** [comment]
您好，现在temperature支持保存在浏览器cookie中（frontier分支），之后会把该功能合并到主分支
