### ISSUE TITLE
[Feature]: #1675 求助

### ISSUE THREAD

**Issue by lizkefan** [binary-husky/gpt_academic#1677]
### Class | 类型

None

### Feature Request | 功能请求
#1675 
感谢您的指点。按照您的指点，可以使用，但这样操作是直接把所有模型（3.5     4.0     claude）的api_url都替换了。

我 **仅需要替换一部分**。我尝试修改了bridge_all.py >  one-api model信息更新里的endpoint。但是通过网页输入的api 提示 “您提供的api-key不满足要求，不包含任何可用于one-api-claude-3-opus-20240229的api-key。您可能选择了错误的模型或请求源。”

我的用途：3.5用的是官方的。现在想询问：通过one-api接入第三方的api，如何仅修改通过one-api接入第三方api的配置，使其正常使用呢？

**Comment by binary-husky** [comment]
很抱歉，目前不能同时支持openai官方和one-api的中转，因为二者用的配置项是重叠的。

如果你使用官方openai + 官方claude，
或者用第三方openai + 第三方claude都是没问题的，
用第三方openai + 官方claude也是没问题的

在所有4种情况中，唯独你这1种情况，很难弄。
建议先本地部署一个one-api吧，大模型路由这方面，one-api是比较专业的
