### ISSUE TITLE
bridge_chatgpt.py", line 255, in predict     raise ValueError(f'无法读取以下数据，请检查配置。\n\n{chunk_decoded}')[Bug]: 

### ISSUE THREAD

**Issue by pizhongpi** [binary-husky/gpt_academic#1689]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

![提问1](https://github.com/binary-husky/gpt_academic/assets/99616529/f4e86e0b-80b2-4ec7-9197-04367f08a512)
使用的是中转api，在配置时修改了上述两处，第三方api及中转api的路由请求接口

### Screen Shot | 有帮助的截图
报错如下图所示：bridge_chatgpt.py”，第 255 行，预测中 raise ValueError(f'无法读取以下数据，请检查配置。\n\n{chunk_decoded}')

![提问](https://github.com/binary-husky/gpt_academic/assets/99616529/fae268d0-2536-4c7e-a16a-ebbf34dfc814)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

https://api.quzhi.life/，中转api地址

**Comment by binaryYuki** [comment]
这个 just a moment看起来是中转服务商开了 cloudflare 五秒盾  
建议联系商家合适情况 
目前看来不是 bug  谢谢

**Comment by binary-husky** [comment]
> cloudflare

认同，所以我先close下这个issue
