### ISSUE TITLE
[Bug]:  docker安装方案1配置好后，打开浏览器显示localhost拒绝连接

### ISSUE THREAD

**Issue by ccdontworry** [binary-husky/gpt_academic#1704]
### Installation Method | 安装方法与平台

Docker-Compose（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

docker-compose up安装的，然后所有都显示没问题  就是打开浏览器显示localhost拒绝连接

### Screen Shot | 有帮助的截图

![af297943e4d2983a1661221445b94ec8](https://github.com/binary-husky/gpt_academic/assets/88469872/0fb976c8-c3b7-4ab8-913e-dab4032be6d7)
![{0DCA988C-2864-4368-AB46-41828B46B499}](https://github.com/binary-husky/gpt_academic/assets/88469872/7ac05615-8ae1-4336-8ce1-a625b90cfc34)

**Comment by Menghuan1918** [comment]
在前面手动加`http://`?edge有时候会自动改成https
或者把localhost改成127.0.0.1试试，比如这儿改成
`http://127.0.0.1:22303`

**Comment by ccdontworry** [comment]
非常感谢您的回复！不过这两个方法还是不能解决，因此就本地配置了，现在可以使用了。再次感谢！！！



在 2024-04-13 10:09:31，"Menghuan1918" ***@***.***> 写道：

在前面手动加http://?edge有时候会自动改成https
或者把localhost改成127.0.0.1试试，比如这儿改成
http://127.0.0.1:22303

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/fd6e68f3-8027-49e9-b4ba-b0d580a0da3f)

**Comment by binary-husky** [comment]
其实答案就在docker-compose.yml里，如上图

 ^_^

**Comment by ccdontworry** [comment]
我明白了，感谢您的解答！！！我在Windows docker中配置了它，怪不得不行。



在 2024-04-14 22:16:34，"binary-husky" ***@***.***> 写道：

其实答案就在docker-compose.yml里，如上图

^_^
