### ISSUE TITLE
[Feature]: 完善 OpenAI vision 相关接口，并将 gpt-4-turbo 从临时方案切换过去

### ISSUE THREAD

**Issue by awwaawwa** [binary-husky/gpt_academic#1707]
### Class | 类型

大语言模型

### Feature Request | 功能请求

根据 https://github.com/binary-husky/gpt_academic/pull/1698#issuecomment-2049372497 ，当前 OpenAI vision 模型相关接口实现存在以下几点问题：
1. predict_no_ui_long_connection 暂未实现（或许没有必要？暂时应该是没有插件需要用vision能力吧）
2. predict 强制要求上传图片
3. predict 仅支持单轮对话

有必要完善相关接口并将 gpt-4-turbo 从临时方案切换过去。

**Comment by awwaawwa** [comment]
4o也出来了，本 issue 是否应扩展为：完善 OpenAI 多模态相关接口，并预留 audio 相关接口？

**Comment by tzcskys** [comment]
+1，“GPT-4o is 50% cheaper than GPT-4 Turbo”，“It has better vision capabilities and improved support for non-English languages ”，没有audio等其他接口可以后续慢慢考虑，但API价格降低50%以及更好的非英语（如中文）的支持会带来很大的提升。

**Comment by awwaawwa** [comment]
目前 gpt-4o 的支持已在 #1760 合入主线

**Comment by XiaolongYang-HZAU** [comment]
目前gpt-4o和turbo还不支持识图是吗

**Comment by JinchaoLove** [comment]
同问

> 目前gpt-4o和turbo还不支持识图是吗

**Comment by awwaawwa** [comment]
应该在 https://github.com/binary-husky/gpt_academic/commit/7de6015800d2d4de5f626dd3a278356db3292779 提交之后 gpt-4o 就支持识图了，代码详见: https://github.com/binary-husky/gpt_academic/blob/16f4fd636ecc42788e30f312b342e490014316f8/request_llms/bridge_chatgpt.py#L227C1-L236C49 和 https://github.com/binary-husky/gpt_academic/blob/16f4fd636ecc42788e30f312b342e490014316f8/request_llms/bridge_all.py#L198C1-L198C41  。

测试效果如下图所示：
![CleanShot 2024-08-22 at 17 00 50@2x](https://github.com/user-attachments/assets/822a6fc2-6f11-4ae7-83dc-f601b9a74bac)

**Comment by JinchaoLove** [comment]
非常感谢~

用Azure的朋友可以在bridge_all.py里面新加一个自定义的模型，比如：

```python

    "azure-gpt-4o":{
        "fn_with_ui": chatgpt_ui,
        "fn_without_ui": chatgpt_noui,
        "has_multimodal_capacity": True,
        "endpoint": azure_endpoint,
        "max_token": 8192,
        "tokenizer": tokenizer_gpt4,
        "token_cnt": get_token_num_gpt4,
    },
```
