### ISSUE TITLE
[Bug]: 依赖库 `pydantic` 的版本问题：cannot import name 'Undefined' from 'pydantic.fields'

### ISSUE THREAD

**Issue by RonghaiHe** [binary-husky/gpt_academic#1710]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

运行
```shell
python main.py
```
出现如题目所示的报错，详见下方。查阅网上信息，像[issues](https://github.com/vladmandic/automatic/issues/1670#issuecomment-1952307496)说用回版本 `1.10.11`。我查了下，是在 `gpt-academic 3.72` 版本的时候将 `pydantic` 的版本修改为 `2.5.2`

我改成 `pydantic==1.10.11` 与 `zhipuai` 有冲突；改成 `pydantic==2.7.0` (最新版) ，报同样的错

### Screen Shot | 有帮助的截图

-

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

E:\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
Traceback (most recent call last):
  File "main.py", line 371, in <module>
    main()
  File "main.py", line 28, in main
    import gradio as gr
  File "E:\anaconda3\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\anaconda3\lib\site-packages\gradio\components.py", line 32, in <module>
    from fastapi import UploadFile
  File "E:\anaconda3\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "E:\anaconda3\lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "E:\anaconda3\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "E:\anaconda3\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (E:\anaconda3\lib\site-packages\pydantic\fields.py)

**Comment by binaryYuki** [comment]
Hi，

我尝试在我的电脑上复现这个issue 但是很遗憾没有成功
在**我的环境**中：

```
(gpt_academic-)  ~/gpt_academic/ [master] pip freeze | grep pandas       
pandas==2.2.2
(gpt_academic-)  ~/gpt_academic/ [master] pip freeze | grep pydantic
pydantic==2.5.2
pydantic_core==2.14.5
```

据此推定您的issue 应该是因为 conda 内的包有版本冲突/旧版本

请您尝试以下方法：
方案 1 重建环境
- 重新建立一个 conda 环境  `conda create -n your_env_name python=x.x`
- 启用环境 `conda activate your_env_name`
- 安装包  `conda install --yes --file requirements.txt`

方案 2 尝试重建
- `conda install --force-reinstall --file requirements.txt`

**Comment by RonghaiHe** [comment]
我用的是 `python3.8` 的版本，可能和这个有关。我用 `python3.11` 就没有问题，我关闭这个提问了。

**Comment by Zero01-YP** [comment]
pydantic==1.10.15

**Comment by lazyfuzzyguy** [comment]
gradio version updata to latest to solve this issue
