### ISSUE TITLE
[Bug]: 在配置Azure的GPT4-1106-preview过程中遇到了[Local Message] 异常

### ISSUE THREAD

**Issue by Su2hengY** [binary-husky/gpt_academic#1715]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

纯小白，不知道问题出现在哪里，只能提供几张截图给大佬帮忙看看问题。

### Screen Shot | 有帮助的截图

<img width="305" alt="1713355891113" src="https://github.com/binary-husky/gpt_academic/assets/162291186/eacf2487-c64e-47a2-a6ce-97ebc39e0df4">
<img width="687" alt="1713356062138" src="https://github.com/binary-husky/gpt_academic/assets/162291186/ec56b8e4-c9e4-4279-afdd-cd799ca2a015">
<img width="726" alt="1713356186306" src="https://github.com/binary-husky/gpt_academic/assets/162291186/30e81541-f2fc-44fd-bacb-bd2bc37026b0">

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File ".\request_llms\bridge_chatgpt.py", line 227, in predict
    chunk = next(stream_response)
StopIteration

**Comment by binary-husky** [comment]
显示access token没有，请前往wiki查阅一下azure的配置说明
