### ISSUE TITLE
[Feature]: Translate UI in English

### ISSUE THREAD

**Issue by arsaboo** [binary-husky/gpt_academic#1722]
### Class | 类型

None

### Feature Request | 功能请求

I see the `translate_english.json` but I am not sure if it can be used to translate the UI to English. Any advice?

**Comment by awwaawwa** [comment]
You can try to refer to the header comments of this file: https://github.com/binary-husky/gpt_academic/blob/master/multi_language.py

**Comment by oanhcuongdo** [comment]
H i try it but now work: multi_language.py", line 352, in step_1_core_key_translate
    chinese_core_keys_norepeat_mapping.update({k:cached_translation[k]})
                                                 ~~~~~~~~~~~~~~~~~~^^^
KeyError: '注释Python项目'
