### ISSUE TITLE
[Bug]: 您的 API_KEY 不满足任何一种已知的密钥格式，请在config文件中修改API密钥之后再运行。

### ISSUE THREAD

**Issue by chjj159159** [binary-husky/gpt_academic#1723]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

![屏幕截图 2024-04-19 144904](https://github.com/binary-husky/gpt_academic/assets/167509134/f62b08a1-b623-4141-9687-dc2b781f434b)

### Screen Shot | 有帮助的截图

我用的自己的openai创建的api
API_KEY = "sk-proj-TUqe9R0DGi1PMRgLffujT3BlbkFJJ2gb6GTjaw0QPfabYmFe"

**Comment by binaryYuki** [comment]
[https://github.com/binary-husky/gpt_academic/blob/ae4407135db8a8910755cf6895cf90037b651d34/config.py#L230
https://github.com/binary-husky/gpt_academic/blob/ae4407135db8a8910755cf6895cf90037b651d34/config.py#L231](https://github.com/binary-husky/gpt_academic/blob/ae4407135db8a8910755cf6895cf90037b651d34/config.py#L229-L232)

**Comment by binaryYuki** [comment]
请查看
https://github.com/binary-husky/gpt_academic/blob/ae4407135db8a8910755cf6895cf90037b651d34/config.py#L229-L232

**Comment by chjj159159** [comment]
> 请查看
> 
> https://github.com/binary-husky/gpt_academic/blob/ae4407135db8a8910755cf6895cf90037b651d34/config.py#L229-L232

![2](https://github.com/binary-husky/gpt_academic/assets/167509134/a6081d6a-9e7d-40b0-a569-dccb5e2255e5)
![4](https://github.com/binary-husky/gpt_academic/assets/167509134/32a1160e-8728-4e85-ae8d-5a1c6d0b8837)

**Comment by binaryYuki** [comment]
请确认您的 key 是否可用 谢谢 我看了您提供的截图 是openai 返回错误“apikey 错误”

**Comment by chjj159159** [comment]
好吧，我搞个新的试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月23日(星期二) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/gpt_academic] [Bug]: 您的 API_KEY 不满足任何一种已知的密钥格式，请在config文件中修改API密钥之后再运行。 (Issue #1723)














 
请确认您的 key 是否可用 谢谢 我看了您提供的截图 是openai 返回错误“apikey 错误”

**Comment by kevinliu616** [comment]
請問換新的能解決嗎？我也有相同問題

**Comment by binaryYuki** [comment]
@kevinliu616 

Hi，能否 po 一下你的報錯信息？

**Comment by binary-husky** [comment]
目前应该已经支持这种格式了
sk-proj-TUqe9R0DGi1PMRgLffujT3BlbkFJJ2gb6GTjaw0QPfabxxxx

**Comment by binary-husky** [comment]
更新下代码试试

**Comment by Chuyusiren** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/97970257/92386fb9-1461-42ee-84b1-16f543d1893d)
zhe's这是3.74版本的，还是无法识别
该怎么解决

**Comment by YuFengQu** [comment]
我的API的格式是:sk-None-xxxxxxxxxxxxxxxxxx，但是输入后就显示不满足，但是我输入的地方是没有问题的，免费版用户不可以使用吗，为什么别人申请到的是sk-xxxxxxxxxxx。

**Comment by binaryYuki** [comment]
> 我的API的格式是:sk-None-xxxxxxxxxxxxxxxxxx，但是输入后就显示不满足，但是我输入的地方是没有问题的，免费版用户不可以使用吗，为什么别人申请到的是sk-xxxxxxxxxxx。
Hi,

能否详细描述你的场景 不满足是在输入框输入的时候没匹配还是在config.py中没读取？

**Comment by FYZ-1539874** [comment]
(gptac_venv) D:\chatgpt_academic-master\chatgpt_academic-master>python main.py
网络代理状态：运行。
网络代理状态：运行。
Traceback (most recent call last):
  File "D:\chatgpt_academic-master\chatgpt_academic-master\predict.py", line 12, in <module>
    try: from config_private import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic-master\chatgpt_academic-master\config_private.py", line 29, in <module>
    assert False, "请在config文件中修改API密钥, 添加海外代理之后再运行"
           ^^^^^
AssertionError: 请在config文件中修改API密钥, 添加海外代理之后再运行

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\chatgpt_academic-master\chatgpt_academic-master\main.py", line 3, in <module>
    from predict import predict
  File "D:\chatgpt_academic-master\chatgpt_academic-master\predict.py", line 13, in <module>
    except: from config import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatgpt_academic-master\chatgpt_academic-master\config.py", line 29, in <module>
    assert False, "请在config文件中修改API密钥, 添加海外代理之后再运行"
           ^^^^^
AssertionError: 请在config文件中修改API密钥, 添加海外代理之后再运行

请问我这是api和代理都有问题吗

**Comment by Leon-0919** [comment]
@binaryYuki 你好哈
还是一样的错误 
API_KEY] 您的 API_KEY 不满足任何一种已知的密钥格式，请在config文件中修改API密钥之后再运行。

**Comment by binaryYuki** [comment]
> @binaryYuki 你好哈 还是一样的错误 API_KEY] 您的 API_KEY 不满足任何一种已知的密钥格式，请在config文件中修改API密钥之后再运行。

能否麻烦您提供 key 的相关格式 类似 sk-proj-xxxxx 这样？

我认为可以通过修改 regular expression 解决

**Comment by moriwlx** [comment]
我也是这个错误

![image](https://github.com/user-attachments/assets/34c0bc06-c5fe-4c92-a12f-d4dc4429278a)
![image](https://github.com/user-attachments/assets/d23afb15-32c0-4f33-bd0f-aa1424f72c97)

**Comment by moriwlx** [comment]
![image](https://github.com/user-attachments/assets/ffaebfd6-c14b-4c4f-b5da-9c461c40caa2)
换成项目api也不行

**Comment by FYZ-1539874** [comment]
好的谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: moriwlx ***@***.***&gt;
发送时间: 2024年8月16日 02:57
收件人: binary-husky/gpt_academic ***@***.***&gt;
抄送: FYZ-1539874 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [binary-husky/gpt_academic] [Bug]: 您的 API_KEY 不满足任何一种已知的密钥格式，请在config文件中修改API密钥之后再运行。 (Issue #1723)





 
image.png (view on web)
 换成项目api也不行

**Comment by linxi220520** [comment]
> 我也是这个错误
> 
> ![image](https://private-user-images.githubusercontent.com/61397407/358353435-34c0bc06-c5fe-4c92-a12f-d4dc4429278a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTExODksIm5iZiI6MTcyMzc5MDg4OSwicGF0aCI6Ii82MTM5NzQwNy8zNTgzNTM0MzUtMzRjMGJjMDYtYzVmZS00YzkyLWExMmYtZDRkYzQ0MjkyNzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2NDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYmVjNWJlYmFhMGY5NTg5NmExMmY2Nzg4YzUzZDU0NWI0ZTI3OWEwZjdlODFlYmQyNmIxZjUyOWUyYWM4MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xKhljxB9WxcjVCO4wdUuErGbi4s5Udzf3WQ24gzupR4) ![image](https://private-user-images.githubusercontent.com/61397407/358353723-d23afb15-32c0-4f33-bd0f-aa1424f72c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTExODksIm5iZiI6MTcyMzc5MDg4OSwicGF0aCI6Ii82MTM5NzQwNy8zNTgzNTM3MjMtZDIzYWZiMTUtMzJjMC00ZjMzLWJkMGYtYWExNDI0ZjcyYzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2NDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMTliMmY1ZjM4YTc1MmFkODIyZjg5ODEzYjBkZWYyZDNlZThjZTIyZDA3MWYyZTE2ZjY2YWNhM2Q4OWNmYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EiYciKklQOeT93uqwVEjNoD-9oMwk8fWkQzYsyOoau4)
> 
> 已经解决了 ![image](https://private-user-images.githubusercontent.com/61397407/358357977-f3a84005-e476-4f67-9bba-1e24d6787e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTExODksIm5iZiI6MTcyMzc5MDg4OSwicGF0aCI6Ii82MTM5NzQwNy8zNTgzNTc5NzctZjNhODQwMDUtZTQ3Ni00ZjY3LTliYmEtMWUyNGQ2Nzg3ZTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA2NDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZjJjODNjMzViYWNjNDZiMjIyYzEzODg4ZmMzMjNkODhhNzBkNmRiYWM0MDg4MjBjNDQ3YjQwMDI3MjUzYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wI8zpCcO65-7iS-cF9M0Izw1I4fd1612l1vN39o4XjQ)

请问你这个是怎么解决的呀

**Comment by yangcqyx** [comment]
原因：造成这个问题的原因是当前版本（包括最新版本）的GPT学术优化的API Key正则代码有点问题，无法匹配最新的OpenAI API key，例如这位用户的API key里有一个下划线，就无法被匹配到，所以报错无法识别，缺少api key。

解决方案：在config.py里找到CUSTOM_API_KEY_PATTERN参数，自定义一个正则表达式，例如最简单的只匹配前面的：

CUSTOM_API_KEY_PATTERN='^sk-proj-.+$'

来源：https://chatgptboke.com/gpt-academic-new-openai-api-key-not-recognized.html
