### ISSUE TITLE
RuntimeError: OpenAI拒绝了请求

### ISSUE THREAD

**Issue by CGUO00** [binary-husky/gpt_academic#1726]
### Class | 类型

函数插件

### Feature Request | 功能请求

在使用插件分析一个cpp项目时，可能时因为cpp项目文件过多，调用API过于频繁，就会导致报错。
提示如下：RuntimeError: OpenAI拒绝了请求：{"code":429,"error":"rate limit exceeded\n"}。
也有可能本人使用的是copilot学生认证的API速率限制较低，希望开发者大佬们能给点指导，是否能限制函数插件调用api接口的速率。
![image](https://github.com/binary-husky/gpt_academic/assets/85145166/58a12cf0-9de2-40fd-84f8-57ac66725ad6)

**Comment by binaryYuki** [comment]
Hi，

请查看 

https://github.com/binary-husky/gpt_academic/blob/ae4407135db8a8910755cf6895cf90037b651d34/config.py#L69

**Comment by CGUO00** [comment]
您好，十分感谢您的解答，但我在config文件中设置的默认访问线程数3，并没有变动，我觉得在使用批量分析整个cpp项目函数插件处理大量的cpp项目文件时，应该并没有触发线程数上限，而是可能达到了单位时间内token字节数量的限制，如果是这种原因该如何避免，同时我也会将访问线程数将为2或1再次尝试，再次感谢您的解答。
________________________________

**Comment by binaryYuki** [comment]
不好意思 请确认一下您用的是逆向的 copilot吗？

**Comment by binary-husky** [comment]
DEFAULT_WORKER_NUM 改成 1 试试，也不需要只看openai的模型
