### ISSUE TITLE
[Bug]: nougat: error: the following arguments are required: pdf

### ISSUE THREAD

**Issue by blue-eyed-g** [binary-husky/gpt_academic#1732]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

使用精准翻译PDF文档插件，显示一下错误：
`nougat: error: the following arguments are required: pdf `
这是webui反馈的错误：
`Traceback (most recent call last):
  File "./toolbox.py", line 205, in decorated
    yield from f(main_input, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, *args, **kwargs)
  File "./crazy_functions/批量翻译PDF文档_NOUGAT.py", line 93, in 批量翻译PDF文档
    yield from 解析PDF_基于NOUGAT(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File "./crazy_functions/批量翻译PDF文档_NOUGAT.py", line 111, in 解析PDF_基于NOUGAT
    fpp = yield from nougat_handle.NOUGAT_parse_pdf(fp, chatbot, history)
  File "./crazy_functions/crazy_utils.py", line 600, in NOUGAT_parse_pdf
    raise RuntimeError("Nougat解析论文失败。")
RuntimeError: Nougat解析论文失败。 `

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/67051930/40b33e1d-3457-4e32-9dfd-e27df0b91fe9)
![image](https://github.com/binary-husky/gpt_academic/assets/67051930/de424b6d-212d-4943-9cb6-b701414420ed)

**Comment by binary-husky** [comment]
nougat 可能版本迭代了？

**Comment by Menghuan1918** [comment]
https://github.com/binary-husky/gpt_academic/pull/1738
