### ISSUE TITLE
[Bug]: [Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

### ISSUE THREAD

**Issue by APLMY** [binary-husky/gpt_academic#1737]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

### Screen Shot | 有帮助的截图

![Uploading 801713931277_.pic_hd.jpg…]()

**Comment by MFYSIGS** [comment]
same question as you

**Comment by binary-husky** [comment]
#1
