### ISSUE TITLE
请问下修改代码什么地方可以让开启的服务监听指定的IP？

### ISSUE THREAD

**Issue by fishfree** [binary-husky/gpt_academic#1739]
当我按照README操作后：
```
如果浏览器没有自动打开，请复制并转到以下URL：
	「暗色主题已启用（支持动态切换主题）」: http://localhost:59239
```
我希望运行在http://0.0.0.0:59239 上。谢谢！

**Comment by binary-husky** [comment]
> 当我按照README操作后：
> 
> ```
> 如果浏览器没有自动打开，请复制并转到以下URL：
> 	「暗色主题已启用（支持动态切换主题）」: http://localhost:59239
> ```
> 
> 我希望运行在http://0.0.0.0:59239 上。谢谢！

实际上就是运行在0.0.0.0的

**Comment by fishfree** [comment]
哦，谢谢！提示信息有点误导
