### ISSUE TITLE
[Bug]: 出現錯誤, You exceeded your current quota. OpenAI以账户额度不足为由, 拒绝服务. 

### ISSUE THREAD

**Issue by kevinliu616** [binary-husky/gpt_academic#1746]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由, 拒绝服务. 请登录OpenAI查看详情 https://platform.openai.com/signup
請問這是什麼原因,出現這個問題該如何解決？
謝謝

### Screen Shot | 有帮助的截图

<img width="1311" alt="截圖 2024-04-28 上午9 35 05" src="https://github.com/binary-husky/gpt_academic/assets/60931976/c8c4bf04-6951-4c52-815c-5c962c73df85">
![1](https://github.com/binary-husky/gpt_academic/assets/60931976/f3aaab10-bdc6-4ec5-940e-9a9566124b0b)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

![1](https://github.com/binary-husky/gpt_academic/assets/60931976/cd9f2b4c-1579-49dd-bb46-9110e538c62b)

**Comment by ycwfs** [comment]
用API要账户额度的，要绑定付款方式

**Comment by kevinliu616** [comment]
> 用API要账户额度的，要绑定付款方式

請問那用免費的chat got 3.5的api不能用是嗎
謝謝

**Comment by zhangdulin** [comment]
如何获取市面上的能用的 gpt-3.5-turbo
