### ISSUE TITLE
[Bug]: 每次打开都显示选择一种依赖安装方式 似乎每次都要重新装一次

### ISSUE THREAD

**Issue by Binary0371** [binary-husky/gpt_academic#1747]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

每次打开都显示选择一种依赖安装方式 似乎每次都要重新装一次

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/168278936/63f49436-0ec1-4af5-aef4-7a045a545f79)

**Comment by binary-husky** [comment]
不会的，第二次就不会再安装了，只是重新检查一遍
