### ISSUE TITLE
[Bug]: Version of dependent package "gradio"  cannnot be too high

### ISSUE THREAD

**Issue by ArcueidShiki** [binary-husky/gpt_academic#1749]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Others | 非最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

python 3.11.0, gradio 4.38 not working
but, graio 3.23 worked well.
compatibility problem.

### Screen Shot | 有帮助的截图

![1714360136094](https://github.com/binary-husky/gpt_academic/assets/52120441/f60c4a9a-d63b-456a-aa2d-59f2e7c28c14)

**Comment by binaryYuki** [comment]
Hi, 

Thanks for getting in touch.

Please note that the official gradio package was not used by this project.

Instead, a cloned branch with additional modifications was used.[Link to install](https://public.agent-matrix.com/publish/gradio-3.32.9-py3-none-any.whl#sha256=d068a44119e1b838e26f3d2d8091c2273f54b2ed88cda3dac0b30e1f7f855ae2) & [Link to the repo](https://github.com/binary-husky/gradio-fix)

I recommend installing it using `pip install -r requirements.txt` so you won't need to deal with compatibility problems.

Hope this can help.

**Comment by binary-husky** [comment]
In addition, we have listed the enhanced feature of our gradio fork at [here](https://github.com/binary-husky/gpt_academic/wiki/%E5%BC%80%E5%8F%91GPT%E2%80%90Academic%E7%9A%84%E5%89%8D%E7%AB%AF)

**Comment by binary-husky** [comment]
GPT-Academic前端基于Gradio的一个3.32版本分支，源代码开源地址 https://github.com/binary-husky/gradio-fix

该分支和官方相比，有以下不同：

修复不能在动态输出时选中文本的BUG
支持mermaid脑图绘制和动态生长
新增一个浮窗控件 gr.Floating（左上的工具栏 以及 可拖动的输入区）
减小了录音控件的数据采集间隔提高实时性
为按钮控件添加info_str参数，当鼠标悬浮在按钮上时，显示提示
为按钮控件添加proxy_of参数，可以把一个按钮当做另一个按钮的克隆（代理）
移除gradio里面很多导致断网机器（在保密机构内运行的机器）无法运行的链接、字体
