### ISSUE TITLE
[Feature]: 新手提问： 如何升级版本？

### ISSUE THREAD

**Issue by Stephenzero** [binary-husky/gpt_academic#1750]
### Class | 类型

None

### Feature Request | 功能请求

新手提问： 如何升级版本？
比如我之前安装了 Version 3.72，如何升级到Version 3.74？能不能做个一键升级的工具？

**Comment by Menghuan1918** [comment]
使用的什么方式安装的？一键安装脚本吗？

**Comment by Stephenzero** [comment]
> 使用的什么方式安装的？一键安装脚本吗？

是按照你的说明文档一步一步直接在Python上面下载安装的（使用命令）

**Comment by Menghuan1918** [comment]
> > 使用的什么方式安装的？一键安装脚本吗？
> 
> 是按照你的说明文档一步一步直接在Python上面下载安装的（使用命令）

这样的话，如果网络连得上GitHub，使用python启动的时候应该是有一个提示你升级的，输入Y再按空格就可以了：

![图片](https://github.com/binary-husky/gpt_academic/assets/122662527/6862e9b7-8246-4cc7-bc2b-d046620eaae0)

**Comment by Stephenzero** [comment]
> > > 使用的什么方式安装的？一键安装脚本吗？
> > 
> > 
> > 是按照你的说明文档一步一步直接在Python上面下载安装的（使用命令）
> 
> 这样的话，如果网络连得上GitHub，使用python启动的时候应该是有一个提示你升级的，输入Y再按空格就可以了：
> 
> ![图片](https://private-user-images.githubusercontent.com/122662527/326890095-6862e9b7-8246-4cc7-bc2b-d046620eaae0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTMyNDQsIm5iZiI6MTcxNDQ5Mjk0NCwicGF0aCI6Ii8xMjI2NjI1MjcvMzI2ODkwMDk1LTY4NjJlOWI3LTgyNDYtNGNjNy1iYzJiLWQwNDY2MjBlYWFlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxNjAyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmU1NmUwMGI3NmRlOThhNzNlNWRkNGQ4YzBhOTYyMjY1NWQ5YmIzZmMyNzc1MGIxNTVkYWRmNTJkMDc4MWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j34X0ShTdgWXC1D6Hu8RAQAUKAcVZUVWr4aXsfHq5Xc)

谢谢，已经顺利升级！感谢

**Comment by kieran0625** [comment]
![1715786912234](https://github.com/binary-husky/gpt_academic/assets/81095191/3a2be9d2-ce1b-417f-9851-3b4a9c97e1ce)
您好，我是通过git命令安装的，运行main.py时更新失败是什么原因呀？
