### ISSUE TITLE
GPT4的适配性?

### ISSUE THREAD

**Issue by Damonrt** [binary-husky/gpt_academic#176]
首先感谢作者的分享, 虽然我的代理国家显示IP查询频繁,但是目前3.5运行良好.
尝试使用4.0,系统可以识别但是提问没有相应. 想咨询一下现在是不能调用4.0吗

**Comment by Damonrt** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/129445606/228961195-0f2a93bc-cd91-473a-ab56-1671eeb13797.png">
给一个这样的return, 尝试过吧turbo去掉但是不行

**Comment by binary-husky** [comment]
gpt-4的api接口没开放，只有plus会员能从网页访问（即使是plus会员的api key也没用）

所有人都在等

**Comment by longfuxu** [comment]
假设现在拿到API key了（Gpt4), 只需要把模型那里改为“GPT-4”就可以了，还是别的地方也需要修改？纯小白谢谢

**Comment by albert-ying** [comment]
同问，已有 gtp4 的 api access。

**Comment by binary-husky** [comment]
我们这没人申请到gpt4的api，~~o(>_<)o ~~
