### ISSUE TITLE
[Bug]: 缺少api_key。

### ISSUE THREAD

**Issue by Phantom-Aria** [binary-husky/gpt_academic#1764]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

只能识别sk-123456789xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx123456789这种类型的openai apikey

sk-proj-4AiTz10xxxxxxxxxxxxxxxxxxxxxxxxxxx这种类型的openai apikey无法被正确识别，显示缺少api_key。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/6726462/335c35dc-f165-46bc-8f91-a257f9c63674)

**Comment by Phantom-Aria** [comment]
说明一下，不是我的apikey问题，同样的apikey在chat-gpt-next-web项目中是可以使用的
![image](https://github.com/binary-husky/gpt_academic/assets/6726462/9b277ef7-a721-4a38-87d8-9d87f23a714e)
也不是我不想换apikey....这个谷歌账号被封了登不上openai官网......

**Comment by Phantom-Aria** [comment]
已通过自定义API解决

**Comment by xiaosamuel** [comment]
> 已通过自定义API解决

请问怎么自定义呢？
