### ISSUE TITLE
[Bug]: 是不是不支持过长的自定义API_KEY？

### ISSUE THREAD

**Issue by wwjCMP** [binary-husky/gpt_academic#1778]
### Installation Method | 安装方法与平台

Docker-Compose（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

参考 https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97
进行自定义API_KEY设置，设置如下。但还是不行

API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMzY3NDcwOSwianRpIjoiNjMzYTRmNDctNTkyZi00Nzg0LWI3N2ItZTc1Njk3YzdjZjIwIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiIxMWFiZDBjNThmNmM0NTIwODdiOTM1MzlkMzRjN2Q5YyIsIm5iZiI6MTcxMzY3NDcwOSwiZXhwIjoxNzI5MjI2NzA5LCJ1aWQiOiI2NWE2Nzk4MjU2M2M4ZTIyYzI1ODVlMDciLCJ1cGxhdGZvcm0iOiJwYyIsInJvbGVzIjpbInVuYXV0aGVkX3VzZXIiXX0.b6uPwHQyCqSt7DudakXD23Vqec9M2ZUU7efoOUy_rYw "

# 自定义API KEY格式
CUSTOM_API_KEY_PATTERN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMzY3NDcwOSwianRpIjoiNjMzYTRmNDctNTkyZi00Nzg0LWI3N2ItZTc1Njk3YzdjZjIwIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiIxMWFiZDBjNThmNmM0NTIwODdiOTM1MzlkMzRjN2Q5YyIsIm5iZiI6MTcxMzY3NDcwOSwiZXhwIjoxNzI5MjI2NzA5LCJ1aWQiOiI2NWE2Nzk4MjU2M2M4ZTIyYzI1ODVlMDciLCJ1cGxhdGZvcm0iOiJwYyIsInJvbGVzIjpbInVuYXV0aGVkX3VzZXIiXX0.b6uPwHQyCqSt7DudakXD23Vqec9M2ZUU7efoOUy_rYw "

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/32979859/145d55a7-b86d-425e-bb95-ecf05a3ec710)
![image](https://github.com/binary-husky/gpt_academic/assets/32979859/1fcc8ed3-8a8b-4df0-8ae8-c40558351bfb)

**Comment by binaryYuki** [comment]
Hi，

请修改 `CUSTOM_API_KEY_PATTERN = r"^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.[A-Za-z0-9-_.+/=]*$"`

**Comment by wwjCMP** [comment]
> Hi，
> 
> 请修改 `CUSTOM_API_KEY_PATTERN = r"^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.[A-Za-z0-9-_.+/=]*$"`
> 
> 以适配 JWT 类型的 API_KEY

谢谢你的回答，但还是一样的问题

**Comment by wwjCMP** [comment]
> Hi，
> 
> 请修改 `CUSTOM_API_KEY_PATTERN = r"^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.[A-Za-z0-9-_.+/=]*$"`
> 
> 以适配 JWT 类型的 API_KEY

API key现在可以了。我想问一下，怎么将openai的链接重定向到本地的服务。我在本地运行了下面链接的代理，可正常运行。但这里重定向失败。是设置的问题吗？

      API_URL_REDIRECT:                  '    "https://api.openai.com/v1/chat/completions": "http://localhost:8006/v1/chat/completions"                                            '
![image](https://github.com/binary-husky/gpt_academic/assets/32979859/2d770086-9409-4aa2-90bf-1f5c90b0c170)
