### ISSUE TITLE
[Bug]: 月之暗面 {"error":{"message":"Invalid Authentication","type":"invalid_authentication_error"}}

### ISSUE THREAD

**Issue by wwjCMP** [binary-husky/gpt_academic#1781]
### Installation Method | 安装方法与平台

Docker-Compose（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

月之暗面 报错 {"error":{"message":"Invalid Authentication","type":"invalid_authentication_error"}}

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/32979859/6fd63dc5-0d1f-410b-8985-5e1bebd449b3)
![image](https://github.com/binary-husky/gpt_academic/assets/32979859/78347647-9ce9-4e36-8b7f-72d0fb1c49c9)

**Comment by Skyorca** [comment]
怎么解决的呀
