### ISSUE TITLE
[Bug]: 前端界面只有一个停住的“等待响应”，后台没有报错信息

### ISSUE THREAD

**Issue by dfmjndm** [binary-husky/gpt_academic#1786]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

![image](https://github.com/binary-husky/gpt_academic/assets/57401901/23adf9e1-2833-4d95-b30d-d8a3feeeac0f)

我使用的是第三方claude opus，已配置API_URL_REDIRECT，proxies，USE_PROXY，API_KEY，CUSTOM_API_KEY_PATTERN，ANTHROPIC_API_KEY，其中ANTHROPIC_API_KEY和API_KEY都填的同一个第三方key

如果是任何兼容问题我想应该收到debug信息，这里什么说明也没有

### Screen Shot | 有帮助的截图

软件没有debug信息

**Comment by Menghuan1918** [comment]
第三方claude opus很有可能走的是openai格式的API，可以试试[将其视为oneapi接入](https://github.com/binary-husky/gpt_academic/wiki/%E5%A6%82%E4%BD%95%E6%9B%B4%E4%BE%BF%E6%8D%B7%E5%9C%B0%E6%8E%A5%E5%85%A5one%E2%80%90api)
