### ISSUE TITLE
[Bug]: Error code: 403, with error text {"error":{"code":"1220","message":"您的请求无法被处理，因为您的IP地址没有接口访问权限。如果您认为这是一个错误，请联系客服获取帮助。"}}

### ISSUE THREAD

**Issue by LYK0520** [binary-husky/gpt_academic#1791]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Error code: 403, with error text {"error":{"code":"1220","message":"您的请求无法被处理，因为您的IP地址没有接口访问权限。如果您认为这是一个错误，请联系客服获取帮助。"}}

### Screen Shot | 有帮助的截图

none

**Comment by awwaawwa** [comment]
请联系卖给你 API 的客服，从报错信息上看，这不是本项目的 Bug。

**Comment by LYK0520** [comment]
感谢！是因为白名单的原因，已解决！
