### ISSUE TITLE
第三方api接口接入之后显示OpenAI以提供了不正确的API_KEY为由, 拒绝服务. [Feature]: 

### ISSUE THREAD

**Issue by bangetang** [binary-husky/gpt_academic#1795]
### Class | 类型

None

### Feature Request | 功能请求

如题
我按照第三方api接口的使用方法设置了config_private文件，但是还是提示OpenAI以提供了不正确的API_KEY为由, 拒绝服务. 
![image](https://github.com/binary-husky/gpt_academic/assets/169810228/7bd545a7-3c72-42c0-80d3-51c93cd55400)
![1](https://github.com/binary-husky/gpt_academic/assets/169810228/65f1b10a-09a5-4f9c-8f78-6a4c820f6c4a)

**Comment by Menghuan1918** [comment]
应该是这种格式重定向：

API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "http://0.0.0.0:4000/v1/chat/completions"}

大括号两边不应该有`'`这个符号，`API_URL_REDIRECT`后面也应该是跟着`=`号

> 你写的这个是用在docker-compose.yml里面的格式来着

**Comment by binary-husky** [comment]
格式错了
