### ISSUE TITLE
[Bug]: Undefined array key “max_tokens”

### ISSUE THREAD

**Issue by dfmjndm** [binary-husky/gpt_academic#1806]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

调用第三方出现了这种报错，看起来是maxtoekn这个参数导致的，句子拆解成字了，请问要怎么适配
![image](https://github.com/binary-husky/gpt_academic/assets/57401901/3af1efbe-4e70-4664-8e46-a02c678b555b)

### Screen Shot | 有帮助的截图

无

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

无

**Comment by binary-husky** [comment]
缺乏信息
