### ISSUE TITLE
[Bug]: 百度千帆api调用出错

### ISSUE THREAD

**Issue by Luochen-Echo** [binary-husky/gpt_academic#1824]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

在config.py中，我修改了自己的百度api_key，llm_module中添加了'qianfan'，在后面千帆key中修改了我自己的key。但是启动后出错。
## config.py修改如下：
![apikey](https://github.com/binary-husky/gpt_academic/assets/124498616/498665a1-d880-4b1a-b615-a56465611db3)
![llm](https://github.com/binary-husky/gpt_academic/assets/124498616/292f17bc-50a3-458a-a29b-53fd73ab6668)
![qianfan](https://github.com/binary-husky/gpt_academic/assets/124498616/93a41015-9137-4225-81fd-fa0c5018621e)

## 错误代码如下：
Traceback (most recent call last):
  File "./request_llms/bridge_qianfan.py", line 110, in generate_from_baidu_qianfan
    incoming = dec['result']
               ~~~^^^^^^^^^^
KeyError: 'result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./request_llms/bridge_qianfan.py", line 151, in predict
    for response in generate_from_baidu_qianfan(inputs, llm_kwargs, history, system_prompt):
  File "./request_llms/bridge_qianfan.py", line 117, in generate_from_baidu_qianfan
    raise RuntimeError(dec['error_msg'])
RuntimeError: Open api daily request limit reached



### Screen Shot | 有帮助的截图

![错误](https://github.com/binary-husky/gpt_academic/assets/124498616/6a77fcb4-3862-4b38-9d07-782c33b55a80)


### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

_No response_

**Comment by qychen2001** [comment]
应该是QPS达到了限制，或者去千帆工作台检查对应的模型服务是否打开

**Comment by Luochen-Echo** [comment]
已经解决，应该先在工作台中选择一个模型，然后开通付费，注意查看下brdige_qianfan.py中的url_lib中的url链接，对照下百度自己的api文档
