### ISSUE TITLE
[Bug]: 我按照#1765的方法配置deepseek但是不起作用

### ISSUE THREAD

**Issue by yanzexi0622** [binary-husky/gpt_academic#1827]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

我按照#1765的方法配置deepseek但是不起作用，仍然提示：

连接超时，请您依次尝试：1、刷新网页重新登录；2、启用浏览器隐私模式；3、关代理并重启；4、Github反馈

### Screen Shot | 有帮助的截图

![屏幕截图 2024-05-25 150231](https://github.com/binary-husky/gpt_academic/assets/151909793/ac1a40aa-9e79-47ce-9d63-87e9fbc6a159)

**Comment by qychen2001** [comment]
请贴出你的完整config便于定位问题

**Comment by yanzexi0622** [comment]
<img width="612" alt="微信图片_20240527144323" src="https://github.com/binary-husky/gpt_academic/assets/151909793/dfd56ad2-f337-4d5f-99b0-0698f9513d17">
<img width="346" alt="微信图片_20240527144338" src="https://github.com/binary-husky/gpt_academic/assets/151909793/557deb2a-df2d-47f9-9c5d-f48e038fc364">
只修改了这两个地方，其他没有改动

**Comment by qychen2001** [comment]
控制台的回溯有吗？

**Comment by yanzexi0622** [comment]
解决了，有一个变量写错了，感谢
