### ISSUE TITLE
[Feature]: gpt_academic是否对外提供API服务

### ISSUE THREAD

**Issue by bluescv** [binary-husky/gpt_academic#1838]
### Class | 类型

程序主体

### Feature Request | 功能请求

如果我想把gpt学术作为一个后台服务，由其他的后台服务调用来利用其能力，需要怎么做？gpt学术有对外提供服务API吗？看前端是用websocket与后台进行通信的。

**Comment by binary-husky** [comment]
https://github.com/binary-husky/void-terminal
