### ISSUE TITLE
[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

### ISSUE THREAD

**Issue by EYE-YGK** [binary-husky/gpt_academic#1841]
[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。
![98de4d3596d9affb452400b4e4c0952](https://github.com/binary-husky/gpt_academic/assets/153922200/cfd72a4b-720f-4cc7-beb4-7aa06f78aff1)
![捕获](https://github.com/binary-husky/gpt_academic/assets/153922200/a5c2aafc-ab18-4b6e-83b8-9beacc0871bc)
![捕获1](https://github.com/binary-husky/gpt_academic/assets/153922200/ed4108c2-2cd7-4568-bcd0-ff47bd4ebe6f)
快疯了，求救，安装了很多遍都不行，确定都按照要求改好了，梯子可用，怎么办啊？安装旧版本也不行了。。。。

_Originally posted by @EYE-YGK in https://github.com/binary-husky/gpt_academic/issues/1#issuecomment-2142443831_

**Comment by EYE-YGK** [comment]
@binary-husky

**Comment by binary-husky** [comment]
#1 可能是整个飞机场都被openai屏蔽了，不如用国产模型吧

**Comment by EYE-YGK** [comment]
> #1 可能是整个飞机场都被openai屏蔽了，不如用国产模型吧

博主能不能出一个阿里千问和百度千帆大模型的教程啊，十分需要，之前就按照其他教程做成了一个星火的国产模型，其他的还没搞懂。。。十分感谢
