### ISSUE TITLE
我加入用户名和密码之后直接通过域名+端口访问提示 connection errored out

### ISSUE THREAD

**Issue by Soramuse** [binary-husky/gpt_academic#185]
如果不加用户名和密码就没事儿，请问有什么办法呢？

**Comment by binary-husky** [comment]
你好，剔除清华pip源，然后升级gradio

**Comment by Soramuse** [comment]
感谢回复，我刚刚试了一下，我的gradio是最新的，而且没用清华的pip源

**Comment by sunchongwei** [comment]
https://github.com/gradio-app/gradio/issues/3716   it's a bug!

**Comment by veinkr** [comment]
@Soramuse 使用https反代就可以了

**Comment by 0xZhangxu** [comment]
解决办法: https://github.com/gradio-app/gradio/issues/3716#issuecomment-1493272631

**Comment by fkcptlst** [comment]
在nginx反向代理的location块设置一下websocket就行了

location / {
...
 # websocket reverse proxy
 proxy_http_version 1.1;
 proxy_set_header Upgrade $http_upgrade;
 proxy_set_header Connection "upgrade";
}
