### ISSUE TITLE
[Bug]: Arxiv论文翻译失败

### ISSUE THREAD

**Issue by watashihame** [binary-husky/gpt_academic#1872]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

使用官方提供的[带有latex的docker镜像](https://github.com/users/binary-husky/packages/container/package/gpt_academic_with_latex)
执行 _Arxiv论文精细翻译（输入arxivID）\[需Latex\]_ 时返回：

`输入文件的路径 (Arxiv下载目录) 存在，但位置非法。请将文件上传后再执行该任务。`

#1865 中给出的原因为此[函数](https://github.com/binary-husky/gpt_academic/blob/15cc08505f7fbffb4ef1a9027f74e5e94b7a8947/shared_utils/fastapi_server.py#L50)有误。

### Screen Shot | 有帮助的截图

![QQ20240627-162204](https://github.com/binary-husky/gpt_academic/assets/15100339/514e16e4-7197-49a7-bf98-ba8e6aa29da8)

**Comment by binary-husky** [comment]
此bug已修复
