### ISSUE TITLE
[Bug]: git pull到了新的版本，安装了requirements.txt

### ISSUE THREAD

**Issue by alleniver** [binary-husky/gpt_academic#1886]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

图片对应的那几个按钮点击不了，点击后会报错。

Uncaught (in promise) ReferenceError: register_plugin_init is not defined
    at eval (eval at <anonymous> (Blocks.svelte:68:25), <anonymous>:3:26)
    at Object.eval [as frontend_fn] (eval at <anonymous> (Blocks.svelte:68:25), <anonymous>:3:46853)
    at je (Blocks.svelte:369:6)
3common.js:1539 Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at generate_menu (http://localhost:7865/file=themes/common.js:1539:24)
    at run_advanced_plugin_launch_code (http://localhost:7865/file=themes/common.js:1700:5)
    at eval (eval at <anonymous> (http://localhost:7865/assets/Blocks-7e74d7b8.js:56:3356), <anonymous>:3:25)
    at Object.eval [as frontend_fn] (eval at <anonymous> (http://localhost:7865/assets/Blocks-7e74d7b8.js:56:3356), <anonymous>:3:68)
    at je (http://localhost:7865/assets/Blocks-7e74d7b8.js:57:2855)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/6006650/41df599e-0187-4cb2-85f8-b6f1bda83d86)

**Comment by binary-husky** [comment]
`register_plugin_init`这个函数是在项目的themes/common.js里面，我不能复现这个bug，能详细说明一下安装过程吗？

**Comment by binary-husky** [comment]
> VM70:3 Uncaught (in promise) ReferenceError: register_plugin_init is not defined at eval (eval at (Blocks.svelte:68:25), :3:26) at Object.eval [as frontend_fn] (eval at (Blocks.svelte:68:25), :3:46853) at je (Blocks.svelte:369:6) common.js:1539 Uncaught (in promise) DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded. at generate_menu (http://localhost:7865/file=themes/common.js:1539:24) at run_advanced_plugin_launch_code (http://localhost:7865/file=themes/common.js:1700:5) at eval (eval at (http://localhost:7865/assets/Blocks-7e74d7b8.js:56:3356), :3:25) at Object.eval [as frontend_fn] (eval at (http://localhost:7865/assets/Blocks-7e74d7b8.js:56:3356), :3:68) at je (http://localhost:7865/assets/Blocks-7e74d7b8.js:57:2855) 2VM58:3 Uncaught (in promise) ReferenceError: run_classic_plugin_via_id is not defined at eval (eval at (Blocks.svelte:68:25), :3:25) at Object.eval [as frontend_fn] (eval at (Blocks.svelte:68:25), :3:68) at je (Blocks.svelte:369:6) 3VM55:3 Uncaught (in promise) ReferenceError: run_classic_plugin_via_id is not defined at eval (eval at (Blocks.svelte:68:25), :3:25) at Object.eval [as frontend_fn] (eval at (Blocks.svelte:68:25), :3:67) at je (Blocks.svelte:369:6)
> 
> ```
> config文件我很久没更新了，对齐更新了下，所有库都更新了，运行后还是这个样子。
> ```

不对，这个代码不是最新的。新版的代码会生成一个minimize的js文件，不可能直接访问file=themes/common.js
