### ISSUE TITLE
[Bug]: api额度不足

### ISSUE THREAD

**Issue by DBook111** [binary-husky/gpt_academic#1887]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我明明购买了gpt-4的套餐，但是提示api的额度不足。。难道api额度需要额外购买？

### Screen Shot | 有帮助的截图

无

**Comment by gg177088627** [comment]
我也这样
