### ISSUE TITLE
one-api 等待响应后显示 代理服务器无法使用

### ISSUE THREAD

**Issue by Wangtc525** [binary-husky/gpt_academic#1898]
您好，我配置one-api遇到了一些问题，我猜测是小问题，可一直发现不了，能否帮忙看一下，不胜感激~
我本地起了one-api的服务，且测试能通。
![image](https://github.com/user-attachments/assets/e8875046-2567-4e55-a9c1-45f54e652407)
接着我在gpt-academic的config.py里面配置了百川大模型。
```py
AVAIL_LLM_MODELS  = ["one-api-Baichuan2-Turbo"]
API_URL_REDIRECT = {"https://api.baichuan-ai.com/v1/assistants": "http://localhost:3000"}
```
但提交问题后仍然会请求超时。
一直等待响应：
![image](https://github.com/user-attachments/assets/c9b5ee45-32a2-4977-86ab-cb436fd06f47)
后续报错：
![image](https://github.com/user-attachments/assets/d884a45a-4e9c-4002-b555-869a10f13cf9)
![image](https://github.com/user-attachments/assets/b5d3a894-e690-49fa-af15-93e45e09032b)
请问该如何解决~

**Comment by binaryYuki** [comment]
"http://localhost:3000"？ 请参照 one-api [文档](https://github.com/songquanpeng/one-api?tab=readme-ov-file#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)
