### ISSUE TITLE
[Bug]: 无法运行，提示“ AttributeError: 'set' object has no attribute 'get' ”

### ISSUE THREAD

**Issue by DreammStill** [binary-husky/gpt_academic#1920]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

根据配置说明安装完成后，创建了config_private.py文件，在其中修改了API-KEY和API_URL_REDIRECT两项，其中
API_URL_REDIRECT = {"https://api.openai-proxy.org/v1/chat/completions"}
运行时报错  AttributeError: 'set' object has no attribute 'get'

### Screen Shot | 有帮助的截图

![image](https://github.com/user-attachments/assets/9f14f009-fdb2-4ce0-8207-c662996b5bf9)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

> python main.py
 [PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。
Traceback (most recent call last):
  File "D:\GPT_Academic\gpt_academic\main.py", line 364, in <module>
    main()
  File "D:\GPT_Academic\gpt_academic\main.py", line 45, in main
    from request_llms.bridge_all import predict
  File "D:\GPT_Academic\gpt_academic\request_llms\bridge_all.py", line 68, in <module>
    API_URL_REDIRECT, AZURE_ENDPOINT, AZURE_ENGINE = get_conf("API_URL_REDIRECT", "AZURE_ENDPOINT", "AZURE_ENGINE")
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT_Academic\gpt_academic\shared_utils\config_loader.py", line 114, in get_conf
    r = read_single_conf_with_lru_cache(arg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GPT_Academic\gpt_academic\shared_utils\config_loader.py", line 81, in read_single_conf_with_lru_cache
    oai_rd = r.get("https://api.openai.com/v1/chat/completions", None) # API_URL_REDIRECT填写格式是错误的，请阅读`https://github.com/binary-husky/gpt_academic/wiki/项目配置说明`
             ^^^^^
AttributeError: 'set' object has no attribute 'get'

**Comment by RonghaiHe** [comment]
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.openai-proxy.org/v1/chat/completions"}

改成这个试试，这个是字典格式
