### ISSUE TITLE
Mac clash for chatgpt_academic问题

### ISSUE THREAD

**Issue by Drxdx** [binary-husky/gpt_academic#195]
根据官网和B站每一个步骤都相同，获取到了代理，但是一直出现"代理所在地查询超时，代理可能无效"（开科学上网和不开一样），所以肯定有问题。
对于clash，我把proxies = {"http_proxy": "http://127.0.0.1:7890", "https_proxy": "http://127.0.0.1:7890"}，（check-proxy.py）出现的问题是:

网络代理状态：运行。
{'http_proxy': 'http://127.0.0.1:7890', 'https_proxy': 'http://127.0.0.1:7890'}
查询代理的地理位置，返回的结果是{'ip': '2401:ec00:15:1008:3c3d:12ef:7f59:9b55', 'network': '2401:ec00::/32', 'version': 'IPv6', 'city'
代理配置 http://127.0.0.1:7890, 代理所在地：China
但是根据网站查询协议的时候，都是一样的，但是位置一直在China，不知道怎么解决，希望Mac端有人遇到这个问题讨论一下

**Comment by samqin123** [comment]
我建议你rm掉目录，重新装一遍，clash配置修改config.py的部分
按照这个来 proxies = {
  'http': 'http://127.0.0.1:7890',
  'https': 'http://127.0.0.1:7890'
}

**Comment by samqin123** [comment]
你多了_proxy

**Comment by Drxdx** [comment]
> 你多了_proxy

我也用了你说的那种方法，一直是IP受限，连China都出不来

**Comment by BSC1116** [comment]
和你一样的问题，蹲一个解决方案。

**Comment by Jackory** [comment]
同问题，蹲解决方法
