### ISSUE TITLE
[Bug]: 连接超时

### ISSUE THREAD

**Issue by jiangangoddog** [binary-husky/gpt_academic#1950]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

连接超时，请您依次尝试：1、刷新网页重新登录；2、启用浏览器隐私模式；3、关代理并重启；4、Github反馈
Connection errored out.

### Screen Shot | 有帮助的截图

![image](https://github.com/user-attachments/assets/e8ff2fc7-7a6d-42cf-bef9-3c682de03353)

**Comment by jiangangoddog** [comment]
Solved

**Comment by jiangangoddog** [comment]
> 你是怎么解决的？我发现我使用ip+端口访问没有问题，但是使用域名+nginx反向代理也会出现你这个错误。

不好意思我忘了，很久不用了

**Comment by Cz1544252489** [comment]
我发现解决的办法了。我使用的是nginx，在使用反向代理的时候只代理域名是不行的，同时还要处理一个/queue 的代理部分，这个可以用浏览器的F12开发者模式发现。
一个额外的websocket代理配置如下，当然这可能只是这种报错的原因之一：
```    
location /queue/ {
        proxy_pass http://127.0.0.1:10000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
```
