### ISSUE TITLE
[Bug]: ERROR: Could not install packages due to an OSError

### ISSUE THREAD

**Issue by Kylelly** [binary-husky/gpt_academic#1995]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

突然就出现问题了，今天在运行的时候卡在了开头，以为是网络问题，但似乎不太对（文科研究牲对代码啥的不是很懂）

### Screen Shot | 有帮助的截图

![461a5ae9025ad3a5b9634b0e06ba1b5](https://github.com/user-attachments/assets/fde95fff-d6f9-421c-9b95-162483229ea9)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

选择一种依赖安装方式:

1: 使用pypi官方

2: 使用阿里源

输入1或2. 然后敲回车: 1
Looking in indexes: https://pypi.org/simple/
Collecting gradio==3.32.10 (from -r requirements.txt (line 1))
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='public.agent-matrix.com', port=443): Max retries exceeded with url: /publish/gradio-3.32.10-py3-none-any.whl (Caused by ResponseError('too many 502 error responses'))

Command '"D:\GPTAcademic\installer_files\conda\condabin\conda.bat" activate "D:\GPTAcademic\installer_files\env" >nul && python -m pip install -r requirements.txt --upgrade -i https://pypi.org/simple/' failed with exit status code '1'. Exiting...

Done!
请按任意键继续. . .

**Comment by woai369** [comment]
请问解决了么，我也出现这个问题

**Comment by Kylelly** [comment]
> 请问解决了么，我也出现这个问题
没有，刚准备写Assignment，准备分析一些文件，结果发现出问题了

**Comment by MG-Wang** [comment]
服务器正在升级维护：
![PixPin_2024-10-09_20-12-20](https://github.com/user-attachments/assets/c95c5dba-739e-4110-a8b5-27d6a0bdbc56)

**Comment by Kylelly** [comment]
> 服务器正在升级维护： ![PixPin_2024-10-09_20-12-20](https://private-user-images.githubusercontent.com/58323546/374951572-c95c5dba-739e-4110-a8b5-27d6a0bdbc56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzAyNTcsIm5iZiI6MTcyODUyOTk1NywicGF0aCI6Ii81ODMyMzU0Ni8zNzQ5NTE1NzItYzk1YzVkYmEtNzM5ZS00MTEwLWE4YjUtMjdkNmEwYmRiYzU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzMTIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NzlmYjAwNWM5NTUxNjhhMmU2MTU3YTVjMDcxYzk3OTE4N2JmMWI3ODU3ZDRiNTRmNDQzZWVkY2JiZWI3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HQlkbYVIVmV33_CkpcdsZyKszeszUQsRwJAvnfQJNpI)

 破案了，哈哈哈

**Comment by binary-husky** [comment]
已经修复

**Comment by Kylelly** [comment]
> 已经修复

感谢
