### ISSUE TITLE
[Feature]: 模型自主选择

### ISSUE THREAD

**Issue by zhanghg1983** [binary-husky/gpt_academic#2019]
### Class | 类型

None

### Feature Request | 功能请求

希望可以参考vscode 的continue 插件中的通过字段自定义模型的功能，而不是硬编码，因为模型越来越多，完全硬编码可能无法满足最新模型，比如claude-sonnet-3-5-new已经出来了，而claude-sonnet-3-5还不支持

**Comment by watermeloncq** [comment]
这个可以通过和oneapi协同实现，但目前在win系统下用docker部署gpt_academic和oneapi后，无法正常协同。
只能用源码部署gpt_academic和oneapi

**Comment by zhanghg1983** [comment]
刚看到以下教程，不好意思
如何接入其他在线大语言模型
复制request_llms/bridge_zhipu.py，重命名为你喜欢的名字

修改predict_no_ui_long_connection
