### ISSUE TITLE
[Feature]: 希望增加输入区换行功能

### ISSUE THREAD

**Issue by yfthu** [binary-husky/gpt_academic#2042]
### Class | 类型

程序主体

### Feature Request | 功能请求

在输入区，有时候想换行，但按Enter后，直接提交了。按Ctrl+Enter也不管用。希望增加输入区换行功能，谢谢！

**Comment by yfthu** [comment]
@HougeLangley @fayujiang @inkydragon @moetayuko

**Comment by moetayuko** [comment]
shift+enter

**Comment by yfthu** [comment]
> shift+enter

好的谢谢！
