### ISSUE TITLE
   proxies = { "http":"socks5h//localhost:4781", "https":"socks5h://localhost:4781", }请问各位大神这里哪里出了问题

### ISSUE THREAD

**Issue by MengLiu999** [binary-husky/gpt_academic#206]

**Comment by syaohweichen** [comment]
改成你主机地址和代理的端口，注释写得很详细了

**Comment by WanZunGe** [comment]
> 改成你主机地址和代理的端口，注释写得很详细了

[https://files.catbox.moe/35l5yb.png](url)
我这样写对吗 proxies = { "http": "http://127.0.0.1:7890", "https": "http://127.0.0.1:7890", }

**Comment by Carr-110** [comment]
> 
proxies = { "http": "http://127.0.0.1:7890", "https": "https://127.0.0.1:7890", }

**Comment by pzhren** [comment]
我也是你这个，用的clash，但是不对，你弄好了吗，求助

**Comment by ilray88** [comment]
> 我也是你这个，用的clash，但是不对，你弄好了吗，求助


> > 改成你主机地址和代理的端口，注释写得很详细了
> 
> [https://files.catbox.moe/35l5yb.png](url) 我这样写对吗 proxies = { "http": "http://127.0.0.1:7890", "https": "http://127.0.0.1:7890", }

注释中地址位置“http://”是域名时候使用，地址为ip时候要把“http://”删掉。即proxies = { "http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }，这样就能成共代理了

**Comment by healerlalala** [comment]
我还是说无效，到底要咋配置哇 哭了

**Comment by Lustrewilkin** [comment]
> > 我也是你这个，用的clash，但是不对，你弄好了吗，求助
> 
> > > 改成你主机地址和代理的端口，注释写得很详细了
> > 
> > 
> > [https://files.catbox.moe/35l5yb.png](url) 我这样写对吗 proxies = { "http": "http://127.0.0.1:7890", "https": "http://127.0.0.1:7890", }
> 
> 注释中地址位置“http://”是域名时候使用，地址为ip时候要把“http://”删掉。即proxies = { "http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }，这样就能成共代理了

协议，地址，端口，不能删除
