### ISSUE TITLE
[Bug]: 翻译结束后编译PDF失败

### ISSUE THREAD

**Issue by XZXS321** [binary-husky/gpt_academic#2076]
### Installation Method | 安装方法与平台

OneKeyInstall (一键安装脚本-windows)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在使用 PDF翻译中文并重新编译PDF[需Latex] 插件在最后会出现编译失败问题：由于最为关键的转化PDF编译失败, 将根据报错信息修正tex源文件并重试, 当前报错的latex代码处于第[-1]行 ...。
在排除字体问题后，阅读merge_translate_zh.log和merge.log文件发现，生成的latex中使用了fontspec宏包，该宏包是一个基于XeLaTeX和LuaLaTeX的宏包，而插件中定义并调用的是pdflatex来重新编译

### Screen Shot | 有帮助的截图

![image](https://github.com/user-attachments/assets/fb0db87a-92c2-4a5d-9e67-d366ab403961)

**Comment by Daibo-Baby** [comment]
改一下latex编译代码的编译引擎就可以了，本来的是pdflatex，改成xelatex就能用了

**Comment by XZXS321** [comment]
> 改一下latex编译代码的编译引擎就可以了，本来的是pdflatex，改成xelatex就能用了

您好，能具体说一下在哪里改吗？在提issues之前我自己改过，但失败了，如果能指点一下将不胜感激！
