### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Fan-Ji** [binary-husky/gpt_academic#2099]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

[Local Message] 异常

Traceback (most recent call last):
  File ".\request_llms\bridge_chatgpt.py", line 353, in predict
    raise ValueError(f'无法读取以下数据，请检查配置。\n\n{chunk_decoded}')
ValueError: 无法读取以下数据，请检查配置。

<html>
 
404 Not Found
nginx

### Screen Shot | 有帮助的截图

![Snipaste_2024-12-26_09-32-25](https://github.com/user-attachments/assets/262d3ef5-2658-40ab-b885-3e303c19ae94)
![Snipaste_2024-12-26_09-33-06](https://github.com/user-attachments/assets/65d58fe2-60e0-4b62-96a4-40a362b138d0)

**Comment by Fan-Ji** [comment]
Thank you for your reply
     I used
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.chatanywhere.com.cn/v1/chat/completions"}
so received above issue, But it could work properly before yesterday.

Besides,
    When I use 
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://reverse-proxy-url/v1/chat/completions"}
    It has following problem: [Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。
    May I ask how to set it correctly? Thank you a lot!

**Comment by binaryYuki** [comment]
@Fan-Ji I just double-checked their documentation, and I would suggest switching to the following configuration as mentioned in their [documentation](https://github.com/chatanywhere/GPT_API_free):

```python
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.chatanywhere.tech/v1/chat/completions"}
```

Hope it works!
