### ISSUE TITLE
香港独立公网IP服务器能够用来直接部署吗？

### ISSUE THREAD

**Issue by mikestut** [binary-husky/gpt_academic#215]
香港独立公网IP服务器能够用来直接部署吗？我有一个香港服务器和OPENAI 的日本地区KEY，想问下是否可以用来部署？

**Comment by binary-husky** [comment]
看下wiki上有大佬的部署经验https://github.com/binary-husky/chatgpt_academic/wiki

**Comment by sunchongwei** [comment]
亲测可以

**Comment by mikestut** [comment]
可以部署，不过会提醒没有走代理，然后报：未走代理，可能无法使用的提醒。
港服linux下远程第一次远程可以访问，设备重启后，远程无法访问，本地无法直接用浏览器打开。另外港服下，window下本地可以访问，开防火墙端口，远程依旧无法访问。
