### ISSUE TITLE
第一次提交的问题可以回答，第二次一直等待，只能刷新页面重新使用

### ISSUE THREAD

**Issue by whoaimedith** [binary-husky/gpt_academic#221]
为什么只能在主界面里问一次问题呢？我问第一个问题的时候chatGPT可以快速解答，但是再继续提问的话就会一直卡在等待中，无法给出答复。只有刷新一次网页后才能继续输入问题进行提问。
![image](https://user-images.githubusercontent.com/108109700/229266784-9c895288-53de-4bd7-97dc-8f06846e9a8b.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/229275706-21292764-eb0c-402a-b8eb-f71e4f91c27f.png)
无法复现

**Comment by YSAA1** [comment]
我的也是这种情况，终端也并没有报错。不知道如何解决
