### ISSUE TITLE
开通了plus会员，plus会员不限制次数，能否接入plus会员，而不只是apikey

### ISSUE THREAD

**Issue by williamzhao95** [binary-husky/gpt_academic#226]
开通了plus会员，plus会员不限制次数，能否接入plus会员，而不只是apikey

**Comment by lixibi** [comment]
还不能api调用4.0 
网页对话都是免费的

**Comment by binary-husky** [comment]
目前有没有可以调动网页接口的api？

**Comment by williamzhao95** [comment]
有可以调用网页接口的：https://github.com/cooolr/chatgpt_plus_python_api，类似爬虫的形势，比较麻烦，但是plus会员是不限制次数的，api和会员都买有点儿贵啊

**Comment by williamzhao95** [comment]
> 目前有没有可以调动网页接口的api？

有可以调用网页接口的：https://github.com/cooolr/chatgpt_plus_python_api，类似爬虫的形式，需要构造头，但是plus会员是不限制次数的，api和会员都买的话有点儿贵啊，期待加入自动登录plus然后调用plus的模型的，这样玩儿法多一些

**Comment by williamzhao95** [comment]
> 目前有没有可以调动网页接口的api？

有可以调用网页接口的：https://github.com/cooolr/chatgpt_plus_python_api，类似爬虫的形式，需要构造头，但是plus会员是不限制次数的，api和会员都买的话有点儿贵啊，期待加入自动登录plus然后调用plus的模型的，这样玩儿法多一些

**Comment by jkhcc11** [comment]
有啥用，不申请开通api的网页对话版，还有限制。plus开了不申请api等于没开。
