### ISSUE TITLE
API key 的Free trial usage到期了，各位有什么解决方法吗

### ISSUE THREAD

**Issue by Ultrasty** [binary-husky/gpt_academic#227]
![H{4)TLVY0YOYDJ%9861XP@X](https://user-images.githubusercontent.com/51046846/229273838-44c3129c-1aa5-4528-888b-7a52c55f1d23.jpg)

今天使用时遇到了"You exceeded your current quota, please check your plan and billing details."的报错，发现是API key的免费额度过期了，又注册了一个新的号，发现并没有给我分配$18的免费额度，求助各位大佬有什么解决方法吗？

**Comment by Ultrasty** [comment]
问题已解决

**Comment by Theresa-0328** [comment]
请问现在新号还发额度吗？发的额度是多少？

**Comment by JackeyLoveT** [comment]
> 问题已解决

您好 请问如何解决的？

**Comment by Ultrasty** [comment]
> > 问题已解决
> 
> 您好 请问如何解决的？

注册新号，最好用微软账号登录，很多邮箱注册不发额度

**Comment by JackeyLoveT** [comment]
> > > 问题已解决
> > 
> > 
> > 您好 请问如何解决的？
> 
> 注册新号，最好用微软账号登录，很多邮箱注册不发额度

ok 谢谢 这个免费使用额度大概一周就会过期是吧

**Comment by Ultrasty** [comment]
> > > > 问题已解决
> > > 
> > > 
> > > 您好 请问如何解决的？
> > 
> > 
> > 注册新号，最好用微软账号登录，很多邮箱注册不发额度
> 
> ok 谢谢 这个免费使用额度大概一周就会过期是吧

应该挺久的

**Comment by xzbdmw** [comment]
> > > > > 问题已解决
> > > > 
> > > > 
> > > > 您好 请问如何解决的？
> > > 
> > > 
> > > 注册新号，最好用微软账号登录，很多邮箱注册不发额度
> > 
> > 
> > ok 谢谢 这个免费使用额度大概一周就会过期是吧
> 
> 应该挺久的

新号啥时候过期

**Comment by binary-husky** [comment]
我的额度也过期了，有没有卖key的良心商家呀

额度不足，或者额度没用完但是过期了  #263 #227

**Comment by fouzhe** [comment]
> 我的额度也过期了，有没有卖key的良心商家呀
> 
> 额度不足，或者额度没用完但是过期了 #263 #227
同求

**Comment by zzxcodelife** [comment]
key过期的可以使用nobepay注册虚拟信用卡，绑定信用卡，绑定信用卡的时候需要开隐身模式

**Comment by RidiculousDoge** [comment]
这个额度是为什么会过期呀，咋样才能不过期（

**Comment by Yuhao-Luo** [comment]
> 时候

请问隐身模式是啥意思呢

**Comment by Yuhao-Luo** [comment]
> key过期的可以使用nobepay注册虚拟信用卡，绑定信用卡，绑定信用卡的时候需要开隐身模式

请问隐身模式是啥以上呢

**Comment by zzxcodelife** [comment]
隐身模式就是隐私窗口。好像现在停止注册新账号了？

**Comment by adrianzzk** [comment]
我找了一个在国外的朋友绑卡，api不太贵，比plus便宜多了去了

**Comment by 1251480932** [comment]
![2f50d10f9389573c0fd0a1d2d3c5c03](https://github.com/binary-husky/gpt_academic/assets/47667939/1c6a51f7-a273-49f8-b2e4-df5ca6370184)

**Comment by zzxcodelife** [comment]
> ![2f50d10f9389573c0fd0a1d2d3c5c03](https://user-images.githubusercontent.com/47667939/237593125-1c6a51f7-a273-49f8-b2e4-df5ca6370184.png)

没关系的，给你这么多额度，不是要扣这么多钱。

**Comment by 1251480932** [comment]
> > ![2f50d10f9389573c0fd0a1d2d3c5c03](https://user-images.githubusercontent.com/47667939/237593125-1c6a51f7-a273-49f8-b2e4-df5ca6370184.png)
> 
> 没关系的，给你这么多额度，不是要扣这么多钱。

她就帮我绑一个月的银行卡 然后就收回了 这个月我能使劲用到120 是我的本事 我是研一同校我可以给你分享一波

**Comment by 1251480932** [comment]
买的不限额的账号 就给一个月的使用期限 随便造 感觉你看到这个消息 应该是需要的 咱同校的 加我qq一起用 真用不了我白花钱了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月11日(星期四) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/gpt_academic] API key 的Free trial usage到期了，各位有什么解决方法吗 (Issue #227)





  

  
没关系的，给你这么多额度，不是要扣这么多钱。

**Comment by zzxcodelife** [comment]
> 买的不限额的账号 就给一个月的使用期限 随便造 感觉你看到这个消息 应该是需要的 咱同校的 加我qq一起用 真用不了我白花钱了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "binary-husky/gpt_academic" ***@***.***&gt;; 发送时间:&nbsp;2023年5月11日(星期四) 下午3:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [binary-husky/gpt_academic] API key 的Free trial usage到期了，各位有什么解决方法吗 (Issue #227) 没关系的，给你这么多额度，不是要扣这么多钱。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

谢谢，我有自己账号

**Comment by wkaiyun** [comment]
> 买的不限额的账号 就给一个月的使用期限 随便造 感觉你看到这个消息 应该是需要的 咱同校的 加我qq一起用 真用不了我白花钱了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "binary-husky/gpt_academic" ***@***.***&gt;; 发送时间:&nbsp;2023年5月11日(星期四) 下午3:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [binary-husky/gpt_academic] API key 的Free trial usage到期了，各位有什么解决方法吗 (Issue #227) 没关系的，给你这么多额度，不是要扣这么多钱。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

能给我用用吗？

**Comment by formoree** [comment]
> 买的不限额的账号 就给一个月的使用期限 随便造 感觉你看到这个消息 应该是需要的 咱同校的 加我qq一起用 真用不了我白花钱了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "binary-husky/gpt_academic" ***@***.***&gt;; 发送时间:&nbsp;2023年5月11日(星期四) 下午3:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [binary-husky/gpt_academic] API key 的Free trial usage到期了，各位有什么解决方法吗 (Issue #227) 没关系的，给你这么多额度，不是要扣这么多钱。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
求一个

**Comment by BNTang** [comment]
> 买的不限额的账号 就给一个月的使用期限 随便造 感觉你看到这个消息 应该是需要的 咱同校的 加我qq一起用 真用不了我白花钱了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "binary-husky/gpt_academic" ***@***.***&gt;; 发送时间:&nbsp;2023年5月11日(星期四) 下午3:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [binary-husky/gpt_academic] API key 的Free trial usage到期了，各位有什么解决方法吗 (Issue #227) 没关系的，给你这么多额度，不是要扣这么多钱。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

可以给我用用吗

**Comment by qcgm1978** [comment]
> 隐身模式就是隐私窗口。好像现在停止注册新账号了？

需要填邀请码？

**Comment by AlisonIsAnArtist** [comment]
> 我找了一个在国外的朋友绑卡，api不太贵，比plus便宜多了去了

没错，现在感觉曾经买过一个月plus的自己是傻瓜/(ㄒoㄒ)/~~
