### ISSUE TITLE
[Feature Request]多会话、持久化支持，以及更好的长会话处理方式

### ISSUE THREAD

**Issue by HansBug** [binary-husky/gpt_academic#241]
如题：
* 可以考虑支持在gradio中开启多个tab，每个tab均有不同的会话
* 现有的会话状态可以通过gpt_log等方式进行持久化，并在下一次启动的时候再次加载
* 建议当因会话过长而导致api报错时，能提供一个partial remove的功能，只删除比较久远的而保留比较近的会话；或者也可以不清除会话，但只提交最近一段范围内的会话（对于个别比较重要的对话内容，可以让用户标记为important而强制保留），以确保可以持久使用，这样一来可以明显降低被迫reset带来的信息损失，这对读论文而言尤其重要（实际上的模式常常是翻译了好多段后，然后最终希望选取重要对话来做个总结，而现有的强制reset模式会打断这一过程）

**Comment by orientlee88** [comment]
确实非常需要这一功能。保留重要的信息，而不是为了重复获得这一信息再重复对话（有时候得不到相同的回复）。
