### ISSUE TITLE
能不能使用azure openai key?

### ISSUE THREAD

**Issue by Moss-qc** [binary-husky/gpt_academic#252]
代理服务器不够稳定，更麻烦的是给openai续费，还要个美国信用卡

非常好的应用，希望出更多的插件功能，谢谢

**Comment by binary-husky** [comment]
能详细说说吗，啥是azure openai key

**Comment by Moss-qc** [comment]
https://github.com/openai/openai-python#microsoft-azure-endpoints
这里有azure key和URL的使用示例
https://github.com/stulzq/azure-openai-proxy
后端代理转换azure key到openAI key

经过实际测试azure到openai有专线，调azure url比直接调openai响应快很多，
最关键的是省虚拟信用卡手续费

**Comment by binary-husky** [comment]
好的谢谢，我们调查下相关情况

**Comment by kotobuki09** [comment]
I also looking for the Azure OpenAPI key instead of the ChatGPT API key. Looking forward to this feature to updated

**Comment by binary-husky** [comment]
> I also looking for a solution with the Azure OpenAPI key instead of the ChatGPT API key. Looking forward to this feature to update

get, working on it

**Comment by kotobuki09** [comment]
I found out about this solution: [https://github.com/haibbo/cf-openai-azure-proxy](url)
This required: a custom API domain and an Azure API key. I think it's reduced the modification in the code!

**Comment by kotobuki09** [comment]
I try to use the azure openai key by changing the API key and URL. After removing the verify openai key, I still got this issue and I couldn't find where in the code giving this. Do anyone been successful in doing so?

缺少api_key。

    临时解决方案：直接在输入区键入api_key，然后回车提交。

    长效解决方案：在config.py中配置。

**Comment by kn1ghtjay** [comment]
感谢作者 同求！！

**Comment by JoWooShin** [comment]
我也出现了同样的问题。测试别的开源程序都可以直接在openai的api上填写azure openai的key，然后输入cf代理的地址就可以直接访问openai，但是非常需要学术这个，希望作者可以帮忙。

**Comment by JoWooShin** [comment]
我是按这个网站的操作步骤进行的。https://www.evlit.com/65478.html
