### ISSUE TITLE
Nginx 该如何配置Location？

### ISSUE THREAD

**Issue by LisnXy** [binary-husky/gpt_academic#267]
我的服务器端口绑定在`10002`这是我当前的配置，我通过该配置可以正常使用
```bash
location / {
  proxy_pass http://127.0.0.1:10002/;
}
```
因为服务器上还有其他服务需要占用`/`路径，我试图将该应用的路径更改为`/academic`我将配置文件修改到如下:
```bash
location /academic/ {
  proxy_pass http://127.0.0.1:10002/;
}
```
完成如上修改后，应用无法正常访问，页面显示正在loading，且没有图片资源：
![image](https://user-images.githubusercontent.com/53891402/229344653-6826a29c-565a-4a3d-b7a6-ca9f65bce574.png)

求助，一下午没搞明白。

**Comment by binary-husky** [comment]
Nginx配置建议看下wiki

**Comment by Li-colonel** [comment]
我的也是一样，如果使用二级的网址，就会这样。
查看浏览器被告知：
![image](https://github.com/binary-husky/gpt_academic/assets/80799130/c2badeae-aabc-4656-8546-817e60aa4712)
Chatgpt这样说：
另一个可能的问题是，如果您的应用程序中嵌入了某些资源，如图片、CSS样式表或JavaScript文件，并且这些资源并没有使用相对路径引用，那么它们就只能请求原始主机名上的这些资源，而不是反向代理服务器上的资源。解决这个问题的方法是将这些资源的绝对路径更改为相对路径，或者在反向代理服务器上使用配置指令将这些资源映射到正确的位置。
我猜测就是如此。

**Comment by Li-colonel** [comment]
> 我的也是一样，如果使用二级的网址，就会这样。 查看浏览器被告知： ![image](https://user-images.githubusercontent.com/80799130/243647817-c2badeae-aabc-4656-8546-817e60aa4712.png) Chatgpt这样说： 另一个可能的问题是，如果您的应用程序中嵌入了某些资源，如图片、CSS样式表或JavaScript文件，并且这些资源并没有使用相对路径引用，那么它们就只能请求原始主机名上的这些资源，而不是反向代理服务器上的资源。解决这个问题的方法是将这些资源的绝对路径更改为相对路径，或者在反向代理服务器上使用配置指令将这些资源映射到正确的位置。 我猜测就是如此。

我看到了，就在config.py文件底部
![image](https://github.com/binary-husky/gpt_academic/assets/80799130/8afc644d-82b3-431e-ac34-937b3e4201c3)

**Comment by huapingchen** [comment]
请参考下面nginx.conf 解决方向代理问题：
https://huggingface.co/spaces/radames/nginx-gradio-reverse-proxy/blob/main/nginx.conf

location / {
--
  |# Serve GRADIO 7860
   proxy_pass http://localhost:xxx; //port number
   proxy_http_version 1.1;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection 'upgrade';
   proxy_set_header Host $host;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_cache_bypass $http_upgrade;
   proxy_read_timeout 86400;
   proxy_redirect off;
   }

**Comment by Li-colonel** [comment]
> 请参考下面nginx.conf 解决方向代理问题： https://huggingface.co/spaces/radames/nginx-gradio-reverse-proxy/blob/main/nginx.conf
> 
> ## location / {
>   |# Serve GRADIO 7860   proxy_pass http://localhost:xxx; //port number   proxy_http_version 1.1;   proxy_set_header Upgrade $http_upgrade;   proxy_set_header Connection 'upgrade';   proxy_set_header Host $host;   proxy_set_header X-Real-IP $remote_addr;   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;   proxy_cache_bypass $http_upgrade;   proxy_read_timeout 86400;   proxy_redirect off;   }



> 请参考下面nginx.conf 解决方向代理问题： https://huggingface.co/spaces/radames/nginx-gradio-reverse-proxy/blob/main/nginx.conf
> 
> ## location / {
>   |# Serve GRADIO 7860   proxy_pass http://localhost:xxx; //port number   proxy_http_version 1.1;   proxy_set_header Upgrade $http_upgrade;   proxy_set_header Connection 'upgrade';   proxy_set_header Host $host;   proxy_set_header X-Real-IP $remote_addr;   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;   proxy_cache_bypass $http_upgrade;   proxy_read_timeout 86400;   proxy_redirect off;   }

这并不能解决反代工作在二级路径的情况。
