### ISSUE TITLE
打开页面是白板，请问有什么解决方法么？

### ISSUE THREAD

**Issue by xiaozhangyongqin** [binary-husky/gpt_academic#269]

**Comment by GHGluck** [comment]
遇到同样的问题，代理配置没问题，打开的网页是空白的

**Comment by chennanlei** [comment]
自动弹出的网页打不开，不知道什么原因。代理配置没问题，终端也显示没问题，但网页加载不出来

**Comment by Waston12** [comment]
我也有相同的问题

**Comment by 972063175** [comment]
我以为只有我一个人这样

**Comment by 972063175** [comment]
> 我也有相同的问题

刚刚试了试虽然是白板本地打不开，但是可以用公网ip换个电脑打开

**Comment by Waston12** [comment]
我的问题解决了，我最后发现是代理节点的问题，我换了一个之后就好了，有可能是代理延迟太高

**Comment by xiaozhangyongqin** [comment]
> 我的问题解决了，我最后发现是代理节点的问题，我换了一个之后就好了，有可能是代理延迟太高
感谢 好像是的 延迟太高
