### ISSUE TITLE
采用PyInstaller打包成可执行文件运行不了

### ISSUE THREAD

**Issue by Saltsmart** [binary-husky/gpt_academic#278]
如果能像jupyter notebook一样双击执行，则会方便很多！
（Windows ）

- 采用PyInstaller可以打包，但执行main.exe后没有任何反应
- 创建快捷方式调用python执行，界面也是一闪而过。快捷方式配置如下：

![image](https://user-images.githubusercontent.com/40828952/229393628-e177ec87-278b-481b-a5ac-db98c8f00fef.png)
目标是：`C:\ProgramData\Anaconda3\python.exe E:\chatgpt_academic\main.py`
起始位置选`E:\chatgpt_academic`和`C:\ProgramData\Anaconda3`都不对

* * *
系统环境：
Python：3.9.16
OS: Windows_NT x64 10.0.19045

**Comment by ynwessnso** [comment]
同样 使用PyInstaller打包后，运行main.exe报错。
使用python main.py,运行正常。想让程序后台运行，使用pythonw main.py，没有任何反应。网址也打不开，估计是运行中出错了
![QQ截图20230403170424](https://user-images.githubusercontent.com/19602114/229464543-fc4be80c-5298-407c-bee1-6d259b618ef0.jpg)

**Comment by binary-husky** [comment]
我估计和函数插件的热加载有关

**Comment by Saltsmart** [comment]
## 针对[version 3.2](https://github.com/binary-husky/gpt_academic/releases/tag/version3.2)
1. 目前快捷方式运行已经成功，按照以上方法即可
2. 使用`pythonw main.py`无console运行，以及PyInstaller打包还是不成功

3. 我尝试注释掉所有热加载模块，包括：
  
     a.  `toolbox.py`内的`HotReload`装饰器，对应调用这个装饰器的`crazy_functional.py`内均换成调用原来的函数
     b. `request_llm/bridge_chatglm.py`、`request_llm/bridge_tgui.py`、`request_llm/bridge_chatgpt.py`各有一句` importlib.reload(core_functional)    # 热更新prompt`也相应注释掉了

但仍然不成功，可能证明这个问题和热更新（热加载？）无关
