### ISSUE TITLE
[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由，拒绝服务.

### ISSUE THREAD

**Issue by youthkiss** [binary-husky/gpt_academic#279]
普通的网页对话现在也开始要收费了吗？

**Comment by kongyan66** [comment]
好像是被封了

**Comment by youthkiss** [comment]
> 

我看好像是免费18刀的额度到期了，前天还是可以正常调用的

**Comment by kongyan66** [comment]
我也是昨天过期的 要么购买套餐 要么注册一个新账号吧 不知道还有啥解决方案呢

**Comment by DotWang** [comment]
新建一个key就行了

**Comment by youthkiss** [comment]
> 新建一个key就行了

试过了，不行

**Comment by DotWang** [comment]
> > 新建一个key就行了
> 
> 试过了，不行

好吧，我是前天搞的key，也没玩几下，昨天就不能用了说让充值，刚才新建了一个又好了

**Comment by molu-ggg** [comment]
> > > 新建一个key就行了
> > 
> > 
> > 试过了，不行
> 
> 好吧，我是前天搞的key，也没玩几下，昨天就不能用了说让充值，刚才新建了一个又好了

是新建key吗

**Comment by DotWang** [comment]
> > > > 新建一个key就行了
> > > 
> > > 
> > > 试过了，不行
> > 
> > 
> > 好吧，我是前天搞的key，也没玩几下，昨天就不能用了说让充值，刚才新建了一个又好了
> 
> 是新建key吗

是的
![image](https://user-images.githubusercontent.com/35402675/229404635-98550c7c-2ab9-4e83-8b7e-566570b50036.png)

**Comment by zhoouzhe** [comment]
我也试了新建一个key，也不行

**Comment by DotWang** [comment]
稍微细说一下，就是昨天不能用以后，我没有第一时间新建key，而是按照网上的教程向openai充点钱，然而那钱一直在结算，并没有真正到账，openai官网上也没有充值记录，哪怕是今天上午不换key之前还是不能用，然而当我新建了key，config文件中的key也相应更新，重新启动`chatgpt_academic`，就可以了，所以我认为应该还是新key的原因，而不是因为充值

**Comment by adrianzzk** [comment]
> 

openai不是说了吗，那5刀是预扣款，到月底结算，多退少补

**Comment by DotWang** [comment]
> > > > 
> > > 
> > > 
> > > openai不是说了吗，那5刀是预扣款，到月底结算，多退少补
> > 
> > 
> > 是的，你是对的，所以能用的原因是 绑卡+新建key 了 ![image](https://user-images.githubusercontent.com/35402675/229475614-0dd8b7cf-ff8a-4f3a-93cd-988e6837b177.png)
> 
> 没有国外的卡，真难受，感觉直接用不了了

网上充值教程一大把，我是okex+depay，dddd

**Comment by dog-master** [comment]
> 
我的拒绝绑卡啊

**Comment by chengdashia** [comment]
现在怎么解决啊

**Comment by ZCyueternal** [comment]
> 蹲一个除了绑定卡充值以外的解决方案

蹲

**Comment by jkhcc11** [comment]
![2000$](https://user-images.githubusercontent.com/28553032/232950987-573add7a-9cb6-473c-b9f6-e746fe4e3d32.png)
直接买个这种大额的吧，小几百吧  唉！

**Comment by jkhcc11** [comment]
> > ![2000$](https://user-images.githubusercontent.com/28553032/232950987-573add7a-9cb6-473c-b9f6-e746fe4e3d32.png) 直接买个这种大额的吧，小几百吧 唉！
> 
> Hi 我想请问一下怎么买的大额账号？ 如果可以的话请到我的任意一个repo底下提issue教教我

我也是找别人买的，那人Q：1549930804。如有需要可以联系他。

**Comment by binary-husky** [comment]
> > > ![2000$](https://user-images.githubusercontent.com/28553032/232950987-573add7a-9cb6-473c-b9f6-e746fe4e3d32.png) 直接买个这种大额的吧，小几百吧 唉！
> > 
> > 
> > Hi 我想请问一下怎么买的大额账号？ 如果可以的话请到我的任意一个repo底下提issue教教我
> 
> 我也是找别人买的，那人Q：1549930804。如有需要可以联系他。

目前项目已经支持[api2d](https://api2d.com/)，没有优质梯子的、想尝鲜gpt-4的可以试试

**Comment by Karenina-na** [comment]
![image](https://user-images.githubusercontent.com/95676643/234344556-e0b1e67d-fcc1-415d-9789-90a1ba618176.png)
我的新号新key都不行

**Comment by 1251480932** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/47667939/92ff2e63-041d-476d-aeea-3278405dcf77)
冲动消费了 来人平摊一下  就一个月时间 120额度  私我联系方式 给sk

**Comment by Achellesphi** [comment]
> ![image](https://user-images.githubusercontent.com/47667939/237592192-92ff2e63-041d-476d-aeea-3278405dcf77.png) 冲动消费了 来人平摊一下 就一个月时间 120额度 私我联系方式 给sk

麻烦加我Q 1053538739 我想要sk

**Comment by forbruce** [comment]
蹲一个可以不绑卡充值的法子

**Comment by yubanmeiqinQAQ** [comment]
> > > > ![2000$](https://user-images.githubusercontent.com/28553032/232950987-573add7a-9cb6-473c-b9f6-e746fe4e3d32.png) 直接买个这种大额的吧，小几百吧 唉！
> > > 
> > > 
> > > Hi 我想请问一下怎么买的大额账号？ 如果可以的话请到我的任意一个repo底下提issue教教我
> > 
> > 
> > 我也是找别人买的，那人Q：1549930804。如有需要可以联系他。
> 
> 目前项目已经支持[api2d](https://api2d.com/)，没有优质梯子的、想尝鲜gpt-4的可以试试

试了下，还是不行，呜呜。。。

**Comment by binary-husky** [comment]
> > > > > ![2000$](https://user-images.githubusercontent.com/28553032/232950987-573add7a-9cb6-473c-b9f6-e746fe4e3d32.png) 直接买个这种大额的吧，小几百吧 唉！
> > > > 
> > > > 
> > > > Hi 我想请问一下怎么买的大额账号？ 如果可以的话请到我的任意一个repo底下提issue教教我
> > > 
> > > 
> > > 我也是找别人买的，那人Q：1549930804。如有需要可以联系他。
> > 
> > 
> > 目前项目已经支持[api2d](https://api2d.com/)，没有优质梯子的、想尝鲜gpt-4的可以试试
> 
> 试了下，还是不行，呜呜。。。

[第三方API‐KEY接入指南](https://github.com/binary-husky/gpt_academic/wiki/%E7%AC%AC%E4%B8%89%E6%96%B9API%E2%80%90KEY%E6%8E%A5%E5%85%A5%E6%8C%87%E5%8D%97)
