### ISSUE TITLE
可否添加对manuscript全文 (.pdf或.doc格式）进行润色的功能？

### ISSUE THREAD

**Issue by Ford666** [binary-husky/gpt_academic#294]
目前已有上传pdf进行内容分析，并回答任何提问的功能，类似于chatpdf，请问作者是否可以添加对pdf或者word格式的manuscript全文进行润色（润色后手稿提供下载）的功能？不知道通过chatgpt API是否能满足这个需求

**Comment by binary-husky** [comment]
持续开发，正在尝试

**Comment by Microbion** [comment]
可以用这个工具 http://trinka.enago.cn/  ，上传word会帮助你润色，完成后下载

**Comment by Ford666** [comment]
> 持续开发，正在尝试

好的，辛苦了，很棒的学术工具！

**Comment by Ford666** [comment]
> 可以用这个工具 http://trinka.enago.cn/ ，上传word会帮助你润色，完成后下载

谢谢你的推荐，看评价还挺好的！
