### ISSUE TITLE
能否做一个Windows客户端的？

### ISSUE THREAD

**Issue by fengzhiku123** [binary-husky/gpt_academic#315]
能否做一个Windows客户端的？

**Comment by earth-5G** [comment]
zhichi支持，支持！现在这个配置太过于反锁了！

**Comment by Xu-Jam** [comment]
支持

**Comment by binary-husky** [comment]
想做，但是没经验

**Comment by wozaitianwai** [comment]
试着再用embed做个简易的打包环境py 3.11.2 embed版总是有各种打包有问题，有低版本的python安装的么，我晚上切换个版本再试试

**Comment by earth-5G** [comment]
> 试着再用embed做个简易的打包环境py 3.11.2 embed版总是有各种打包有问题，有低版本的python安装的么，我晚上切换个版本再试试

功德无量！

**Comment by wozaitianwai** [comment]
> > 试着再用embed做个简易的打包环境py 3.11.2 embed版总是有各种打包有问题，有低版本的python安装的么，我晚上切换个版本再试试
> 
> 功德无量！
main.py需要修改下
揉了个python3.10，还是需要自己手动配置下config里的key和代理，然后".\chatgpt_academic\环境配置文件及说明\Start.bat"能一键启动，这样可以同步git
下面是懒人包指引
 https://cowtransfer.com/s/ee37714530c142 点击链接查看 [ Chatgpt_academic.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 fo87j0 查看；

**Comment by earth-5G** [comment]
> 

感谢！

**Comment by sunchongwei** [comment]
我做了个网页版的，需要填自己的key：http://193.134.209.143:2622/

**Comment by earth-5G** [comment]
> 我做了个网页版的，需要填自己的key：http://193.134.209.143:2622/

体验了一下，还可以，弄个靠谱的域名，然后适当的收费也是可以的！

**Comment by Harry67Hu** [comment]
> > 我做了个网页版的，需要填自己的key：http://193.134.209.143:2622/
> 
> 体验了一下，还可以，弄个靠谱的域名，然后适当的收费也是可以的！

收费的话恐怕需要谨慎考虑，如果商业化的话必须要遵守GPL协议，否则后果很严重

**Comment by yhqgege** [comment]
支持博主开发成客户端比较好，谢谢

**Comment by drq1024** [comment]
> 我做了个网页版的，需要填自己的key：http://193.134.209.143:2622/

请问key是什么呀，怎么获取呢

**Comment by sunchongwei** [comment]
> > 我做了个网页版的，需要填自己的key：http://193.134.209.143:2622/
> 
> 请问key是什么呀，怎么获取呢

登录：https://platform.openai.com/account/usage  在右上角Personal 里选择API KEY，进入之后创建自己的key

**Comment by PeterBilly** [comment]
可以用Edge登录网页版的页面然后生成一个网页应用？感觉体验接近windows客户端
