### ISSUE TITLE
 "message": "Invalid URL (POST /v1/chat/completions)",

### ISSUE THREAD

**Issue by gaorui0** [binary-husky/gpt_academic#318]
{
  "error": {
    "message": "Invalid URL (POST /v1/chat/completions)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by Univercp** [comment]
me too ,the issue is that , annybody can fix it ?

**Comment by Clarence-Feng** [comment]
同样遇到这个问题，请问有人知道如何解决吗？
