### ISSUE TITLE
按照教程命令docker运行后只有容器内部能访问到，宿主机访问不了

### ISSUE THREAD

**Issue by miku8miku** [binary-husky/gpt_academic#32]
加入映射也不行，求指导
![image](https://user-images.githubusercontent.com/52441374/228127491-d3b5ddc0-0d2a-49f2-896d-cd94c8ff9202.png)
![image](https://user-images.githubusercontent.com/52441374/228127572-2f8ef4d1-8c35-4ac3-a4b8-922459a8d558.png)

**Comment by binary-husky** [comment]
是windows下的docker吧？
windows docker的网络配置和linux不一样，这是关键

要麻烦一点，
首先吧--net=host去掉，
然后-v 12345:12345指定端口映射，
最后config.py中WEB_PORT=12345改成你映射的端口
