### ISSUE TITLE
【新功能请求】联网搜索paper功能

### ISSUE THREAD

**Issue by cmcccopy** [binary-husky/gpt_academic#325]
希望能链接 谷歌学术 进行更准确，更多样化的学术搜索功能。

**Comment by binary-husky** [comment]
详细说说你的想法？

**Comment by longfuxu** [comment]
插个话：现在可以对本地pdf进行批量总结，赞！
可否通过搜索关键词、指定作者等方式定期追踪某一个领域的文章，然后通过semantic，biorxiv或google scholar或者其他开放API的数据库搜索，搜索后通过自己的学校代理下载，然后进行分析总结。
这样可以，比如每周一次，追踪本领域的文章，然后就得到这个领域的最新进展？
这个repo做的是机器学习方面【https://github.com/kaixindelele/ChatPaper】，但是很多生物学或化学领域的文章并没有在Arxiv 里。
希望考虑，谢谢

**Comment by binary-husky** [comment]
哪个源质量更高一点呢？cs领域感觉paper with code更好一点
https://paperswithcode.com/search?q_meta=&q_type=&q=reinforcement+learning

**Comment by binary-husky** [comment]
google scholar也应该也好办

**Comment by cmcccopy** [comment]
> 插个话：现在可以对本地pdf进行批量总结，赞！ 可否通过搜索关键词、指定作者等方式定期追踪某一个领域的文章，然后通过semantic，biorxiv或google scholar或者其他开放API的数据库搜索，搜索后通过自己的学校代理下载，然后进行批量分析总结。然后建议在总结的时候可以再详细一些，现在有些简单。 这样可以，比如每周一次，追踪本领域的文章，比如生物、化学等实验性科目，然后就得到这个领域的最新进展？如果可以自动推送到邮件或手机上就更赞了，哈哈哈 这个repo做的是机器学习方面【[https://github.com/kaixindelele/ChatPaper】](https://github.com/kaixindelele/ChatPaper%E3%80%91) 希望考虑，谢谢

这个想法比我想得要好，不过追踪某个领域的最新进展，自动推送到邮件或手机上，这个可能要服务器支持，不如添加一个“获取最新研究”按钮，重新搜索一遍数据，找出最新的，然后可以选择论文下载，并使用gpt总结。

**Comment by longfuxu** [comment]
个人认为google scholar受益面/覆盖面可能会广一些，因为各个领域，即使是preprint上也可以及时索引到。通过“获取最新研究”按钮，这样在研究的各个阶段，即使刚开始或到最后阶段都可以去跟踪这个领域的变化。
大概步骤： 特定关键词搜索-》filter一部分文献，或根据数据库-〉下载-》gpt总结
