### ISSUE TITLE
有意思的BUG，貌似如果开启了Edge的微软自动翻译，那么就无法发送第二句。会无反应

### ISSUE THREAD

**Issue by White208** [binary-husky/gpt_academic#327]
**Describe the bug 简述**

貌似如果开启了Edge的微软自动翻译，那么就无法发送第二句。会无反应

**Screen Shot 截图**

![1](https://user-images.githubusercontent.com/100404913/230019299-14738644-3e3a-42e1-a1fe-c5114eeb4136.png)
![2](https://user-images.githubusercontent.com/100404913/230019342-6fd20708-5bb2-4a2a-ba7c-9a9dd5a1b3b1.png)

**Comment by binary-husky** [comment]
这是为啥呀

**Comment by White208** [comment]
> 这是为啥呀

不清楚，我是通过git2.34加Python3.11，加安装依赖的选择一，WIN10来运行。
不影响使用，
不过要是有人开了自动翻译，可能会搞不明白为啥用不了。

**Comment by White208** [comment]
> 这是为啥呀

**Comment by White208** [comment]
> 这是为啥呀

不清楚，我是通过git2.34加Python3.11，加安装依赖的选择一，WIN10来运行。
不影响使用，
不过要是有人开了自动翻译，可能会搞不明白为啥用不了。

PS：这个Open，close选择逻辑好奇怪，点错好几次
