### ISSUE TITLE
支持所有编程语言的项目解析

### ISSUE THREAD

**Issue by XixuHu** [binary-husky/gpt_academic#330]
您好，请问为什么分析整个文件夹的功能仅限于C++和python呢？请问为什么不能支持所有的编程语言？（来自一个想要学习前后端的人）

**Comment by binary-husky** [comment]
简单来说，我们不熟悉其他语言，更像把这个交给学过这些语言的人去做。

我们认为每种语言应该有其独特的处理方式，只有经常使用这语言的人，才能把这个搞好。

目前已经有这些编程语言的PR，都已经以高优先级merge了

![image](https://user-images.githubusercontent.com/96192199/230094220-79f4ca90-be7c-46a3-8201-5bb22402c48f.png)
