### ISSUE TITLE
直接使用英文进行“解析整个Py项目“及类似请求

### ISSUE THREAD

**Issue by ww2283** [binary-husky/gpt_academic#333]
首先感谢作者提供如此好用的项目。
我想问一下，有没有选项能够直接显示出英文的GPT回答。目前来说，如果使用“解析整个Py项目“，我看到的是中文的解释。如果我想要直接显示英文的解释，应该如何配置呢？目前我没有在WIKI中找到如何设置。还望指点。

**Comment by binary-husky** [comment]
这太简单了，把https://github.com/binary-husky/chatgpt_academic/blob/master/crazy_functions/%E8%A7%A3%E6%9E%90%E9%A1%B9%E7%9B%AE%E6%BA%90%E4%BB%A3%E7%A0%81.py脚本里面的中文指令替换成英文的就行
