### ISSUE TITLE
[RFC] 根据设备自适应调整chatbox高度

### ISSUE THREAD

**Issue by lxg199788** [binary-husky/gpt_academic#339]
挂载在服务器上，有小伙伴用手机访问。如果是默认高度，手机上chatbox高度非常高，需要下拉很久，使用不方便；如果修改为适应手机的高度，电脑上chatbox高度又不足。请求添加一个自适应高度的功能

**Comment by binary-husky** [comment]
一直想办法弄这个，但gradio没查到类似的功能，谁有solution@我一下

**Comment by binary-husky** [comment]
@lxg199788 已添加动态chatbot高度调整功能
