### ISSUE TITLE
希望解析项目源码功能优化

### ISSUE THREAD

**Issue by JiangshuoZhao** [binary-husky/gpt_academic#340]
希望能对解析项目源码功能进一步优化。我发现当上传的项目有多级目录时，会报错。希望可以改进一下。

**Comment by binary-husky** [comment]
我们测试没发现有问题？有测试样本可以提供吗？

**Comment by JiangshuoZhao** [comment]
抱歉，是我搞错原因了。问题应该是项目中有其他类型的文件时会报错。比如我选择解析c++项目，但上传的项目里面有py文件，会直接报错:
异常 ‘utf-8’ codec can’t decode byte 0xe7 in position 112: invalid continuation byte

可以自动跳过这些文件（py），或者根据文件类型自动解析，因为有些项目不全是用一种语言写的。

**Comment by binary-husky** [comment]
如果源代码里面有非‘utf-8’编码的文件，需要处理成utf8才能读取
