### ISSUE TITLE
【在提交的PDF过长时，超时上限如何更改】

### ISSUE THREAD

**Issue by Zp121382** [binary-husky/gpt_academic#344]
在使用批量PDF功能时，只上传一个PDF，但是该PDF较大，会导致chat回复时间较长。所以修改哪个变量可以更改超时上限呀~

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/230433320-f3889be0-b6c8-46f4-b4c4-514875c94f9c.png)
