### ISSUE TITLE
一直在waiting gpt response

### ISSUE THREAD

**Issue by 962164845** [binary-husky/gpt_academic#347]
**Describe the bug 简述**
[Local Message] Warning! Input file is too long, cut into half. waiting gpt response 273/150.
一直在等待回应
**Screen Shot 截图**
<img width="979" alt="image" src="https://user-images.githubusercontent.com/74752331/230378587-f5450f27-767f-4c08-b7cc-86d0349c53a6.png">

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
网络不好，再碰上文本长的问题……
我们最近在不断改进界面的反馈，相信这类问题能很快解决
