### ISSUE TITLE
解析一个过大的项目最后的项目总结陷入循环无法停止

### ISSUE THREAD

**Issue by ylsislove** [binary-husky/gpt_academic#353]
**Describe the bug 简述**
我在解析一个前端项目，自己设置了只解析 `js、ts、css、scss` 这四种后缀类型的文件，最后得到292个文件待解析。

除了个别文件因为超过Token限制被部分截断外，文件的解析过程都算正常。但最后的总结部分感觉陷入了死循环，我去洗了个澡，回来就发现界面已经显示 `[Local Message] 警告，文本过长将进行截断，Token溢出数：4284，截断比例：54%。waiting gpt response 1067/150...`，但它还在不断的等待响应/捂脸，看控制台也一直在不断输出 `gpt-3.5-turbo : 292 : 根据以上你自己的分析，对程序的整体功能和构架做出概括。然后用一张markdown表格整理每个文件的功能（包括...此处省略一大段文件路径）。`，最后只能自己去控制台按 `Ctrl + C` 终止程序了。

最关键的是，没有生成分析报告啊/捂脸，去OpenAI后台看了下，本次分析消耗了1.53美元的额度，要是最后的总结报告分析不出来，能把前面生成的内容先持久化保存了也行，不然前面分析了这么久，突然一个界面崩溃就欲哭无泪了

**Screen Shot 截图**
![QQ截图20230406235433](https://user-images.githubusercontent.com/41816449/230434837-bc65512a-5d9c-4010-880a-18a26b09b438.png)
![QQ截图20230406235345](https://user-images.githubusercontent.com/41816449/230438983-600035cb-32c5-420c-8352-574582a5e81e.png)

**Terminal Traceback 终端traceback（如果有）**
![QQ截图20230407002402](https://user-images.githubusercontent.com/41816449/230439230-fdcc1dad-fefc-48aa-9704-d44a8528bcf9.png)

本次分析所使用的项目：
[src.zip](https://github.com/binary-husky/chatgpt_academic/files/11172601/src.zip)

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
好的

**Comment by binary-husky** [comment]
这个我们确实要改进

**Comment by binary-husky** [comment]
2.6版重构了多线程逻辑，专门针对这类问题，目前在测试阶段，过天更新
