### ISSUE TITLE
如何修改登录页面的文字和提示信息（启用了账号密码登录，部署在内网多人使用）

### ISSUE THREAD

**Issue by moxi000** [binary-husky/gpt_academic#364]
如题，本人将服务做了学术领域内的各种微调后，上传到了组里内网公用，请问如何修改登录页面的UI，或者是提示字符什么的

**Comment by KingMV** [comment]
> 如题，本人将服务做了学术领域内的各种微调后，上传到了组里内网公用，请问如何修改登录页面的UI，或者是提示字符什么的
main.py中的html字符中，可以自己插入相应的文字

**Comment by moxi000** [comment]
> 如题，本人将服务做了学术领域内的各种微调后，上传到了组里内网公用，请问如何修改登录页面的UI，或者是提示字符什么的
> main.py中的html字符中，可以自己插入相应的文字

我在main.py中没有找到相关的代码，也可能是我看漏了，可否给一下具体咋哪个位置？（上下文）

**Comment by binary-husky** [comment]
这个需要改gradio里面的代码了，这部分是依托gradio的功能
