### ISSUE TITLE
今天openAI对免费用户的调用频率限制 和 openAI的API调用费用

### ISSUE THREAD

**Issue by AJo07krate** [binary-husky/gpt_academic#369]
**请问openAI的API调用是要收费的嘛？**

![image](https://user-images.githubusercontent.com/32976633/230654458-840cb077-9fa2-44c3-894b-a35181cd3836.png)

**Comment by siran-CN** [comment]
可以到 https://platform.openai.com/overview 查看文档和收费标准

**Comment by kevin19971** [comment]
新号送18美元的api量（但有时间限制），没了就要自己充值了

**Comment by hansongtong** [comment]
> 



> 新号送18美元的api量（但有时间限制），没了就要自己充值了

这个要咋操作呢？老铁

**Comment by KingMV** [comment]
> 

支持visa的国际信用卡充值，每一条api调用费用为0.07美元

**Comment by binary-husky** [comment]
充api费用，或者用解码平台注册新号，再拿一波key

**Comment by ruiuuu-cry** [comment]
API调用一次是指什么意思，没打开一次学术版GPT是调用一次，还是说在GPT中每问一个问题就是调用一次？


> 

API调用一次是指什么意思，没打开一次学术版GPT是调用一次，还是说在GPT中每问一个问题就是调用一次？

**Comment by 15058415003** [comment]
按照token计算金额，gpt-3.5-turbo应该是每1000token0.002美元，每一次request消耗的token数可以在
https://platform.openai.com/account/usage
这个网址里查看

**Comment by jkhcc11** [comment]
可以用depay绑卡就行了，先扣5$然后，过7天会退款，这样就有120$的免费额度了。https://dwurl.cn/5fvnNS

**Comment by deepdarkfans** [comment]
> 可以用depay绑卡就行了，先扣5$然后，过7天会退款，这样就有120$的免费额度了。https://dwurl.cn/5fvnNS

这个要求用加密货币充值

**Comment by jkhcc11** [comment]
> > 可以用depay绑卡就行了，先扣5$然后，过7天会退款，这样就有120$的免费额度了。https://dwurl.cn/5fvnNS
> 
> 这个要求用加密货币充值

那没办法，现在也有只有这个稍微门槛第一点了。也可以找人帮忙充值就行,然后自己绑卡就行。我试过绑卡了,退余额。放心食用。

**Comment by deepdarkfans** [comment]
想问一下这个120刀不是免费额度吧，我绑卡之后说是每月最高120美刀的token量，超了18刀免费额度还是要扣钱的

破浪前行的一条鱼 ***@***.***>于2023年4月14日 周五17:22写道：

**Comment by jkhcc11** [comment]
> 

试过了么？免费额度现在只有5$ 那个120$没说啥时候扣么，反正我depay，没钱让它扣 哈哈哈哈哈

**Comment by jkhcc11** [comment]
> > > 
> > 
> > 
> > 试过了么？免费额度现在只有5$ 那个120$没说啥时候扣么，反正我depay，没钱让它扣 哈哈哈哈哈
> 
> 这个应该不是免费额度，只是每月最大使用量吧

得下个月才知道，我这个月刚绑的卡，还在用。要扣里面也没钱

**Comment by seekerhuang** [comment]
> > > > 
> > > 
> > > 
> > > 试过了么？免费额度现在只有5$ 那个120$没说啥时候扣么，反正我depay，没钱让它扣 哈哈哈哈哈
> > 
> > 
> > 这个应该不是免费额度，只是每月最大使用量吧
> 
> 得下个月才知道，我这个月刚绑的卡，还在用。要扣里面也没钱

https://juejin.cn/post/7223733256689451069这个链接里说 “目前chatGPT是每月结账一次，上限是120美金，如果结账的时候，卡里没钱扣，GPT应该会封你账号。”

**Comment by jkhcc11** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 试过了么？免费额度现在只有5$ 那个120$没说啥时候扣么，反正我depay，没钱让它扣 哈哈哈哈哈
> > > 
> > > 
> > > 这个应该不是免费额度，只是每月最大使用量吧
> > 
> > 
> > 得下个月才知道，我这个月刚绑的卡，还在用。要扣里面也没钱
> 
> [https://juejin.cn/post/7223733256689451069这个链接里说](https://juejin.cn/post/7223733256689451069%E8%BF%99%E4%B8%AA%E9%93%BE%E6%8E%A5%E9%87%8C%E8%AF%B4) “目前chatGPT是每月结账一次，上限是120美金，如果结账的时候，卡里没钱扣，GPT应该会封你账号。”

不准确，3月份的时候，我有几个号，到了4月份还可以继续用。

**Comment by 1251480932** [comment]
![2f50d10f9389573c0fd0a1d2d3c5c03](https://github.com/binary-husky/gpt_academic/assets/47667939/bfcb5bdb-e881-4f26-a1f1-9fd29f1c9730)
