### ISSUE TITLE
你们好首先感谢这么好的封装idea省了很多时间,我想咨询一下假设我已經开通了GPT-4,在config.py中如何进行更改？

### ISSUE THREAD

**Issue by AMSSWANGYIJIA** [binary-husky/gpt_academic#377]
因为我尝试更改LLM_model为gpt-4但是网页在提交之后会报错

**Comment by binary-husky** [comment]
已经通过了gpt-4 waitlist了吗？仅仅是plus会员是不行的。
可以把报错贴一下

**Comment by fengqiaogit** [comment]
![image](https://user-images.githubusercontent.com/15885479/231986659-68784d9f-f71c-4278-b2ce-8dcad41f4079.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/232049650-2e56464c-16a4-4a4a-a839-063b175f3f06.png)
这个你通过了？

**Comment by fengqiaogit** [comment]
我还没有申请[waitlist](https://openai.com/waitlist/gpt-4-api)，通过后我再尝试一下GPT-4。
