### ISSUE TITLE
不知为何，我这边部署好以后任何请求都是永远等待，没有任何反应。（人在海外，按道理应该不需要再配置代理了）

### ISSUE THREAD

**Issue by TangVarie** [binary-husky/gpt_academic#378]
**Describe the bug 简述**
如题所示
**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/129793361/230716267-b058e7da-797a-45e8-b006-0d778afb281e.png)

**Comment by TangVarie** [comment]
按钮也好，input也好，点击之后就是无限等待

**Comment by Nicoals-James** [comment]
你是不是用的是public url 进入的网页

**Comment by YSAA1** [comment]
> 你是不是用的是public url 进入的网页

我也是这个问题，输入几个问题后面就是无限等待，我这个网页是自动弹出来的，请问有什么办法解决吗

**Comment by ASH521** [comment]
同样问题
