### ISSUE TITLE
英文润色出现问题

### ISSUE THREAD

**Issue by hansongtong** [binary-husky/gpt_academic#379]
**Describe the bug 简述**英文润色 显示OpenAI以账户额度不足为由，拒绝服务.

**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/39651274/230722143-d1a4c1dc-f5d4-4c32-893f-276276e9eb8d.png)

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by KingMV** [comment]
你的open ai账户没钱了，需要用信用卡充值。注：每调用一次的开销为0.07美元，你账户初始赠送了18美元，现在全部使用完了
