### ISSUE TITLE
能否新增批量给作者发邮件要代码的功能

### ISSUE THREAD

**Issue by nickcao123456** [binary-husky/gpt_academic#384]
最近实现算法通常很难找到开源代码，通过上传想要批量发邮件的pdf论文路径，通过pdf内容判断文章的主要算法/模型，然后自动写英文邮件要代码(英文的回复率高一点 bushi)

**Comment by binary-husky** [comment]
6

**Comment by nickcao123456** [comment]
> 6，你这issue一看就很有故事😂

最近给十几个作者发了邮件，都没有回复，心态炸了。要代码只能海发邮件，看有没有一个回复的哈哈哈

**Comment by binary-husky** [comment]
> > 6，你这issue一看就很有故事😂
> 
> 最近给十几个作者发了邮件，都没有回复，心态炸了。要代码只能海发邮件，看有没有一个回复的哈哈哈

一般不回就是不想给😂 :-( 如果愿意分享的，那一般就github开源了
