### ISSUE TITLE
想问一下最新版本2.4中一键更新是什么意思，好像默认的是不能一键更新

### ISSUE THREAD

**Issue by nickcao123456** [binary-husky/gpt_academic#385]
**Describe the bug 简述**

**Screen Shot 截图**

**Terminal Traceback 终端traceback（如果有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
就是检查本地版本号和github版本号，如果github有新版本才会触发

**Comment by binary-husky** [comment]
希望之后有新版本之后能正常触发吧😂 不过不用担心，这部分程序独立于其他部分，不会影响程序主逻辑

**Comment by MR-D-CJ** [comment]
是下载最新版，然后重新配置吗
