### ISSUE TITLE
海外云服务器(基于阿里云)Linux和公网解决方案

### ISSUE THREAD

**Issue by EricChLee** [binary-husky/gpt_academic#386]
不是专业玩家，大概根据文科大佬https://github.com/binary-husky/chatgpt_academic/issues/374的调整的。
采用的是阿里云美国服务器和Linux Ubuntu服务器系统搭建
1. 海外阿里云可以通过学生验证获取一个轻量级(1核1G内存40G储存空间1M带宽)的云服务器，具体看这里https://www.alibabacloud.com/zh/developer/students （需要海外云，中国站不知道是否有海外服务器)
![image](https://user-images.githubusercontent.com/51077374/230743785-1421b585-16f0-41bd-bf9a-06efd5a610f0.png)
2. 申请需要审核，成功后会邮件通知，申请成功后配置服务器的过程参考这里: https://www.alibabacloud.com/help/doc-detail/163467.html 这里介绍的是基于ubuntu 22.0的版本，所以镜像选择的就是ubuntu。地址选择美国硅谷。
3. 然后就是登录控制台
![image](https://user-images.githubusercontent.com/51077374/230744201-16b925f3-8528-4d7c-8c5d-a0c1a0c3dc5b.png)

4. 然后就是进入服务器控制台，可能后续有些组件会提示你安装，安装就行。
![image](https://user-images.githubusercontent.com/51077374/230744251-7d373f99-9077-484d-818a-00c866199942.png)
5. 服务台里就这样子
![image](https://user-images.githubusercontent.com/51077374/230744420-4447d2a4-0ad0-456c-bbd0-8fa96f3974bc.png)
6.点击远程连接，使用默认选项，立即登录。
![image](https://user-images.githubusercontent.com/51077374/230744442-cfd6993f-5cc4-48f3-8173-8027f9644d19.png)
这里可能会需要输入登录ubuntu的用户名和密码，用户名默认为root，密码在配置的时候有要求设置过，具体参考这里:https://www.alibabacloud.com/help/zh/elastic-compute-service/latest/quick-start-for-linux-instances
登录后大概这样子
![image](https://user-images.githubusercontent.com/51077374/230744515-9d34d6fc-a20d-4776-9a56-e1fb592a9c3f.png)
7. 安装chatgpt_academic，直接git安装
git clone https://github.com/binary-husky/chatgpt_academic.git
cd chatgpt_academic（记得cd到文件夹)
9. 使用nano 命令进入config.py文件添加chatGPT API的key,具体看主页介绍https://github.com/binary-husky/chatgpt_academic
`nano config.py`
进入后添加API的key和修改访问端口（记住端口号，后面要添加到服务器设置中），然后按Ctrl+X,回车保存，这里按照项目推荐，最好直接保存为private_config.py。
同样的方式使用nano命令进入main.py文件，修改文件权限，修改跟这里一样https://github.com/binary-husky/chatgpt_academic/issues/374
都把最后一行中demo.queue(concurrency_count=CONCURRENT_COUNT).launch(server_name="0.0.0.0", share=True, server_port=PORT, auth=AUTHENTICATION), share=True改为False，另外根据个人需求，也可以修改一下System prompt的内容，这个对应的就是main.py中的这里:
![image](https://user-images.githubusercontent.com/51077374/230744856-d5c08b84-e714-4e58-be6a-8edbf160dc37.png)
11. 完成后可以使用下面的命令打开对应的端口（把5000替换成你在config.py中设置的端口)
`sudo ufw allow 5000/tcp`
12.这时候需要回到第5步的服务器控制台这里，点击实例的名称(第5步图中被涂红的那一大块)，进入实例详情
![image](https://user-images.githubusercontent.com/51077374/230745156-1d8cb350-247a-4c02-8174-cd9165e3f676.png)
点击安全组，再点击配置规则
![image](https://user-images.githubusercontent.com/51077374/230745192-6aed9cc6-01a1-4dee-ad8d-627350b7c8c5.png)
选择手动添加，端口写上你设置的端口
![image](https://user-images.githubusercontent.com/51077374/230745249-6e709462-695a-49fb-b0b7-423f32d63e41.png)
13. 下面就再次回到远程连接，进入系统，同样cd到chatgpt_academic文件夹内，使用nohup命令
`nohup python3 main.py`
就可以创建一个后台运行的访问系统，通过你的服务器的公网IP(第五步可以查询到)加上端口号就可以访问了
示例：公网IP为14.253.15.24，设置端口为5631则直接再浏览器输入14.253.15.24:5631访问。
14. 如何结束进程,需要结束进程的时候则使用命名`ps aux | grep main.py`搜索后台执行的PID，使用`kill PIDnumber`结束进程，调试阶段可以不用`nohup python3 main.py`命令，而直接使用`python3 main.py`这样子可以直接运行，使用Ctrl+C停止进程，这种情况下退出远程登录也会直接结束进程（时刻记得先cd到chatgpt_academic路径再运行）。

**Comment by RuSignalFlag** [comment]
直接docker不是更方便吗

**Comment by EricChLee** [comment]
> 

自学小白，对docker使用很不熟练，所以就没用docker，我也摸索一下，我看到你的里面有个[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)，感觉很好的样子，我要如何搬到我的云上面呢？

**Comment by RuSignalFlag** [comment]
@EricChLee 那个项目是我fork的，不用服务器可以直接一键部署，也可以部署在服务器上，国内服务器的话准备好代理和key，最简单的部署还是docker ，Google一下docker 官网，按照文档安装就几行命令，然后项目里readme 往下拉有docker部署的方案，docker run的时候填上你的代理和key还有访问密码啥的，直接运行就行，最后打开浏览器ip 加端口就可以访问了

**Comment by EricChLee** [comment]
@RuSignalFlag 多谢多谢，确实docker方便很多啊，已经部署了ChatGPT-Next-Web了。
![image](https://user-images.githubusercontent.com/51077374/230789563-213902ea-71ea-49d8-9801-e2b0fec1e011.png)
可以直接设置密码也是比较方便和安全的。

**Comment by Marfars** [comment]
如果希望在服务器上使用docker部署的话，可以参考以下步骤（其中前几点和master上的前几点都是一样的）：
1、在你的指定目录下执行
```Git
git clone https://github.com/binary-husky/chatgpt_academic.git
```
2、`cd chatgpt_academic`
3、将config.py的内容拷贝到config_private.py中（如果不需要设置自己的config，可忽略）
``` shell
cp config.py config_private.py
```
4、根据master指引，修改自己的配置，分别是以下几项：
```Python
# Your Key是自己的api key，此处位于第二行
API_KEY = "Your Key"

# 由于我是国外的服务器，所以USE_PROXY设置的是false，即默认值未做修改
USER_PROXY = False

# 修改自己的暴露端口，我选的是443，此处位于37行
WEB_PROT = 443
```
5、**可选，修改镜像源**  国外服务器访问DockerFile里的阿里镜像可能会慢，所以我去掉了其对镜像源的指定，如果也需要取消，可参考以下步骤：首先确保自己位于chatgpt_academic目录下，执行命令```vim Dockerfile```，删除3~5行的内容，结果如下
```Dockerfile
FROM python:3.11
  
WORKDIR /gpt
COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY . .

CMD ["python3", "-u", "main.py"]
```
6、打包Docker镜像，和master教程一致，命令为：
```
docker build -t gpt-academic .
```
7、运行Docker镜像，使用以下命令：
```Shell
# --name可选，是给容器起的名字，-d是为了让他后台运行，443:443是为了把端口暴露出去
# 请确保暴露的端口telnet的通，同时此端口没有其他服务运行
docker run -itd --name chat -p 443:443 gpt-academic
```
8、**可选 如果要更新怎么办**  比如说key要换，或者某个配置错了，可以修改文件之后，按照第六步打一个新包，然后执行以下三条命令：
```
# 暂停原容器，如果没有设置名字，那这里的chat就用gpt-academic
docker stop chat

# 删除原容器，如果没有设置名字，那这里的chat就用gpt-academic
docker rm chat

# 重新执行第七步的命令
docker run -itd --name chat -p 443:443 gpt-academic
```

**Comment by gysabc** [comment]
> 

请问这个需要重新注册吗，我在注册的时候发现没有中国，只有中国香港啥的

**Comment by EricChLee** [comment]
> 

这个没注意到啊，是注册账号阶段吗？不记得了，要不发个截图看看。

**Comment by gysabc** [comment]
> > 
> 
> 这个没注意到啊，是注册账号阶段吗？不记得了，要不发个截图看看。
 
![1](https://user-images.githubusercontent.com/68911920/233064600-1479166c-1b5b-4a39-b58f-55ac3435b4a0.png)

![2](https://user-images.githubusercontent.com/68911920/233064704-aab1879a-dfaf-4d1e-8579-ce5de797e980.png)

![3](https://user-images.githubusercontent.com/68911920/233064741-8aca59e7-a247-48a7-8aff-cb4617f34993.png)

![4](https://user-images.githubusercontent.com/68911920/233064778-ca82dc40-3a28-47f1-9384-515e21c9262e.png)

如最后一张图所示，在选择国家的地方，没有中国大陆

**Comment by gysabc** [comment]
> > 
> 
> 这个没注意到啊，是注册账号阶段吗？不记得了，要不发个截图看看。

但是我在阿里云中国站控制台厘米看到有海外服务器可以购买

**Comment by gysabc** [comment]
> > > 
> > 
> > 
> > 这个没注意到啊，是注册账号阶段吗？不记得了，要不发个截图看看。
> 
> 但是我在阿里云中国站控制台厘米看到有海外服务器可以购买

但是中国站免费试用的服务器在国内。。。。

**Comment by EmanuellaS826** [comment]
> > > > 
> > > 
> > > 
> > > 这个没注意到啊，是注册账号阶段吗？不记得了，要不发个截图看看。
> > 
> > 
> > 但是我在阿里云中国站控制台厘米看到有海外服务器可以购买
> 
> 但是中国站免费试用的服务器在国内。。。。

这个方案需要阿里云海外账户，直接注册海外阿里云需要地区选国外，且需要国外手机号接收验证码，然而SMS-Activate这样的平台上并没有针对阿里云海外注册开通的虚拟收码业务...

**Comment by yanlc-1** [comment]
怎么绑定域名呢，有自己的域名，不想用ip+端口

**Comment by abandon-alt** [comment]
> 如果希望在服务器上使用docker部署的话，可以参考以下步骤（其中前几点和master上的前几点都是一样的）： 1、在你的指定目录下执行
> 
> ```
> git clone https://github.com/binary-husky/chatgpt_academic.git
> ```
> 
> 2、`cd chatgpt_academic` 3、将config.py的内容拷贝到config_private.py中（如果不需要设置自己的config，可忽略）
> 
> ```shell
> cp config.py config_private.py
> ```
> 
> 4、根据master指引，修改自己的配置，分别是以下几项：
> 
> ```python
> # Your Key是自己的api key，此处位于第二行
> API_KEY = "Your Key"
> 
> # 由于我是国外的服务器，所以USE_PROXY设置的是false，即默认值未做修改
> USER_PROXY = False
> 
> # 修改自己的暴露端口，我选的是443，此处位于37行
> WEB_PROT = 443
> ```
> 
> 5、**可选，修改镜像源** 国外服务器访问DockerFile里的阿里镜像可能会慢，所以我去掉了其对镜像源的指定，如果也需要取消，可参考以下步骤：首先确保自己位于chatgpt_academic目录下，执行命令`vim Dockerfile`，删除3~5行的内容，结果如下
> 
> ```dockerfile
> FROM python:3.11
>   
> WORKDIR /gpt
> COPY requirements.txt .
> RUN pip3 install -r requirements.txt
> 
> COPY . .
> 
> CMD ["python3", "-u", "main.py"]
> ```
> 
> 6、打包Docker镜像，和master教程一致，命令为：
> 
> ```
> docker build -t gpt-academic .
> ```
> 
> 7、运行Docker镜像，使用以下命令：
> 
> ```shell
> # --name可选，是给容器起的名字，-d是为了让他后台运行，443:443是为了把端口暴露出去
> # 请确保暴露的端口telnet的通，同时此端口没有其他服务运行
> docker run -itd --name chat -p 443:443 gpt-academic
> ```
> 
> 8、**可选 如果要更新怎么办** 比如说key要换，或者某个配置错了，可以修改文件之后，按照第六步打一个新包，然后执行以下三条命令：
> 
> ```
> # 暂停原容器，如果没有设置名字，那这里的chat就用gpt-academic
> docker stop chat
> 
> # 删除原容器，如果没有设置名字，那这里的chat就用gpt-academic
> docker rm chat
> 
> # 重新执行第七步的命令
> docker run -itd --name chat -p 443:443 gpt-academic
> ```

![image](https://user-images.githubusercontent.com/78953620/235045452-e14a9323-0753-4143-8c2f-1df32a792f26.png)
您好，加载完毕之后就不动了要怎么解决呢

**Comment by piwawa** [comment]
> 怎么绑定域名呢，有自己的域名，不想用ip+端口

同问，我想知道怎么通过nginx代理这个网站

**Comment by ghostning** [comment]
> 如果希望在服务器上使用docker部署的话，可以参考以下步骤（其中前几点和master上的前几点都是一样的）： 1、在你的指定目录下执行
> 
> ```
> git clone https://github.com/binary-husky/chatgpt_academic.git
> ```
> 
> 2、`cd chatgpt_academic` 3、将config.py的内容拷贝到config_private.py中（如果不需要设置自己的config，可忽略）
> 
> ```shell
> cp config.py config_private.py
> ```
> 
> 4、根据master指引，修改自己的配置，分别是以下几项：
> 
> ```python
> # Your Key是自己的api key，此处位于第二行
> API_KEY = "Your Key"
> 
> # 由于我是国外的服务器，所以USE_PROXY设置的是false，即默认值未做修改
> USER_PROXY = False
> 
> # 修改自己的暴露端口，我选的是443，此处位于37行
> WEB_PROT = 443
> ```
> 
> 5、**可选，修改镜像源** 国外服务器访问DockerFile里的阿里镜像可能会慢，所以我去掉了其对镜像源的指定，如果也需要取消，可参考以下步骤：首先确保自己位于chatgpt_academic目录下，执行命令`vim Dockerfile`，删除3~5行的内容，结果如下
> 
> ```dockerfile
> FROM python:3.11
>   
> WORKDIR /gpt
> COPY requirements.txt .
> RUN pip3 install -r requirements.txt
> 
> COPY . .
> 
> CMD ["python3", "-u", "main.py"]
> ```
> 
> 6、打包Docker镜像，和master教程一致，命令为：
> 
> ```
> docker build -t gpt-academic .
> ```
> 
> 7、运行Docker镜像，使用以下命令：
> 
> ```shell
> # --name可选，是给容器起的名字，-d是为了让他后台运行，443:443是为了把端口暴露出去
> # 请确保暴露的端口telnet的通，同时此端口没有其他服务运行
> docker run -itd --name chat -p 443:443 gpt-academic
> ```
> 
> 8、**可选 如果要更新怎么办** 比如说key要换，或者某个配置错了，可以修改文件之后，按照第六步打一个新包，然后执行以下三条命令：
> 
> ```
> # 暂停原容器，如果没有设置名字，那这里的chat就用gpt-academic
> docker stop chat
> 
> # 删除原容器，如果没有设置名字，那这里的chat就用gpt-academic
> docker rm chat
> 
> # 重新执行第七步的命令
> docker run -itd --name chat -p 443:443 gpt-academic
> ```

  大佬，想问一下 在打包镜像那一步，有两个文件始终下载不下来，通过vim也改过镜像了还是下载不下来
