### ISSUE TITLE
做出的一个小白用教程

### ISSUE THREAD

**Issue by Bigsevenying** [binary-husky/gpt_academic#387]
[结合诸位大佬的经验，鄙人做出一个小白用的教程。过程粗暴且粗糙，万望诸位斧正
[chatgpt academic小白级教程.docx](https://github.com/binary-husky/chatgpt_academic/files/11184687/chatgpt.academic.docx)

**Comment by yhyu13** [comment]
安装&运行在conda环境了，其实可以不用删除原生的py环境吧

**Comment by Bigsevenying** [comment]
> 安装&运行在conda环境了，其实可以不用删除原生的py环境吧

这个我暂时不清楚。只是几次配置过程中，经常出现gradio已安装却无法调用的问题，就干脆卸载了

**Comment by Bigsevenying** [comment]
> 不必单独安装gradio，只要换成官方pip源或者阿里源就行。某些大学的宕机源真的害人不浅

请教一下，如果使用官方pip源是要用python3.11.0吗？我之前用python3.11.2运行“python -m pip install -r requirements.txt”总是失败

**Comment by wojofja** [comment]
> 

厉害

**Comment by binary-husky** [comment]
> > 不必单独安装gradio，只要换成官方pip源或者阿里源就行。某些大学的宕机源真的害人不浅
> 
> 请教一下，如果使用官方pip源是要用python3.11.0吗？我之前用python3.11.2运行“python -m pip install -r requirements.txt”总是失败

任何python版本都要用官方源
