### ISSUE TITLE
是否可以在docker中使用environment来定义api key 和 proxy config

### ISSUE THREAD

**Issue by java160** [binary-husky/gpt_academic#397]
如题，每次改这俩就要重新build，有点慢，如果这样的话是不是就方便一点。
另外，是不是可以搞个docker-compose文件来编排。
毕竟我这种使用nginx_proxy docker的选手基本所有容器都是用compose来编排的。

**Comment by java160** [comment]
另外又想到两点：
1.是否支持webapi，就跟隔壁chatgpt-qq-bot一样，支持下有人搭设的chatgpt webapi，这样可以减少api的花费
2.是否支持为不同用户调用不同对话的场景，并增加用户登录验证系统。web app最主要的问题是多个用户连接到server，如果不做区分不如打包成桌面app直接使用。

**Comment by binary-husky** [comment]
下个2.6版本将支持在输入区直接输入apikey

**Comment by binary-husky** [comment]
> 另外又想到两点： 1.是否支持webapi，就跟隔壁chatgpt-qq-bot一样，支持下有人搭设的chatgpt webapi，这样可以减少api的花费 2.是否支持为不同用户调用不同对话的场景，并增加用户登录验证系统。web app最主要的问题是多个用户连接到server，如果不做区分不如打包成桌面app直接使用。

- 暂无支持webapi的计划，目前的关注重点（2.7版本规划）是接入本地小型llm，比如chatglm和tgui的所有模型
- 我们暂时没有人手去做多用户优化，2.7之后会考虑

**Comment by neo-pan** [comment]
可以在 docker-compose.yml 中通过挂载目录的方式覆盖docker container中的代码，这样更改config或者更改代码时就不需要重新build image。

```
volumes:
  - /path/to/chatgpt_academic:/gpt
```
