### ISSUE TITLE
win10 clash配置proxy后，check可以成功查到国外ip，但是实际使用超时

### ISSUE THREAD

**Issue by Li-Mingshuang** [binary-husky/gpt_academic#41]

**Comment by Li-Mingshuang** [comment]
rt

**Comment by liuqigui** [comment]
哥们，你是怎么配置的啊？可以发个教程连接么？
我也试一下，看看能不能行。

**Comment by njausxl** [comment]
> 哥们，你是怎么配置的啊？可以发个教程连接么？ 我也试一下，看看能不能行。

https://zhuanlan.zhihu.com/p/616922151?  可以看看这个

**Comment by jndmw-111** [comment]
> > 哥们，你是怎么配置的啊？可以发个教程连接么？ 我也试一下，看看能不能行。
> 
> https://zhuanlan.zhihu.com/p/616922151? 可以看看这个

hello，链接失效了，有没有新的配置方法呢

**Comment by binary-husky** [comment]
盲猜飞机场被chatgpt拉黑了，换个代理试试

**Comment by clippersman** [comment]
有兄弟给一个详细点的教程吗，代理配置显示能运行但是还是用不了

**Comment by thudjx** [comment]
我可以在chat.openai.com上使用chatgpt，但是网络代理状态依然显示的是未配置。
我的代理软件是clash, 代理设置应该没有问题，也有其他软件在使用这个代理。
操作系统为windows。
请问我现在应该在哪里查看日志，并且排查问题呢？

**Comment by clippersman** [comment]
> 

可以打开页面，但是提示代理所在地查询超时，代理可能无效

**Comment by thudjx** [comment]
代理无效是什么意思。。另外提示的信息是这样：
```bash
网络代理状态：未配置。无代理状态下很可能无法访问。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'ip': '===', 'network': '2402:f000::/38', 'version': 'IPv6', 'city': 'Beijing', 'region': 'Beijing', 'region_code': 'BJ', 'country': 'CN', 'country_name': 'China', 'country_code': 'CN', 'country_code_iso3': 'CHN', 'country_capital': 'Beijing', 'country_tld': '.cn', 'continent_code': 'AS', 'in_eu': False, 'postal': None, 'latitude': 39.9143, 'longitude': 116.3861, 'timezone': 'Asia/Shanghai', 'utc_offset': '+0800', 'country_calling_code': '+86', 'currency': 'CNY', 'currency_name': 'Yuan Renminbi', 'languages': 'zh-CN,yue,wuu,dta,ug,za', 'country_area': 9596960.0, 'country_population': 1411778724, 'asn': 'AS45576', 'org': '==='}
代理配置 无, 代理所在地：China
```
奇怪的地方是，ip项看起来像是ipv6而不是ipv4。

**Comment by Aaron1iu** [comment]
我用的也是机场，但是不太懂代理的信息在哪里查看？请问是在机场的主页吗？

**Comment by thudjx** [comment]
> 我用的也是机场，但是不太懂代理的信息在哪里查看？请问是在机场的主页吗？

如果你用的clash的话，Port就是转发端口：
![image](https://user-images.githubusercontent.com/32637321/228399752-cd28194d-ea8b-4185-baf7-0449faf9a842.png)

**Comment by njausxl** [comment]
> 哥们，你是怎么配置的啊？可以发个教程连接么？ 我也试一下，看看能不能行。

zhuanlan.zhihu.com/p/616922151  这个链接试一下，或者在知乎、微信公众号 生信森林，里面有个教程，可以参考一下

**Comment by xuekai1024** [comment]
参考我在Issues:请问代理网络的地址在哪里看？中的回复

**Comment by Vole23** [comment]
我用的clash ，直接把端口号改成clash的本地端口号就行了啊

**Comment by feiyang110402** [comment]
> 我用的clash ，直接把端口号改成clash的本地端口号就行了啊

麻烦说具体点呗，我也用clash，一直失败

**Comment by Vole23** [comment]
> > 我用的clash ，直接把端口号改成clash的本地端口号就行了啊
> 
> 麻烦说具体点呗，我也用clash，一直失败

建议多爬爬楼 比如说close里面的 https://github.com/binary-husky/chatgpt_academic/issues/1 https://github.com/binary-husky/chatgpt_academic/issues/9 https://github.com/binary-husky/chatgpt_academic/issues/42#issuecomment-1487871603 之类的都有说到
设置上就是USE_PROXY = True 以及 proxies = {"http": "127.0.0.1:7890", "https": "127.0.0.1:7890", }
这个7890是你clash的端口，但是有可能机场上其他人频繁访问导致该节点ip被限制，切换节点或者过一段时间就好了。

**Comment by GXY0116** [comment]
> 

麻烦问一下，定位问题有解决吗，我已经是clash的global状态了。

**Comment by GXY0116** [comment]
> 代理无效是什么意思。。另外提示的信息是这样：
> 
> ```shell
> 网络代理状态：未配置。无代理状态下很可能无法访问。
> 所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
> 查询代理的地理位置，返回的结果是{'ip': '===', 'network': '2402:f000::/38', 'version': 'IPv6', 'city': 'Beijing', 'region': 'Beijing', 'region_code': 'BJ', 'country': 'CN', 'country_name': 'China', 'country_code': 'CN', 'country_code_iso3': 'CHN', 'country_capital': 'Beijing', 'country_tld': '.cn', 'continent_code': 'AS', 'in_eu': False, 'postal': None, 'latitude': 39.9143, 'longitude': 116.3861, 'timezone': 'Asia/Shanghai', 'utc_offset': '+0800', 'country_calling_code': '+86', 'currency': 'CNY', 'currency_name': 'Yuan Renminbi', 'languages': 'zh-CN,yue,wuu,dta,ug,za', 'country_area': 9596960.0, 'country_population': 1411778724, 'asn': 'AS45576', 'org': '==='}
> 代理配置 无, 代理所在地：China
> ```
> 
> 上边"==="是一些私人信息。奇怪的地方是，ip项看起来像是ipv6而不是ipv4。

麻烦问一下，这个代理在China的问题有解决么，现在全局其他节点要么代理出问题，要么定位出问题

**Comment by binary-husky** [comment]
may related to #1

**Comment by ZRQii** [comment]
请问下，这个情况是什么原因？
网络代理状态：运行。
网络代理状态：运行。
Traceback (most recent call last):
  File "D:\--\Documents\chatgpt_academic\predict.py", line 12, in <module>
    try: from config_private import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
ImportError: cannot import name 'TIMEOUT_SECONDS' from 'config_private' (D:\--\Documents\chatgpt_academic\config_private.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from predict import predict
  File "D:\--\Documents\chatgpt_academic\predict.py", line 13, in <module>
    except: from config import proxies, API_URL, API_KEY, TIMEOUT_SECONDS, MAX_RETRY, LLM_MODEL
ImportError: cannot import name 'TIMEOUT_SECONDS' from 'config' (D:\--\Documents\chatgpt_academic\config.py)
