### ISSUE TITLE
能否从剪贴板自动读取内容？

### ISSUE THREAD

**Issue by HydroNing** [binary-husky/gpt_academic#429]
每次复制、粘贴到输入框、再点击功能按钮有点麻烦，比如一段一段润色的时候就很繁琐。
当输入框为空时，能否自动读取剪贴板的内容？这样就省了一步

**Comment by 15058415003** [comment]
问题是，如果你某一次打开网页时，剪贴板里有之前复制的无关内容呢？这样的话，不是又要把输入框清空吗
不如加一个按钮，点击后才会读取剪贴板

**Comment by HydroNing** [comment]
>

> 问题是，如果你某一次打开网页时，剪贴板里有之前复制的无关内容呢？这样的话，不是又要把输入框清空吗 不如加一个按钮，点击后才会读取剪贴板

我意思是：【当输入框为空时，点击功能按钮，直接从剪贴板读取内容】。而不是：【剪贴板内容自动导入输入框，点击功能按钮再从输入框读取】。

**Comment by hlblade** [comment]
我也需要这个功能，写文章的时候，word里面复制一段需要润色的句子，到网页这里点一个按钮就可以润色了还是很方便的，最后简陋地实现了下，本地运行可以正常运行，部署到服务器应该就不行了，因为两部不是同一个剪贴板：
```
"润色剪贴板内容": {
            "Prefix":   r"Rewrite this paragraph in an academic langauge:" + "\n",
            "Suffix":   r"",
            "PreProcess": get_clipboard,
        },
       ```
