### ISSUE TITLE
服务器小白部署教程【个人实践】

### ISSUE THREAD

**Issue by sfvsfv** [binary-husky/gpt_academic#442]
docker..不会用...python不会用...服务器默认python版本3.6不会升级...代理也不会配置....各种命令不会用....

那么下面就是最简单办法，点点点即可【希望有帮助？】
##  一、个人环境
我的环境：
1. 新加坡服务器，centos系统，
2. 宝塔

### 2.1 config.py文件
第一步：修改密钥：
![image](https://user-images.githubusercontent.com/62045791/231562796-86aa0555-50d9-4955-ba49-ce841ef1d326.png)
由于是海外服务器，所以代理也可以不用配置了。

第二步：加上密码（我的需求是可以把部署好的项目给几个朋友一起使用,所以加密）
![image](https://user-images.githubusercontent.com/62045791/231563055-7ef48368-dc87-44f5-908b-75a12cd02221.png)

### 2.2 main.py文件
第三步：修改为True
![image](https://user-images.githubusercontent.com/62045791/231563482-eb73f4f8-a478-47f9-ae4a-08d0de75772c.png)

大概就是配置这几个（其它我好像没改什么了）
##  三、下载项目
我是在我的一个域名下，直接执行的以下命令(或者IP文件夹下）
`
git clone https://github.com/binary-husky/chatgpt_academic.git

cd chatgpt_academic
`
## 四、项目部署
宝塔商店安装项目管理器：
![image](https://user-images.githubusercontent.com/62045791/231564015-3f25b7e6-302a-439e-b15a-40fd11c1cc77.png)
安装好后点开，切换安装3.9以上：
![image](https://user-images.githubusercontent.com/62045791/231564274-9dc3a6cc-8c58-4079-9390-67846529ccfb.png)
添加项目：
![image](https://user-images.githubusercontent.com/62045791/231565261-259a3d49-6c97-4a1a-952b-8d7bc586eadf.png)
添加好后如下：
![image](https://user-images.githubusercontent.com/62045791/231565371-0d2cd190-f90c-450b-acd8-31a1a203bd7d.png)
开启映射：
![image](https://user-images.githubusercontent.com/62045791/231565492-b184a777-1bec-46de-aadc-4e108326c478.png)
这样就可以直接IP访问我的项目了：
![image](https://user-images.githubusercontent.com/62045791/231565754-9d41e460-cc77-4d08-ba23-9246e8378164.png)

上述是我的大概记录，对于小白来说，不用各种命令，直接一直点点点、安装即可。（我不清楚步骤是否清楚，有可能漏了步骤，大概是这样）。

##  效果测试
![GIF 2023-4-13 3-46-02](https://user-images.githubusercontent.com/62045791/231569419-2139fa42-cff3-42db-9d05-04eb8bb58a55.gif)

## 补充声明
我用的2.5版本镜像，部署很成功。哦，对了，记得把端口改成固定的值，config,py里面有注释，自己看下。

**Comment by binary-husky** [comment]
非常感谢

**Comment by vampireseraph** [comment]
理论上可以搞到自己的群晖上吧

**Comment by binary-husky** [comment]
引用到wiki里面了

https://github.com/binary-husky/chatgpt_academic/wiki/%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9C%E7%A8%8B%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97

**Comment by sfvsfv** [comment]
> 
群晖?不理解。你放自己服务器上就行，然后直接通过ip访问镜像就可以了。

**Comment by huajixiaoyan** [comment]
你好，我在部署的时候，那个文件里面找不到你图片里面的项目。那个第二大步是在本地修改吗。

**Comment by sfvsfv** [comment]
> 直接在服务器修改。请注意步骤中明确说明了 config.py文件和main.py文件，请对应查看。

**Comment by ShiDing007** [comment]
大佬，请教个问题：
1.config.py文件中，那个密码是指什么密码？所使用服务器的用户名和密码吗？
<img width="806" alt="image" src="https://user-images.githubusercontent.com/75664459/231946957-30bff54d-5d0d-4c88-80aa-5095c3f79058.png">

**Comment by sfvsfv** [comment]
> 大佬，请教个问题： 1.config.py文件中，那个密码是指什么密码？所使用服务器的用户名和密码吗？ <img alt="image" width="806" src="https://user-images.githubusercontent.com/75664459/231946957-30bff54d-5d0d-4c88-80aa-5095c3f79058.png">

你好，这个是你部署好后，登录镜像的账号和密码，是你自定义的。

**Comment by smqaf** [comment]
安装python3和依赖会很久

**Comment by sfvsfv** [comment]
> 安装python3和依赖会很久

国外服务器的话，下载两三分钟就好了。如果你是国内服务器，需要配置镜像。在我教程基础上，添加代理才行。

**Comment by KKXLIVE** [comment]
映射域名，具体怎么操作呀，我被困在这一步了，用宝塔部署后，也设置了端口，后面怎么操作才能在公网进行访问？
![image](https://user-images.githubusercontent.com/106319645/235125720-4012d8aa-efce-41c4-90da-87fde82033f8.png)

**Comment by sfvsfv** [comment]
> 映射域名，具体怎么操作呀，我被困在这一步了，用宝塔部署后，也设置了端口，后面怎么操作才能在公网进行访问？ ![image](https://user-images.githubusercontent.com/106319645/235125720-4012d8aa-efce-41c4-90da-87fde82033f8.png)

填写你的IP，或者填写一个未使用的域名，提交即可。

**Comment by THN168** [comment]
您好，我被困在这里了，请问该怎么解决呀，谢谢您的帮助
![截屏2023-06-10 12 20 49](https://github.com/binary-husky/gpt_academic/assets/136144753/d79c6801-7958-42ac-b967-6f73c36ab2d6)

**Comment by systemoutprintlnhelloworld** [comment]
> 您好，我被困在这里了，请问该怎么解决呀，谢谢您的帮助 ![截屏2023-06-10 12 20 49](https://user-images.githubusercontent.com/136144753/244847016-d79c6801-7958-42ac-b967-6f73c36ab2d6.png)

pip install gradio试试?

**Comment by CT911266** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/97796378/d47fe2fe-348b-40a2-b6b6-7fd5465b29a5)
为什么我的项目启动失败QAQ

**Comment by daerbiubiu** [comment]
> 您好，我被困在这里了，请问该怎么解决呀，谢谢您的帮助 ![截屏2023-06-10 12 20 49](https://user-images.githubusercontent.com/136144753/244847016-d79c6801-7958-42ac-b967-6f73c36ab2d6.png)

我也发生了同样的问题，请问如何解决

**Comment by Gsatb** [comment]
安装依赖说什么python缺ssl模块，导致gradio报错，搞一天了，难道是系统问题？

**Comment by Gsatb** [comment]
> 安装依赖说什么python缺ssl模块，导致gradio报错，搞一天了，难道是系统问题？

更换系统后成功了：
![image](https://github.com/binary-husky/gpt_academic/assets/64628070/205719f0-ab28-4932-b590-b24822f53fca)

**Comment by hrply** [comment]
更简单的方法是直接用volume参数把本地的config_private.py挂载到docker内的/gpt目录内，参考的宝塔可用docker编排如下：

```yaml
services:
  gpt_academic_nolocalllms:
    image: ghcr.io/binary-husky/gpt_academic_nolocal:master
    networks:
      - baota_net
    ports:
      - "${HOST}:${PORT}:80/tcp"#80是config_private.py里WEB_PORT变量的赋值，可以修改为你喜欢的，但是没必要，这是docker内的端口。
    volumes:
      - /home/hrply/software/gpt/config_private.py:/gpt/config_private.py#/home/hrply/software/gpt/config_private.py是我的本地config_private.py储存路径，可修改为自己的路径。

    # 启动命令
    command: >
      bash -c "python3 -u main.py"
      
networks:
  baota_net:
    external: true
```
对应的env内容为：
```
HOST=
PORT=20323#这是你自己设置的docker对外开放的端口，也就是你实际通过哪个端口访问Academic GPT，不建议用host模式是为了更好的管理多个docker运行时的端口和防火墙设置。
```

然后config_private.py里将WEB_PORT变量固定为80（或者其他都行，反正是docker内部的端口，但是需要确认和docker编排里的ports里的端口一致）。这样未来需要添加或者修改apikey或者其他设置，只要修改config_private.py即可。
