### ISSUE TITLE
努力的小白---使用docker镜像服务器，部署完运行不起来，有大佬帮忙看下吗？？

### ISSUE THREAD

**Issue by ShiDing007** [binary-husky/gpt_academic#471]
在腾讯云买的海外服务器--docker镜像；
操作流程：
1.下载项目；
2.把自己的apikey填入config.py文件；
3.安装；
4.启动运行；
然后就出现下边的内容了：
<img width="827" alt="image" src="https://user-images.githubusercontent.com/75664459/231946257-b580ac7a-bdbc-40ed-bf1f-38d0dccd599b.png">
有没有大佬帮忙看看什么情况？？
服务器的小白虚心请教。

**Comment by binary-husky** [comment]
sudo

**Comment by Marfars** [comment]
没有权限，在docker run之前加个sudo试试

**Comment by ShiDing007** [comment]
> 没有权限，在docker run之前加个sudo试试
使用sudo了，报的错又不一样了。有点难搞，服务器太小白了。

**Comment by ShiDing007** [comment]
> 没有权限，在docker run之前加个sudo测试

使用sudo了，报其他错了，没截屏下来。
服务器小白，太难了。

**Comment by Marfars** [comment]
#386 最下面有个外网部署docker的文档，如果你执行过程中遇到问题可以回复我😶‍🌫️
