### ISSUE TITLE
我之前配置代理成功运行，但是现在却不行，而其它api应用可以使用，chat官网也能登录

### ISSUE THREAD

**Issue by 14790897** [binary-husky/gpt_academic#472]
![image](https://user-images.githubusercontent.com/121866954/231947292-711064ad-4ed3-460c-90b3-d1bf53dbc5d7.png)
![image](https://user-images.githubusercontent.com/121866954/231947549-408167e9-91e9-40d7-ac84-23679986a2e5.png)

**Comment by Marfars** [comment]
看看你代理软件的端口是不是7890，我用小猫咪他有时候会莫名其妙改端口

**Comment by Marfars** [comment]
然后我的http和https都是配置的http，也可能和这个有关系，我猜的

**Comment by maifulmax** [comment]
我也出现同样的问题，之前都能访问，现在不能用了，我的配置是：

proxies = { "http": "socks5h://localhost:10808", "https": "socks5h://localhost:10808", }

代理用的v2ray

**Comment by 14790897** [comment]
我现在用cloud flare进行反向代理，但是json解析错误
![image](https://user-images.githubusercontent.com/121866954/232054642-44b01514-18e0-4bef-94f8-e8ecd5ba2652.png)

**Comment by gysabc** [comment]
我用的clash，我在mac上用的clashx pro，里面有增强模式，可以正常使用；但是在windows pc上，用clash，没有增强模式，外网可以上，但是这个chatgpt academic就是用不了

**Comment by song4875343** [comment]
我很想知道，为啥我代理设置成全局后，还需要折腾这些代理设置。我的其他软件连接chatgpt都没问题，就这个程序不行，设置代理依然不行。谁能救救我

**Comment by song4875343** [comment]
v2rayN 软件最下面一行有代理服务器的设置，config.py提示的sock5h，改成了sock5,loucalhost改成了127.0.0.1，其实不是一个意思吗？但是改为了，它成功了，其实我还是不明白我都开了全局代理，所有的软件都行这个为啥还要专门设置。看了源代码，跟所有软件一样的post代码，不过本着能跑就行的原则，庆祝一下。

**Comment by gysabc** [comment]
祝贺祝贺😃。我是换了个代理，然后可以了


 ***@***.***
 ***@***.***
  



---- 回复的原邮件 ----
发件人  ***@***.***> 日期  2023年04月21日 08:08 收件人  ***@***.***> 抄送至  Gao ***@***.***>***@***.***> 主题  Re: [binary-husky/chatgpt_academic] 我之前配置代理成功运行，但是现在却不行，而其它api应用可以使用，chat官网也能登录 (Issue #472)  

v2rayN 软件最下面一行有代理服务器的设置，config.py提示的sock5h，改成了sock5,loucalhost改成了127.0.0.1，其实不是一个意思吗？但是改为了，它成功了，其实我还是不明白我都开了全局代理，所有的软件都行这个为啥还要专门设置。看了源代码，跟所有软件一样的post代码，不过本着能跑就行的原则，庆祝一下。

**Comment by xzm123456** [comment]
proxies = { "http": "socks5h://localhost:7890", "https": "socks5h://localhost:7890", }
注意   :   的问题，我是这样写的，可以了。
