### ISSUE TITLE
注册OpenAI和token问题的讨论

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [binary-husky/gpt_academic#473]
我记得opneapi开放了这个的接口
另：
一键更新功能我看先前也有人询问了我没看到您的意思，请问是目前还没更新完预接入的状态吗😳

**Comment by binary-husky** [comment]
真的不用那么焦虑，gpt3.5它花不了多少钱😂

**Comment by PeterBilly** [comment]
免费用户似乎无法查询token用量
我目前还没有配置好国外的银行卡，没有付费用户来测试openai库的余额查询功能

**Comment by systemoutprintlnhelloworld** [comment]
> 
好像是了，我记得以前还开放了赠金查询功能的

**Comment by systemoutprintlnhelloworld** [comment]
> 免费用户似乎无法查询token用量 我目前还没有配置好国外的银行卡，没有付费用户来测试openai库的余额查询功能

是了，这个浏览器插件[chatgptbox](https://github.com/josStorer/chatGPTBox)以前的版本能查询赠金余额，但是现在也不行了

**Comment by systemoutprintlnhelloworld** [comment]
> 真的不用那么焦虑，gpt3.5它花不了多少钱😂

也是哈，刚五毛钱又注册了个账号，除了麻烦也没啥了😂

另外，您在HF上的2.67版本使用后发现貌似一在app.py的launch中加入分享外链就报错，而且修改代码后自动更新功能也执行不了，是不是因为是docker部署的原因呀

**Comment by sfvsfv** [comment]
我根据一个开源代码，部署的一个KEY余额查询网站，可以使用：https://key.yanghanwen.xyz/billing/

**Comment by systemoutprintlnhelloworld** [comment]
> 我根据一个开源代码，部署的一个KEY余额查询网站，可以使用：https://key.yanghanwen.xyz/billing/

非常感谢❤️❤️❤️

**Comment by baicaifanbao** [comment]
这个网址就能查啊，openai官方的https://platform.openai.com/account/usage

**Comment by sfvsfv** [comment]
> 这个网址就能查啊，openai官方的https://platform.openai.com/account/usage

是的，网址接口就是官方的这个地址，图个方便。

**Comment by KongFanJin** [comment]
刚办个招行的全币信用卡, 试试能不能充值. 有渠道充值吗. 要不然只能薅羊毛(5美元的账号了)

**Comment by stay-leave** [comment]
> 

老哥怎么注册新账号的，听说已经不让注册了

**Comment by systemoutprintlnhelloworld** [comment]
> 刚办个招行的全币信用卡, 试试能不能充值. 有渠道充值吗. 要不然只能薅羊毛(5美元的账号了)

Waylaidwanderer APl 可以，githyb查查·

**Comment by systemoutprintlnhelloworld** [comment]
> > 
> 
> 老哥怎么注册新账号的，听说已经不让注册了

原生/住宅ip+sms平台+edge无痕，得到key后不再登录

**Comment by jkhcc11** [comment]
> 刚办个招行的全币信用卡, 试试能不能充值. 有渠道充值吗. 要不然只能薅羊毛(5美元的账号了)

不行的，会寄。不是visa卡就行的，还认卡。

**Comment by systemoutprintlnhelloworld** [comment]
> 刚办个招行的全币信用卡, 试试能不能充值. 有渠道充值吗. 要不然只能薅羊毛(5美元的账号了)

[可以看看这个回答](https://github.com/binary-husky/chatgpt_academic/issues/279#issuecomment-1496239081)

**Comment by JackeyLoveT** [comment]
> > > 
> > 
> > 
> > 老哥怎么注册新账号的，听说已经不让注册了
> 
> 原生/住宅ip+sms平台+edge无痕，得到key后不再登录

大佬 我输入手机号提示Your account was flagged for potential abuse. If you feel this is an error, please contact us at help.openai.com是为什么？

**Comment by systemoutprintlnhelloworld** [comment]
> > > > 
> > > 
> > > 
> > > 老哥怎么注册新账号的，听说已经不让注册了
> > 
> > 
> > 原生/住宅ip+sms平台+edge无痕，得到key后不再登录
> 
> 大佬 我输入手机号提示Your account was flagged for potential abuse. If you feel this is an error, please contact us at help.openai.com是为什么？

换号
