### ISSUE TITLE
上传pdf错误

### ISSUE THREAD

**Issue by GitYohoo** [binary-husky/gpt_academic#474]
- **(1) Describe the bug 简述**
不停的循环发送pdf上传的消息

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/53508470/231973226-78a3efcf-abaf-4720-b8d4-de7cb9fc1c62.png)

- **(3) Terminal Traceback 终端traceback（如有）**
终端无异常

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by GitYohoo** [comment]
换了浏览器和重启电脑都不行

**Comment by Marfars** [comment]
我也遇到了这个问题，晚上下班在我自己的仓库尝试定位修复下

**Comment by binary-husky** [comment]
是gradio 3.26的问题，降级到gradio 3.25

**Comment by binary-husky** [comment]
#476

**Comment by Marfars** [comment]
`pip install gradio==3.25.0`可以卸载你高版本的包安装3.25的
