### ISSUE TITLE
上传文件时重复上传

### ISSUE THREAD

**Issue by BTFKM** [binary-husky/gpt_academic#476]
上传文件时重复上传
样例文件[1.docx](https://github.com/binary-husky/chatgpt_academic/files/11230280/1.docx)
界面![TE$JF@(Q$565$CWJ4)9(A(P](https://user-images.githubusercontent.com/51219393/231979388-e73140de-f563-40c6-9e97-7f0148505cec.png)

**Comment by BTFKM** [comment]
终端上看似乎没有重复 截图为节选
第一次测试![2](https://user-images.githubusercontent.com/51219393/231981380-a6dc9d4a-3e2b-4ae8-809b-d8d053aac137.png)
第二次测试![3](https://user-images.githubusercontent.com/51219393/231981704-226a6eea-ca4b-4329-89ef-97666effec22.png)

**Comment by suiahae** [comment]
关闭程序，上传的文件应该存在类似这样的文件夹里：private_upload\2023-04-14-15-46-15，重启程序，不要上传文件，把`private_upload\2023-04-14-15-46-15`手动写到输入区。

**Comment by BTFKM** [comment]
> 

这方法妙啊

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/231993971-2e4afd22-affe-49f3-9393-0c418f6f638f.png)
上传文件之前有什么其他步骤吗?没发现重复上传的现象

**Comment by binary-husky** [comment]
什么浏览器呢？

**Comment by binary-husky** [comment]
是gradio 3.26的问题，降级到gradio 3.25

**Comment by Marfars** [comment]
@binary-husky 那是不是requirements要改下，那里面的大于等于会一直拉最新的

**Comment by binary-husky** [comment]
> @binary-husky 那是不是requirements要改下，那里面的大于等于会一直拉最新的

嗯嗯 对的
