### ISSUE TITLE
已经配置好 api_key和代理, 运行python main.py后, 打开的页面一直显示loading

### ISSUE THREAD

**Issue by AfreyAwsome** [binary-husky/gpt_academic#480]
- **(1) Describe the bug 简述**
已经配置好 api_key和代理, 运行python main.py后, 打开的页面一直显示loading

- **(2) Screen Shot 截图**

![image](https://user-images.githubusercontent.com/32808548/232036261-53b83a6d-fe3f-4189-8d9d-f23acc98fa72.png)

**Comment by Marfars** [comment]
给看下你的日志输出 你python main.py之后，虽然跳到了浏览器，但是你的控制台应该还有些输出

**Comment by binary-husky** [comment]
尝试
- 切换代理模式
- 看看浏览器F12的输出？

**Comment by AfreyAwsome** [comment]
> 尝试
> 
> * 切换代理模式
> * 看看浏览器F12的输出？

![image](https://user-images.githubusercontent.com/32808548/232261371-c026c1c2-81ef-445f-88a1-36d0afced4a0.png)

**Comment by binary-husky** [comment]
> > 尝试
> > 
> > * 切换代理模式
> > * 看看浏览器F12的输出？
> 
> ![image](https://user-images.githubusercontent.com/32808548/232261371-c026c1c2-81ef-445f-88a1-36d0afced4a0.png)

如果完全关闭代理呢？

**Comment by AfreyAwsome** [comment]
>关了代理后, 看起来也是这个报错啊
![image](https://user-images.githubusercontent.com/32808548/232686900-42ca4fa2-911c-471f-b38a-7a09da1c8cd6.png)

**Comment by Pytorchlover** [comment]
![image](https://user-images.githubusercontent.com/115700050/232697745-11b8770b-edd1-4811-9daa-4a631b84a6ce.png)
我也是这个问题，请问有没有什么好的解决方法呢？

**Comment by Pytorchlover** [comment]
我后来换了代理节点，就好了，感觉进不去的原因可能是代理的问题。

**Comment by HXF-hxf-bit** [comment]
我也有这个问题，还没解决，换了各种代理节点也没进去

**Comment by hellozhaoming** [comment]
感觉是这个网页模板用的google fonts，建议改成本地fonts或将本地google fonts下载到本地再加载。
比如我把所有的google fonts都改称为微软雅黑。

只要改一个文件。“theme.py"


搜索google 就出来了，把带google fonts的都注释掉

`def adjust_theme():
    try:
        color_er = gr.themes.utils.colors.fuchsia
        set_theme = gr.themes.Default(
            primary_hue=gr.themes.utils.colors.orange,
            neutral_hue=gr.themes.utils.colors.gray,
            font=["sans-serif", "Microsoft YaHei", "ui-sans-serif", "system-ui",
                  #"sans-serif", gr.themes.utils.fonts.GoogleFont("Source Sans Pro")],
                    "sans-serif", "Microsoft YaHei"],
            font_mono=["ui-monospace", "Consolas", "monospace", "Microsoft YaHei"])    #gr.themes.utils.fonts.GoogleFont("IBM Plex Mono")])`

**Comment by changecool** [comment]
#625 可以参看

**Comment by RemoteS2023** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/130020098/0956d560-d489-475e-bf9c-35e7bd39b722)
wo'ye'sh我也是同样的问题，但是报错的代码不一样，有大佬知道吗...
