### ISSUE TITLE
用cloud flare进行反向代理，但是json解析错误

### ISSUE THREAD

**Issue by 14790897** [binary-husky/gpt_academic#486]
![image](https://user-images.githubusercontent.com/121866954/232178118-983952f4-fa38-4596-8ad8-f0ffbe3b5fe2.png)

**Comment by Roger-Dong** [comment]
这个问题有解答了吗？

**Comment by 14790897** [comment]
这种一般是获得了空的回复吧，可能openai根本没收到消息，不过我懒得研究了
