### ISSUE TITLE
Proposal to create Japanese documentation

### ISSUE THREAD

**Issue by Akihisa-Watanabe** [binary-husky/gpt_academic#491]
Hello, chatgpt_academic developers.

Thank you for creating this wonderful project. I believe that chatgpt_academic would be useful for Japanese researchers as well, and having Japanese documentation would make it more accessible to a wider Japanese audience.

With that in mind, I'd like to propose the creation of Japanese documentation for chatgpt_academic. If you agree, I am willing to help with the translations myself. Could you please let me know which branch I should work on for this translation task?

Thank you for considering my proposal.

**Comment by binary-husky** [comment]
v3.1 would be fine, we have implemented ChatGLM in this branch
