### ISSUE TITLE
能不能增加读取网页信息的功能？

### ISSUE THREAD

**Issue by BHC1205** [binary-husky/gpt_academic#492]
这样可以搭一个简易的搜索功能，扩充模型的知识库；
甚至可以将搜到的结果二次输入给模型，从而实现伪联网功能

**Comment by binary-husky** [comment]
@BHC1205  您好，这个想法很有价值，能详细讲讲您的想法吗，比如用哪种搜索引擎什么的

**Comment by achilatiao** [comment]
import re

# 假设这是一个模型的知识库
knowledge_base = [
    "人工智能是一种科技",
    "机器学习是人工智能的一个分支",
    "深度学习是机器学习的一个分支",
    "自然语言处理是人工智能的一个分支",
]

# 定义一个函数，用于搜索知识库中的内容
def search(query, knowledge_base):
    results = []
    for item in knowledge_base:
        if re.search(query, item, re.IGNORECASE):
            results.append(item)
    return results

# 测试搜索函数
query = "机器学习"
results = search(query, knowledge_base)
print("搜索结果：")
for result in results:
    print(result)

# 给出二次输入的示例
if len(results) > 0:
    print("请选择一个结果进行二次输入：")
    for i, result in enumerate(results):
        print(f"{i+1}. {result}")
    choice = int(input()) - 1
    print(f"您选择了：{results[choice]}")
    print("请输入您的二次输入：")
    feedback = input()
    knowledge_base.append(feedback)
else:break


import openai
openai.api_key = "YOUR_API_KEY"  # 替换为你自己的 API Key

# 定义一个函数，用于扩充模型知识库
def expand_knowledge(query):
    results = googlesearch(query)  # 调用已有的搜索功能
    for result in results:
        response = openai.Completion.create(
            engine="davinci", 
            prompt=f"Please provide more information about {result}:",
            max_tokens=1024,
            n=1,
            stop=None,
            temperature=0.5,
        )
        feedback = response.choices[0].text.strip()

**Comment by achilatiao** [comment]
但扩充需要爬虫，可以去乌鸦找找，连个Google应该不错【doge】

**Comment by binary-husky** [comment]
@BHC1205 @achilatiao 新增了一个简单的联机搜索功能

![image](https://user-images.githubusercontent.com/96192199/233571511-f2a8636e-70a8-4678-8a00-1ff9c5951646.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/233572605-6d1dff51-3dd3-4299-aa86-d2b3106d67e3.png)
