### ISSUE TITLE
Local Models

### ISSUE THREAD

**Issue by Kerushii** [binary-husky/gpt_academic#5]
Hi, any thoughts on galactica(opt pretrained on pubmed and wiki) and llama(no domain specific knowledge trained yet)
and any plan to release pretrained domain specific models for local inference?
Thanks

**Comment by binary-husky** [comment]
Just took a look at Galactica at Hugging Face. It seems very easy to implement, but like Visual-ChatGPT, the local package dependency behind it is very heavy. (Visual-ChatGPT models almost blow up my hard drive.)

However, it is a good idea to be able to switch between models. We'll keep looking into models such as Galactica, GPT-4, 文心一言, and LLaMA, as well as their academic usage.

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/229303571-c66dea56-480f-4ae7-8756-769da2a4f375.png)

Hello, I have successfully run the local galactica-1.3b on the morellm branch here, but the model keeps saying strange things continuously after answering questions. Have you encountered a similar issue?
