### ISSUE TITLE
Json异常 “error”: 

### ISSUE THREAD

**Issue by cunning2017** [binary-husky/gpt_academic#507]
- **(1) Describe the bug 简述**

- **(2) Screen Shot 截图**

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by cunning2017** [comment]
Json异常 “error”: { “message”: “This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?”, “type”: “invalid_request_error”, “param”: “model”, “code”: null }}

**Comment by cunning2017** [comment]
![image](https://user-images.githubusercontent.com/56642800/232366639-218a1ac5-41d7-4e06-adb4-7e65336496d6.png)

**Comment by Joseph-Chen-Jh** [comment]
+1，用了最新版代码，在https://huggingface.co/spaces/qingxu98/gpt-academic 检查apikey可以导入，但还是会报json error

**Comment by Joseph-Chen-Jh** [comment]
> +1，用了最新版代码，在https://huggingface.co/spaces/qingxu98/gpt-academic 检查apikey可以导入，但还是会报json error

应该是API被封了，重开了个号就好了

**Comment by JackeyLoveT** [comment]
> > +1，用了最新版代码，在https://huggingface.co/spaces/qingxu98/gpt-academic 检查apikey可以导入，但还是会报json error
> 
> 应该是API被封了，重开了个号就好了

大佬您好 我也是api过期了 最近怎么重新开号啊？我注册到输入手机号那一步就报错”Your account was flagged for potential abuse. If you feel this is an error, please contact us at help.openai.com“ 该怎么解决呢？
