### ISSUE TITLE
解析java项目代码时 其中一个线程失效

### ISSUE THREAD

**Issue by king0billy** [binary-husky/gpt_academic#518]
- **(1) Describe the bug 简述**

1.解析java项目代码时 其中一个线程失效，少解释一个文件
2.解析java项目代码时  对话框 “我上传了文件，请查收”的消息重复太多次，甚至在结束后也一样被刷屏，只能去\gpt_log里面找结果

- **(2) Screen Shot 截图**

![image](https://user-images.githubusercontent.com/52921954/232536327-af43c4ce-98d9-429b-9b0b-f1bfa81b5be9.png)

- **(3) Terminal Traceback 终端traceback（如有）**

#### [11/28] 请对下面的程序文件做一个概述: C:\Users\22427\AndroidStudioProjects\chatgpt_academic-version2.68-3\private_upload\2023-04-17-23-12-10\MiniServer0精简33.zip.extract\MiniServer0\getdata-service\src\main\java\com\liangjinglin\getdataservice\utils\R.java

[Local Message] 警告，线程11在执行过程中遭遇问题, Traceback：

```
Traceback (most recent call last):
  File "C:\Users\22427\AndroidStudioProjects\chatgpt_academic-version2.68-3\crazy_functions\crazy_utils.py", line 198, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\22427\AndroidStudioProjects\chatgpt_academic-version2.68-3\request_llm\bridge_chatgpt.py", line 85, in predict_no_ui_long_connection
    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-32Lg6GVB2rDhO8ameis0nUZG on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",        "type": "requests",        "param": null,        "code": null    }}
```

[Local Message] 警告，线程11在执行过程中遭遇问题, Traceback：

```
Traceback (most recent call last):
  File "C:\Users\22427\AndroidStudioProjects\chatgpt_academic-version2.68-3\crazy_functions\crazy_utils.py", line 198, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\22427\AndroidStudioProjects\chatgpt_academic-version2.68-3\request_llm\bridge_chatgpt.py", line 85, in predict_no_ui_long_connection
    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-32Lg6GVB2rDhO8ameis0nUZG on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",        "type": "requests",        "param": null,        "code": null    }}
```

[Local Message] 警告，线程11在执行过程中遭遇问题, Traceback：

```
Traceback (most recent call last):
  File "C:\Users\22427\AndroidStudioProjects\chatgpt_academic-version2.68-3\crazy_functions\crazy_utils.py", line 198, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\22427\AndroidStudioProjects\chatgpt_academic-version2.68-3\request_llm\bridge_chatgpt.py", line 85, in predict_no_ui_long_connection
    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-32Lg6GVB2rDhO8ameis0nUZG on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",        "type": "requests",        "param": null,        "code": null    }}
```

#### [12/28] 请对下面的程序文件做一个概述: C:\Users\22427\AndroidStudioProjects\chatgpt_academic-version2.68-3\private_upload\2023-04-17-23-12-10\MiniServer0精简33.zip.extract\MiniServer0\getdata-service\src\main\java\com\liangjinglin\getdataservice\utils\TemHum.java

这是一个Java程序文件，文件名为TemHum.java，路径是MiniServer0精简33.zip.extract\MiniServer0\getdata-service\src\main\java\com\liangjinglin\getdataservice\utils\。它包含一个名为TemHum的类，具有两个成员变量temperature和humidity，以及两个构造函数（一个带参数，一个不带参数）。这个类还使用了Lombok库的@Data注解，自动生成getter和setter方法。该类可能是一个用于存储温度和湿度值的实用工具类，可以被其他类调用来读取或写入这些值。

**Comment by binary-husky** [comment]
- 请运行pip install -r requirements.txt回滚gradio的版本
- 请更新最新代码，新版代码中config.py可以配置并行线程数（免费用户只能设为3或者更低）

**Comment by king0billy** [comment]
1.消息队列被“我上传了文件，请查收”无限刷屏   也是靠回滚gradio版本解决吗
2.一直是最新2.68版本  也没改默认配置并行线程数3

**Comment by king0billy** [comment]
> * 请运行pip install -r requirements.txt回滚gradio的版本
> * 请更新最新代码，新版代码中config.py可以配置并行线程数（免费用户只能设为3或者更低）

1.消息队列被“我上传了文件，请查收”无限刷屏 也是靠回滚gradio版本解决吗
2.一直是最新2.68版本 也没改默认配置并行线程数3

**Comment by king0billy** [comment]
我现在的gradio版本是 gradio-3.27.0-py3-none-any，requirement里面写了“ gradio>=3.25.0 ”，如果要回滚回滚到什么版本

> > * 请运行pip install -r requirements.txt回滚gradio的版本
> > * 请更新最新代码，新版代码中config.py可以配置并行线程数（免费用户只能设为3或者更低）
> 
> 1.消息队列被“我上传了文件，请查收”无限刷屏 也是靠回滚gradio版本解决吗 2.一直是最新2.68版本 也没改默认配置并行线程数3

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/232712813-c4d37ec4-9739-499c-8afc-bde537dec332.png)

**Comment by king0billy** [comment]
> ![image](https://user-images.githubusercontent.com/96192199/232712813-c4d37ec4-9739-499c-8afc-bde537dec332.png)

1.需要去下载一个低版本的gradio吗？
2.先 pip install gradio-3.25.0-py3-none-any.whl吗？
3.要把requirement里面的>=3.25改成=3.25吗

**Comment by king0billy** [comment]
1.需要去下载一个低版本的gradio吗？
2.先 pip install gradio-3.25.0-py3-none-any.whl吗？
3.要把requirement里面的>=3.25改成=3.25吗

> ![image](https://user-images.githubusercontent.com/96192199/232712813-c4d37ec4-9739-499c-8afc-bde537dec332.png)

**Comment by binary-husky** [comment]
- 更新最新代码
- 清理pip源，替换为官方源或阿里源，杜绝使用某些大学的pip源
- 运行pip install -r requirements.txt一键回滚gradio的版本
