### ISSUE TITLE
请教一下怎么开启自动更新

### ISSUE THREAD

**Issue by aizensuk** [binary-husky/gpt_academic#527]
请教一下怎么开启自动更新

**Comment by binary-husky** [comment]
- 自动更新在main.py运行时自动触发。如果不触发，直接去github下载新版解压覆盖即可
- 如果很想用自动更新，请尝试在check_proxy.py中把timeout加大
![image](https://user-images.githubusercontent.com/96192199/233009962-948a131a-0c59-4cc5-87e5-8af79220b75d.png)

**Comment by aizensuk** [comment]
谢谢大佬

**Comment by yibowan19** [comment]
如何去解压覆盖原文件，是指把config文件换成原来的吗？ 谢谢

**Comment by binary-husky** [comment]
> 如何去解压覆盖原文件，是指把config文件换成原来的吗？ 谢谢

@BOBW-Y @aizensuk 
- 如果之前配置用了`config_private.py`，直接无脑覆盖就行
- 如果没有，先把`config.py`重命名为`config_private.py`，然后覆盖
