### ISSUE TITLE
增加对API2D

### ISSUE THREAD

**Issue by Xiaoyuyoupang** [binary-husky/gpt_academic#529]

**Comment by Xiaoyuyoupang** [comment]
能否加入对API2D的API支持，毕竟好多人还没来得及注册现在玩不了 好难受呀

**Comment by Xiaoyuyoupang** [comment]
我刚更新到3.1呀 那可能是我设置出了问题 哈哈 我去看看

**Comment by CCTVastu** [comment]
![image](https://user-images.githubusercontent.com/113247074/233566578-75b9417b-2006-448e-b1ce-10cff7153ff2.png)
![image](https://user-images.githubusercontent.com/113247074/233566587-2709a087-75e5-4e7e-a382-38a1110d736a.png)
使用API2D的API时候，一直出现图中问题，应该怎么修改

**Comment by binary-husky** [comment]
> 使用API2D的API时候，一直出现图中问题，应该怎么修改

@CCTVastu 先切换

![image](https://user-images.githubusercontent.com/96192199/233612870-b1db8390-12e9-424b-bc72-53f6450dbd0b.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/233613078-638d8bf6-43a2-4763-a3c6-299059f628b0.png)

**Comment by CCTVastu** [comment]
> ![image](https://user-images.githubusercontent.com/96192199/233613078-638d8bf6-43a2-4763-a3c6-299059f628b0.png)

非常感谢~
