### ISSUE TITLE
解决腾讯云安装最新的 python 包报错问题

### ISSUE THREAD

**Issue by yoa1226** [binary-husky/gpt_academic#565]
# 解决腾讯云安装最新的 python 包报错问题

## 问题引入

而我在本地却能够正常， 安装相关 Python 云服务报下面的错误。

> No matching distribution found for gradio==3.23

在查阅相关资料后仍没有解决。于是猜想是不是 Python 版本的问题。本地电脑 Python 版本是：

```shell
➜  ~ python3 -V
Python 3.9.6
```

云服务器 Python 版本是：

```shell
～ python3 -V
Python 3.6.8
```

## 重要环境说明

- 云服务厂商: 腾讯云
- OS: CentOS7.6
- 云服务 Python 版本: 3.6.8

## 重装 Python

安装 Python 主要是参考一下文章:

[腾讯云服务器如何安装Python的运行环境？ - 酒坛坛儿的回答 - 知乎](https://www.zhihu.com/question/276285094/answer/1573284386)

[centos 安装python3.8报错](https://blog.csdn.net/qq_36664203/article/details/106301856)

下载解压

``` shell
# 下载安装包
wget https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz

# 解压缩
tar -zxf Python-3.9.9.tgz
```

OS 环境准备

执行下面的更新操作系统的包

```
yum -y install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel
```

特别注意必须安装下面的包

```shell
yum install libffi-devel
```

不然会在 Python 安装其他包的时候报下面的错误

> ModuleNotFoundError: No module named '_ctypes'

设置 Python 安装路径

```shell
cd  Python-3.9.9

./configure --prefix=/usr/local/python39
```

注意 **不能** 添加 ` --enable-optimizations` 参数， 不然会报下面的错误。

> returned NULL without setting an error generate-posix-vars failed

安装 Python

```shell
# 这一步需要几分钟的时间
make clean & make && make install
```

安装后配置

``` shell
# 创建启动软连接
ln -s /usr/local/python39/bin/python3.9 /usr/bin/python39

# 安装pip
python39 -m pip install -U pip

# 创建python3.x对应的pip软连接
ln -s /usr/local/python39/bin/pip /usr/bin/pip39
```

查看版本

```shell
~ python39 -V
Python 3.9.9
```

## 安装 python 包

```shell
python39 -m pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
```

**Comment by binary-husky** [comment]
3Q! I will add this issue to wiki https://github.com/binary-husky/chatgpt_academic/wiki/%E4%BA%91%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9C%E7%A8%8B%E9%83%A8%E7%BD%B2%E6%8C%87%E5%8D%97

**Comment by wangguijiepedeval** [comment]
请问一下，找不到模块“_bz2”，但是已经下载了bzip2-devel是怎么回事呢？:(
详细报错： File "/usr/local/python39/lib/python3.9/bz2.py", line 18, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
