### ISSUE TITLE
聊天时鬼畜【gradio有bug，需要降级到requirements.txt指定的版本】

### ISSUE THREAD

**Issue by Kimagure7** [binary-husky/gpt_academic#569]
- **(1) Describe the bug 简述**
表现为每当chatgpt生成新的文字时，右侧滚动条疯狂鬼畜，同时对话框给我一种不断删除再新建的样子。此外，上传文件后会反复刷提示框

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/100174610/233770268-10daf419-f49d-42bc-aeff-eb5530a02c14.png)

- **(3) Terminal Traceback 终端traceback（如有）**
无报错，仅鬼畜

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by Kimagure7** [comment]
当然最后是能成功运行的，但结果有点鬼畜

**Comment by binary-husky** [comment]
gradio新版本有bug，降级到我们requirement.txt要求的版本

**Comment by Kizai** [comment]
降级到3.25.0还是会鬼畜
