### ISSUE TITLE
支持使用本地chatglm模型吗，可以更改本地模型路径吗

### ISSUE THREAD

**Issue by abigkeep** [binary-husky/gpt_academic#572]
支持使用本地chatglm模型吗，可以更改本地模型路径吗

**Comment by binary-husky** [comment]
缓存模型的位置是自动的
`C:\Users\username\.cache\huggingface\hub\models--THUDM--chatglm-6b`

**Comment by liliaoyuan** [comment]
> 缓存模型的位置是自动的 `C:\Users\username\.cache\huggingface\hub\models--THUDM--chatglm-6b`

请问一下plus修改模型是在config文件里面修改这行代码吗
LLM_MODEL = "gpt-3.5-turbo"  =》LLM_MODEL = "gpt-4"

**Comment by qiujunhan** [comment]
![QQ截图20230424113913](https://user-images.githubusercontent.com/38062062/233894981-971a8d6f-09c1-4e38-a568-e3a70aaea741.png)
