### ISSUE TITLE
建议如果用GPT-4的model，可以加上图像互动的功能

### ISSUE THREAD

**Issue by wlp233** [binary-husky/gpt_academic#574]

**Comment by KangtanC** [comment]
怎么用chatGPT4的model啊？

**Comment by liliaoyuan** [comment]
> _No description provided._

请问是开了plus后面修改这部分代码：
LLM_MODEL = "gpt-3.5-turbo" => LLM_MODEL = "gpt4"

**Comment by wlp233** [comment]
我用的也是APID的GPT-4，openai的申请还没有到

**Comment by hanhantie233** [comment]
> 为何我修改为gpt-4后显示模型不存在呀

你解决了吗？我也是这个问题
