### ISSUE TITLE
newbing模型三种模式在webui中直接选取

### ISSUE THREAD

**Issue by DefensiveSniper** [binary-husky/gpt_academic#575]
本想看看初始是哪种模式，翻阅代码找到
![GK2LBPJ4W%A7V{Z}X0EO4V7](https://user-images.githubusercontent.com/105640670/233827018-4228da71-f248-4ae1-9ee4-aa1f59713a31.png)
每次改模式是不是需要关闭程序重新开启？

**Comment by binary-husky** [comment]
目前是的，这种模拟浏览器的api调用方式限制很大

另外这几种模式有什么不同吗

**Comment by DefensiveSniper** [comment]
creative适用于聊天娱乐
balanced感觉有点四不像
precise可以问一些学术上的问题

**Comment by zdevc** [comment]
creative创作风格，感觉生成的内容更详实一些，其他两种风格几句话就结束了

**Comment by DefensiveSniper** [comment]
> 目前是的，这种模拟浏览器的api调用方式限制很大
> 
> 另外这几种模式有什么不同吗

creative适用于聊天娱乐
balanced感觉有点四不像
precise可以问一些学术上的问题
