### ISSUE TITLE
文件上传超过1M就一直显示uploading

### ISSUE THREAD

**Issue by reckonzzz** [binary-husky/gpt_academic#582]
- **(1) Describe the bug 简述**
上传文件小于1M时均可快速上传，当文件大于1M时，始终显示Uploading而不会上传

- **(2) Screen Shot 截图**
<img width="368" alt="longer" src="https://user-images.githubusercontent.com/20457530/233858025-9d9b37a4-5f84-42d2-ba49-4eda58768ee3.png">

- **(3) Terminal Traceback 终端traceback（如有）**
docker logs并没有显示任何报错等（没有相关记录出现）

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**
可以上传：
[long.pdf](https://github.com/binary-husky/chatgpt_academic/files/11304544/long.pdf)
无法成功上传：
[longer.pdf](https://github.com/binary-husky/chatgpt_academic/files/11304543/longer.pdf)

**Comment by binary-husky** [comment]
gradio版本？是否满足requirements.txt的要求？

**Comment by reckonzzz** [comment]
gradio                    3.25.0                   pypi_0    pypi
gradio-client             0.1.3                    pypi_0    pypi

**Comment by reckonzzz** [comment]
测试过了，直接部署和用docker部署都是超过1M就无法上传，不清楚原因是什么。

**Comment by doveppp** [comment]
我docker也是这样

**Comment by doveppp** [comment]
![image](https://user-images.githubusercontent.com/54977106/234586743-b3a73de8-3f1d-4f1e-9f95-f6b11de635e8.png)

**Comment by wangfeng35** [comment]
上传个10M的文件就一直卡在Uploading

**Comment by ryanzhang2022** [comment]
修改nginx配置
client_max_body_size 20M;

**Comment by GrootLiu** [comment]
在 nginx 设置中找到 server 块，在其中添加：
``` sh
client_max_body_size 100m;
client_body_timeout 120s;
```
然后重新加载 nginx 配置：
``` sh
sudo service nginx reload
sudo systemctl reload nginx
```
