### ISSUE TITLE
[Local Message] 异常：OpenAI拒绝了请求：

### ISSUE THREAD

**Issue by isZhanqianqian** [binary-husky/gpt_academic#585]
- **(1) Describe the bug 简述**
[Local Message] 异常：OpenAI拒绝了请求：{ "error": { "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-gXutWuGvd6GLe01dIA8eqHtl on requests per min. Limit: 3 / min. Please try again in 20s. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.", "type": "requests", "param": null, "code": null }}.

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/84821239/233882438-da620fab-ea64-4412-b2e1-65a8355b82b4.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/233893976-4ab8935a-2947-44cf-98be-6853c3258a64.png)
