### ISSUE TITLE
chatglm停止重置功能完全失效

### ISSUE THREAD

**Issue by qiujunhan** [binary-husky/gpt_academic#588]
- **(1) Describe the bug 简述**
输入比较长的内容就容易测试出来

- **(2) Screen Shot 截图**
通过调试发现，即使点击停止，重置，更改输入框内容，再次运行仍然是上一次的history
![QQ截图20230424113459](https://user-images.githubusercontent.com/38062062/233894434-6930c13f-f03e-4a43-b185-e431e0ffd1c6.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**
例如输入以下内容，过会后点击停止，重置，再次运行，他会从上次的结果继续输出，即使更换文本内容也是这样
翻译成中文
# STA 208: Homework 1 (Do not distribute)

## Due 04/28/2023 midnight (11:59pm)

__Instructions:__ 

1. Submit your homework using one file name ”LastName_FirstName hw1.html” on canvas. 
2. The written portions can be either done in markdown and TeX in new cells or written by hand and scanned. Using TeX is strongly preferred. However, if you have scanned solutions for handwriting, you can submit a zip file. Please make sure your handwriting is clear and readable and your scanned files are displayed properly in your jupyter notebook. 
3. Your code should be readable; writing a piece of code should be compared to writing a page of a book. Adopt the one-statement-per-line rule. Consider splitting a lengthy statement into multiple lines to improve readability. (You will lose one point for each line that does not follow the one-statementper-line rule)
4. To help understand and maintain code, you should always add comments to explain your code. (homework with no comments will receive 0 points). For a very long comment, please break it into multiple lines.
5. In your Jupyter Notebook, put your answers in new cells after each exercise. You can make as many new cells as you like. Use code cells for code and Markdown cells for text.
6. Please make sure to print out the necessary results to avoid losing points. We should not run your code to figure out your answers. 
7. However, also make sure we are able to open this notebook and run everything here by running the cells in sequence; in case that the TA wants to check the details.
8. You will be graded on correctness of your math, code efficiency and succinctness, and conclusions and modelling decisions

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
推测是上一次的输出没结束，长文本相关的bug？

**Comment by qiujunhan** [comment]
> 

应该和长文本无关，就是输出中途停止重置后，再次运行还是会从上次的输出中继续

**Comment by binary-husky** [comment]
> > 
> 
> 应该和长文本无关，就是输出中途停止重置后，再次运行还是会从上次的输出中继续

是的，目前存在这个问题，终止命令没发送到子进程那边，这个需要时间完善

**Comment by qiujunhan** [comment]
> 

辛苦大佬
