### ISSUE TITLE
PDF批量上传显示tiktoken未安装

### ISSUE THREAD

**Issue by liliaoyuan** [binary-husky/gpt_academic#591]
上传PDF进行总结时，提示运行 pip install --upgrade pymupdf tiktoken

![image](https://user-images.githubusercontent.com/34170909/233939291-4d631a7e-2ebb-4ab2-b193-139fdf5e414d.png)

显示ERROR: Ignored the following versions that require a different python version: 0.1.1 Requires-Python >=3.9; 0.1.2 Requires-Python >=3.8; 0.2.0 Requ

我自己python是3.7.4
请问一定需要更新版本吗，考虑很多包更新之后不能用

**Comment by StarCode000** [comment]
可以安装一个最新版本的python，可以同时存在多个版本的
