### ISSUE TITLE
成功运行但被防火墙阻止，请问如何解决

### ISSUE THREAD

**Issue by kevinlzk** [binary-husky/gpt_academic#593]
- **(1)跳转网页时无法打开**
系统为Windows10，已经尝试了一些方法，但均无法通过浏览器打开

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/56974734/233962728-06e7ae82-6bd8-4b8d-a969-26c71f6da303.png)
![image](https://user-images.githubusercontent.com/56974734/233962774-d3879827-96d4-4488-8f17-119f8d871204.png)

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
关掉代理/调整代理模式试试？
