### ISSUE TITLE
想问一问，有没有保存历史对话的功能呢？就类似chatGPT网页左边的那种。。。

### ISSUE THREAD

**Issue by ShaySheng** [binary-husky/gpt_academic#597]
如果有的话，我该怎样使用这个功能呢？如果没有，是否有可能改进添加上这个功能呢😂

**Comment by binary-husky** [comment]
插件下拉菜单里有

**Comment by binary-husky** [comment]
> 插件下拉菜单里有

目前是保存为html本地文件

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/234166176-e01fceec-7880-40e2-9def-234b7646a519.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/234166220-daa66585-6aa6-4fe9-ac49-c23114c99ae0.png)

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/234166286-13f23b9e-fd12-49fa-b7d7-5e4d22121d16.png)

**Comment by ShaySheng** [comment]
如何能继续上次对话就好了，就类似于chatGPT网页的左边那种

**Comment by RTX10086** [comment]
> > 插件下拉菜单里有
> 
> 目前是保存为html本地文件

同求多对话切换和保存功能，这个感觉非常有用，因为很多时候都是几篇论文同时读，先问问关于论文A的，再问问关于论文B的。然后第二天要是想起来了，还可以在中断的地方继续（就不用再解析一遍PDF了！！）

谢谢大佬！

**Comment by binary-husky** [comment]
> 如何能继续上次对话就好了，就类似于chatGPT网页的左边那种

@ShaySheng @RTX10086 新版加了保存+恢复功能
