### ISSUE TITLE
在NEW BING模型下使用基础功能区有概率会不返回结果

### ISSUE THREAD

**Issue by Autoo2017** [binary-husky/gpt_academic#598]
- **(1) Describe the bug 简述**
在NEW BING模型下使用基础功能区大概率会不返回结果

- **(2) Screen Shot 截图**
![SharedScreenshot](https://user-images.githubusercontent.com/27143798/234027242-84c725ab-adc7-4270-a117-0efbf7fe9a1b.jpg)

- **(3) Terminal Traceback 终端traceback（如有）**
![cmd](https://user-images.githubusercontent.com/27143798/234027258-796042fc-1a80-401e-b4a7-0dfa7d28b693.jpg)

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

**Comment by Autoo2017** [comment]
NEWBING_STYLE 是 "precise"

**Comment by ShaySheng** [comment]
new_bing模型是什么，怎么设置啊

**Comment by Autoo2017** [comment]
> new_bing模型是什么，怎么设置啊

更新了之后在config.py或者config_private.py最下面设置new bing的cookies就行

**Comment by zff168** [comment]
> > new_bing模型是什么，怎么设置啊
> 
> 更新了之后在config.py或者config_private.py最下面设置new bing的cookies就行

请问去哪里查看new bing的cookies？

**Comment by sunchongwei** [comment]
newbing_cookies具体是哪些内容，我的为什么显示cookie不正确

**Comment by sunchongwei** [comment]
> 

已解决

**Comment by zdevc** [comment]
> new_bing模型是什么，怎么设置啊
> newbing_cookies具体是哪些内容，我的为什么显示cookie不正确

- 要求
一个已经通过候补名单的微软账户 https://bing.com/chat (必填)
需要在 New Bing 支持的国家（中国大陆需使用VPN）

- 检查访问权限 (必需)
安装最新版本的 Microsoft Edge
或者, 您可以使用任何浏览器并将用户代理设置为Edge的用户代理 (例如Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) [Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg)/111.0.0.0 Safari/537.36 Edg/111.0.1661.51). 您可以使用像 "User-Agent Switcher and Manager" Chrome 和 [Firefox](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/) 这样的扩展轻松完成此操作.
打开 [bing.com/chat](https://bing.com/chat)
如果您未跳转至cn.bing.com，且可以看到聊天功能，就准备就绪

- 获取身份验证 (必需)
打开edge、chrome或firefox浏览器扩展商店，安装 cookie editor 扩展
移步到 bing.com
打开扩展程序
点击右下角的"导出" (将会把内容保存到你的剪贴板上)
找到config.py文件中NEWBING_COOKIES = """your bing cookies here"""，粘贴全部内容替换“your bing cookies here”

- 参考https://github.com/acheong08/EdgeGPT/blob/master/docs/README_zh.md
