### ISSUE TITLE
账户里面还有余额，但是提示拒绝服务

### ISSUE THREAD

**Issue by lyq627** [binary-husky/gpt_academic#603]
- **(1) Describe the bug 简述**
账户里面还有余额，但是提示拒绝服务？

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/35457106/234156155-d18c0010-a4df-458a-85fc-e6a326349640.png)

![image](https://user-images.githubusercontent.com/35457106/234156070-623c3f21-62fd-40c8-8a06-0b05ce3b7b85.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by StarCode000** [comment]
你可以查查expired是什么意思

**Comment by StarCode000** [comment]
免费额度已经过期，你需要绑定国外的有效银行卡，并且保证银行卡内至少有5美元才能继续使用API
