### ISSUE TITLE
对话区对于“*”符号的识别问题，主要影响对于Excel公式的复制输出。

### ISSUE THREAD

**Issue by yinjiashu** [binary-husky/gpt_academic#612]
- **(1) Describe the bug 简述**
如果gpt的输出存在“ * ”的话，在对话框处有很大概率不会识别、显示，使得复制结果的时候会缺少“ * ”符号，主要问题是出在关于Excel公式的回答过程中。
作为对比，Vscode中的genie插件可以输出“ * ”，至少可以正确将公式复制出，猜测是在“*”前后自动添加了空格。
另，本插件及时输入时在“ * ”前后添加了英文空格，在输入框界面仍然不显示“ * ”符号。
- **(2) Screen Shot 截图**
chatgpt_academic
![image](https://user-images.githubusercontent.com/116946335/234203384-f01ddc03-dca2-480c-820a-8f9cf621049d.png)

vscode的genie
![image](https://user-images.githubusercontent.com/116946335/234204293-67f3b9af-8325-4096-8a88-58ba6ecb724c.png)

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**
给出 1 * 2 * 3 * 75 * 84 * 6 的分步计算过程。

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
@yinjiashu  这个是和markdown的斜体/加粗语法冲突了，修正这个bug需要时间进行大量测试

目前比较方便的workaround有以下两种：
1. 修改prompt
![image](https://user-images.githubusercontent.com/96192199/234615832-687a13d1-57eb-4042-9aa2-4bf30ff340b8.png)

2. 修改system prompt
![image](https://user-images.githubusercontent.com/96192199/234616815-229dde43-45e3-45e2-a650-14b83842fb2e.png)
