### ISSUE TITLE
本地部署时，谷歌学术和谷歌搜索的功能均无效，需要修改什么设置？

### ISSUE THREAD

**Issue by reckonzzz** [binary-husky/gpt_academic#616]
- **(1) Describe the bug 简述**
如题，但是在huggingface里没有问题

- **(2) Screen Shot 截图**
<img width="1125" alt="longer" src="https://user-images.githubusercontent.com/20457530/234240044-c2ff6f16-86cf-4e8b-b694-7ce6db6d2b6e.png">

**Comment by binary-husky** [comment]
config.py 中的 proxies 设置

**Comment by UOYIII** [comment]
> 感谢回复，我已经排查出来了，因为我用的RackNerd服务器，ip在google和scholar受限，所以我改了请求的函数代码，网址挂的是我自己部署的Google和scholar。

您好，我也遇到了这个问题，请问具体是怎么解决的呀
