### ISSUE TITLE
多人在不同窗口先后请求newbing，部分请求被丢弃，页面不再响应，建议完善消息排队或请求限制

### ISSUE THREAD

**Issue by zdevc** [binary-husky/gpt_academic#618]
- **(1) Describe the bug 简述**

多人在不同窗口先后请求newbing，部分请求被丢弃，页面不再响应，建议完善消息排队或请求限制

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/40593221/234268192-b80e47b9-0f84-4255-bf3f-d94669224519.png)

![image](https://user-images.githubusercontent.com/40593221/234268120-ad88db64-8d51-4a23-a72e-914c42da1501.png)
![image](https://user-images.githubusercontent.com/40593221/234268703-533a379d-3b33-465a-aaa4-1a8947d5e7c5.png)
- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**
1、设置 main.py lanch()中 share=True 启用临时公网地址
2、多台设备、窗口打开公网地址
3、第一人提问，收到响应时，第二人、第三人在各自窗口开始提问
如何做炒面
如何做炒饭
如何蒸馒头

**Comment by binary-husky** [comment]
目前用了线程锁，所以不能同时请求


![image](https://user-images.githubusercontent.com/96192199/234454972-97d8e4a9-8bc1-461d-96b0-10671db5cf45.png)

**Comment by changecool** [comment]
请问NEWBING_COOKIES在哪找啊？

**Comment by zdevc** [comment]
> 请问NEWBING_COOKIES在哪找啊？
> 

- 要求
一个已经通过候补名单的微软账户 https://bing.com/chat （必填）
需要在 New Bing 支持的国家（中国大陆需使用VPN）

- 检查访问权限 （必需）
安装最新版本的 Microsoft Edge
或者， 您可以使用任何浏览器并将用户代理设置为Edge的用户代理 (例如Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) [Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg)/111.0.0.0 Safari/537.36 Edge/111.0.1661.51）。 您可以使用像 "User-Agent Switcher and Manager" Chrome 和 [Firefox]（https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/） 这样的扩展轻松完成此操作。
打开 [bing.com/chat]（https://bing.com/chat）
如果您未跳转至cn.bing.com，且可以看到聊天功能，就准备就绪

- 获取身份验证 （必需）
打开edge、chrome或firefox浏览器扩展商店，安装 cookie editor 扩展
移步到 bing.com
打开扩展程序
点击右下角的“导出为JSON" （将会把内容保存到你的剪贴板上）
找到config.py文件中NEWBING_COOKIES = """your bing cookies here"""，粘贴全部内容替换“your bing cookies here”

- 参考https://github.com/acheong08/EdgeGPT/blob/master/docs/README_zh.md
