### ISSUE TITLE
想问问newbing的cookies怎么填写，我从javascript:alert(document.cookie)找到了cookies但是一直显示cookies有错

### ISSUE THREAD

**Issue by wlp233** [binary-husky/gpt_academic#620]
![image](https://user-images.githubusercontent.com/73226302/234341095-273ea6e0-aadc-4e19-8966-05709d61f9b1.png)
![image](https://user-images.githubusercontent.com/73226302/234341151-017d0634-620a-4377-b972-ddb2d7a22d2a.png)

**Comment by wlp233** [comment]
从网页上用newbing是正常的

**Comment by wlp233** [comment]
是不是因为我用到是py311

**Comment by zdevc** [comment]
- 要求
一个已经通过候补名单的微软账户 https://bing.com/chat （必填）
需要在 New Bing 支持的国家（中国大陆需使用VPN）

- 检查访问权限 （必需）
安装最新版本的 Microsoft Edge
或者， 您可以使用任何浏览器并将用户代理设置为Edge的用户代理 (例如Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) [Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg)/111.0.0.0 Safari/537.36 Edge/111.0.1661.51）。 您可以使用像 "User-Agent Switcher and Manager" Chrome 和 [Firefox]（https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/） 这样的扩展轻松完成此操作。
打开 [bing.com/chat]（https://bing.com/chat）
如果您未跳转至cn.bing.com，且可以看到聊天功能，就准备就绪

- 获取身份验证 （必需）
打开edge、chrome或firefox浏览器扩展商店，安装 cookie editor 扩展
移步到 bing.com
打开扩展程序
点击右下角的“导出为JSON" （将会把内容保存到你的剪贴板上）
找到config.py文件中NEWBING_COOKIES = """your bing cookies here"""，粘贴全部内容替换“your bing cookies here”

- 参考https://github.com/acheong08/EdgeGPT/blob/master/docs/README_zh.md

**Comment by wlp233** [comment]
搞定了，感谢！

> * 要求
>   一个已经通过候补名单的微软账户 https://bing.com/chat （必填）
>   需要在 New Bing 支持的国家（中国大陆需使用VPN）
> * 检查访问权限 （必需）
>   安装最新版本的 Microsoft Edge
>   或者， 您可以使用任何浏览器并将用户代理设置为Edge的用户代理 (例如Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) [Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg)/111.0.0.0 Safari/537.36 Edge/111.0.1661.51）。 您可以使用像 "User-Agent Switcher and Manager" Chrome 和 [Firefox]（[https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/）](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/%EF%BC%89) 这样的扩展轻松完成此操作。
>   打开 [bing.com/chat]（[https://bing.com/chat）](https://bing.com/chat%EF%BC%89)
>   如果您未跳转至cn.bing.com，且可以看到聊天功能，就准备就绪
> * 获取身份验证 （必需）
>   打开edge、chrome或firefox浏览器扩展商店，安装 cookie editor 扩展
>   移步到 bing.com
>   打开扩展程序
>   点击右下角的“导出为JSON" （将会把内容保存到你的剪贴板上）
>   找到config.py文件中NEWBING_COOKIES = """your bing cookies here"""，粘贴全部内容替换“your bing cookies here”
> * 参考https://github.com/acheong08/EdgeGPT/blob/master/docs/README_zh.md

搞定了，感谢！

**Comment by EdisonWendy** [comment]
请问导出JSON后"your bing cookies here"替换的是里面的哪一个字段内容啊？

**Comment by zdevc** [comment]
> 请问导出JSON后"your bing cookies here"替换的是里面的哪一个字段内容啊？

复制出来的方括号和方括号里的全部，直接粘贴在这

**Comment by EdisonWendy** [comment]
> 

方括号里有一大堆全部复制？

**Comment by EdisonWendy** [comment]
> > 请问导出JSON后"your bing cookies here"替换的是里面的哪一个字段内容啊？
> 
> 复制出来的方括号和方括号里的全部，直接粘贴在这

方括号里面的东西有点多，全部复制吗？

**Comment by zdevc** [comment]
> > > 请问导出JSON后"your bing cookies here"替换的是里面的哪一个字段内容啊？
> > 
> > 复制出来的方括号和方括号里的全部，直接粘贴在这
> 
> 方括号里面的东西有点多，全部复制吗？

是的

**Comment by EdisonWendy** [comment]
> > > > 请问导出JSON后"your bing cookies here"替换的是里面的哪一个字段内容啊？
> > > 
> > > 
> > > 复制出来的方括号和方括号里的全部，直接粘贴在这
> > 
> > 
> > 方括号里面的东西有点多，全部复制吗？
> 
> 是的

要加上方括号吗

**Comment by zdevc** [comment]
> > > > > 请问导出JSON后"your bing cookies here"替换的是里面的哪一个字段内容啊？
> > > > 
> > > > 
> > > > 复制出来的方括号和方括号里的全部，直接粘贴在这
> > > 
> > > 
> > > 方括号里面的东西有点多，全部复制吗？
> > 
> > 是的
> 
> 要加上方括号吗

是的

**Comment by csujia** [comment]
> * 要求
>   一个已经通过候补名单的微软账户 https://bing.com/chat （必填）
>   需要在 New Bing 支持的国家（中国大陆需使用VPN）
> * 检查访问权限 （必需）
>   安装最新版本的 Microsoft Edge
>   或者， 您可以使用任何浏览器并将用户代理设置为Edge的用户代理 (例如Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) [Chrome](https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg)/111.0.0.0 Safari/537.36 Edge/111.0.1661.51）。 您可以使用像 "User-Agent Switcher and Manager" Chrome 和 [Firefox]（[https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/）](https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/%EF%BC%89) 这样的扩展轻松完成此操作。
>   打开 [bing.com/chat]（[https://bing.com/chat）](https://bing.com/chat%EF%BC%89)
>   如果您未跳转至cn.bing.com，且可以看到聊天功能，就准备就绪
> * 获取身份验证 （必需）
>   打开edge、chrome或firefox浏览器扩展商店，安装 cookie editor 扩展
>   移步到 bing.com
>   打开扩展程序
>   点击右下角的“导出为JSON" （将会把内容保存到你的剪贴板上）
>   找到config.py文件中NEWBING_COOKIES = """your bing cookies here"""，粘贴全部内容替换“your bing cookies here”
> * 参考https://github.com/acheong08/EdgeGPT/blob/master/docs/README_zh.md

非常感谢！用这个方法同样成功了！

**Comment by JiashengLiu** [comment]
> 我这返回信息是“'result': {'value': 'Success', 'message': None}}”，是不是除了cookie之外，还要填newbing账号密码的？填到哪儿？我在newbing网页里面用我自己账号可以聊天。

好像不止是newbing，我用ap2id的也没有返回信息，但是ap2id那边显示我的点数有下降.....
