### ISSUE TITLE
请求支持Azure的API

### ISSUE THREAD

**Issue by behinder85** [binary-husky/gpt_academic#621]
现将代理或者是Azure的endpoint和openai的url完成映射后
输入Azure的api key仍旧无法使用

报错如下：
临时解决方案：直接在输入区键入api_key，然后回车提交。

长效解决方案：在config.py中配置。
相关需求也可在#557 和 #252 中找到

**Comment by binary-husky** [comment]
azure的apikey张什么样子呀？

**Comment by binary-husky** [comment]
需要适配一下
![image](https://user-images.githubusercontent.com/96192199/234863673-3337432e-91b8-4fbb-ab28-84507ed36452.png)

**Comment by xhzhu0628** [comment]
> 需要适配一下 ![image](https://user-images.githubusercontent.com/96192199/234863673-3337432e-91b8-4fbb-ab28-84507ed36452.png)

`def is_azure_key(key):
    API_MATCH = re.match(r"[a-zA-Z0-9]{32}$", key)
    return bool(API_MATCH)

def is_openai_api_key(key):
    API_MATCH = re.match(r"sk-[a-zA-Z0-9]{48}$", key)
    return bool(API_MATCH) or is_azure_key(key)
`
我使用https://github.com/haibbo/cf-openai-azure-proxy 的项目进行代理，然后将判断api的位置改成了上面那个样子，暂时是可以用了

**Comment by binary-husky** [comment]
> > > 需要适配一下 
> > 
> > ```python
> > def is_azure_key(key):
> >     API_MATCH = re.match(r"[a-zA-Z0-9]{32}$", key)
> >     return bool(API_MATCH)
> > 
> > def is_openai_api_key(key):
> >     API_MATCH = re.match(r"sk-[a-zA-Z0-9]{48}$", key)
> >     return bool(API_MATCH) or is_azure_key(key)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我使用https://github.com/haibbo/cf-openai-azure-proxy 的项目进行代理，然后将判断api的位置改成了上面那个样子，暂时是可以用了
> 
> 可用！！ 感谢，但希望大大能改进main里

这样改？
```
def is_openai_api_key(key):
    API_MATCH_ORIGINAL = re.match(r"sk-[a-zA-Z0-9]{48}$", key)
    API_MATCH_AZURE = re.match(r"[a-zA-Z0-9]{32}$", key)
    return bool(API_MATCH_ORIGINAL) or bool(API_MATCH_AZURE)
```

**Comment by Moss-qc** [comment]
请问这个问题现在解决了吗？在哪里加代码或者怎样配置才可以使用azure key?

**Comment by jssyzjc** [comment]
> 现将代理或者是Azure的endpoint和openai的url完成映射后 输入Azure的api key仍旧无法使用
> 
> 报错如下： 临时解决方案：直接在输入区键入api_key，然后回车提交。
> 
> 长效解决方案：在config.py中配置。 相关需求也可在#557 和 #252 中找到

请问这个映射是怎么做的

**Comment by XiaojianTang** [comment]
我写了个pull request #795 可以参考下
不需要代理啊，转发啊，也不用别的项目
增加了一个`bridge_azure_test.py`的文件，修改了`bridge_all.py` 把相关的 `model_info` 加了进去，最后在` config.py`中加了相关配置。
这样就可以直接使用了。
应该是改动最小，使用也最简单的方式了。

不过多线程没测试过，大家可以试试。

**Comment by XiaojianTang** [comment]
我是增加了一个` bridge_azure_test.py` 文件，然后在`bridge_all.py`里也加了一个`model_info`，具体的API可以加在`config.py`里。这样也就不用配置什么代理或映射了。在选模型的下拉菜单里，选择`azure`的模型就好了
具体可以看 #797
不过我没测过多线程，所以先取名字叫 `bridge_azure_test `
