### ISSUE TITLE
希望能够在config.py中增加 亮色主题/暗色主题 的默认打开选项

### ISSUE THREAD

**Issue by ShaySheng** [binary-husky/gpt_academic#623]
（亮色主题）: http://localhost:51680
（暗色主题）: http://localhost:51680/?__dark-theme=true

**Comment by ShaySheng** [comment]
就是希望，能一打开就是亮色主题，我比较喜欢亮色主题，每次代码一更新，就需要手动调，挺麻烦的，不如在config.py里面改一个

**Comment by binary-husky** [comment]
@ShaySheng 加了
