### ISSUE TITLE
端口更新

### ISSUE THREAD

**Issue by Nicholasasni** [binary-husky/gpt_academic#624]
每次更换节点时，电脑的局域网端口会自动更换，但是config.py里面的端口不能自动更新，只能每次手动更改，能不能实现端口自动更新？

**Comment by StarCode000** [comment]
能描述的详细点吗？

**Comment by binary-husky** [comment]
> 每次更换节点时，电脑的局域网端口会自动更换，但是config.py里面的端口不能自动更新，只能每次手动更改，能不能实现端口自动更新？

一般不会变的吧……

**Comment by Nicholasasni** [comment]
是我用的软件的问题吗？科学上网软件每次更换节点之后，电脑Internet属性中的局域网设置里的地址后面的端口值会一直改变，导致我config.py文件配置里的协议/地址/端口就需要手动更改数值。不然运行之后，就会说：[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

**Comment by StarCode000** [comment]
https://github.com/binary-husky/gpt_academic/blob/master/config.py

**Comment by Nicholasasni** [comment]
我vpn软件的问题。。。找了半天，我用的软件没有固定端口，每次都变换，换了一个vpn，现在固定不换了。解决了解决了，谢谢
