### ISSUE TITLE
毫无报错，就是卡这一直省略号processing没反应

### ISSUE THREAD

**Issue by changecool** [binary-husky/gpt_academic#625]
- **(1) Describe the bug 简述**
毫无报错，就是卡这没放映，一直等待，等待期间按其他按钮同样无反应，并且打不开折叠区域。api key是我自己的付费账户，没问题，代理配置没问题，我的chatpaper本地部署可用。

- **(2) Screen Shot 截图**
![屏幕截图 2023-04-26 124547](https://user-images.githubusercontent.com/58013379/234472465-c9a0da13-aa15-40ae-80d1-51eb5e952a33.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by changecool** [comment]
![image](https://user-images.githubusercontent.com/58013379/234473289-4169b283-fbf3-4d29-a299-904febf91a9c.png)

**Comment by changecool** [comment]
用回之前的2.68版本则一切正常。目前测试了3.3和3.2都出现一直processing的情况。

**Comment by changecool** [comment]
2.68可以正常对话，但点击本地文件上传 确定上传后 出现同样问题。之前用2.68一切正常

**Comment by changecool** [comment]
![image](https://user-images.githubusercontent.com/58013379/234477671-1a06042b-4074-43b4-8aee-3b520cf08113.png)

**Comment by changecool** [comment]
解决问题，
把EDGE浏览器插件”沉浸式翻译“禁用即可

**Comment by Halflifefa** [comment]
感谢,确实是这个原因
