### ISSUE TITLE
关于网络连接失败的问题

### ISSUE THREAD

**Issue by michael1618** [binary-husky/gpt_academic#627]
将配置文件中的
proxies = {
# [协议]:// [地址] :[端口]
"http": "http：//127.0.0.1:7890",
"https": "https;//127.0.0.1:7890",
}
改为：
proxies = {
# [协议]:// [地址] :[端口]
"http": "127.0.0.1:7890",
"https": "127.0.0.1:7890",
}
不要加 [协议]://

**Comment by michael1618** [comment]
将配置文件中的
proxies = {
        #          [协议]://  [地址]  :[端口]
        "http":  "http：//127.0.0.1:7890",
        "https": "https;//127.0.0.1:7890",
    }
改为：
proxies = {
        #          [协议]://  [地址]  :[端口]
        "http":  "127.0.0.1:7890",
        "https": "127.0.0.1:7890",
    }
不要加   [协议]://

**Comment by ta-xiang** [comment]
好人一生平安

**Comment by binary-husky** [comment]
注意：此方法仅适用 http:// 协议，也可能仅适用于clash
