### ISSUE TITLE
关于ChatGLM部署

### ISSUE THREAD

**Issue by IceCream613** [binary-husky/gpt_academic#628]
您好，在部署 ChatGLM 的时候遇到显存不足的错误。经过查看后发现程序默认采用的是fp16版本的模型。请问能否考虑修改这部分代码，让其可以根据显存容量自动选择不同的版本呢？

**Comment by binary-husky** [comment]
您好，我们欢迎类似的改进PR

**Comment by codeofyu** [comment]
非常重要
