### ISSUE TITLE
能否添加反向代理设置，用社区的url

### ISSUE THREAD

**Issue by SAKURA-LBY** [binary-husky/gpt_academic#629]
能配置下吗？不怎么熟悉python，看不太懂源码hh😄。感谢大神们

**Comment by SAKURA-LBY** [comment]
<img width="966" alt="2023-04-26 21 44 47" src="https://user-images.githubusercontent.com/57472755/234595673-aa4c0b02-d585-4c2f-baf1-3d1ab493bf79.png">

**Comment by SAKURA-LBY** [comment]
没找着，是改API_URL_REDIRECT吗？

**Comment by binary-husky** [comment]
> 没找着，是改API_URL_REDIRECT吗？

是的

**Comment by binary-husky** [comment]
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "在这里填写重定向的社区的URL"}

**Comment by SAKURA-LBY** [comment]
想问下，走代理的话用chatgpt会被封帐号吗？

**Comment by binary-husky** [comment]
没被封过，有个网站whatismyiplookup可以查询ip地址的Fraud Score和Malicious activity，检查您的proxy是否足够干净

**Comment by SAKURA-LBY** [comment]
大神，有推荐的代理嘛😀

**Comment by SAKURA-LBY** [comment]
我有点怕代理软件的ip是动态的，openai会疯
