### ISSUE TITLE
[Local Message] 不能加载Newbing组件 ValueError: Unknown scheme for proxy URL URL('127.0.0.1:7890')

### ISSUE THREAD

**Issue by changecool** [binary-husky/gpt_academic#630]
- **(1) Describe the bug 简述**

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/58013379/234595444-6f76dcc5-8507-421c-8c76-a416583d5cc4.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by zdevc** [comment]
![image](https://user-images.githubusercontent.com/40593221/234746929-3db29c5f-f2f8-4351-b1de-68107f9bd530.png)
格式填对了没

**Comment by Edelweissor** [comment]
+1，同样的问题

**Comment by YH721** [comment]
同样的问题，解决了吗@Edelweissor

**Comment by YH721** [comment]
> ![image](https://user-images.githubusercontent.com/40593221/234746929-3db29c5f-f2f8-4351-b1de-68107f9bd530.png)
> 格式填对了没

加上之后又会出现其他错误

**Comment by zhaobudaomingzi** [comment]
请问解决问题了吗

**Comment by YH721** [comment]
解决了，不好用然后就没用
