### ISSUE TITLE
使用Dockerfile+ChatGLM编译镜像运行，没法加载config_private.py里newbing的cookie，导致newbing没法使用

### ISSUE THREAD

**Issue by ShayDuane** [binary-husky/gpt_academic#632]

**Comment by RuSignalFlag** [comment]
<img width="773" alt="1682521820303" src="https://user-images.githubusercontent.com/78648337/234620359-7be77b23-e63d-46a1-93b4-a985abbf702a.png">
不知道这样改一下是否正确

**Comment by RuSignalFlag** [comment]
<img width="674" alt="1682523325314" src="https://user-images.githubusercontent.com/78648337/234627216-ba29e156-b737-4510-9c6f-cd01c44d219c.png">
或者可以这么写吗

**Comment by binary-husky** [comment]
> 或者可以这么写吗，还有仓库名不是改成了gpt_academic，上面克隆仓库的url是不是也得改一下

cookie好像失效的很快😂，您可以运行之前进容器做一些调整: 
```
docker run --rm -it --net=host --gpus="0" gpt-academic bash   # 进入容器，但不启动
nano config_private.py  # 修改cookies
tmux # 打开一个长效终端
python3 main.py   # 在tmux中运行
# ctrl+b 然后 ctrl +d 退出，留下程序在tmux中运行
```

**Comment by binary-husky** [comment]
> > 或者可以这么写吗，还有仓库名不是改成了gpt_academic，上面克隆仓库的url是不是也得改一下
> 
> cookie好像失效的很快😂，您可以运行之前进容器做一些调整:
> 
> ```
> docker run --rm -it --net=host --gpus="0" gpt-academic bash   # 进入容器，但不启动gpt_academic
> nano config_private.py  # 修改cookies
> tmux # 打开一个长效终端
> python3 main.py   # 在tmux中运行
> # ctrl+b 然后 ctrl +d 退出，留下程序在tmux中运行
> ```
