### ISSUE TITLE
显存或统一内存的占用大小问题？

### ISSUE THREAD

**Issue by cloudsummer** [binary-husky/gpt_academic#634]
- **(1) Describe the bug 简述**
-想请问下大家使用 gpt、glm 时候显存或者统一内存都占用多少？
我在 arm 版本的mac上（64G 内存 m1Max）glm统一内存（显存）占用随着使用 python版本有着显著变化：
如果用 python3.9刚开glm的时候占用12-14G，用 python3.10 刚打开就是21-22G统一内存（显存），为啥不同 python 的版本区别这么大？差接近一倍的占用。
- **(2) Screen Shot 截图**
<img width="275" alt="image" src="https://user-images.githubusercontent.com/24847317/234694115-e079c7a9-dc35-4528-ad4c-3649db34187c.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/24847317/234694138-dacc608f-b164-448f-97cb-c31a6a561049.png">

**Comment by xy317272** [comment]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/24847317/234710430-8e43a36b-2854-40d7-9a65-4f0241701cb3.png">
不知道是不是设置的问题，我这个在运行的时候，统一内存会爆表
