### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by Xiaoyuyoupang** [binary-husky/gpt_academic#636]
- **(1) Describe the bug 简述**

3.1 和3.2版本的自动更新都是好用的，不知道为什么这次3.3版本输入之后提示更新失败
- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/103171021/234745577-3a7b514f-13d3-4ef5-b261-efc4087891f1.png)
- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
自动更新模块需要连接github，一旦超时就会这样子。
手动下载代码，然后全部覆盖效果是一样一样的
