### ISSUE TITLE
markdown英译中更能很有用，翻译后的文本总是会加入翻译 private_upload/2023-04-27-10-39-20\CHANGELOG.md.part-0.md，怎么不要类似的话

### ISSUE THREAD

**Issue by jian1929** [binary-husky/gpt_academic#637]
# chatGPT 分析报告

## 翻译 private_upload/2023-04-27-10-39-20\CHANGELOG.md.part-0.md

一直到  

翻译 private_upload/2023-04-27-10-39-20\CHANGELOG.md.part-128.md

怎么在生成的文本中不显示这行字，一行一行的删除太麻烦

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/blob/master/crazy_functions/%E6%89%B9%E9%87%8FMarkdown%E7%BF%BB%E8%AF%91.py

64行` inputs_show_user_array = [f"翻译 {f}" for f in pfg.sp_file_tag]`
改成 ` inputs_show_user_array = [f"" for f in pfg.sp_file_tag]`

**Comment by binary-husky** [comment]
你也可以在vscode中打开分析报告
- 光标选中“翻译 private_upload”
- 按死ctrl+D全选
- 键盘左箭头脱离选中
- 最后ctrl+x全部删除

**Comment by jian1929** [comment]
感谢，两种方式了下，都不行，第一种还是在翻译的文本里有这个内容，第二个快捷键只能删除单行，有很多行，能不能看看代码需要怎么改才能运行？

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/235048557-aba8dc31-cd6d-419f-9138-34702678d439.png)
这两个地方都要删

第二种方法要摁死ctrl+D就可以选多行了
