### ISSUE TITLE
自定义url的格式没看懂，是下面的哪一种？

### ISSUE THREAD

**Issue by jian1929** [binary-husky/gpt_academic#638]
# 重新URL重新定向，实现更换API_URL的作用（常规情况下，不要修改!!）
# 格式 {"https://api.openai.com/v1/chat/completions": "在这里填写重定向的api.openai.com的URL"}
API_URL_REDIRECT = {}

这个自定义的格式没看懂，比如我要将url改成https://api.openai-agent.com/v1/chat/completions，怎么改？
1、API_URL_REDIRECT = {"https://api.openai-agent.com/v1/chat/completions"}
2、API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://api.openai-agent.com/v1/chat/completions"}

是第一个还是第二个？

**Comment by binary-husky** [comment]
第二个

**Comment by jian1929** [comment]
感谢，下一个版本直接在源文件改成这个，不就不需要手动改了吗
