### ISSUE TITLE
环境中安装pytorch和tensorflow后无法运行main.py

### ISSUE THREAD

**Issue by cqz123** [binary-husky/gpt_academic#642]
- **(1) Describe the bug 简述**
python小白一枚见谅……

环境中未安装pytorch和tensorflow时可以运行main.py，安装后再运行main.py，显示

ModuleNotFoundError: No module named ‘pandas._libs.interval‘

使用 pip install --force-reinstall pandas，再运行main.py，显示

ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (D:\anaconda\envs\gptac_venv\lib\site-packages\matplotlib\__init__.py)

- **(2) Screen Shot 截图**
![1682588467687](https://user-images.githubusercontent.com/22143744/234824368-397cd3f1-2e0b-494e-86c6-00bd1e404941.png)

**Comment by binary-husky** [comment]
这是依赖安装炸了😂。不要试图把gpu版的torch和tensorflow安装在一起吧
