### ISSUE TITLE
可以增加一个上传文件，自定义对话内容的功能

### ISSUE THREAD

**Issue by Jiyang00** [binary-husky/gpt_academic#643]
现在我都是需要去代码里修改对话内容，可以增加个功能，上传文件之后，自定义对话内容

**Comment by binary-husky** [comment]
😂比如？

**Comment by Jiyang00** [comment]
就是我上传一个word文档，然后可以通过对话框来获取我想要的内容。比如我的word文章是全年的销售记录，我上传word文档后，我可以再输入框里输入我想要四月份的，不只是总结word文章的内容。

**Comment by binary-husky** [comment]
短文章不难实现，
`yield from update_ui(chatbot=chatbot, history=history) # 刷新界面`的时候，把word文章内容放到history中，就可以直接通过输入框对话了。

如果文章比较长就稍微有点麻烦了，目前还在构思一个拓展性强的函数插件增强架构
