### ISSUE TITLE
上传文件，出现问题

### ISSUE THREAD

**Issue by kavstall** [binary-husky/gpt_academic#644]
- **(1) Describe the bug 简述**

当成功部署项目后，我上传一个zip格式的文件（pdf也一样），web界面就会一直在闪烁，提示我上传了文件，而后台上，也在不停的弹出提示。
- **(2) Screen Shot 截图**

![1682661630872](https://user-images.githubusercontent.com/24399832/235066719-1673c72b-4328-412a-881a-8d1ac5463cfb.png)
![1682661699595](https://user-images.githubusercontent.com/24399832/235066883-ee41c087-6575-4c05-9626-b800ab00e77a.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
看readme第一行

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/235177705-47eeadba-0729-412c-a90f-874b4748f7c2.png)
