### ISSUE TITLE
切换为newbing模型后，latex公式不渲染

### ISSUE THREAD

**Issue by moxi000** [binary-husky/gpt_academic#645]
- **(1) Describe the bug 简述**
切换为newbing模型后，latex公式不渲染

- **(2) Screen Shot 截图**
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/66484370/235078876-812547ae-dcdf-4514-9fce-b3aadd1f987d.png">
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/66484370/235078915-f8e308f8-9fc3-4a10-8e6f-dbabebc27f41.png">

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/235207142-e29ef102-fa41-48c5-aa87-0e6d6345c0a2.png)
3.32修复

**Comment by moxi000** [comment]
> ![image](https://user-images.githubusercontent.com/96192199/235207142-e29ef102-fa41-48c5-aa87-0e6d6345c0a2.png)
> 3.32修复

看你图片上的bing回复那个 三种浮力公式 那个地方显示有点问题 我也遇到了类似的 能修复吗

**Comment by binary-husky** [comment]
和markdown的语法撞了，先暂时把[]替换成()解决吧

![image](https://user-images.githubusercontent.com/96192199/235231775-e6fd4b81-86e7-4a73-8347-83fb2327b563.png)
