### ISSUE TITLE
我重置后，或者重启之后，可以根据历史对话来调教新的对话内容吗

### ISSUE THREAD

**Issue by Jiyang00** [binary-husky/gpt_academic#646]
有时候我调教出了他回答的格式，但是重启之后又得重新调教。我没看到有读历史对话的地方

**Comment by binary-husky** [comment]
已添加
https://github.com/binary-husky/gpt_academic/commit/6c17f3e9c826074c16496b69e6bfa2ef4f1b4bca

**Comment by binary-husky** [comment]
@Jiyang00 
#597
#345
#230
