### ISSUE TITLE
建议读config_private.py配置时，如果没有配置，读取默认的config.py

### ISSUE THREAD

**Issue by Jiyang00** [binary-husky/gpt_academic#647]
一键更新之后，代码里多了config_private.py文件，但是没有注意到。今天增加new bing 的cookie，由于没有注意到config_private.py文件，一直往config.py里面写，cookie一直不对，后来去代码里打印才找到原因。

**Comment by StarCode000** [comment]
config_private优先级高于config，本来就是建议使用private的。

**Comment by binary-husky** [comment]
config_private.py里面的会优先读，所以尽可能避免config_private.py中存在错误设置
