### ISSUE TITLE
请求支持chatGPT网页版的accessToken连接

### ISSUE THREAD

**Issue by ShaySheng** [binary-husky/gpt_academic#648]
https://chat.openai.com/api/auth/session
登录官网之后，再点开上面的官方链接就会有accessToken，通过这个token连接gpt官网也是有可能的
这对于一次性购买过chatGPT plus的人来说非常重要，这就样就不用使用昂贵的chatGPT API了
可以参考如下两个项目的实现：
https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy
https://github.com/Chanzhaoyu/chatgpt-web
特别是chatgpt-web里面的历史对话功能，非常强大，值得借鉴的😭

**Comment by binary-husky** [comment]
#646 新增了历史对话载入功能

**Comment by 14790897** [comment]
这个厉害
