### ISSUE TITLE
支持自建源

### ISSUE THREAD

**Issue by borisxxz** [binary-husky/gpt_academic#650]
API2D接入是个非常棒的决定，但有些时候能找到更便宜的接口，能否提供自建源的入口或是网页版的chatGPT（反代理）？

**Comment by binary-husky** [comment]
支持的，在config.py中定义API_URL或者API_URL_REDIRECT

duplication of #629

**Comment by borisxxz** [comment]
API_URL是自建源，API_URL_REDIRECT是网页版？那网页版的token填在哪里呢？

**Comment by binary-husky** [comment]
这个项目近期不计划接小站点搭的网页版，这样一来不稳定，二来不道德。
