### ISSUE TITLE
大佬们，帮我看看nginx配置对吗？为什么academic和xui网页都无法通过https访问但可以通过http域名加端口加路径访问?

### ISSUE THREAD

**Issue by 14790897** [binary-husky/gpt_academic#658]
nginx配置：
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    gzip on;

    server {
        listen 443 ssl;
        
        server_name lightsail.liuweiqing.top;  
        ssl_certificate       /etc/x-ui/server.crt;  #证书位置
        ssl_certificate_key   /etc/x-ui/server.key; #私钥位置
        
        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;
        ssl_session_tickets off;
        ssl_protocols    TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

		location /academic {
            proxy_pass http://127.0.0.1:39473;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
		}
 

        location / {
            proxy_pass http://cloudreve.fengbohan.com/; #伪装网址
            proxy_redirect off;
            proxy_ssl_server_name on;
            sub_filter_once off;
            sub_filter "cloudreve.fengbohan.com" $server_name;
            proxy_set_header Host "cloudreve.fengbohan.com";
            proxy_set_header Referer $http_referer;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header User-Agent $http_user_agent;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header Accept-Encoding "";
            proxy_set_header Accept-Language "zh-CN";
        }

        location /ray {   #分流路径
            proxy_redirect off;
            proxy_pass http://127.0.0.1:8880; #Xray端口
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        location /xui {   #xui路径
            proxy_pass http://127.0.0.1:9999;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    }
    }
    server {
        listen 80;
        location /.well-known/ {
               root /var/www/html;
            }
        location / {
                rewrite ^(.*)$ https://$host$1 permanent;
            }
    }
    
}

**Comment by 14790897** [comment]
网址：http://lightsail.liuweiqing.top:9999/xui/
http://lightsail.liuweiqing.top:39473/

**Comment by 14790897** [comment]
无法访问：https://lightsail.liuweiqing.top/academic
https://lightsail.liuweiqing.top/xui/

**Comment by 14790897** [comment]
![image](https://user-images.githubusercontent.com/121866954/235287489-f36f2241-ee81-4a7c-ad02-1fb15c83ad71.png)
此项目运行信息

**Comment by nulshell** [comment]
我碰到了同样问题。用机器的IP和端口可以访问，非SSL。类似上面的朋友用nginx分流路径会反馈 not found。

**Comment by TonyHuang0711** [comment]
> ![image](https://user-images.githubusercontent.com/121866954/235287489-f36f2241-ee81-4a7c-ad02-1fb15c83ad71.png) 此项目运行信息

你是在二级路径运行吗？如果是的话你是否有修改main.py中的Line246-253?

**Comment by 14790897** [comment]
> > ![image](https://user-images.githubusercontent.com/121866954/235287489-f36f2241-ee81-4a7c-ad02-1fb15c83ad71.png) 此项目运行信息
> 
> 你是在二级路径运行吗？如果是的话你是否有修改main.py中的Line246-253?

感谢大佬指点，我明白了

**Comment by 14790897** [comment]
刚刚那位很有礼貌的人呢？
