### ISSUE TITLE
多线程翻译pdf的编码bug

### ISSUE THREAD

**Issue by EmperorJia** [binary-husky/gpt_academic#661]
- **(1) Describe the bug 简述**
将某些论文使用多线程翻译这个功能时，会出现文件写出错误的问题。目前是把toolbox.py里的
with open(f'./gpt_log/{file_name}', 'w', encoding='utf8') as f:
改为：
with codecs.open('./gpt_log/{file_name}', 'w', encoding='utf-16', errors='ignore') as f:
可以解决

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/48755782/235316361-ecd9a8d3-ed61-4d1a-9807-96316ec272be.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**
翻译的论文链接：https://arxiv.org/pdf/2211.00216

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by huyang531** [comment]
我也遇到了这个问题。我把`with open(f'./gpt_log/{file_name}', 'w', encoding='utf8') as f:`改为了 `with open(f'./gpt_log/{file_name}', 'w', encoding='utf8', errors='ignore') as f:`，但是似乎改成utf16会更好。

**Comment by binary-husky** [comment]
找到问题了#773
