### ISSUE TITLE
能否部署在Huggingface space 或者 vercel 上

### ISSUE THREAD

**Issue by Nothingness-Void** [binary-husky/gpt_academic#667]
如题 ：
[huggingface space](https://huggingface.co/spaces/)
[vercel](https://vercel.com/)

**Comment by binary-husky** [comment]
https://huggingface.co/spaces/qingxu98/gpt-academic


https://github.com/binary-husky/gpt_academic/tree/huggingface

**Comment by Nothingness-Void** [comment]
> huggingface demo: https://huggingface.co/spaces/qingxu98/gpt-academic
> 
> huggingface branch: https://github.com/binary-husky/gpt_academic/tree/huggingface

感谢您的回复，我在使用过程中无法调用newbing模型 是我的用法有问题吗
![image](https://user-images.githubusercontent.com/55913486/235830708-59a19a56-df35-43a7-bb45-2f0ba86bbe98.png)

**Comment by TonyHuang0711** [comment]
> > huggingface demo: https://huggingface.co/spaces/qingxu98/gpt-academic
> > huggingface branch: https://github.com/binary-husky/gpt_academic/tree/huggingface
> 
> 感谢您的回复，我在使用过程中无法调用newbing模型 是我的用法有问题吗 ![image](https://user-images.githubusercontent.com/55913486/235830708-59a19a56-df35-43a7-bb45-2f0ba86bbe98.png)

建议检查是否已安装 request_llm/requirements_newbing.txt中的依赖项

**Comment by WanZunGe** [comment]
> huggingface demo: https://huggingface.co/spaces/qingxu98/gpt-academic
> 
> huggingface branch: https://github.com/binary-husky/gpt_academic/tree/huggingface

huggingface上代理怎么设置啊，一直提示没有设置代理，我把代理打开也不行，huggingface服务器不是本身就能链接openAI的吗，为什么还要设置代理，不知道该怎么改，求教

**Comment by Nothingness-Void** [comment]
> > > huggingface demo: https://huggingface.co/spaces/qingxu98/gpt-academic
> > > huggingface branch: https://github.com/binary-husky/gpt_academic/tree/huggingface
> > 
> > 
> > 感谢您的回复，我在使用过程中无法调用newbing模型 是我的用法有问题吗 ![image](https://user-images.githubusercontent.com/55913486/235830708-59a19a56-df35-43a7-bb45-2f0ba86bbe98.png)
> 
> 建议检查是否已安装 request_llm/requirements_newbing.txt中的依赖项

我是直接复制的huggingface demo 的空间

**Comment by Nothingness-Void** [comment]
> > huggingface demo: https://huggingface.co/spaces/qingxu98/gpt-academic
> > huggingface branch: https://github.com/binary-husky/gpt_academic/tree/huggingface
> 
> huggingface上代理怎么设置啊，一直提示没有设置代理，我把代理打开也不行，huggingface服务器不是本身就能链接openAI的吗，为什么还要设置代理，不知道该怎么改，求教

可直连，不用设置代理

**Comment by WanZunGe** [comment]
> > > huggingface demo: https://huggingface.co/spaces/qingxu98/gpt-academic
> > > huggingface branch: https://github.com/binary-husky/gpt_academic/tree/huggingface
> > 
> > 
> > huggingface上代理怎么设置啊，一直提示没有设置代理，我把代理打开也不行，huggingface服务器不是本身就能链接openAI的吗，为什么还要设置代理，不知道该怎么改，求教
> 
> 可直连，不用设置代理

现在又可以了，之前不知道怎么回事，一直提示要设置代理
