### ISSUE TITLE
功能请求：支持 RWKV 模型（目前已有 pip package & rwkv.cpp 等等）

### ISSUE THREAD

**Issue by BlinkDL** [binary-husky/gpt_academic#668]
您好，我是 RWKV 的作者，介绍见：https://zhuanlan.zhihu.com/p/626083366 （一键生成论文演示）

欢迎大家一起合作加入 RWKV 的支持 :)

目前支持 RWKV 的中英文界面有：
* 闻达：https://github.com/l15y/wenda
* Gradio DEMO: https://huggingface.co/spaces/BlinkDL/Raven-RWKV-7B
* ooba：https://github.com/oobabooga/text-generation-webui/issues/1401

使用方法：
* pip package: https://pypi.org/project/rwkv/
* 问答DEMO代码：https://github.com/BlinkDL/ChatRWKV/blob/main/v2/benchmark_more.py
* 聊天代码：https://github.com/BlinkDL/ChatRWKV
* CPU INT4/8 量化运行: https://github.com/saharNooby/rwkv.cpp

**Comment by binary-husky** [comment]
方便加我qq聊一下吗 505030475 @BlinkDL

**Comment by BlinkDL** [comment]
@binary-husky 请看QQ，直接用RWKV pip package，不要用第三方库，很多都有bug
