### ISSUE TITLE
You exceeded your current quota. OpenAI以账户额度不足为由, 拒绝服务.

### ISSUE THREAD

**Issue by houstonwhy** [binary-husky/gpt_academic#671]
在尝试历史上的今天遇到了这个问题。
Traceback (most recent call last):
  File ".\crazy_functions\crazy_utils.py", line 78, in _req_gpt
    result = predict_no_ui_long_connection(
  File ".\request_llm\bridge_all.py", line 173, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
  File ".\request_llm\bridge_chatgpt.py", line 87, in predict_no_ui_long_connection
    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "You exceeded your current quota, please check your plan and billing details.",        "type": "insufficient_quota",        "param": null,        "code": null    }}

**Comment by StarCode000** [comment]
余额过期或者余额不足，本来就是要收费的

**Comment by houstonwhy** [comment]
> 

啊我忘了说，我是买了plus的，所以出现这种情况就很奇怪

**Comment by StarCode000** [comment]
plus和API不是同一个东西，或者是你银行卡里面余额太少了

**Comment by houstonwhy** [comment]
嗷嗷，那我给卡里充点钱，谢谢!

**Comment by Runaway00** [comment]
是开始收费了吗？？

**Comment by StarCode000** [comment]
一直都是收费的，只不过每个账号都有免费额度而已，但是免费额度会过期

**Comment by Runaway00** [comment]
> 一直都是收费的，只是不过每个账号都有免费额度而已经，但是是免费额度会过期

这个在哪可以充呢

**Comment by StarCode000** [comment]
自己找找哪里可以绑定OpenAI账户的支付方式吧，很好找的，就是国外的银行卡比较难搞。你自己去搜吧，网上教程不少的

**Comment by xiemy1214** [comment]
我也有这样的问题, 但是我在官网上同样的账户是可以使用的...

**Comment by StarCode000** [comment]
> 我也有这样的问题, 但是我在官网上同样的账户是可以使用的...

都说了，官网和API没关系，官网只要不充Plus会员就是完全免费用的，api免费额度过期后就需要你绑定银行卡使用了。官网是给所有人用的，API是给程序员用的，程序员可以用API去赚取额外的收益所以需要付费，这不是有很明显的区别吗
