### ISSUE TITLE
我写了个油猴插件用来语音播放

### ISSUE THREAD

**Issue by LiZheGuang** [binary-husky/gpt_academic#673]
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/16920092/235738112-a85ee302-2f3c-4046-8e9c-13014c2f4a6a.png">

在写文献或者学习算法的时候阅读文字会感觉不太专注，我希望语音可以播放我最后一次的GPT返回的内容。

有需要这种油猴插件的想法吗，我可以分享出来，现在只有我自己用，

**Comment by LiZheGuang** [comment]
我尝试想用python 去语音播放，但是我不太知道该从哪里入手，用的类似语音库，生成的环节比较慢

**Comment by binary-husky** [comment]
很强哦！

**Comment by LiZheGuang** [comment]
油猴插件 ：gpt_academic语音播放功能
