### ISSUE TITLE
已解决，设置反向代理后，直接用域名访问

### ISSUE THREAD

**Issue by TLimerence** [binary-husky/gpt_academic#675]
已解决，设置反向代理后，直接用域名访问

_Originally posted by @Astro-Lee in https://github.com/binary-husky/gpt_academic/issues/125#issuecomment-1489628033_
            具体是怎么做的呢，我也出现这个问题

**Comment by abandon-alt** [comment]
https://blog.csdn.net/LinkSLA/article/details/129946162
