### ISSUE TITLE
[Local Message] 异常"Your account is not active"

### ISSUE THREAD

**Issue by stone00789** [binary-husky/gpt_academic#681]
不知什么原因，我的账号正常使用，api余量充足，但是报错是账号未激活...实在不懂如何处置。求解大神

**Comment by binary-husky** [comment]
以下是gpt-academic综合互联网的回答：

![image](https://user-images.githubusercontent.com/96192199/236426328-3509e43a-7342-45e3-b882-525816a85115.png)

**Comment by stone00789** [comment]
我的chatgpt账号可以正常使用，但使用api连接时，出现账户问题。不知啥原因...

**Comment by TonyHuang0711** [comment]
> 我的chatgpt账号可以正常使用，但使用api连接时，出现账户问题。不知啥原因...

请尝试在官网重新生成ApiKey

**Comment by stone00789** [comment]
> > 我的chatgpt账号可以正常使用，但使用api连接时，出现账户问题。不知啥原因...
> 
> 请尝试在官网重新生成ApiKey
生成了很多新的apikey，但给出的结果都一样
Json异常 “error”: { “message”: “Your account is not active, please check your billing details on our website.”, “type”: “billing_not_active”, “param”: null, “code”: null

**Comment by TonyHuang0711** [comment]
是不是因为你的免费额度过期了并且你没有添加付款方式？

**Comment by TonyHuang0711** [comment]
> > > 我的chatgpt账号可以正常使用，但使用api连接时，出现账户问题。不知啥原因...
> > 
> > 
> > 请尝试在官网重新生成ApiKey
> > 生成了很多新的apikey，但给出的结果都一样
> > Json异常 “error”: { “message”: “Your account is not active, please check your billing details on our website.”, “type”: “billing_not_active”, “param”: null, “code”: null

接口https://api.openai.com/dashboard/billing/subscription
查看["canceled"]是否为false

**Comment by stone00789** [comment]
> 

  "has_payment_method": true,
  "canceled": true,

**Comment by stone00789** [comment]
> 
  "has_payment_method": true,
  "canceled": true,

**Comment by stone00789** [comment]
> > > > 我的chatgpt账号可以正常使用，但使用api连接时，出现账户问题。不知啥原因...
> > > 
> > > 
> > > 请尝试在官网重新生成ApiKey
> > > 生成了很多新的apikey，但给出的结果都一样
> > > Json异常 “error”: { “message”: “Your account is not active, please check your billing details on our website.”, “type”: “billing_not_active”, “param”: null, “code”: null
> 
> 接口https://api.openai.com/dashboard/billing/subscription 查看["canceled"]是否为false

  "has_payment_method": true,
  "canceled": true,

**Comment by TonyHuang0711** [comment]
> > > > > 我的chatgpt账号可以正常使用，但使用api连接时，出现账户问题。不知啥原因...
> > > > 
> > > > 
> > > > 请尝试在官网重新生成ApiKey
> > > > 生成了很多新的apikey，但给出的结果都一样
> > > > Json异常 “error”: { “message”: “Your account is not active, please check your billing details on our website.”, “type”: “billing_not_active”, “param”: null, “code”: null
> > 
> > 
> > 接口https://api.openai.com/dashboard/billing/subscription 查看["canceled"]是否为false
> 
> "has_payment_method": true, "canceled": true,

那应该是cancel了 个人认为有三种情况 1 payment扣费失败 2 订阅被取消 3.账号被封禁 按照@binary_husky提供的那张图里面的联系方式联系客服吧
