### ISSUE TITLE
Looking to purchase GPT-4 API Keys

### ISSUE THREAD

**Issue by SunnyGPT** [binary-husky/gpt_academic#682]
Is anyone still on the waiting list for GPT-4? Don't worry, [https://www.openai-365.com](https://www.openai-365.com) this platform offers a reliable GPT-4 API key rental service, which many people are already using. This is really great!

**Comment by yhyu13** [comment]
假的，有骗子

**Comment by SunnyGPT** [comment]
> 假的，有骗子

Hey! I can be responsible for what I say, can you? If you can't, then why are you talking nonsense here?
