### ISSUE TITLE
端口问题导致无法连接Localhost

### ISSUE THREAD

**Issue by freetosmash** [binary-husky/gpt_academic#685]
- **(1) Describe the bug 简述**
在config中将port改为：
WEB_PORT = 38282
并在启动的时候使用
docker run -p 38282:38282 gpt-academic

启动返回的localhost端口非规定之端口导致无法访问localhost

如果浏览器没有自动打开，请复制并转到以下URL：
	（亮色主题）: http://localhost:58829
	（暗色主题）: http://localhost:58829/?__dark-theme=true

- **(2) Screen Shot 截图**
![Xnip2023-05-05_16-56-11](https://user-images.githubusercontent.com/33079010/236416522-a8f7139a-37e3-4c7a-a104-3b68f87d6239.png)

**Comment by binary-husky** [comment]
有config_private的话，删掉config_private，config_private的优先级更高，环境变量的优先级最高

**Comment by freetosmash** [comment]
> 有config_private的话，删掉config_private，config_private的优先级更高，环境变量的优先级最高

您好，感谢回复。
之前是在config_private中进行修改，也是一样的情况。
后在config中进行修改，还是一样情况（config_private 已删除）
不知道您是否碰到过类似问题……

**Comment by binary-husky** [comment]
> > 有config_private的话，删掉config_private，config_private的优先级更高，环境变量的优先级最高
> 
> 您好，感谢回复。 之前是在config_private中进行修改，也是一样的情况。 后在config中进行修改，还是一样情况（config_private 已删除） 不知道您是否碰到过类似问题……

改完之后是不是漏掉了docker build这步？

**Comment by freetosmash** [comment]
> > > 有config_private的话，删掉config_private，config_private的优先级更高，环境变量的优先级最高
> > 
> > 
> > 您好，感谢回复。 之前是在config_private中进行修改，也是一样的情况。 后在config中进行修改，还是一样情况（config_private 已删除） 不知道您是否碰到过类似问题……
> 
> 改完之后是不是漏掉了docker build这步？

感谢，搞定了
