### ISSUE TITLE
请教一下，我在虚拟机上跑了项目，但是另外的设备无法访问，应该怎么做？

### ISSUE THREAD

**Issue by themis0009** [binary-husky/gpt_academic#686]
虚拟机地址是192.168.1.100
然后在另外一台设备上访问192.168.1.100:12345，失败。
没有开防火墙。
请教这个应该如何让局域网设备也能访问这个页面？
谢谢~

**Comment by binary-husky** [comment]
抱歉很少用虚机

![image](https://user-images.githubusercontent.com/96192199/236424501-4e402b9c-e3ec-45ad-bf14-4b4137461a94.png)

**Comment by themis0009** [comment]
> 抱歉很少用虚机
> 
> ![image](https://user-images.githubusercontent.com/96192199/236424501-4e402b9c-e3ec-45ad-bf14-4b4137461a94.png)

感谢大佬，已经成功~
原因是我自己的设置中，NAS设备使用了双网卡，没有配置好走哪个网卡。
