### ISSUE TITLE
写了一个ChatGPT Academic的免翻墙部署教程，适合个人或课题组生产环境

### ISSUE THREAD

**Issue by elphen-wang** [binary-husky/gpt_academic#687]
如题，欢迎大家进行友好交流与讨论，共同促进技术开放与进步！
https://github.com/elphen-wang/chatgpt_wallfree

**Comment by elphen-wang** [comment]
建议大家在ChatGPT Academic的requirements.txt尾后补一个库函数 pdfminer, 否则arxiv下载和分析功能可能不能正常使用。

**Comment by binary-husky** [comment]
谢谢，加到requirements.txt里啦

**Comment by zhoumaochao** [comment]
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://mydomain.ciom/v1/chat/completions"}
url 重定向后，还是连不上。提示：[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

URL重定向后还需要设置proxy吗？
