### ISSUE TITLE
请求支持poe的api接入

### ISSUE THREAD

**Issue by seekerhuang** [binary-husky/gpt_academic#688]
请求支持poe的api，这样可以规避直接使用chatgpt所带来的大量token消耗，以及支持多模型选择，感觉是很有意义的一件事。
具体实现可以参考：
https://github.com/ading2210/poe-api
https://github.com/muharamdani/poe

**Comment by binary-husky** [comment]
您好，这个不在3.4，3.5规划中，但随时欢迎pull request

对不同模型的后端支持是模块化的，
如果需要新增模块，随便复制已有的模板作为模板（例如newbing）即可：
https://github.com/binary-husky/gpt_academic/tree/master/request_llm
https://github.com/binary-husky/gpt_academic/tree/jittor/request_llm

单元测试在：
https://github.com/binary-husky/gpt_academic/blob/jittor/request_llm/test_llms.py
