### ISSUE TITLE
APIKEY怎么获取

### ISSUE THREAD

**Issue by ambglh** [binary-husky/gpt_academic#689]
- **(1) Describe the bug 简述**

- **(2) Screen Shot 截图**

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by yhyu13** [comment]
3.5 淘宝遍地

**Comment by binary-husky** [comment]
能科学上网去淘宝
不能科学上网去api2d

**Comment by ambglh** [comment]
OPENAI官网有






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月6日(星期六) 晚上10:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/gpt_academic] APIKEY怎么获取 (Issue #689)





 
能科学上网去淘宝
 不能科学上网去api2d

**Comment by wohaocaiji** [comment]
> 能科学上网去淘宝（淘宝关键词解封了） 不能科学上网去api2d

淘宝啥关键词啊，搜了一圈搜不出来

**Comment by healerlalala** [comment]
> > 能科学上网去淘宝（淘宝关键词解封了） 不能科学上网去api2d
> 
> 淘宝啥关键词啊，搜了一圈搜不出来

同问！

**Comment by Jasperrpc** [comment]
> 

搜api key, 像ChatGPT之类的词被屏蔽了

**Comment by Jasperrpc** [comment]
> > > 能科学上网去淘宝（淘宝关键词解封了） 不能科学上网去api2d
> > 
> > 
> > 淘宝啥关键词啊，搜了一圈搜不出来
> 
> 同问！

直接搜api key，像ChatGPT，openai之类的词都被屏蔽了

**Comment by hero-y** [comment]
万能淘宝
