### ISSUE TITLE
阿里镜像太慢，替换为清华镜像吧

### ISSUE THREAD

**Issue by mozhuanzuojing** [binary-husky/gpt_academic#690]
> [清华镜像](https://mirrors.tuna.tsinghua.edu.cn/help/pypi/)

pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by binary-husky** [comment]
嗯 都可以 慢不慢和地域有关

阿里虽然慢点，不过它背靠阿里云，可靠度更高一点
