### ISSUE TITLE
推荐一下rwkv.cpp

### ISSUE THREAD

**Issue by Asukaleo-aa** [binary-husky/gpt_academic#691]
[rwkv.cpp](https://github.com/saharNooby/rwkv.cpp)这个项目是将rwkv的模型转换成[ggml](https://github.com/ggerganov/ggml)，极大地提高了rwkv模型在纯cpu环境下的运行效率，目前rwkv在更新模型的时候也有提供转换好的版本，非常推荐引入一下这个模型

**Comment by binary-husky** [comment]
您好，我们在这个分支已经支持了rwkv：https://github.com/binary-husky/gpt_academic/tree/jittor
您可以通过主分支的docker-compose进行尝试：https://github.com/binary-husky/gpt_academic/blob/master/docker-compose.yml
