### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Dragon-CUG** [binary-husky/gpt_academic#693]
- **(1) Describe the bug 简述**
![image](https://user-images.githubusercontent.com/51327911/236609929-a9cb7786-037b-49c4-96db-a47cc30b7a22.png)

- **(2) Screen Shot 截图**

![image](https://user-images.githubusercontent.com/51327911/236609934-cde0516c-de08-4cd1-ae59-dd4f715aadcb.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by HanZhang-ZERO** [comment]
我也出现了这个问题

**Comment by Dragon-CUG** [comment]
将requirement.txt中的gradio改为3.26.0 就好了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/gpt_academic] KeyError (Issue #693)





 
我也出现了这个问题

**Comment by HanZhang-ZERO** [comment]
可以了 感谢～

**Comment by binary-husky** [comment]
> 将requirement.txt中的gradio改为3.26.0 就好了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "binary-husky/gpt_academic" ***@***.***&gt;; 发送时间:&nbsp;2023年5月6日(星期六) 下午4:38 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [binary-husky/gpt_academic] KeyError (Issue #693) 我也出现了这个问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

gradio 3.26.0有严重文件上传的bug！

**Comment by Dragon-CUG** [comment]
我在B站上看有人改为3.28.3也可以，你试一下 如果没有问题的话请和我同步以下消息，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 晚上10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/gpt_academic] KeyError (Issue #693)





  
将requirement.txt中的gradio改为3.26.0 就好了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "binary-husky/gpt_academic" @.&gt;; 发送时间:&nbsp;2023年5月6日(星期六) 下午4:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [binary-husky/gpt_academic] KeyError (Issue #693) 我也出现了这个问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
gradio 3.26.0有严重文件上传的bug！

**Comment by binary-husky** [comment]
gradio 3.28也有小bug

以前3.25是稳定的，怎么突然出问题了呀

**Comment by Dragon-CUG** [comment]
不清楚，我今天第一次使用这个，如果你有了好的解决办法，方便的话 和我同步一下信息，谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/gpt_academic] KeyError (Issue #693)





 
gradio 3.28也有小bug
 
以前3.25是稳定的，怎么突然出问题了呀

**Comment by binary-husky** [comment]
python -m pip install gradio==3.28.3

**Comment by Dragon-CUG** [comment]
3.28.3你不是说有点小bug么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月6日(星期六) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/gpt_academic] KeyError (Issue #693)





 
python -m pip install gradio==3.28.3

**Comment by binary-husky** [comment]
3.28.3至少能运行
python -m pip install gradio==3.28.3

gradio升级也就算了，非要替换掉旧版本（3.25）的包，
替换也就算了，还替换了一个有bug的包
3.25大家用的好好的，动它干啥呀【doge】
