### ISSUE TITLE
在huggingface上使用，处理后的文件在哪里可以下载？

### ISSUE THREAD

**Issue by linkwoodworking** [binary-husky/gpt_academic#696]
rt，比如英译中完成后，提示以上材料已经被写入/home/user/app/gpt_log/

这个/home/user/app/gpt_log/怎么找到呢？没有用过huggingface，不清楚在哪里

谢谢帮忙

**Comment by binary-husky** [comment]
展开文件上传区，就可以下载。
或者在网址后面指定  /file=/home/user/app/gpt_log/xxxxx 也可以下载。

**Comment by linkwoodworking** [comment]
> 展开文件上传区，就可以下载。 或者在网址后面指定 /file=/home/user/app/gpt_log/xxxxx 也可以下载。

谢谢，成功了，过程如下：
1、在文件上传区，上传了test.pdf
2、点击红色区域的批量翻译PDF文档（多线程）
3、坐等程序跑完

第一种文件上传区会下载了，如下图
![20230507下载huggingface的生成文件](https://user-images.githubusercontent.com/13827306/236647624-3dee3e7c-a33f-4cb3-a4e8-f36d4486624b.png)

第二种在网址后面指定也成功，地址如下（********为huggingface的用户名）
https://********-gpt-academic.hf.space/file=/home/user/app/gpt_log/总结论文-test.pdf.trans.md

**Comment by linkwoodworking** [comment]
抱歉，我又有了一个新问题，就是跑完批量翻译PDF文档（多线程）后，程序提示：
`以上材料已经被写入/home/user/app/gpt_log/test.pdf.trans.md`
但是我尝试使用下面这个地址去下载，系统提示Internal Server Error，这个是系统原因，还是我姿势不对？
https://@@@@@@-gpt-academic.hf.space/file=/home/user/app/gpt_log/test.pdf.trans.md

**Comment by binary-husky** [comment]
新版本已经可以从对话中直接打开链接了
