### ISSUE TITLE
python main.py运行错误

### ISSUE THREAD

**Issue by Xuexii1** [binary-husky/gpt_academic#697]
查询代理的地理位置，返回的结果是{'ip': '140.99.6.156', 'network': '140.99.6.0/24', 'version': 'IPv4', 'city': 'Los Angeles', 'region': 'California', 'region_code': 'CA', 'country': 'US', 'country_name': 'United States', 'country_code': 'US', 'country_code_iso3': 'USA', 'country_capital': 'Washington', 'country_tld': '.us', 'continent_code': 'NA', 'in_eu': False, 'postal': '90043', 'latitude': 33.9883, 'longitude': -118.3294, 'timezone': 'America/Los_Angeles', 'utc_offset': '-0700', 'country_calling_code': '+1', 'currency': 'USD', 'currency_name': 'Dollar', 'languages': 'en-US,es-US,haw,fr', 'country_area': 9629091.0, 'country_population': 327167434, 'asn': 'AS35913', 'org': 'DEDIPATH-LLC'}
代理配置 http://localhost:7890, 代理所在地：United States
Traceback (most recent call last):
  File "C:\Users\86152\Desktop\gpt_academic\main.py", line 206, in <module>
    main()
  File "C:\Users\86152\Desktop\gpt_academic\main.py", line 54, in main
    with gr.Blocks(title="ChatGPT 学术优化", theme=set_theme, analytics_enabled=False, css=advanced_css) as demo:
  File "C:\Users\86152\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "C:\Users\86152\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "C:\Users\86152\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio_client\serializing.py", line 40, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'

各位大佬，这是怎么回事啊（纯小白）

**Comment by Github1258** [comment]
pip install --upgrade gradio

**Comment by Xuexii1** [comment]
> 

大佬，这是什么意思

**Comment by Xuexii1** [comment]
> pip install --upgrade gradio

大佬，这是什么意思

**Comment by XuZerui2023** [comment]
命令行输入 pip install --upgrade gradio
更新web框架gradion，否则会报错

**Comment by Xuexii1** [comment]
> 命令行输入 pip install --upgrade gradio 更新web框架gradion，否则会报错

![image](https://user-images.githubusercontent.com/132743639/236624111-dc8d767e-503e-4959-91f7-3de68113c709.png)
这样么，好像不行

**Comment by binary-husky** [comment]
报错请把 gradio 升级到 3.28.3 （无语，每次gradio一升级都搞出一堆幺蛾子）

`python -m pip install gradio==3.28.3`

**Comment by Xuexii1** [comment]
> 

问题已解决，方案正确，感谢大佬

**Comment by YeliYumeiji** [comment]
我也遇到这个问题，谢谢大佬给的解决方案，可以使用。
