### ISSUE TITLE
如何获取apikey

### ISSUE THREAD

**Issue by Tina-LT** [binary-husky/gpt_academic#698]
apikey如何获取

**Comment by Xuexii1** [comment]
淘宝直接搜，随便买一个就好，十块钱左右

**Comment by binary-husky** [comment]
能科学上网去淘宝
不能科学上网去api2d

**Comment by 1251480932** [comment]
![2f50d10f9389573c0fd0a1d2d3c5c03](https://github.com/binary-husky/gpt_academic/assets/47667939/3f521fb1-5854-4339-ba39-d483d604541d)
