### ISSUE TITLE
使用“理解PDF文档内容（模仿chatPDF）”出现报错

### ISSUE THREAD

**Issue by KamilYZ** [binary-husky/gpt_academic#701]
- **(1) Describe the bug 简述**
我使用理解PDF文档内容（模仿chatPDF）功能的时候出现下面的报错
Traceback (most recent call last):
  File ".\crazy_functions\crazy_utils.py", line 78, in _req_gpt
    result = predict_no_ui_long_connection(
  File ".\request_llm\bridge_all.py", line 173, in predict_no_ui_long_connection
    return method(inputs, llm_kwargs, history, sys_prompt, observe_window, console_slience)
  File ".\request_llm\bridge_chatgpt.py", line 87, in predict_no_ui_long_connection
    raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "Incorrect API key provided: sk-cI0Rv***************************************IFk8. You can find your API key at https://platform.openai.com/account/api-keys.",        "type": "invalid_request_error",        "param": null,        "code": "invalid_api_key"    }}

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/106416335/236626457-7519e450-131d-4a35-b21d-99ebaa0eb31f.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by KamilYZ** [comment]
各位，问题解决了，不用了

**Comment by binary-husky** [comment]
Incorrect API key填错key了
