### ISSUE TITLE
运行main.py时报错 KeyError: 'serialized_input'

### ISSUE THREAD

**Issue by xingyichen777** [binary-husky/gpt_academic#702]
尝试了重装pydantic、重装fastapi，但都报这个错，可以帮忙看一下吗？
![image](https://user-images.githubusercontent.com/96731725/236626554-50aab3b3-ff05-49ca-8144-ec55433aa4d1.png)

**Comment by binary-husky** [comment]
gradio 升级到 3.28.3 （无语，每次gradio一升级都搞出一堆幺蛾子）

**Comment by frangled123** [comment]
> 

改成了 3.28.3就成功了，但是huggingface上的不行

**Comment by wangfeng35** [comment]
gradio真是造孽啊

**Comment by xingyichen777** [comment]
> gradio 升级到 3.28.3 （无语，每次gradio一升级都搞出一堆幺蛾子）

嗯嗯，我升级了gradio，但运行后依然是这个错误，检查requirement.txt后也重装了，然后出现了下面这个tiktoken的问题，我尝试pip install tiktoken，会一直提示这两个错误。
![image](https://user-images.githubusercontent.com/96731725/236640264-a4580e05-7eda-4193-913b-ddfb7c35b2ae.png)

**Comment by binary-husky** [comment]
> > gradio 升级到 3.28.3 （无语，每次gradio一升级都搞出一堆幺蛾子）
> 
> 嗯嗯，我升级了gradio，但运行后依然有这个错误，检查requirement.txt后也重装了，然后出现了下面关于tiktoken的问题，我尝试pip install tiktoken，但一直提示下面两个错误。 ![image](https://user-images.githubusercontent.com/96731725/236640264-a4580e05-7eda-4193-913b-ddfb7c35b2ae.png)

试试 `pip install tiktoken== -i https://mirrors.aliyun.com/pypi/simple/`
![image](https://user-images.githubusercontent.com/96192199/236640624-579681be-7e88-4282-a4ec-94bedd5bfa9c.png)
如果还没有，那就是python版本太旧了

**Comment by xingyichen777** [comment]
> 

是的，是我的python版本太低了，已经解决了谢谢！！

**Comment by Tim-Saijun** [comment]
感谢，同样的问题`pip install gradio==3.28.3`解决了
