### ISSUE TITLE
基于WSL2的docker使用问题

### ISSUE THREAD

**Issue by qingju32** [binary-husky/gpt_academic#703]
对于docker-compose的一些设置
- 首先是端口问题，设置为host模式好像访问不了，这是正常的吗？改用了暴露端口。
- 关于NVIDIA显卡，提示找不到显卡。查了资料说docker desktop已经支持调用GPU，所以我删掉了runtime部分，加了deploy。但是我试了方案二，发现它调用的是集显，占用也不高，而且反应时间很长也不出结果。有教程说要在wsl里安装cuda，但是我nvidia-smi里看到了它的版本号，而且docker不是不基于发行版吗？我怎么去安装呢。

**Comment by binary-husky** [comment]
wsl2已经开始支持nvidia运行时了吗，什么时候这么强了😂

**Comment by qingju32** [comment]
> 
我不太清楚什么runtime啊😂
https://docs.docker.com/desktop/windows/wsl/

**Comment by zdevc** [comment]
这篇微软官方文档有用么？
https://learn.microsoft.com/zh-cn/windows/wsl/tutorials/gpu-compute
使用 Docker 设置 NVIDIA CUDA

**Comment by lixiang0926** [comment]
同样的操作 我在wsl2上找不到显卡
