### ISSUE TITLE
回答记录文本有反应response记录，但页面不显示内容

### ISSUE THREAD

**Issue by 13299118606** [binary-husky/gpt_academic#704]
- **(1) Describe the bug 简述**

回答记录文本有反应response记录，但页面不显示内容
版本3.33最新一版，且安装所有需求

conda list 
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    4.2.2                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
arxiv                     1.4.7                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2022.12.7            h5b45459_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
fastapi                   0.95.1                   pypi_0    pypi
feedparser                6.0.10                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
gradio                    3.28.3                   pypi_0    pypi
gradio-client             0.2.0                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  0.17.0                   pypi_0    pypi
httpx                     0.24.0                   pypi_0    pypi
huggingface-hub           0.14.1                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
latex2mathml              3.75.3                   pypi_0    pypi
libexpat                  2.5.0                h63175ca_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h8ffe710_5    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.40.0               hcfcfb64_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               hcfcfb64_4    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
linkify-it-py             2.0.2                    pypi_0    pypi
lxml                      4.9.2                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdtex2html                1.2.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
openai                    0.27.6                   pypi_0    pypi
openssl                   3.1.0                hcfcfb64_3    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
orjson                    3.8.11                   pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.1                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.1.2             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pydantic                  1.10.7                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pymupdf                   1.22.2                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.11.3          h2628c8c_0_cpython    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-docx               0.8.11                   pypi_0    pypi
python-markdown-math      0.8                      pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
regex                     2023.5.5                 pypi_0    pypi
requests                  2.30.0                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                67.7.2             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sgmllib3k                 1.0.0                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
starlette                 0.26.1                   pypi_0    pypi
tiktoken                  0.3.3                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tokenizers                0.13.3                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.28.1                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
urllib3                   2.0.2                    pypi_0    pypi
uvicorn                   0.22.0                   pypi_0    pypi
vc                        14.3                hb25d44b_16    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vc14_runtime              14.34.31931         h5081d32_16    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vs2015_runtime            14.34.31931         hed1258a_16    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
websockets                11.0.2                   pypi_0    pypi
wheel                     0.40.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.6                h8d14728_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yarl                      1.9.2                    pypi_0    pypi
- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/58963158/236657488-21338be9-04f8-45f8-8cc8-67db0aa90175.png)
![image](https://user-images.githubusercontent.com/58963158/236657492-22e4423d-1e9f-4ba3-ad0f-7c282e2dd2e0.png)

- **(3) Terminal Traceback 终端traceback（如有）**

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
这边无法复现，请按下F12看一下浏览器报错。

尝试
- 更换浏览器，代理模式禁止全局代理
- 清华源替换成pypi官方源/阿里源

**Comment by binary-husky** [comment]
你的部署方法是什么，本地部署还是云服务器

**Comment by 13299118606** [comment]
解决了 就是浏览器插件冲突  那个merlin： chatgpt  插件 问题，关闭或者删除插件后就好了

**Comment by denwade-05** [comment]
> 你的部署方法是什么，本地部署还是云服务器

我部署在远程服务器上，不在本地
1. 更换浏览器，代理模式禁止全局代理：已更换，无论是Chrome访客模式还是edge都无法回复，一直使用的是rule代理
