### ISSUE TITLE
https://huggingface.co/qingxu98 runtime error

### ISSUE THREAD

**Issue by vocmiku01** [binary-husky/gpt_academic#707]
![1683465324322](https://user-images.githubusercontent.com/106459020/236679770-5746e79c-8dd0-4b42-863b-1459fcfb2c7f.png)
beta版api导入后提示：您提供的api-key不满足要求，不包含任何可用于api2d-gpt-3.5-turbo的api-key。
api没有问题，之前一直使用
希望作者尽快修复，救救没法科学上网的孩子们

**Comment by vocmiku01** [comment]
duplicate space后也会出现该issue 急急急~

**Comment by binary-husky** [comment]
已经修复

**Comment by vocmiku01** [comment]
太优秀了

**Comment by DavinQi1210** [comment]
> 已经修复

太厉害了，能和Husky认识下吗，我在一个大模型公司里，VX 13261569307
