### ISSUE TITLE
如何启用一键更新？

### ISSUE THREAD

**Issue by DoctorOfEyjafjalla** [binary-husky/gpt_academic#708]
- **(1) Describe the bug 简述**
3.2版本更新后无法进行一键更新了，如何对代码进行修改以启用自动更新？还是只能手动更新？我没在代码中找到launch()

- **(2) Screen Shot 截图**
![image](https://user-images.githubusercontent.com/132829648/236682079-62631925-8d77-492b-868f-f5bae2f5a1b1.png)

- **(3) Terminal Traceback 终端traceback（如有）**
To create a public link, set `share=True` in `launch()`.

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
3.2之前的一键更新脚本有点bug，需要手动更新跨过去，3.3之后依然有问题吗？

**Comment by DoctorOfEyjafjalla** [comment]
刚手动从3.2更新到最新版，如果更新还遇到问题会再反馈。谢谢您。

binary-husky ***@***.***> 于2023年5月7日周日 22:42写道：

**Comment by Bailey-24** [comment]
![image](https://user-images.githubusercontent.com/72083251/237063209-11fe6838-9ac2-4987-8837-32d9f3695f39.png)

Ubuntu20.04下的3.31版本一键更新失败。

**Comment by Bailey-24** [comment]
如何手工更新代码。

git新手不是很会。本地已经修改过一些文件，比如config.py

**Comment by zlfccnu** [comment]
更新被禁用，怎么启用？每次弹出更新界面都很快，一闪而过
