### ISSUE TITLE
优化输入框位置

### ISSUE THREAD

**Issue by zhaoyundi** [binary-husky/gpt_academic#709]
目前输入框在右上角或者左下角，当右面内容特别长的时候，有点不符合正常的输入习惯，可否优化一下位置，仿照chatgpt原生的那种。谢谢大佬

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/236684171-0805d08e-9951-4baa-a5d7-b1fa2cc49bcc.png)
这样吗，config中改一下布局就行了
