### ISSUE TITLE
docker成功运行后container后，报错[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

### ISSUE THREAD

**Issue by huazai-create** [binary-husky/gpt_academic#711]
用docker运行container后，一直报错：[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。
![image](https://user-images.githubusercontent.com/72012812/236761036-f02517f1-bea8-4ec4-b135-680bca716e4f.png)
确定代理格式设置和代理连接应该没有问题，因为同样设置下，之前的老版本不用docker可以正常运行,想问问大佬可能得原因是什么？（新版本用anaconda搭建环境各种报错，心累，想用docker试试，结果又有问题···）
老版本可正常使用
![image](https://user-images.githubusercontent.com/72012812/236761561-272dbd12-4e89-4fcf-8ebc-fd138bacb17f.png)
logs,显示代理查询超时。
<img width="883" alt="image" src="https://user-images.githubusercontent.com/72012812/236762348-57e12b26-a922-4638-8073-cb8670498f76.png">

**Comment by binary-husky** [comment]
操作系统？config.py配置？请详细说明部署问题

**Comment by huazai-create** [comment]
> 操作系统？config.py配置？请详细说明部署问题

操作系统为macos，但是win11下用docker部署，也是相同的报错。config.py配置如下图，只改了API_KEY，proxies，WEB_PORT。
![Snipaste_2023-05-08_18-29-51](https://user-images.githubusercontent.com/72012812/236801698-5cdb54c9-b27a-4541-b6ea-90428d887c6b.png)

**Comment by binary-husky** [comment]
windows下docker需要用 -v 选项进行端口映射（科学上网端口 + web端口），例如 
`docker run  .........          -v 7860: 7860    -v 50923: 50923      ..............

**Comment by huazai-create** [comment]
> windows下docker需要用 -v 选项进行端口映射（科学上网端口 + web端口），例如 `docker run ......... -v 7860: 7860 -v 50923: 50923 ..............`

-v好像不是端口映射的指令，您是否想表示的是-p ?
![image](https://user-images.githubusercontent.com/72012812/236810840-b59e51a2-2f1c-4650-80d2-9c5e5fa683b7.png)

我对docker和端口映射不是很了解，之前是按照安装方法中的指示运行的（docker run --rm -it -p 38282:38282 gpt-academic）。请问如果需要映射科学上网端口（如7890），该如何修改运行指令？

**Comment by binary-husky** [comment]
docker run --rm -it -p 38282:38282 -p 7860:7860  gpt-academic

**Comment by binary-husky** [comment]
> > windows下docker需要用 -v 选项进行端口映射（科学上网端口 + web端口），例如 `docker run ......... -p 7860: 7860 -p 50923: 50923 ..............`
> 
> -v好像不是端口映射的指令，您是否想表示的是-p ? ![image](https://user-images.githubusercontent.com/72012812/236810840-b59e51a2-2f1c-4650-80d2-9c5e5fa683b7.png)
> 
> 我对docker和端口映射不是很了解，之前是按照安装方法中的指示运行的（docker run --rm -it -p 38282:38282 gpt-academic）。请问如果需要映射科学上网端口（如7890），该如何修改运行指令？

应该是 -p 不是 -v，我记错了

**Comment by G-czh** [comment]
> > windows下docker需要用 -v 选项进行端口映射（科学上网端口 + web端口），例如 `docker run ......... -v 7860: 7860 -v 50923: 50923 ..............`
> 
> -v好像不是端口映射的指令，您是否想表示的是-p ? ![image](https://user-images.githubusercontent.com/72012812/236810840-b59e51a2-2f1c-4650-80d2-9c5e5fa683b7.png)
> 
> 我对docker和端口映射不是很了解，之前是按照安装方法中的指示运行的（docker run --rm -it -p 38282:38282 gpt-academic）。请问如果需要映射科学上网端口（如7890），该如何修改运行指令？

请问你解决了吗，我遇到了一样的问题

**Comment by liyishuai** [comment]
如果你的代理服务器部署在宿主机，那么需要通过`host.docker.internal`来访问。例：`socks5h://host.docker.internal:13659`

**Comment by huazai-create** [comment]
> 如果你的代理服务器部署在宿主机，那么需要通过`host.docker.internal`来访问。例：`socks5h://host.docker.internal:13659`

感谢，问题得到解决，在config中将代理的地址更改后，可以访问了~

**Comment by huazai-create** [comment]
> > > windows下docker需要用 -v 选项进行端口映射（科学上网端口 + web端口），例如 `docker run ......... -v 7860: 7860 -v 50923: 50923 ..............`
> > 
> > 
> > -v好像不是端口映射的指令，您是否想表示的是-p ? ![image](https://user-images.githubusercontent.com/72012812/236810840-b59e51a2-2f1c-4650-80d2-9c5e5fa683b7.png)
> > 我对docker和端口映射不是很了解，之前是按照安装方法中的指示运行的（docker run --rm -it -p 38282:38282 gpt-academic）。请问如果需要映射科学上网端口（如7890），该如何修改运行指令？
> 
> 请问你解决了吗，我遇到了一样的问题
已解决
