### ISSUE TITLE
[Bug]: newbing 的一些问题反馈

### ISSUE THREAD

**Issue by Maddaxman** [binary-husky/gpt_academic#712]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

nuwbing如果操作停止输出，那么newbing就再不能响应了，只能重开进程才能恢复正常

**Comment by binary-husky** [comment]
目前的问题是停止输出的信号没传递newbing子进程，并不是没响应，只是在等待上一次的输出结束……

后续版本会关注这个问题的解决
