### ISSUE TITLE
[Bug]: 如果要在本地跑chatglm，需要添加python库，缺好几个依赖

### ISSUE THREAD

**Issue by bisonliao** [binary-husky/gpt_academic#714]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

如果要在本地跑chatglm，需要添加python库，缺好几个依赖
sentencepiece
cpm_kernels
pytorch

其中pytorch，如果需要使用cuda，还得根据下面url里的版本选择，最好直接加到Dockerfile里
https://pytorch.org/get-started/locally/

进一步的，如果需要使用宿主机已经下载好的chatglm文件，需要在docker容器启动的时候挂载-v /root/.cache:/root/.cache

我把chatglm跑起来了，但是中译英效果不好，也能上传代码文件供添加注释。但远程chatGPT的方式是ok的。

**Comment by binary-husky** [comment]
Pip安装，docker，还是docker-compose呢

**Comment by binary-husky** [comment]
如果是pip，还有些这些requirements.txt；如果是docker，应该dockerfile里面已经安装了

(https://github.com/binary-husky/gpt_academic/blob/master/request_llm/requirements_chatglm.txt)

[requirements_jittorllms.txt](https://github.com/binary-husky/gpt_academic/blob/master/request_llm/requirements_jittorllms.txt)

[requirements_moss.txt](https://github.com/binary-husky/gpt_academic/blob/master/request_llm/requirements_moss.txt)

[requirements_newbing.txt](https://github.com/binary-husky/gpt_academic/blob/master/request_llm/requirements_newbing.txt)

**Comment by wakewon** [comment]
如果是 docker 的话，把需要的 requirements_*.txt 内容附加到 requirements.txt，然后再 docker build 应该就可以了。
如：
`cat request_llm/requirements_chatglm.txt >>requirements.txt`
