### ISSUE TITLE
[Bug]: moss是在windows部署无法成功的

### ISSUE THREAD

**Issue by codeofyu** [binary-husky/gpt_academic#720]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

[notice] To update, run: F:\AI\chatgpt_academic\py310\python.exe -m pip install --upgrade pip
2023-05-10 11:54:13,714 - INFO - 获取moss.txt 中的依赖项
Looking in indexes: https://pypi.org/simple/
Requirement already satisfied: torch in f:\ai\chatgpt_academic\py310\lib\site-packages (from -r request_llm\requirements_moss.txt (line 1)) (1.13.1+cu117)
Collecting transformers==4.25.1
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
Requirement already satisfied: sentencepiece in f:\ai\chatgpt_academic\py310\lib\site-packages (from -r request_llm\requirements_moss.txt (line 3)) (0.1.97)
Collecting datasets
  Using cached datasets-2.12.0-py3-none-any.whl (474 kB)
Collecting accelerate
  Using cached accelerate-0.19.0-py3-none-any.whl (219 kB)
Requirement already satisfied: matplotlib in f:\ai\chatgpt_academic\py310\lib\site-packages (from -r request_llm\requirements_moss.txt (line 6)) (3.7.1)
Requirement already satisfied: huggingface_hub in f:\ai\chatgpt_academic\py310\lib\site-packages (from -r request_llm\requirements_moss.txt (line 7)) (0.13.2)
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

码还是出现了一个错误，就是 pip 无法找到 triton 这个包的合适版本。这可能是因为 triton 只支持 Linux 系统，而我的系统是 Windows。

**Comment by binary-husky** [comment]
连接到moss的代码issue：

https://github.com/OpenLMLab/MOSS/issues/65

https://github.com/OpenLMLab/MOSS/issues/68

**Comment by jumping-xwz** [comment]
我也遇到了同样的问题：

```log
(gpt_academic) I:\gpt_academic>python -m pip install -r request_llm/requirements_moss.txt
Requirement already satisfied: torch in i:\oobabooga\installer_files\conda\envs\gpt_academic\lib\site-packages (from -r request_llm/requirements_moss.txt (line 1)) (2.0.1)
Collecting transformers==4.25.1 (from -r request_llm/requirements_moss.txt (line 2))
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
Requirement already satisfied: sentencepiece in i:\oobabooga\installer_files\conda\envs\gpt_academic\lib\site-packages (from -r request_llm/requirements_moss.txt (line 3)) (0.1.99)
Collecting datasets (from -r request_llm/requirements_moss.txt (line 4))
  Obtaining dependency information for datasets from https://files.pythonhosted.org/packages/66/f8/38298237d18d4b6a8ee5dfe390e97bed5adb8e01ec6f9680c0ddf3066728/datasets-2.14.4-py3-none-any.whl.metadata
  Using cached datasets-2.14.4-py3-none-any.whl.metadata (19 kB)
Collecting accelerate (from -r request_llm/requirements_moss.txt (line 5))
  Obtaining dependency information for accelerate from https://files.pythonhosted.org/packages/70/f9/c381bcdd0c3829d723aa14eec8e75c6c377b4ca61ec68b8093d9f35fc7a7/accelerate-0.21.0-py3-none-any.whl.metadata
  Using cached accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: matplotlib in i:\oobabooga\installer_files\conda\envs\gpt_academic\lib\site-packages (from -r request_llm/requirements_moss.txt (line 6)) (3.7.2)
Requirement already satisfied: huggingface_hub in i:\oobabooga\installer_files\conda\envs\gpt_academic\lib\site-packages (from -r request_llm/requirements_moss.txt (line 7)) (0.16.4)
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton

(gpt_academic) I:\gpt_academic>
```
