### ISSUE TITLE
能否将添加一项保存对话信息至指定文件的功能

### ISSUE THREAD

**Issue by liliaoyuan** [binary-husky/gpt_academic#724]
或者有没有大佬有已经实现的脚本可以分享一下

**Comment by binary-husky** [comment]
有一个保存会话的按钮，

https://github.com/binary-husky/gpt_academic/blob/master/crazy_functions/%E5%AF%B9%E8%AF%9D%E5%8E%86%E5%8F%B2%E5%AD%98%E6%A1%A3.py

如果要固定文件，修改下84行即可
