### ISSUE TITLE
Docker加载main.py，但localhost打不开

### ISSUE THREAD

**Issue by xinshen1** [binary-husky/gpt_academic#726]
Mac本地使用Docker加载main.py，但localhost打不开

<img width="1210" alt="Screenshot 2023-05-11 at 11 20 09" src="https://github.com/binary-husky/gpt_academic/assets/90529730/ad164fa1-2d69-4e2d-9952-4083eb2b557a">
<img width="1428" alt="Screenshot 2023-05-11 at 11 21 26" src="https://github.com/binary-husky/gpt_academic/assets/90529730/16af5cce-d4d0-4e58-a7ea-dfc6db12b11f">

**Comment by binary-husky** [comment]
@xinshen1 @Gan-Xing 

可能修改config.py出错了，试试用环境变量WEB_PORT覆盖一下配置

docker run --rm -it -e WEB_PORT=50923 -p 50923:50923 gpt-academic

**Comment by Gan-Xing** [comment]
来信已收到。谢谢。——此为自动回复。Votre courrier est bien re?0?4u,merci.//C'est une réponse automatique.Your e-mail has been received,thanks.//This is an automatic reply.

**Comment by Gan-Xing** [comment]
来信已收到。谢谢。——此为自动回复。Votre courrier est bien re?0?4u,merci.//C'est une réponse automatique.Your e-mail has been received,thanks.//This is an automatic reply.
