### ISSUE TITLE
[Bug]: 更新失败错误

### ISSUE THREAD

**Issue by zeroxiaoyaoLI** [binary-husky/gpt_academic#728]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

![1683798374731](https://github.com/binary-husky/gpt_academic/assets/114148402/354f4973-3d1c-4a1e-9027-69cd68f1ade4)
我是老版本的，第一次更新的时候能够更新第二次就不行了我该怎么办

**Comment by zeroxiaoyaoLI** [comment]
@binary-husky

**Comment by binary-husky** [comment]
3.1的自动更新组件后来发现有bug，新版本已经修复，但您现在的版本只能手动更新啦 ~

手动更新：下载代码直接覆盖就行了

**Comment by zeroxiaoyaoLI** [comment]
@binary-husky 直接git覆盖就行了嘛，谢谢啦

**Comment by zhouyu98** [comment]
@binary-husky 3.37版本好像也不行诶，和楼主一样的报错
