### ISSUE TITLE
在群晖ds220+上部署了该项目，通过本地局域网IP:端口号，可以正常访问；通过设置的https域名，能打开登录页面，也能正常登录，但提交问题的时候出错，该怎么处理。

### ISSUE THREAD

**Issue by mengxiangbao** [binary-husky/gpt_academic#730]
### Installation Method | 安装方法与平台

Docker（Linux）

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

请大佬不吝赐教：在群晖ds220+上部署了该项目，通过本地局域网IP:端口号，可以正常登录并访问，提问及回答都很正常；通过设置的https域名，能打开登录页面，也能正常登录，但提交问题的时候出错，该怎么处理。我的群晖使用OpenClash代理*学*网。看了https://github.com/binary-husky/gpt_academic/issues/155#issuecomment-1493199402，并按照里面的内容一步一步进行了配置，不管用，还是问题依旧，请问该怎么解决？？？
![image](https://github.com/binary-husky/gpt_academic/assets/132032455/90065aa4-6f39-4964-a0e1-91836efd9a5f)
在我群晖上通过docker布置的其他项目，都可以通过https域名访问，这个和其他设置都一样，但是不行，我不是搞计算机软件和网络的，很多都不懂，但喜欢折腾。请明白的大佬一定不吝赐教。。。。。。。谢谢。。。。。。

**Comment by binary-husky** [comment]
是websocket的问题吗？浏览器F12看看？

**Comment by mengxiangbao** [comment]
搞复杂了，终于好了，谢谢大家关注。
