### ISSUE TITLE
M1 macbook 环境包orjson安装报错

### ISSUE THREAD

**Issue by huazai-create** [binary-husky/gpt_academic#731]
M1 macbook 在conda下执行python -m pip install -r requirements.txt时，在安装到orjson包时报错，具体报错如下

<img width="687" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/72012812/ec738d8e-7c4a-478d-9798-58b57f3488ca">

尝试按提示安装了rustup（curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh）,还是报错，如下
<img width="737" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/72012812/198a875b-4cc2-41db-83ef-4fcbadee8c92">

麻烦有没有懂的大佬看看怎么解决?

**Comment by yellowos** [comment]
Need science up net.
