### ISSUE TITLE
为什么提示这样，我API生成好几个了

### ISSUE THREAD

**Issue by LinKPrian** [binary-husky/gpt_academic#732]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 181, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
  File "D:\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "", "type": "invalid_request_error", "param": null, "code": "invalid_api_key" }}

**Comment by LinKPrian** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/28661201/5b9f3cc9-e112-4945-853f-7675604fdf9b)

**Comment by Da1Liu** [comment]
+1

**Comment by Hzyyy-rookie** [comment]
我也是

**Comment by binary-husky** [comment]
apikey无效，你可以尝试把apikey从输入框输入，然后看是否识别

**Comment by Keivenhandsome** [comment]
我也是遇到同样的问题，但是我使用这个api测试了其他代码，可以跑通
