### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by XFLasdf** [binary-husky/gpt_academic#733]
详细信息如下：
ubuntu@VM-0-16-ubuntu:/usr/local/gitlab_repositry/chatgpt_academic$ sudo python3 main.py
Traceback (most recent call last):
  File "main.py", line 208, in <module>
    main()
  File "main.py", line 4, in main
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

当前requirements.txt中是gradio==3.28.3，安装的版本也是这个，但仍然报错找不到该模块。

**Comment by gladiator137** [comment]
哥，我也遇到这个问题。咋解决的
