### ISSUE TITLE
这么火的项目没有人建一个docker镜像吗？

### ISSUE THREAD

**Issue by CatAnd-Dog** [binary-husky/gpt_academic#737]
有没有好心人建一个docker镜像啊。

**Comment by binary-husky** [comment]
见docker-compose呀

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/3921a1af-8368-474c-abeb-9d23bd5cb286)

**Comment by CatAnd-Dog** [comment]
> ![image](https://user-images.githubusercontent.com/96192199/238007240-3921a1af-8368-474c-abeb-9d23bd5cb286.png)

我是指托管到docker hub的公共镜像

**Comment by fusang1337** [comment]
俺也奇怪 都是需要本地编译然后才能使用 按道理说git action可以预编译上传吧？我好想看到他们这么做

**Comment by binary-husky** [comment]
> > ![image](https://user-images.githubusercontent.com/96192199/238007240-3921a1af-8368-474c-abeb-9d23bd5cb286.png)
> 
> 我是指托管到docker hub的公共镜像

有任何区别吗？
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/e4ab2a99-da37-400e-84fd-d532b8a6a08e)

**Comment by fusang1337** [comment]
原来已经可以直接pull了 readme里面仍然是编译安装：
安装-方法2：使用Docker
仅ChatGPT（推荐大多数人选择）
git clone https://github.com/binary-husky/chatgpt_academic.git  # 下载项目
cd chatgpt_academic                                 # 进入路径
nano config.py                                      # 用任意文本编辑器编辑config.py, 配置 “Proxy”， “API_KEY” 以及 “WEB_PORT” (例如50923) 等
docker build -t gpt-academic .                      # 安装

#（最后一步-选择1）在Linux环境下，用`--net=host`更方便快捷
docker run --rm -it --net=host gpt-academic
#（最后一步-选择2）在macOS/windows环境下，只能用-p选项将容器上的端口(例如50923)暴露给主机上的端口
docker run --rm -it -e WEB_PORT=50923 -p 50923:50923 gpt-academic

**Comment by binary-husky** [comment]
> 原来已经可以直接pull了 readme里面仍然是编译安装： 安装-方法2：使用Docker 仅ChatGPT（推荐大多数人选择） git clone https://github.com/binary-husky/chatgpt_academic.git # 下载项目 cd chatgpt_academic # 进入路径 nano config.py # 用任意文本编辑器编辑config.py, 配置 “Proxy”， “API_KEY” 以及 “WEB_PORT” (例如50923) 等 docker build -t gpt-academic . # 安装
> 
> #（最后一步-选择1）在Linux环境下，用`--net=host`更方便快捷 docker run --rm -it --net=host gpt-academic #（最后一步-选择2）在macOS/windows环境下，只能用-p选项将容器上的端口(例如50923)暴露给主机上的端口 docker run --rm -it -e WEB_PORT=50923 -p 50923:50923 gpt-academic
> 

下面还有docker-compose方案呀，就是用的我们传到dockerhub的模型

**Comment by CatAnd-Dog** [comment]
> > 原来已经可以直接pull了 readme里面仍然是编译安装： 安装-方法2：使用Docker 仅ChatGPT（推荐大多数人选择） git clone https://github.com/binary-husky/chatgpt_academic.git # 下载项目 cd chatgpt_academic # 进入路径 nano config.py # 用任意文本编辑器编辑config.py, 配置 “Proxy”， “API_KEY” 以及 “WEB_PORT” (例如50923) 等 docker build -t gpt-academic . # 安装
> > #（最后一步-选择1）在Linux环境下，用`--net=host`更方便快捷 docker run --rm -it --net=host gpt-academic #（最后一步-选择2）在macOS/windows环境下，只能用-p选项将容器上的端口(例如50923)暴露给主机上的端口 docker run --rm -it -e WEB_PORT=50923 -p 50923:50923 gpt-academic
> 
> 下面还有docker-compose方案呀，就是用的我们传到dockerhub的模型

不知道是不是我的服务器太拉了，1v1G的vps，每次docker打包到一半就卡死了。然后重新打包还是这样。

**Comment by flashszn** [comment]
> > > ![image](https://user-images.githubusercontent.com/96192199/238007240-3921a1af-8368-474c-abeb-9d23bd5cb286.png)
> > 
> > 
> > 我是指托管到docker hub的公共镜像
> 
> 有任何区别吗？ ![image](https://user-images.githubusercontent.com/96192199/238136771-e4ab2a99-da37-400e-84fd-d532b8a6a08e.png)

国内的话pull的时候非常非常卡，而且没法镜像加速

**Comment by reeink** [comment]
@flashszn  dockerhub 也卡吧，比较大的镜像加速源基本都支持ghcr.io, 比如[南京大学镜像源](https://doc.nju.edu.cn/books/35f4a)

**Comment by onlinedear** [comment]
为啥每次重启，端口号总是会变啊？
