### ISSUE TITLE
[Bug]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by sdf135s** [binary-husky/gpt_academic#739]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

我随便输入了一段文字就出现了这样的错误。有人碰到了解决了的嘛
Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 181, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
  File "D:\ProgramData\Anaconda3\envs\sig_prepro\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\ProgramData\Anaconda3\envs\sig_prepro\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ProgramData\Anaconda3\envs\sig_prepro\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Saint-lsy** [comment]
+1

**Comment by 0lqd0** [comment]
+1

**Comment by binary-husky** [comment]
traceback不完整，缺少截图

**Comment by sdf135s** [comment]
补充个截图：

![1](https://github.com/binary-husky/gpt_academic/assets/119823961/4880a9c4-7b5f-4201-a18c-bf5e73447e1e)

**Comment by geek312** [comment]
+1

**Comment by binary-husky** [comment]
> 补充个截图：
> 
> ![1](https://user-images.githubusercontent.com/119823961/238164338-4880a9c4-7b5f-4201-a18c-bf5e73447e1e.png)

Web界面的截图，而且这个traceback不完整吧？

**Comment by geek312** [comment]
> @sdf135s @geek312 是否使用了非openai官方的API_URL_REDIRECT？

环境未变的情况下，更换apikey和代理解决了该问题。
猜测：api-key 或者 账户过期（原plus用户，重新注册的free 账户）

**Comment by sdf135s** [comment]
> > @sdf135s @geek312 是否使用了非openai官方的API_URL_REDIRECT？
> 
> 环境未变的情况下，更换apikey和代理解决了该问题。 猜测：api-key 或者 账户过期（原plus用户，重新注册的free 账户）

你这一说还真是，应该是apikey的问题，这玩意是不是要花钱买啊？

**Comment by sdf135s** [comment]
> traceback不完整，缺少截图

应该是apikey的问题，我用的apikey确实是无效的apikey。

**Comment by ChinaLinZhen** [comment]
mark

**Comment by fttz** [comment]
可能是apikey的问题，我尝试重新生成apikey，问题得到解决。
