### ISSUE TITLE
想写一个针对gpt_academic的浏览器插件

### ISSUE THREAD

**Issue by LiZheGuang** [binary-husky/gpt_academic#740]
方向是来做功能增强，大家有什么想在插件里集成的功能吗？

- [x] 复制文案-复制代码
- [x] 语音播放
- [x] 左侧转PDF输出
- [x] 左侧导出MD文件
- [x] 支持开启和关闭功能

**Comment by binary-husky** [comment]
👍

**Comment by ShaySheng** [comment]
希望能够支持官方插件的功能，主要是1联网搜索，2Wolfram
Code interpreter如果能够支持就更好了

**Comment by LiZheGuang** [comment]
浏览器插件已经做完第一个小版本了，但需要黑夜模式下进行使用。

ISSUES我就关了 https://github.com/LiZheGuang/gpt_academic_chrome_extension
