### ISSUE TITLE
希望增加对Claude的支持

### ISSUE THREAD

**Issue by JurianZhou** [binary-husky/gpt_academic#744]
如题，希望也能对本地项目使用claude-100k模型！之前分析整个项目头文件的时候显示太多了溢出，用Claude100k是不是就不会了

**Comment by binary-husky** [comment]
关注中

**Comment by zhaobudaomingzi** [comment]
同求

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/pull/746 中添加了通过slack对claude的支持

**Comment by binary-husky** [comment]
@JurianZhou @zhaobudaomingzi 
https://github.com/binary-husky/gpt_academic/pull/746 中添加了通过slack对claude的支持

**Comment by M1saka10010** [comment]
> @JurianZhou @zhaobudaomingzi #746 中添加了通过slack对claude的支持

可否提供一个支持gpt+latex+claude的docker镜像？

**Comment by M1saka10010** [comment]
> @M1saka10010 @zhaobudaomingzi @JurianZhou 添加了claude官方api的支持，docker-compose方案一应该就能用

这里说的是slack-claude

**Comment by Chapoly1305** [comment]
@binary-husky Hi, Claude 我这边使用似乎不太正常，见https://github.com/binary-husky/gpt_academic/issues/1901 
不知最近是否有变更，或是配置上和使用OpenAI的不同？ 谢谢
