### ISSUE TITLE
[Bug]: 根本无法用，windows，不知道为什么，所有东西都配置好了（包括代理），提交后就卡住

### ISSUE THREAD

**Issue by johnspiin** [binary-husky/gpt_academic#747]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug & Screen Shot | 简述 与 有帮助的截图

关掉重开，系统重启，软件重装，系统重装，都没用还是如此

**Comment by binary-husky** [comment]
没有提供有帮助的信息，请提供完整报错信息，详细描述问题
