### ISSUE TITLE
安装依赖时发生错误subprocess-exited-with-error

### ISSUE THREAD

**Issue by rarapazii** [binary-husky/gpt_academic#750]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug | 简述

在安装依赖时发生错误error: subprocess-exited-with-error

### Screen Shot | 有帮助的截图

<img width="559" alt="PNG图像" src="https://github.com/binary-husky/gpt_academic/assets/98836476/4f51a70f-07bd-4147-b33c-9867ecb9139b">

**Comment by binary-husky** [comment]
traceback不完整
