### ISSUE TITLE
[Bug]: 多线程翻译出现 UnicodeEncodeError 错误

### ISSUE THREAD

**Issue by XuNing2** [binary-husky/gpt_academic#752]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt and python>=3.8)

### Describe the bug | 简述

上传pdf文件后，使用 批量翻译pdf文档(多线程)时出现错误。
~~~bash
Traceback (most recent call last):
  File "./toolbox.py", line 88, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "./crazy_functions/批量翻译PDF文档_多线程.py", line 56, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, sys_prompt)
  File "./crazy_functions/批量翻译PDF文档_多线程.py", line 113, in 解析PDF
    res = write_results_to_file(final, file_name=create_report_file_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./toolbox.py", line 178, in write_results_to_file
    f.write(content)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc47' in position 151: surrogates not allowed
~~~

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/80052126/20213366-ea9f-4db9-88c0-21e08d64e6a5)
![image](https://github.com/binary-husky/gpt_academic/assets/80052126/d59bbfa2-841d-4ccb-be40-392865e9b446)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

复现的被翻译的论文材料：
https://arxiv.org/pdf/2305.07239v1.pdf

**Comment by binary-husky** [comment]
感谢反馈，周末我试试修复

**Comment by binary-husky** [comment]
[总结论文-2305.07239v1.pdf.trans.md](https://github.com/binary-husky/gpt_academic/files/11521720/-2305.07239v1.pdf.trans.md)

我无法复现该错误，请问您运行python的终端是什么？cmd、powershell还是gitbash？

**Comment by XuNing2** [comment]
cent os服务器上的 miniconda 终端上直接运行 `python main.py` 得到。

**Comment by binary-husky** [comment]
找到问题了 #773

**Comment by XuNing2** [comment]
> 找到问题了 #773

已经修复了吗？辛苦了
