### ISSUE TITLE
[Bug]: gpt-4模型无法使用

### ISSUE THREAD

**Issue by TSF1995** [binary-husky/gpt_academic#754]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Describe the bug | 简述

使用chatgpt官方网页可以使用GPT-4，在gpt-academic配置了api-key之后，提示"模型不存在，或没有体验资格"。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/40820323/4edb7079-1386-48bb-9da6-0aa420037214)
![image](https://github.com/binary-husky/gpt_academic/assets/40820323/33fe3c25-f76b-42bf-918f-3a6b4d34a320)

**Comment by ccdanpian** [comment]
只要升级了chatgpt Plus，在chat.openai.com就可以试用GPT-4。但是如果调用GPT-4的API插件，需要在官网加入waitlist申请才可以。
