### ISSUE TITLE
[Bug]: [Local Message] Request timeout. Network error. Please check proxy settings in config.py.

### ISSUE THREAD

**Issue by xiaomougu** [binary-husky/gpt_academic#757]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Describe the bug | 简述

已经按照图里的要求配置了，但是还是不行，哪位大神帮忙看看

### Screen Shot | 有帮助的截图

 proxies = {
        #          [协议]://  [地址]  :[端口]
        "http":  "socks5h://127.0.0.1:5480",  # 再例如  "http":  "http://127.0.0.1:7890",
        "https": "socks5h://127.0.0.1:5480",  # 再例如  "https": "http://127.0.0.1:7890",
    }
else:
    proxies = None

**Comment by binary-husky** [comment]
填写之前不要忘记把USE_PROXY改成True

**Comment by danielhu19** [comment]
#627 
试试改成：
```
"http": "127.0.0.1:7890",
"https": "127.0.0.1:7890",
}
```

**Comment by xzm123456** [comment]
我也是相同的bug，旧版的可以运行，新版的怎么都不能。。。

**Comment by DoctorBerlain** [comment]
这个问题解决了吗，我也是这种问题
