### ISSUE TITLE
回复的输出速度比较慢，不知道是api本身的限制，还是可以通过前端进行调整？

### ISSUE THREAD

**Issue by zhugeyicixin** [binary-husky/gpt_academic#758]

**Comment by binary-husky** [comment]
- 应该和openai服务器的负荷有关
- 另外我猜测和你是否是付费用户也有关系

**Comment by nikeaddidaslining** [comment]
> * 应该和openai服务器的负荷有关
> * 另外我猜测和你是否是付费用户也有关系

我之前用的时候很快，但后来到上限了就帮了张卡，换了绑卡的key之后就变慢了，再openai上用还是比较快的，不知道为什么在这边就变慢了

**Comment by nikeaddidaslining** [comment]
> * 应该和openai服务器的负荷有关
> * 另外我猜测和你是否是付费用户也有关系

还会是不是蹦出来一个json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)，这种错误，大佬可以看一下咋办吗？

**Comment by zhugeyicixin** [comment]
> > * 应该和openai服务器的负荷有关
> > * 另外我猜测和你是否是付费用户也有关系
> 
> 我之前用的时候很快，但后来到上限了就帮了张卡，换了绑卡的key之后就变慢了，再openai上用还是比较快的，不知道为什么在这边就变慢了

“在openai上用还是比较快的”是指在用chatgpt的网站么？我也是感觉用api+自己host好像没有chatgpt响应快

**Comment by nikeaddidaslining** [comment]
> 

对的，网站上快很多
