### ISSUE TITLE
[Bug]: 修改API_URL_REDIRECT后报错。

### ISSUE THREAD

**Issue by ooceanxx** [binary-husky/gpt_academic#760]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug | 简述

使用非官方api，通过API_URL_REDIRECT= {"https://api.openai.com/v1/chat/completions": "https://api.chatanywhere.com.cn/v1/chat/completions"} 修改转发地址后，对话显示远程返回错误。更新bridge_chatgpt补丁后也没有改变。

### Screen Shot | 有帮助的截图

![屏幕截图 2023-05-19 114041](https://github.com/binary-husky/gpt_academic/assets/47415080/1ffb2ef1-d932-43f7-90ef-bf521d5eccaf)

**Comment by binary-husky** [comment]
我试试

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/153f2f4f-8537-4881-a225-94516cb79d50)
这是什么网站呀？？？

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/e71be194-c7ff-4cc3-b604-2527daef5947)

我把key替换成https://github.com/chatanywhere/GPT_API_free中提供的key，完全正常，没有发现问题：

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/1976f546-277a-4f4f-a4ae-c80a9eb181a5)

这是我的配置

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/597547b6-a92f-4106-a11b-953f00dc511a)

**Comment by ooceanxx** [comment]
现在我也能正常运行了，不知道之前是怎么回事。。。。
