### ISSUE TITLE
使用clash无论怎么配置，check的时候是正常的，启动后提交查询就会显示超时

### ISSUE THREAD

**Issue by Never-Forget-Heart** [binary-husky/gpt_academic#761]

**Comment by YujunHuang063** [comment]
我也是这个问题，是不是要通过config.py的proxies参数配置代理服务器？

**Comment by Never-Forget-Heart** [comment]
clash更换一个节点就解决了&nbsp;


以往
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yujun ***@***.***&gt;; 
发送时间: 2023年5月21日(星期天) 下午3:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [binary-husky/gpt_academic] 使用clash无论怎么配置，check的时候是正常的，启动后提交查询就会显示超时 (Issue #761)





 
我也是这个问题，是不是要通过config.py的proxies参数配置代理服务器？
