### ISSUE TITLE
对接stable diffusion webui

### ISSUE THREAD

**Issue by VectorZhao** [binary-husky/gpt_academic#762]
https://github.com/AUTOMATIC1111/stable-diffusion-webui
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API

**Comment by VegeBun-csj** [comment]
这也太香了

**Comment by VectorZhao** [comment]
参考项目：
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/browser-version/drawing/sdwebui.py
https://chatgpt-qq.lss233.com/pei-zhi-wen-jian-jiao-cheng/ai-hua-tu

**Comment by VectorZhao** [comment]
当然本项目的发展主线还是以科研为主。其实对接stable diffusion也可以生成一些对学术有帮助的图片，比如行星科学领域学者在做ppt汇报时，便可以利用关键词：`planets, universe`，效果图如下：
![image](https://github.com/binary-husky/gpt_academic/assets/16644993/a7ae3549-55b0-4479-bee3-c04194c3f271)
![photo_2023-05-19_14-12-54](https://github.com/binary-husky/gpt_academic/assets/16644993/2272da3d-7d7e-48a9-a9f9-fbcb18302c0c)
