### ISSUE TITLE
[Bug]: claude生成过程会报错（内容生成到一半 报错了）

### ISSUE THREAD

**Issue by Maddaxman** [binary-husky/gpt_academic#763]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Describe the bug | 简述

claude生成过程会报错（内容生成到一半 报错了）

### Screen Shot | 有帮助的截图

<img width="1002" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/31379908/1f360090-aa33-44f8-b016-bbd779b51807">

**Comment by Rid7** [comment]
这个问题是由于收取slack claude bot时过度请求引起的，可以考虑于
 `request_llm/bridge_stackclaude.py#L67-L68`处添加一个等待延时，示例如下：
```                
if msg["text"].endswith("Typing…_"):
    await asyncio.sleep(0.5)    # 等待时间设置为ui回复刷新率和请求限制之前取得平衡，0.5只是一个示范值
    yield False, msg["text"]
```

**Comment by Maddaxman** [comment]
> await asyncio.sleep(0.5)

解决了
