### ISSUE TITLE
[Bug]: 切换模型之后，前一模型的输入会再次提交

### ISSUE THREAD

**Issue by zhaobudaomingzi** [binary-husky/gpt_academic#766]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt and python>=3.8)

### ChatGPT学术优化：
![image](https://github.com/binary-husky/gpt_academic/assets/54617500/b53c9ca1-cd57-4a28-a9d3-9ed85c7366d4)
### Claude网页端：
![image](https://github.com/binary-husky/gpt_academic/assets/54617500/1bf53049-9d5d-4f2a-bbf0-1189d4fde436)

**Comment by binary-husky** [comment]
提交了一个补丁，再试试？

**Comment by zhaobudaomingzi** [comment]
> 提交了一个补丁，再试试？

我使用方法1安装的，应该怎么打补丁？

**Comment by zhaobudaomingzi** [comment]
> 提交了一个补丁，再试试？

问题解决了，但是我还想问一下，在bridge_stackclaude.py源代码中删除“追加历史”(local history)这个改动对其功能有没有什么影响？
