### ISSUE TITLE
[Bug]: 批量翻译PDF文档（多线程）

### ISSUE THREAD

**Issue by h2bit** [binary-husky/gpt_academic#773]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Describe the bug | 简述

使用`批量翻译PDF文档（多线程）`功能翻译pdf时，翻译完成写入结果时报错，遇到无法解析的字符，程序退出，写入中断

### Screen Shot | 有帮助的截图

> 异常 ‘utf-8’ codec can’t encode character ‘\ud835’ in position 735: surrogates not allowed

> Traceback (most recent call last):
>   File "./toolbox.py", line 88, in decorated
>     yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
>   File "./crazy_functions/批量翻译PDF文档_多线程.py", line 56, in 批量翻译PDF文档
>     yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, sys_prompt)
>   File "./crazy_functions/批量翻译PDF文档_多线程.py", line 113, in 解析PDF
>     res = write_results_to_file(final, file_name=create_report_file_name)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "./toolbox.py", line 178, in write_results_to_file
>     f.write(content)
> UnicodeEncodeError: 'utf-8' codec can't encode character '\ud835' in position 735: surrogates not allowed

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

pdf文件链接[https://dl.acm.org/doi/pdf/10.1145/3543507.3583345](url)

**Comment by binary-husky** [comment]
运行python的终端是什么？cmd、powershell还是gitbash？

**Comment by binary-husky** [comment]
另外安装的时候有没有碰到异常？代码是否经过修改？

**Comment by h2bit** [comment]
> 运行python的终端是什么？cmd、powershell还是gitbash？

您好，感谢回复。我用的是Ubuntu 22.04的shell，使用最新的3.35版本，按照[docker的使用教程](https://github.com/binary-husky/gpt_academic#%E5%AE%89%E8%A3%85-%E6%96%B9%E6%B3%952%E4%BD%BF%E7%94%A8docker)编译运行的：
`docker pull ghcr.io/binary-husky/gpt_academic_nolocal:master`
`docker build -t gpt-academic . `
`docker run --rm -it --net=host gpt-academic  `


> 另外安装的时候有没有碰到异常？代码是否经过修改？

安装没有异常，代码未修改。我试了[huggingface上的demo](https://huggingface.co/spaces/qingxu98/gpt-academic)也存在这个问题。


我修改了`toolbox.py`中的`def write_results_to_file(history, file_name=None):`函数，解决了这个报错，原因是有些公式不能正确识别，但是这样写入的.md文档中公式变成了乱码

```
def write_results_to_file(history, file_name=None):
            ...
            content = content.encode("utf-8", "replace")
            f.write(content.decode())
            ...
```
出错的pdf公式段落如下：
![image](https://github.com/binary-husky/gpt_academic/assets/27765516/5bf1e79f-4251-4bff-947b-3a1c936c7550)

**Comment by binary-husky** [comment]
非常感谢 我再试试

**Comment by h2bit** [comment]
感谢修复，解决了公式识别的问题
