### ISSUE TITLE
请问markdown以源码形式显示了，怎么办？？

### ISSUE THREAD

**Issue by zxb1030** [binary-husky/gpt_academic#778]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt and python>=3.8)

### Describe the bug | 简述

提交后，会显示源码

### Screen Shot | 有帮助的截图

![QQ截图20230523120159](https://github.com/binary-husky/gpt_academic/assets/49875216/20fab427-0bdb-4bbe-bc28-e9a573b18001)

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/28f2a452-50e1-4e64-ab5c-973c39a96345)
请提供复现方法？

**Comment by zxb1030** [comment]
你这个是正常的啊，我另外一台电脑也是正常的，但是这台电脑 随便输入什么， chatgpt 显示的时候 都带有网页代码

**Comment by zxb1030** [comment]
什么复现方法？？？

**Comment by Do1e** [comment]
我的也是，用的最新的代码

**Comment by zxb1030** [comment]
感觉应该加一步，markdown转换为html文件

**Comment by binary-husky** [comment]
gradio版本是否按照requirement.txt ?

**Comment by zxb1030** [comment]
> gradio版本是否按照requirement.txt ?

就是这个问题，我装的gradio 3.32版本，刚才重新装了3.28.3,  就可以了，非常感谢
