### ISSUE TITLE
用量管理

### ISSUE THREAD

**Issue by mobguang** [binary-husky/gpt_academic#779]
Hi @binary-husky ,

你好，这个工具非常实用，感谢！请问工具有ChatGPT API token的用量管理功能吗，谢谢。

**Comment by binary-husky** [comment]
你好，目前没有。

暂时也不太愿意加。打个比方的话，如果洗澡的时候有个水表在你眼前倒计时，洗澡肯定也洗的很焦虑的对吧 ~

**Comment by zhoumaochao** [comment]
你好，想构建一个web,团队使用的话，如果有token管理以及用户管理，会方便很多。一个账户密码很容易泄露，而且没有token管理，比较容易浪费。非常期待这个功能哦！

**Comment by yeq618** [comment]
您好，首先非常感谢这个工具。我同意楼上的观点。我目前也是构建web用于团队使用，如果有某个人滥用浪费我无法发现。我觉得每个用户的用量可以不显示在界面上，而只写到服务器的某个文件里，这样也不会有您说的焦虑的问题，更便于团队管理。
