### ISSUE TITLE
求在Vercel或者zeabur等托管平台上的一键部署

### ISSUE THREAD

**Issue by leizhuray** [binary-husky/gpt_academic#780]
这些托管平台可连接自己的域名，从而不需要在科学上网的环境下使用。Hugging face在48h没有活动的情况下就会自动断开，同时也需要科学上网。如果能够在vercel或者zeabur上进行一键部署就好了。
个人试了一下再zeabur上直接部署，building的log显示成功了
![image](https://github.com/binary-husky/gpt_academic/assets/32698600/22bdb7e1-8ad3-4317-8b0f-aca17cefe48c)

但打开对应的网页时显示如下图
![image](https://github.com/binary-husky/gpt_academic/assets/32698600/9afb6cb3-e113-4498-9e41-a0f181077cd2)

下面这幅图是zeabur的一个python代码的实例配置，不知道作者能否帮忙看看方不方便改
![image](https://github.com/binary-husky/gpt_academic/assets/32698600/fdaaaeb3-980e-4b40-9a79-8906a1563bf8)

**Comment by binary-husky** [comment]
是不是端口问题

**Comment by leizhuray** [comment]
> 是不是端口问题
感觉可能不只是这个问题

**Comment by 1Co1Li1La** [comment]
我也试了试zeabur部署, 但最终结果也是那个界面(甚至running logs都显示正常)

![image](https://github.com/binary-husky/gpt_academic/assets/116722876/f4a179e1-0604-4dbd-8452-bcd4a1b689c1)

**Comment by Co1Li1La1** [comment]
#161

**Comment by ZHEYESHIYU** [comment]
同希望后续能适配zeabur

**Comment by binary-husky** [comment]
> 我也试了试zeabur部署, 但最终结果也是那个界面(甚至running logs都显示正常)
> 
> ![image](https://user-images.githubusercontent.com/116722876/246614779-f4a179e1-0604-4dbd-8452-bcd4a1b689c1.png)

修改WEB_PORT试试？另外zeabur只有1GB存储是不是不太够
