### ISSUE TITLE
[Bug]: Mac安装的时候报错, error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by wang-xulong** [binary-husky/gpt_academic#781]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

在新建conda环境，并在其中使用pip安装阿里云的环境的时候报错。
后面尝试了下运行下main.py文件，说是没有gradio 模块。
Collecting orjson
  Using cached https://mirrors.aliyun.com/pypi/packages/3e/1d/e5628cd5828a325db7c1b3c241c99b76b1640ec2fd7b6eb6bd9895879e6b/orjson-3.8.12.tar.gz (669 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details

### Screen Shot | 有帮助的截图

![Xnip2023-05-23_18-13-14](https://github.com/binary-husky/gpt_academic/assets/50507531/d4305eeb-2b4b-4e82-9272-a7d97c423561)

**Comment by sawyerbutton** [comment]
Same Issue, and also got a subsequent error with `PermissionError: [Errno 13] Permission denied: 'cargo'`  in the following terminal output

**Comment by sawyerbutton** [comment]
@wang-xulong I used docker as virtual env and made a success, try for it as a substitution.
Also, I tried to install rust-cargo in my original env, also met the issue like above.
That's why I switch to docker. 
Just a mention for saving time.

**Comment by wubizhi** [comment]
same probelm, I just installed the rust to slove the issues.
the command is easy:
curl https://sh.rustup.rs -sSf | sh

**Comment by sawyerbutton** [comment]
> same probelm, I just installed the rust to slove the issues. the command is easy: curl https://sh.rustup.rs -sSf | sh

Tried, but does not work. 
It seems that my operating approach might be wrong. 
I'm not very familiar with Rust, and I was trying to install Rust in a Conda env, but it seems that Rust's installation and Conda env do not appear to be associated. 
Is there any special trick I should follow?

**Comment by susannusas** [comment]
To install Rust on macOS, you can follow these steps:

Open a terminal application. You can find the Terminal app in the "Utilities" folder within the "Applications" folder, or you can use Spotlight search by pressing "Command" + "Space" and typing "Terminal".

In the terminal, you'll need to run the following command to start the Rust installation process:

arduino
Copy code
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
This command will download and run the Rustup installer script. It will prompt you to proceed with the installation and display the terms and conditions. Type "y" to agree and proceed.

The installer will then download and install the necessary components for Rust, including the Rust compiler, Cargo (Rust's package manager), and other tools.

Once the installation is complete, the terminal will display a message indicating that the installation was successful.

To enable Rust in your current terminal session, you can either close and reopen the terminal or run the following command:

bash
Copy code
source $HOME/.cargo/env
You can verify the installation by running the following command, which will display the installed Rust version:
css
Copy code
rustc --version
That's it! Rust should now be successfully installed on your macOS system. You can start using Rust by writing and compiling Rust programs using the Rust compiler and managing packages with Cargo.
