### ISSUE TITLE
微软newbing不需要认证了

### ISSUE THREAD

**Issue by 373Kice** [binary-husky/gpt_academic#782]
https://github.com/acheong08/EdgeGPT
EdgeGPT更新已经不需要验证了，up能不能更新下，让gpt_acdemic的new-bing也不需要cookie。

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/b078e564-f0a9-43fd-82e7-52e9c8fdf926)

谢谢提醒，刚刚加上了，欢迎测试https://github.com/binary-husky/gpt_academic/commit/42eef1bea72caf7ac1ab073f58a058d995e9a69b
