### ISSUE TITLE
将config_private.py的路径定义为home目录下的特定文件夹，以便于管理。

### ISSUE THREAD

**Issue by hongyi-zhao** [binary-husky/gpt_academic#784]
建议将 `config_private.py` 的路径定义为 `home` 目录下的特定文件夹，以便于管理。比如: `~/.config/gpt_academic/`。

**Comment by binary-husky** [comment]
目前是支持环境变量的，加入.bashrc即可，详情见docker-compose文件

**Comment by binary-husky** [comment]
环境变量的写法参考docker-compose文件 @hongyi-zhao

**Comment by hongyi-zhao** [comment]
我检查了[docker-compose.yml](https://github.com/binary-husky/gpt_academic/blob/master/docker-compose.yml)文件，并没有发现相关的环境变量啊？

**Comment by binary-husky** [comment]
.bashrc中追加环境变量
```bashrc
API_KEY='sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
USE_PROXY='True'
proxies='{ "http": "socks5h://localhost:10880", "https": "socks5h://localhost:10880", }'
LLM_MODEL='gpt-3.5-turbo'
```
