### ISSUE TITLE
[Bug]: 输入继续的时候，经常碰到这样的错误提示：

### ISSUE THREAD

**Issue by mengxiangbao** [binary-husky/gpt_academic#789]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

![image](https://github.com/binary-husky/gpt_academic/assets/132032455/67447eb9-9dcc-4677-abb3-06b18ac212d3)
![image](https://github.com/binary-husky/gpt_academic/assets/132032455/3d79f47e-541d-4c32-8d61-5dbce8aa2258)
有时候输入“继续”正常执行，有时候会出现上述错误提示。

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/132032455/67447eb9-9dcc-4677-abb3-06b18ac212d3)
![image](https://github.com/binary-husky/gpt_academic/assets/132032455/3d79f47e-541d-4c32-8d61-5dbce8aa2258)
有时候输入“继续”正常执行，有时候会出现上述错误提示。

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

群晖ds220+上的docker安装

**Comment by binary-husky** [comment]
历史文本太长了，只是一个警告而已，提醒你之前的对话某些信息被丢弃了，你可以选择：
- 无视这个提醒
- 清空对话历史

**Comment by mengxiangbao** [comment]
收到，谢谢
