### ISSUE TITLE
[Bug]: copy按钮无法正常

### ISSUE THREAD

**Issue by 1099234990** [binary-husky/gpt_academic#790]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

copy没反应，

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/111104984/033a109e-adc9-4015-9633-06273e77011d)

**Comment by binary-husky** [comment]
已经注意到了这个问题，正在尝试修复
