### ISSUE TITLE
[Bug]: pdf全文翻译bug

### ISSUE THREAD

**Issue by maxadc** [binary-husky/gpt_academic#793]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我测试了 claude与 chatglm的pdf全文翻译..两者都有bug
claude的bug是,多线程问题,claude比较慢,造成后边的翻译全部失败.测试pdf7页,失败两页.
chatglm的问题是,翻译的结果每页都没翻译完成.
我测试了用chatglm自己的webUI,一页的pdf的内容是可以翻译完的.

### Screen Shot | 有帮助的截图

1

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

1

**Comment by maxadc** [comment]
gpt_academic的最大token设置的4096

**Comment by binary-husky** [comment]
关注中

**Comment by maxadc** [comment]
继续反馈，刚测试了最新版，看描述说改了pdf翻译bug。实测是，chatglm之前能翻译一部分，现在是一句都不翻译了。

**Comment by binary-husky** [comment]
> 继续反馈，刚测试了最新版，看描述说改了pdf翻译bug。实测是，chatglm之前能翻译一部分，现在是一句都不翻译了。

请问这个参数设置的是多少？
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/7b286928-f089-4507-a8fa-53f6bb2c4d70)

**Comment by binary-husky** [comment]
如果太小了可能会出问题

**Comment by maxadc** [comment]
sorry，第二次测试chatglm的翻译是我的问题，大意了，忘记了修改maxlenght，不过我也没想到这会有影响。刚刚测试了改为4096是没有问题的。
对了，我记得之前小的是不是会报错！这次小了不报错，直接不翻译！

**Comment by binary-husky** [comment]
支持借助GROBID实现PDF高精度翻译
https://github.com/binary-husky/gpt_academic/commit/ec76d3dcc4c5b8dc514e25a6305f9ff0828623dd
