### ISSUE TITLE
多个API Key的调用顺序？

### ISSUE THREAD

**Issue by seriousAA** [binary-husky/gpt_academic#796]
我有多个OpenAI 的 api key，我都填在config.py里面了，我想知道实际的调用顺序是什么？是第一个api的usage limits到了之后再换下一个，还是说随机选一个调用？

**Comment by binary-husky** [comment]
随机选一个调用

**Comment by BiuBoom1996** [comment]
我想问一下GPT4 api key  能调用GPT4嘛？
