### ISSUE TITLE
[Feature]: 新版一键安装包疑问

### ISSUE THREAD

**Issue by MrGongqi** [binary-husky/gpt_academic#801]
### Class | 类型

其他

### Feature Request | 功能请求

你好，，请问刚刚发布的新版一键安装包是不是不需要之前繁琐的安装步骤和配置了，，，直接安装就行了，一键安装这个不太懂呢大神

**Comment by binary-husky** [comment]
那个只是给不熟悉python的用户用的

另外方便在windows下测试程序用这个很方便

**Comment by MrGongqi** [comment]
你好，，我就是不熟悉python的用户，，，之前一直想安装，看到网上有很多安装教程，有很多都失败了，我感觉我太需要了您这个版本了，，，但是我看了一下压缩包，还是不太懂具体怎样安装呀，我电脑上安装了python3.8, 请问具体怎样安装呢，具体步骤是怎样的呀？我很乐意测试您的程序。再次谢谢

**Comment by binary-husky** [comment]
您好，刚才代码除了点问题，请重新下载压缩包，然后双击 Windows运行.bat 即可
