### ISSUE TITLE
更新后无法登入 [ 需更新到最新代码 ] 

### ISSUE THREAD

**Issue by zhoumaochao** [binary-husky/gpt_academic#802]
更新后登入一直显示loading
![屏幕截图 2023-05-27 222110](https://github.com/binary-husky/gpt_academic/assets/96688571/e055399b-b940-4213-b560-ddf5232f2550)

**Comment by binary-husky** [comment]
很抱歉，我的疏忽，请现在再从github更新代码就行了

**Comment by binary-husky** [comment]
@zhoumaochao

**Comment by zhoumaochao** [comment]
已解决，谢谢。
