### ISSUE TITLE
[Feature]: 能否加入代码重构，与註解功能

### ISSUE THREAD

**Issue by fdsf53451001** [binary-husky/gpt_academic#804]
### Class | 类型

函数插件

**Comment by binary-husky** [comment]
能详细讲讲吗

**Comment by fdsf53451001** [comment]
主要是想用在python程序，简化程式码逻辑与优化代码
这里有一些GPT Prompt的重构代码范例
https://juejin.cn/post/7233695223401627705
我试着写了prompt，结果如下
![code_refactor](https://github.com/binary-husky/gpt_academic/assets/35889113/baf75850-9f51-41f5-b0ce-60437c10e423)

自动添加註解似乎不能很好的相容代码重构，建议先不做，谢谢。
