### ISSUE TITLE
[Bug]: 5月27日代码更新，碰到好多问题 [ 需更新到最新代码 ]

### ISSUE THREAD

**Issue by MrLittleShark** [binary-husky/gpt_academic#805]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我安装了最新版的gpt academic，但是很多功能都不能使用。
1. 一开始运行时，碰到gradio版本报错的问题， 
main.py中有一行 assert gr.__version__.startswith("3.32.1"), "Please run `pip install -r requirements.txt --upgrade` to install a stable gradio fork." 事实上gradio最新版本为3.32.0。手动把这个1改为0后代码运行（当然是更新requirements.txt之后的）
2. markdown格式错误，见截图，尤其是输出公式的时候，不知道是不是我的版本问题，但是我换了markdown的版本后问题依旧存在。
3. Claude用不了，但是newbing还能用

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/112299157/a52ec766-3787-4aae-bc15-d875d5be681d)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'ip': '203.93.11.157', 'network': '203.93.11.0/24', 'version': 'IPv4', 'city': 'Haidian', 'region': 'Beijing', 'region_code': 'BJ', 'country': 'CN', 'country_name': 'China', 'country_code': 'CN', 'country_code_iso3': 'CHN', 'country_capital': 'Beijing', 'country_tld': '.cn', 'continent_code': 'AS', 'in_eu': False, 'postal': None, 'latitude': 39.9881, 'longitude': 116.2846, 'timezone': 'Asia/Shanghai', 'utc_offset': '+0800', 'country_calling_code': '+86', 'currency': 'CNY', 'currency_name': 'Yuan Renminbi', 'languages': 'zh-CN,yue,wuu,dta,ug,za', 'country_area': 9596960.0, 'country_population': 1411778724, 'asn': 'AS4808', 'org': 'China Unicom Beijing Province Network'}
代理配置 socks5h://localhost:7890, 代理所在地：China
如果浏览器没有自动打开，请复制并转到以下URL：
        （亮色主题）: http://localhost:5819
        （暗色主题）: http://localhost:5819/?__theme=dark
正在执行一些模块的预热...
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
正在加载tokenizer，如果是第一次运行，可能需要一点时间下载参数
加载tokenizer完毕
Running on local URL:  http://0.0.0.0:5819

To create a public link, set `share=True` in `launch()`.
 gpt-3.5-turbo : 0 : 你好 ..........
 gpt-3.5-turbo : 1 : 椭圆面积公式、 ..........
 gpt-3.5-turbo : 0 : 圆的面积公式 ..........
Traceback (most recent call last):
  File "D:\Python\Lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\gradio\blocks.py", line 1067, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\gradio\utils.py", line 336, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\gradio\utils.py", line 329, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\gradio\utils.py", line 312, in run_sync_iterator_async        
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "c:\Users\Chen\Downloads\gpt_academic-version3.37\toolbox.py", line 62, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "c:\Users\Chen\Downloads\gpt_academic-version3.37\request_llm\bridge_all.py", line 324, in predict
    method = model_info[llm_kwargs['llm_model']]["fn_with_ui"]
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'slack-claude'
 [PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'socks5h://localhost:7890', 'https': 'socks5h://localhost:7890'} 
{'conversationId': '51D|BingProd|5010FF34F2E8F7993091A45DEDF88FCDCF6D6B4EEE81538949CB0', 'clientId': '1055519180816202', 'conversationSignature': 'TpdwvBGW9YjE8IR5/PP4BTfRiDkPQY=', 'result': {'value': 'Success', 'message': None}}
 [API_KEY] 本项目现已支持OpenAI和API2D的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,api2d-key3" 
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。 
 [API_KEY] 您的 API_KEY 是: sk-*** API_KEY 导入成功 
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
question: Serve me as a writing and programming assistant.
圆的面积公式
你好

你
你好
你好，
你好，这
你好，这里
你好，这里是
你好，这里是必
你好，这里是必应
你好，这里是必应。
你好，这里是必应。我
你好，这里是必应。我可以
你好，这里是必应。我可以用
你好，这里是必应。我可以用中
你好，这里是必应。我可以用中文
你好，这里是必应。我可以用中文和
你好，这里是必应。我可以用中文和你
你好，这里是必应。我可以用中文和你交
你好，这里是必应。我可以用中文和你交流
你好，这里是必应。我可以用中文和你交流。
你好，这里是必应。我可以用中文和你交流。😊
你好，这里是必应。我可以用中文和你交流。😊

你好，这里是必应。我可以用中文和你交流。😊

你好，这里是必应。我可以用中文和你交流。😊

你好，这里是必应。我可以用中文和你交流。😊

-------- receive final ---------

**Comment by MrLittleShark** [comment]
claude能用了，虽然不知道发生了啥

**Comment by MrLittleShark** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/112299157/242536a4-4de6-47e5-8ac7-7b044e7c06ad)
应该是库的版本的问题，这个是之前保留的3.36版本，在更新3.37的库之后同样发生了这样的情况，有可能是库不兼容

**Comment by MrLittleShark** [comment]
破案了：是gradio的版本问题，退回到3.28.3就可以用了，但是3.32.0版本不可以用，估计与markdown库冲突，希望作者修复一下！比心！

**Comment by binary-husky** [comment]
我应该已经把3.32.0拉黑了，没报错吗

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/8ca3f186-6b66-49cb-a5af-a315ae683382)

**Comment by binary-husky** [comment]
请用requirements.txt安装即可

**Comment by MrLittleShark** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/112299157/f3af1826-0a0e-42bd-b6c3-a1f09dadc7b8)
我这边是这样的

**Comment by MrLittleShark** [comment]
这个3.28.3是我自己改的，原文件里是3.32.1，然后报错了。requirements.txt里面好像没有指定版本

**Comment by MrLittleShark** [comment]
作者大大是不是发错版本了

**Comment by MrLittleShark** [comment]
还有个小问题，我看源码里有好多地方写着'stack-claude'，或者'stackclaude'，这是拼错了吧。对调用claude会不会有影响啊

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/2c61b84d-a85c-4104-8f2c-957107a9ed79)

没发错，这个gradio版本就在代码路径下，官方的gradio版本bug太多了，解决PR太慢，我重新打包了一个

![image](https://github.com/binary-husky/gpt_academic/assets/96192199/35c814b6-524b-46cc-b7ba-b60f084c1289)

**Comment by binary-husky** [comment]
请更新代码吧

**Comment by MrLittleShark** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/112299157/b4d10ae3-ceab-46ba-b6bd-50676a6737a0)

**Comment by MrLittleShark** [comment]
okok，感谢！

**Comment by binary-husky** [comment]
嗯嗯，昨天的代码确实出了点问题
