### ISSUE TITLE
[Bug]: Json异常 “error”: { “message”: “”, “type”: “invalid_request_error”, “param”: null, “code”: “invalid_api_key” }}

### ISSUE THREAD

**Issue by hsh819** [binary-husky/gpt_academic#806]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

我在Railway上部署chatgpt_academic，修改了config.py中API_KEY和WEB_PORT，但是访问时出现如下错误：
Traceback (most recent call last):
File "/gpt/request_llm/bridge_chatgpt.py", line 189, in predict
if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
这段代码错误实际上就是缺少API_KEY，但是config.py中的确修改为个人的OPENAI_API_KEY，也可以使用，如果将OPENAI_API_KEY放在页面输入框中，可以成功导入，那为啥config.py中API_KEY不能直接使用，请问有没有朋友遇到类似问题，感谢给予指点~

### Screen Shot | 有帮助的截图

<img width="1083" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/61219683/1b432f00-c793-43bc-a8f6-e03573a417d1">

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/85fc5434-ee6f-4008-8e62-a8954ead0a4c)

**Comment by hsh819** [comment]
感谢您的回复，我复制了一份配置为config_private.py，但是似乎没有用，根本没有读取config_private.py里面的信息，不知道为啥在Railway上就不行，在本地部署没有问题。另外，请问下，如果我只需要设置API_KEY为环境变量，是否只需在config.py中替换API_KEY所在行内容为：
import os
API_KEY = os.environ["API_KEY"]   #API_KEY为系统环境变量名

**Comment by hsh819** [comment]
如果您方便的话，在Railway上部署一下，是否会出现类似问题，谢谢~

**Comment by binary-husky** [comment]
配置读取的程序很简单的，不会出bug，截图打码看看你config咋填的？

**Comment by hsh819** [comment]
<img width="614" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/61219683/da926679-7820-4a3e-9612-514b3f4e24cf">
<img width="637" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/61219683/8dd08bd7-741e-4032-a7d9-1dcba441c14d">
<img width="663" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/61219683/92dd3c50-7592-40b7-ba65-e7d40b20b777">
第一张图是config.py（后面修改为固定端口）， 第二张图是环境变量设置，第三张图是错误信息，似乎Railway无法读取环境变量OPENAI_API_KEY，但是PORT可以，感谢~

**Comment by hsh819** [comment]
我知道怎么回事了，需要修改一下Dockerfile文件，注释以下代码才行：RUN python3  -c 'from check_proxy import warm_up_modules; warm_up_modules()'，感谢您的指导

**Comment by hsh819** [comment]
问题已解决

**Comment by binary-husky** [comment]
谢谢反馈

**Comment by chenjiajieeeee** [comment]
我注释了还是会报和题主同样的错误

**Comment by hsh819** [comment]
> 我注释了还是会报和题主同样的错误

请问你是在Railway上部署吗，如果是的话，需要进行如下操作：
1. 修改config.py文件或者config_private.py文件：
import os
API_KEY = os.getenv("OPENAI_API_KEY")  #使用系统环境变量
# API_KEY = "sk-此处填API密钥"
WEB_PORT = 8000  #自定义固定端口，如8000
2. 在Dockfile文件中注释如下代码：
# RUN echo '[global]' > /etc/pip.conf && \
#    echo 'index-url = https://mirrors.aliyun.com/pypi/simple/' >> /etc/pip.conf && \
#   echo 'trusted-host = mirrors.aliyun.com' >> /etc/pip.conf
# RUN python3  -c 'from check_proxy import warm_up_modules; warm_up_modules()'
3. 部署完成后，添加环境变量PORT和OPENAI_API_KEY，其中PORT为自定义端口，如8000，OPENAI_API_KEY为OPENAI的API密钥。

**Comment by chenjiajieeeee** [comment]
按照您的方法，问题已经解决了，感谢题主！
