### ISSUE TITLE
重定向后出现错误

### ISSUE THREAD

**Issue by zhoumaochao** [binary-husky/gpt_academic#808]
重定向后出现错误
![屏幕截图 2023-05-28 215225](https://github.com/binary-husky/gpt_academic/assets/96688571/a3426221-13dd-4383-8c9c-f12e811fecf9)

**Comment by binary-husky** [comment]
重定向和APIKEY？

**Comment by zhoumaochao** [comment]
重定向地址和APIKEY是没问题的，本地运行是没问题的，但是部署到国内服务器就会出现以上问题？

**Comment by yyx20202020** [comment]
同样问题，而且我本地运行也是报错
