### ISSUE TITLE
[Bug]: clash网络错误

### ISSUE THREAD

**Issue by MrGongqi** [binary-husky/gpt_academic#813]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我明明输入了代理IP，为啥还是提示网络错误

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/49467246/2707eb93-9118-41b9-8712-11fa40679e08)
上图是主页界面。
![image](https://github.com/binary-husky/gpt_academic/assets/49467246/09a0bad3-1a4b-4903-8d7b-cc51ba2ecc29)

下图是我查找出来的网络IP，使用的是clash代理软件：
![image](https://github.com/binary-husky/gpt_academic/assets/49467246/4d2ccd68-dcd8-4737-9aab-1107ab1afc63)

**Comment by GHangyu** [comment]
我的主页跟你一样的提示，但是我的代理是能用的，很奇怪

**Comment by MrGongqi** [comment]
不知道为什么会出现这个错误，我的这个IP能够浏览谷歌和YouTube的啊，还能够用网页版的chatgpt啊，，翻墙可行的啊，为什么在这里就提示代理可能无效

**Comment by wangfeng35** [comment]
> 不知道为什么会出现这个错误，我的这个IP能够浏览谷歌和YouTube的啊，还能够用网页版的chatgpt啊，，翻墙可行的啊，为什么在这里就提示代理可能无效

查询超时，能正常用就不用管这提示

**Comment by MrGongqi** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/49467246/3f975085-7d47-4e77-8726-4ceeba991df3)
但是还是用不了啊，不知道咋滴

**Comment by chewgunboy** [comment]
我也有同样的情况，并且不生成gradio的链接了

**Comment by chewgunboy** [comment]
我也会遇到同样的问题，我是能查询到地址，但是就是会提醒我，协议，ip，端口三缺一不可，但实际我并没有做出任何改动

**Comment by MrGongqi** [comment]
可能确实是我哪里弄错了，，，但是一直找不到原因，期待大神能详细的指导一下

**Comment by wangfeng35** [comment]
> 可能确实是我哪里弄错了，，，但是一直找不到原因，期待大神能详细的指导一下

clash代理的话查看你clash里设置的代理端口，程序里代理http跟https设置成http://127.0.0.1:[端口号]，一般clash默认是7890，则程序里代理应该设置成"http://127.0.0.1:7890"

**Comment by MrGongqi** [comment]
感谢，，，我试试

**Comment by MrGongqi** [comment]
我的端口号确实是7890，那是不是就写成http://127.0.0.1:7890啦，，，前面的127.0.0.1是固定的吗，在哪里找到，不是代理的ip网址吗？，，，求解，谢谢

**Comment by wangfeng35** [comment]
> 我的端口号确实是7890，那是不是就写成[http://127.0.0.1:7890啦，，，前面的127.0.0.1是固定的吗，在哪里找到，不是代理的ip网址吗？，，，求解，谢谢]%B0%A2%E8%B0%A2)

127.0.0.1是本地回环地址，也称为localhost。它是一个特殊的IP地址，指向本地计算机。
clash会在你本地计算机开个端口监听，然后再去连接远程的服务器，所以这里不需要填远程代理IP。

**Comment by MrGongqi** [comment]
喔，，，这下就理清楚了为啥我填写IP一直错误，非常感谢，，，我可不可以这样理解，所有使用clash代理软件的电脑基本上都是填写 127.0.0.1:[端口号] 就行啦

**Comment by wangfeng35** [comment]
> 喔，，，这下就理清楚了为啥我填写IP一直错误，非常感谢，，，我可不可以这样理解，所有使用clash代理软件的电脑基本上都是填写 127.0.0.1:[端口号] 就行啦

是的

**Comment by chewgunboy** [comment]
> > 我的端口号确实是7890，那是不是就写成[http://127.0.0.1:7890啦，，，前面的127.0.0.1是固定的吗，在哪里找到，不是代理的ip网址吗？，，，求解，谢谢]%B0%A2%E8%B0%A2)
> 
> 127.0.0.1是本地回环地址，也称为localhost。它是一个特殊的IP地址，指向本地计算机。 clash会在你本地计算机开个端口监听，然后再去连接远程的服务器，所以这里不需要填远程代理IP。

您好，我也是同样的问题，但是我确定我的clash在使用过程固定的端口好是12138，并且在对应位置做出了修改，运行python时能识别到正确的地址，但是只是在回复的适合出现问题

**Comment by chewgunboy** [comment]
> > 喔，，，这下就理清楚了为啥我填写IP一直错误，非常感谢，，，我可不可以这样理解，所有使用clash代理软件的电脑基本上都是填写 127.0.0.1:[端口号] 就行啦
> 
> 是的

同样还是会出现提示我的三口出现问题，我使用的clash一直都是固定端口12138，在
![image](https://github.com/binary-husky/gpt_academic/assets/47527345/335af37c-b708-4ae9-9521-8a960e69f3bf)
同时，我也在
![image](https://github.com/binary-husky/gpt_academic/assets/47527345/d5188cb5-c42f-4a3c-8969-ac15a84fb4a3)

做了修改，运行之后完全正确能识别
![image](https://github.com/binary-husky/gpt_academic/assets/47527345/23294d44-84b0-458b-9e4d-d4e2a71a0c77)

但是最后，仍然提示我的三个可能有一项错误

您可以给我提示一下还有什么地方可能存在错误吗

**Comment by wangfeng35** [comment]
> > > 
> 您可以给我提示一下还有什么地方可能存在错误吗

您这看起来网络并没错啊 运行起来报网络错误么？？

**Comment by chewgunboy** [comment]
> 

是的，这非常奇怪，因为我昨天甚至还可以使用，今早才出现的这个问题，我在最新的3.37和2.3同时遇到了这个问题，唯一的区别可能是我曾使用过zerotier，但是这应该不影响才对

**Comment by chewgunboy** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/47527345/0cd7180f-58c0-4ac7-8eb1-2c6c077744cc)
![image](https://github.com/binary-husky/gpt_academic/assets/47527345/d870d33f-6a0f-4e38-8ecc-dce737919bd7)
进入之后下方状态栏仍然可以识别我的ip位置，并且hew和我挂的相同，但一旦提交就会出错

**Comment by wangfeng35** [comment]
> > 
> 
> 是的，这非常奇怪，因为我昨天甚至还可以使用，今早才出现的这个问题，我在最新的3.37和2.3同时遇到了这个问题，唯一的区别可能是我曾使用过zerotier，但是这应该不影响才对

你看看远程网是不是可以正常访问openai 你这上面的配置是没错的 因为都正确识别出代理位置了

**Comment by MrGongqi** [comment]
完美

谢谢！！！！
非常感谢！！！！！

**Comment by chewgunboy** [comment]
> > > 
> > 
> > 
> > 是的，这非常奇怪，因为我昨天甚至还可以使用，今早才出现的这个问题，我在最新的3.37和2.3同时遇到了这个问题，唯一的区别可能是我曾使用过zerotier，但是这应该不影响才对
> 
> 你看看远程网是不是可以正常访问openai 你这上面的配置是没错的 因为都正确识别出代理位置了

是可以的，我为了保证不是由于代理的问题直接访问了chat.openai.com，所以我非常疑惑

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/issues/1

https://www.bilibili.com/video/BV1rc411W7Dr

**Comment by q1164012062** [comment]
我也一样，本来用着没事，今天用就不行了，也是clash

**Comment by GHangyu** [comment]
我切换为美国的节点之后可以正常使用，可能是之前的节点被openai限制了

**Comment by tealapwang** [comment]
> https://www.bilibili.com/video/BV1rc411W7Dr

我的情况也一样。之前用得都可以，然后突然就不能用了。但是运行时是可以显示代理地址的，也切换了几个地址都还是不行，一直提示：[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

**Comment by tealapwang** [comment]
我的clash情况也一样。之前用得都可以，然后突然就不能用了。但是运行时是可以显示代理地址的，也切换了几个地址都还是不行，一直提示：[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

**Comment by JRhaha** [comment]
> 

我也是同样的情况，请问你的问题解决了吗

**Comment by dadaniejiangjun** [comment]
> 我切换为美国的节点之后可以正常使用，可能是之前的节点被openai限制了

啊哈，节点从香港切换到日本就可以用了

**Comment by dadaniejiangjun** [comment]
节点从香港切换到日本就可以用了，研究了好半天终于弄好了
