### ISSUE TITLE
API_URL_REDIRECT问题

### ISSUE THREAD

**Issue by chengjian922708** [binary-husky/gpt_academic#817]
### Class | 类型

None

### Feature Request | 功能请求

用自己反代得https://api.openai.com，访问一直都是报下面的错。
[Local Message] Request timeout. Network error. Please check proxy settings in config.py.网络错误，检查代理服务器是否可用，以及代理设置的格式是否正确，格式须是[协议]://[地址]:[端口]，缺一不可。

**Comment by binary-husky** [comment]
有api地址和测试key吗

**Comment by Eternal130** [comment]
试试http,别用https

**Comment by chengjian922708** [comment]
> 有api地址和测试key吗

用cloudflare worker就可以，自己反代的就不行。。
