### ISSUE TITLE
[Bug]: 运行启动后页面布局混乱，疑似渲染不出来，相应功能正常使用。

### ISSUE THREAD

**Issue by ssdlhy** [binary-husky/gpt_academic#822]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

描述：项目利用anaconda正常搭建，均是最新版本，python main.py启动运行后功能正常使用，但是前端界面渲染不出来结果，页面布局混乱。
尝试方法：
1.ctrl F5和ctrl shift del均试过，清除缓存后无法解决；
2. 重置了Internet选项，无效果；
3. F12修改了界面加载速率，无效果；
4. 刷新了dns缓存，无效果；
5. 更换了edge、Chrome、firefox三个浏览器打开界面，均失败，其中edge、chrome页面布局混乱，Firefox空白页
同时F12观察网络元素，均已返回200状态码。
怀疑：
1.项目不兼容，前端渲染无果
2.曾安装过2345，怀疑劫持行为

### Screen Shot | 有帮助的截图

![11111111111](https://github.com/binary-husky/gpt_academic/assets/104998863/cb9684a1-a621-4568-a8f6-a6cfe6cdb3b1)

**Comment by binary-husky** [comment]
有其他人有类似的问题吗？需要确定一下是共性还是个例

**Comment by binary-husky** [comment]
这种情况之前没见过

**Comment by yangbang18** [comment]
+1, win10, 同样布局出现了问题

**Comment by WeiKKJ** [comment]
开发者选项看下估计是一些css没加载出来，把相应的地址加入到代理应该就好了。

**Comment by anjoj0** [comment]
+1

**Comment by anjoj0** [comment]
> 

请问如何查看地址呢

**Comment by WeiKKJ** [comment]
开发者选项   红色的就是访问不到的url

ZhiXian ***@***.***> 于2023年7月6日周四 17:47写道：
