### ISSUE TITLE
[Bug]: 提示[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由, 拒绝服务.

### ISSUE THREAD

**Issue by 1099234990** [binary-husky/gpt_academic#824]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

用着用着突然提示[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由, 拒绝服务.，也更换了新的API KEY

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/111104984/6ecbfa7c-6783-4141-b451-ed922c823631)

**Comment by 1099234990** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/111104984/981eda7e-a0f8-4d30-a3ee-799b3644ebd0)
这是没额度了吗

**Comment by 1099234990** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/111104984/324e51d7-4349-42a7-9465-ef7064859ac9)

**Comment by gyt290811** [comment]
我昨天也遇到了这样的问题，有没有什么大佬有解决的方案呀？

**Comment by leizhuray** [comment]
网页上都提示你过期了，重新搞个号或者尝试绑定吧

**Comment by ascetic-monk** [comment]
我也有一样的问题，网页版的chatGPT是可以使用的，API码也更换过了，本地失败之后在huggingface上也跑过也失败了

**Comment by gyt290811** [comment]
> 
ok,解决了，注册一个新的账号就可以了
如果还是不行，在检查config_private.py里面的APIkey是否和你的config.py文件中的是否相同，以config文件中的为标准

**Comment by Field95** [comment]
expires提示6月1日过期，免费额度过期了，要么更换另外的账号，要么买额度了

**Comment by AlexChen-2020** [comment]
> > 
> 
> ok,解决了，注册一个新的账号就可以了 如果还是不行，在检查config_private.py里面的APIkey是否和你的config.py文件中的是否相同，以config文件中的为标准

我按照这个方法成功了 谢谢
