### ISSUE TITLE
[Bug]: 页脚的Use via API是什么内容，点了打不开，看控制台网络500错误

### ISSUE THREAD

**Issue by maxadc** [binary-husky/gpt_academic#826]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

如题

### Screen Shot | 有帮助的截图

1

**Comment by binary-husky** [comment]
新版本已经删除了呀
