### ISSUE TITLE
[Bug]: 安装出现缺少jaxlib报错

### ISSUE THREAD

**Issue by jcy321** [binary-husky/gpt_academic#827]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

旧版本运行正常，尝试使用新版本失败，原因似乎与jaxlib库有关？附上新版本启动失败报错，尝试安装jaxlib报错与旧版本正常运行截图旧版本，希望对开发人员有所助益。这可是我超级喜欢的开源项目（笑）此祝商祺！

### Screen Shot | 有帮助的截图

<img width="851" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/74154315/6c446b30-f774-478e-8a14-b8acace41a42">
<img width="851" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/74154315/7924b949-d5ea-4d9f-96cc-afd1b122a2cf">
<img width="860" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/74154315/00411e63-6d22-4efa-b6a6-0e74ea3a7721">

**Comment by binary-husky** [comment]
这是chatglm模组加载失败，谢谢反馈 ！

**Comment by jcy321** [comment]
> 这是chatglm模组加载失败，谢谢反馈 ！

那么请问如何解决这一问题以正确安装并启动呢？我已经反复尝试了数十次了，但是依旧毫无效果，恳请您的指正。
