### ISSUE TITLE
[Bug]: 回答问题时，自带无效代码，干扰阅读

### ISSUE THREAD

**Issue by Blackcf** [binary-husky/gpt_academic#828]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

每次回答之前，会添加<div class="markdown-body"><p>代码，如下图所示

gradio-3.32.2-py3-none-any.whl安装失败，故安装的官方版gradio-3.32.0

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/33195344/aa74e4b2-2d2c-4873-848f-0aaee4440e63)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

nohup: ignoring input
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

**Comment by MrLittleShark** [comment]
官方版gradio-3.32.0这个版本不要用，可以用早期的3.28.3版本

**Comment by Blackcf** [comment]
> 官方版gradio-3.32.0这个版本不要用，可以用早期的3.28.3版本

谢谢，改为3.283后，问题解决
