### ISSUE TITLE
[Bug]: multi_language.py gives invalid syntax error now

### ISSUE THREAD

**Issue by cranyy** [binary-husky/gpt_academic#830]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Running the multi_language.py doesnt work anymore. It does create the folder and populates it correctly, but every time you run both the multi_language.py file in the root or the main.py file in /english/  you get the same error : 

 from crazy_functions.LangchainKnowledgeBase import KnowledgeBaseQ&A
                                                                     ^
SyntaxError: invalid syntax

### Screen Shot | 有帮助的截图

![Untitled](https://github.com/binary-husky/gpt_academic/assets/128929586/59124a53-4877-45c4-b844-50024a3c95e2)

**Comment by binary-husky** [comment]
that this a new test function plugin, but I remember I have put it in `try except` clause?

Anyway, solution:
- open your local file `https://github.com/binary-husky/gpt_academic/blob/master/docs/translate_english.json` , search Q&A and change it to QA
- run multi-language again, don't worry, translated words will not be translated again
- perhaps open a pull request about `translate_english.json`?
