### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wyc23** [binary-husky/gpt_academic#831]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

实验性函数调用出错

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/99090103/65e12978-3bb3-43b0-9ae0-5a0b496dcfc6)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "./toolbox.py", line 99, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "./crazy_functions/理解PDF文档内容.py", line 112, in 理解PDF文档内容标准文件输入
    yield from 解析PDF(txt, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File "./crazy_functions/理解PDF文档内容.py", line 15, in 解析PDF
    file_content, page_one = read_and_clean_pdf_text(file_name) # （尝试）按照章节切割PDF
  File "./crazy_functions/crazy_utils.py", line 471, in read_and_clean_pdf_text
    main_fsize = max(fsize_statiscs, key=fsize_statiscs.get)
ValueError: max() arg is an empty sequence

**Comment by worldjack7** [comment]
I have the same issue
