### ISSUE TITLE
[Bug]: 知识库构建失败，缺少模块zh_langchain

### ISSUE THREAD

**Issue by YongjiangXu** [binary-husky/gpt_academic#835]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用知识库功能时，报错，未安装模块：zh_langchain
但是找不到这个包，在各种源上
请教大家有人用过吗，可以指点下吗，谢谢

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/112735821/b0418bb4-8e4d-47de-9948-2ddb71b2d0f9)

**Comment by YongjiangXu** [comment]
> 用官方pip源，别用大学的镜像

大佬你好，安装之后成功运行，在文件区上传数份PDF文档，进行知识库构建时出现这个报错，请问怎么解决，谢谢您的回复。
![image](https://github.com/binary-husky/gpt_academic/assets/112735821/39f3ea76-8ef0-49b9-95b1-69cd693aacc6)

**Comment by binary-husky** [comment]
不应该呀
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/0e8d1fe5-6fad-42a4-8b4d-6205bf4fe48e)

**Comment by binary-husky** [comment]
可能依赖安装失败了

**Comment by MrLee115** [comment]
![图片](https://github.com/binary-husky/gpt_academic/assets/50662855/e4fa4944-664d-4fc9-b696-ff8de544220e)
同问，求解决

**Comment by Esmety** [comment]
已解決，我問了gpt，這是它的回答︰根據您提供的錯誤信息，這應該是因為 knowledge_archive_interface 類沒有被正確地引入到程序中所導致的。您需要確保在您的程序中已經導入了 knowledge_archive_interface 類，方法是使用 import 關鍵字進行導入。例如，在最頂層進行導入：from example_module import knowledge_archive_interface。根據您提供的程式碼，可能需要導入其他的模塊，具體取決於您的程式碼還有哪些其他的部分。確保所有需要導入的模塊都在程序的上下文中進行了相應的導入。
![image](https://github.com/binary-husky/gpt_academic/assets/89382498/f014a5ad-a0c0-46f3-9649-061f11bd1dd6)
然後我出現另一個報錯ModuleNotFoundError: No module named 'pypinyin'
只需要pip就可以了

**Comment by YongjiangXu** [comment]
> 已解決，我問了gpt，這是它的回答︰根據您提供的錯誤信息，這應該是因為 knowledge_archive_interface 類沒有被正確地引入到程序中所導致的。您需要確保在您的程序中已經導入了 knowledge_archive_interface 類，方法是使用 import 關鍵字進行導入。例如，在最頂層進行導入：from example_module import knowledge_archive_interface。根據您提供的程式碼，可能需要導入其他的模塊，具體取決於您的程式碼還有哪些其他的部分。確保所有需要導入的模塊都在程序的上下文中進行了相應的導入。 ![image](https://user-images.githubusercontent.com/89382498/244424015-f014a5ad-a0c0-46f3-9649-061f11bd1dd6.png) 然後我出現另一個報錯ModuleNotFoundError: No module named 'pypinyin' 只需要pip就可以了

@Esmety 谢谢，这个可以正常工作，但是我又出现了另一个报错：
Traceback (most recent call last):
  File ".\toolbox.py", line 99, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File ".\crazy_functions\Langchain知识库.py", line 97, in 读取知识库作答
    resp, prompt = kai.answer_with_archive_by_id(txt, kai_id)
  File ".\crazy_functions\crazy_utils.py", line 673, in answer_with_archive_by_id
    self.qa_handle, self.kai_path = construct_vector_store(
  File "C:\ProgramData\Anaconda3\envs\academic\lib\site-packages\zh_langchain\zh_langchain.py", line 23, in construct_vector_store
    vs_path, loaded_files = local_doc_qa.init_knowledge_vector_store(filelist, vs_path, sentence_size, text2vec)
  File "C:\ProgramData\Anaconda3\envs\academic\lib\site-packages\zh_langchain\chains\local_doc_qa.py", line 214, in init_knowledge_vector_store
    self.vector_store = FAISS.load_local(vs_path, text2vec)
  File "C:\ProgramData\Anaconda3\envs\academic\lib\site-packages\langchain\vectorstores\faiss.py", line 466, in load_local
    index = faiss.read_index(
  File "C:\ProgramData\Anaconda3\envs\academic\lib\site-packages\faiss\swigfaiss.py", line 9795, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open C:\ProgramData\Anaconda3\envs\academic\lib\site-packages\zh_langchain\vector_store\default\index.faiss for reading: No such file or directory
貌似是这个库没正常安装好...

**Comment by nyavana** [comment]
3.50还是有类似的问题，报错ModuleNotFoundError: No module named 'langchain'

<img width="614" alt="Snipaste_2023-09-10_18-05-21" src="https://github.com/binary-husky/gpt_academic/assets/33804090/b85a5c1c-0b0d-4eda-a314-1db1d4b8e9a9">

我是在linux上跑的docker，网络通畅
尝试改官方pip源，手动安装pip install langchain都没用
每次调用知识库构建这个模块就提示依赖不足，即便所有的都装了

![image](https://github.com/binary-husky/gpt_academic/assets/33804090/d83aca71-c8e9-4080-a170-116df6385c64)

<img width="1280" alt="Snipaste_2023-09-10_18-05-34" src="https://github.com/binary-husky/gpt_academic/assets/33804090/e6335ff4-19a6-4c67-968e-16a66916217c">

**Comment by ZLNjust** [comment]
手动进入虚拟环境试试？
`cd ./OneKeyInstallerForWindowsAndMacOS/  #OneKeyInstallerForWindowsAndMacOS 所在目录
 
conda activate ./OneKeyInstallerForWindowsAndMacOS/installer_files/env  #激活配置的虚拟环境

python pip_setup.py   `

**Comment by vic233333** [comment]
> 手动进入虚拟环境试试？ `cd ./OneKeyInstallerForWindowsAndMacOS/ #OneKeyInstallerForWindowsAndMacOS 所在目录
> 
> conda activate ./OneKeyInstallerForWindowsAndMacOS/installer_files/env #激活配置的虚拟环境
> 
> python pip_setup.py `

用一键脚本进环境就会出这个问题，如果手动切环境里面就不会。

**Comment by hchenphd** [comment]
安装zh_langchain的时候会依赖pybind11，在一些平台上（例如我的Mac M2）,pybing11会有bug,  pip 更新一下pybind11即可
