### ISSUE TITLE
[Bug]: Model gpt-4 does not exist. 模型不存在, 或者您没有获得体验资格.

### ISSUE THREAD

**Issue by huangtao-china** [binary-husky/gpt_academic#838]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

GTP3.5正常使用，但是切换成gtp-4后；Model gpt-4 does not exist. 模型不存在, 或者您没有获得体验资格.

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/33545803/f56d7420-716f-4b50-9f55-a1ce354c3752)

**Comment by Coser-pianist** [comment]
一样的问题，等待解答

**Comment by PeterBilly** [comment]
gpt-4 仅限部分API有权限使用，请确定你是否有权限使用这个API

**Comment by hanhantie233** [comment]
> 一样的问题，等待解答

解决了吗？

**Comment by moshangchenkai** [comment]
怎么样解决的

**Comment by ZPWang01** [comment]
请问问题解决了吗？

**Comment by zhengbangyu** [comment]
要消费超过1美元才能使用gpt4
