### ISSUE TITLE
[Feature]: gradio的share功能如何开启

### ISSUE THREAD

**Issue by chewgunboy** [binary-husky/gpt_academic#839]
### Class | 类型

程序主体

### Feature Request | 功能请求

在2.7版本中可以使用的gradio生成一个分享链接的功能消失
只会生成locol链接，但是目前有共享需要

cmd提示设置launch（）share=True不知道应该如何处理

**Comment by shijunbao** [comment]
我这里默认情况下局域网可访问，不需要开share

**Comment by ai1390** [comment]
您好，请问这个问题解决了吗

**Comment by zesttec** [comment]
同样想知道
