### ISSUE TITLE
[Bug]: 使用API2D中怎么设置API_URL?在config_private.py的哪个位置？

### ISSUE THREAD

**Issue by xiangwei6963** [binary-husky/gpt_academic#854]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在“”# 重新URL重新定向，实现更换API_URL的作用（常规情况下，不要修改!!）
# （高危设置！通过修改此设置，您将把您的API-KEY和对话隐私完全暴露给您设定的中间人！）
# 格式 {"https://api.openai.com/v1/chat/completions": "在这里填写重定向的api.openai.com的URL"} 
# 例如 API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://ai.open.com/api/conversation"}
API_URL_REDIRECT = {}“”“
在这个{}里添加"https://openai.api2d.net"，吗？加上也不管用呢

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/58254194/51aa4bf5-4856-4798-827b-7cc069cd2e4d)
![image](https://github.com/binary-husky/gpt_academic/assets/58254194/45596988-6bcf-4f6f-881a-8c79b3ca2406)

**Comment by binary-husky** [comment]
下拉菜单里直接就有

**Comment by blpcx** [comment]
# 重新URL重新定向，实现更换API_URL的作用（常规情况下，不要修改!!）
# （高危设置！通过修改此设置，您将把您的API-KEY和对话隐私完全暴露给您设定的中间人！）
# 格式 {"https://api.openai.com/v1/chat/completions": "在这里填写重定向的api.openai.com的URL"} 
# 例如 API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions": "https://ai.open.com/api/conversation"}
API_URL_REDIRECT = {"https://oa.api2d.net/v1/chat/completions":"https://oa.api2d.net/v1/chat/completions"}

**Comment by xiangwei6963** [comment]
> 下拉菜单哪个位置呢，就是找不到

**Comment by xiangwei6963** [comment]
> 下拉菜单里直接就有

网页版也不行，
![image](https://github.com/binary-husky/gpt_academic/assets/58254194/b63637a7-5532-486b-aedd-6ae726a6e0c2)

**Comment by Lanthanum1** [comment]
相同的问题，设置重定向后仍然提示“您提供的api-key不满足要求，不包含任何可用于api2d-gpt-4的api-key。您可能选择了错误的模型或请求源。”

**Comment by blpcx** [comment]
默认的LLM和重定向API要一致，我试过LLM_MODEL = "gpt-3.5-turbo"，就会报错，应该是LLM_MODEL = "api2d-gpt-3.5-turbo"才可以

config.py 
	LLM_MODEL = "api2d-gpt-3.5-turbo"
	API_URL_REDIRECT = {"https://oa.api2d.net/v1/chat/completions":"https://oa.api2d.net/v1/chat/completions"}

**Comment by xiangwei6963** [comment]
是的要更改默认的LLM，谢谢
