### ISSUE TITLE
[Bug]: 构建知识库报错local variable 'knowledge_archive_interface' referenced before assignment

### ISSUE THREAD

**Issue by QihaoHuang5757** [binary-husky/gpt_academic#855]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

报错全局变量 'knowledge_archive_interface' 被局部修改

### Screen Shot | 有帮助的截图

<img width="1031" alt="截屏2023-06-08 23 32 36" src="https://github.com/binary-husky/gpt_academic/assets/118978920/7c01bcee-234e-4e70-bb1e-5dcc121efe2e">

**Comment by binary-husky** [comment]
功能还不稳定 正在解决 谢谢反馈 
#835

**Comment by binary-husky** [comment]
修复一些问题https://github.com/binary-husky/gpt_academic/commit/6d849eeb121b9f88821d7e46cad95c32bb9a12a9
