### ISSUE TITLE
[Bug]: json报错

### ISSUE THREAD

**Issue by zhaol0106** [binary-husky/gpt_academic#856]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

 gpt-3.5-turbo : 3 : 1 ..........
Traceback (most recent call last):
  File "E:\迅雷下载\gpt_academic-master\gpt_academic-master\request_llm\bridge_chatgpt.py", line 189, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
  File "D:\annconda\envs\PyTorch\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "D:\annconda\envs\PyTorch\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\annconda\envs\PyTorch\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/46555379/b17300fa-55b9-4c45-a0bc-74ae106d70dc)
"error": {        "message": "",        "type": "invalid_request_error",        "param": null,        "code": "account_deactivated"    }}

**Comment by wll-wll** [comment]
我也是这个报错。chatbox用这个api没有问题，官网上用这个账号也能正常回复，但是用这个学术gpt会有报错

**Comment by zhaol0106** [comment]
好像是密钥过期了，不知道是不是

**Comment by Sandy24159** [comment]
换了个号成功了，但是号余额不足，报错不一样了。json倒是不报错了。建议换个号试一下。

**Comment by zangqiourun** [comment]
换个号？key吗

**Comment by zhaol0106** [comment]
是的，不过号里得有钱，要充值

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 上午10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/gpt_academic] [Bug]: json报错 (Issue #856)





 
换个号？key吗

**Comment by zangqiourun** [comment]
我这号里有钱啊  别的地方都能用 不知道为啥这里用不了

**Comment by zhaol0106** [comment]
那就不清楚了，你可以把报错原因发出来看看






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 上午10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [binary-husky/gpt_academic] [Bug]: json报错 (Issue #856)





 
我这号里有钱啊  别的地方都能用 不知道为啥这里用不了

**Comment by zangqiourun** [comment]
发了最新的issuse 和你的报错一样



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月5日(周三) 上午10:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [binary-husky/gpt_academic] [Bug]: json报错 (Issue #856)




 那就不清楚了，你可以把报错原因发出来看看 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "binary-husky/gpt_academic"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年7月5日(星期三) 上午10:14 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [binary-husky/gpt_academic] [Bug]: json报错 (Issue #856) 
 
 
 
 
 
   
 我这号里有钱啊  别的地方都能用 不知道为啥这里用不了

**Comment by binary-husky** [comment]
account_deactivated 就是账号失活了嘛

**Comment by wll-wll** [comment]
我重新下载工程文件，然后输入原来的api，问题就解决了
