### ISSUE TITLE
[Bug]: newbing代码窗口重复回复

### ISSUE THREAD

**Issue by zhouyu98** [binary-husky/gpt_academic#857]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

用newbing的时候，ai的回复每新增一个词都要重复一次完整的回复，可能看截图更清楚一些

### Screen Shot | 有帮助的截图

<img width="765" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/114215812/f7b2f978-317e-416c-b254-7820c6fc8704">

**Comment by binary-husky** [comment]
就只是一个print语句，我回头给它删了吧
