### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by poeallan** [binary-husky/gpt_academic#858]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

切换为stack-claude后运行报错：aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

### Screen Shot | 有帮助的截图

<img width="546" alt="1686304085451" src="https://github.com/binary-husky/gpt_academic/assets/61599644/ed610543-0139-4c2c-b1bb-1a49fa511b97">

**Comment by binary-husky** [comment]
已知sock5代理在某些条件下与aiohttp有冲突
