### ISSUE TITLE
[Bug]: Latex翻译功能出错

### ISSUE THREAD

**Issue by funtasy2333** [binary-husky/gpt_academic#863]
### Installation Method | 安装方法与平台

Pip Install (I ignored requirements.txt)

### Version | 版本

Others | 非最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

Traceback (most recent call last):
  File ".\toolbox.py", line 99, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File ".\crazy_functions\Latex输出PDF结果.py", line 258, in Latex翻译中文并重新编译PDF
    yield from Latex精细分解与转化(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt, mode='translate_zh', switch_prompt=switch_prompt)
  File ".\crazy_functions\latex_utils.py", line 519, in Latex精细分解与转化
    final_tex = lps.merge_result(pfg.file_result, mode, msg)
  File ".\crazy_functions\latex_utils.py", line 368, in merge_result
    position = match.end()
AttributeError: 'NoneType' object has no attribute 'end'

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/133843382/dcde3385-7a87-418c-960f-ed386c8be853)

**Comment by zxp771** [comment]
同问

**Comment by binary-husky** [comment]
给出arxiv ID吧

极个别的论文作者上传的是个假latex项目（实际上是个PDF，套个latex的皮，所以无法翻译）

@zxp771 @funtasy2333

**Comment by OverKit** [comment]
有一些论文里用的不是`\begin{abstract}`的环境，而是`\abstract`命令，比如 [Springer Nature LaTeX Template
](https://www.overleaf.com/latex/templates/springer-nature-latex-template/myxmhdsbzkyd)

**Comment by binary-husky** [comment]
> 有一些论文里用的不是`\begin{abstract}`的环境，而是`\abstract`命令，比如 [Springer Nature LaTeX Template ](https://www.overleaf.com/latex/templates/springer-nature-latex-template/myxmhdsbzkyd)

原来是这样，多谢~

**Comment by funtasy2333** [comment]
> 给出arxiv ID吧
> https://arxiv.org/abs/2305.04518

**Comment by funtasy2333** [comment]
> 给出arxiv ID吧
> 
> 极个别的论文作者上传的是个假latex项目（实际上是个PDF，套个latex的皮，所以无法翻译）
> 
> @zxp771 @funtasy2333
https://arxiv.org/abs/2305.04518

**Comment by zxp771** [comment]
多谢回答

**Comment by zxp771** [comment]
@binary-husky @OverKit 多谢二位的解答
