### ISSUE TITLE
[Bug]: 火狐浏览器在非https环境下的代码复制键失效的问题

### ISSUE THREAD

**Issue by DrZhang1208** [binary-husky/gpt_academic#865]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

火狐浏览器打开的学术优化点击复制按钮无法复制

### Screen Shot | 有帮助的截图

![图片](https://github.com/binary-husky/gpt_academic/assets/97793620/22176910-e346-4253-9e80-7726f1338d71)

**Comment by DrZhang1208** [comment]
换edge没有这个问题，可以正常复制粘贴，就是等待全部输出结束后点的复制按钮

**Comment by DrZhang1208** [comment]
http

**Comment by DrZhang1208** [comment]
我是在服务器上部署的学术优化，访问后无法复制。我刚才试了一下本地运行，就可以正常复制了，应该是我哪里没有设置好

**Comment by binary-husky** [comment]
> 换edge没有这个问题，可以正常复制粘贴，就是等待全部输出结束后点的复制按钮

可能是火狐浏览器的http安全设置的问题，chrome和edge都是没问题的
