### ISSUE TITLE
[Feature]: 请求适配 OpenAI 最新发布的 gpt-3.5-turbo-16k 大上下文模型

### ISSUE THREAD

**Issue by BylethC** [binary-husky/gpt_academic#869]
### Class | 类型

大语言模型

### Feature Request | 功能请求

OpenAI刚刚发布了4倍上下文空间的3.5模型，对于使用体验的提升应该是显著的——尤其对于阅读PDF、解析整个代码项目等需要一次性喂入大量上下文的函数来说，希望能够增加该模型的调用选项！谢谢！

官网介绍：Same capabilities as the standard gpt-3.5-turbo model but with 4 times the context. (16,384 tokens maximum)

参考网址：

1. https://platform.openai.com/docs/models/gpt-3-5
2. https://zhuanlan.zhihu.com/p/636903639

**Comment by binary-husky** [comment]
@BylethC 已加入


刚push一个小commit

![)J4VU09XY21RB4JFKB`V1QP](https://github.com/binary-husky/gpt_academic/assets/96192199/ec5ebb39-da9e-48b4-aafd-79f85828552a)

在这里（或者config.py）修改，以后是否改成默认模型再观望几天

**Comment by binary-husky** [comment]
> > @BylethC 已加入
> > 刚push一个小commit
> > ![)J4VU09XY21RB4JFKB`V1QP](https://user-images.githubusercontent.com/96192199/245654898-ec5ebb39-da9e-48b4-aafd-79f85828552a.png)
> > 在这里（或者config.py）修改，以后是否改成默认模型再观望几天
> 
> @binary-husky 请问需要把Local LLM MaxLength修改到16384吗？

不需要

**Comment by muyi151** [comment]
请问为什么我从3.4版本更新到3.41版本，还是没能在更换LLM源这里看到最新的16k的模型，是需要重新安装还是需要如何设置？

**Comment by jifu23** [comment]
> 请问为什么我从3.4版本更新到3.41版本，还是没能在更换LLM源这里看到最新的16k的模型，是需要重新安装还是需要如何设置？

@muyi151 如果你使用了config_private，应该是该文件中的内容没有同步更改到最新

**Comment by yswlww** [comment]
使用了config_private，该文件中的内容没有同步更改到最新那怎搞?

**Comment by zenyanbo** [comment]
你好，请问有适配azure gpt-3.5-turbo-16k吗？
