### ISSUE TITLE
OPENAI api key对应的网站具体在哪里，在哪个文件里

### ISSUE THREAD

**Issue by MrGongqi** [binary-husky/gpt_academic#870]
### Class | 类型

None

### Feature Request | 功能请求

你好，我在使用反代API key，要更换openai api key和其所对应的网址，我知道api key在哪里修改，
![image](https://github.com/binary-husky/gpt_academic/assets/49467246/ac628e3c-3ab4-44ea-86a4-c1748d727dc7)
但是如上所示，这个api key默认对应的网址是openai api官网，请问我想将我的反代api 填入进去，该在哪里填写网址和key呢？
谢谢

**Comment by Maolaohei** [comment]
你往下翻API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"反代api地址"}

**Comment by MrGongqi** [comment]
好滴，，，知道啦，谢谢
