### ISSUE TITLE
[Bug]: 3.41似乎没有正确读取config_private.py里的API_KEY

### ISSUE THREAD

**Issue by lzhlo** [binary-husky/gpt_academic#873]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

## ChatGPT 学术优化 `3.41`
> `config.py`未做任何修改,不想修改`config.py`中的任何内容免得下次git pull需要进行覆盖
> 确认 `config.py`和`config_private.py`都已配置好`API_KEY`
> 使用的`config_private.py`进行配置后运行`docker build -t gpt-academic .`创建`docker`镜像的方法
错误提示 **[API_KEY] 正确的 API_KEY 是'sk'开头的51位密钥（OpenAI），或者 'fk'开头的41位密钥，请在config文件中修改API密钥之后再运行。**
> 没有读取出API_KEY的配置但是读取出了`WEB_PORT`自己配置的端口

### Screen Shot | 有帮助的截图

不支持上传图片

**Comment by fancl117** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/135203044/426a96da-ba77-4ff6-ac95-ae0e1803b8e5)
淘宝网上的key，亲身验证，可以用的。
