### ISSUE TITLE
[Feature]: 读论文，提出若干问题。

### ISSUE THREAD

**Issue by hongyi-zhao** [binary-husky/gpt_academic#875]
### Class | 类型

函数插件

### Feature Request | 功能请求

我有一篇论文手稿，能否让gpt_academic读一遍，然后针对该文内容提出10个相关问题，并作出对应回答？

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/0e66cd2b-561b-4b44-b8fc-08afa1c2819c)
这个？

**Comment by hongyi-zhao** [comment]
我看看。

另外，我注意到如下项目：

https://github.com/bhaskatripathi/pdfGPT

不知道和上面的问题是否有关？

**Comment by adrianzzk** [comment]
api额度查询https://platform.openai.com/account/api-keys
这个不是免费的功能，跟能不能用chatgpt没什么太大关系

**Comment by Esmety** [comment]
api 免費帳戶只有5美元額度，從注冊月起計只能用三個月

**Comment by hongyi-zhao** [comment]
是下面这个对应的含义吗？

![image](https://github.com/binary-husky/gpt_academic/assets/11155854/eaa9edc5-a2af-4f0f-9b07-63314a81489a)
