### ISSUE TITLE
[Feature]: 加入OpenAI最新的函数调用功能

### ISSUE THREAD

**Issue by HChaZZY** [binary-husky/gpt_academic#878]
### Class | 类型

大语言模型

### Feature Request | 功能请求

OpenAI 为他们最新的`gpt-3.5-turbo-0613` 和 `gpt-4-0613` 加入了可以自主选择自定义函数的功能，参见 [OpenAI Documentation](https://platform.openai.com/docs/guides/gpt/function-calling)。
这将允许GPT自行选择执行当前可用的自定义函数。
建议加入这项功能。

**Comment by PeterBilly** [comment]
我写了一个小的Demo，能够调用Wolfram Alpha API #851 :
![image](https://github.com/binary-husky/gpt_academic/assets/10991308/f4d3a994-ed78-4a90-a024-203557e7e835)
