### ISSUE TITLE
代理配置正常，一提交就error

### ISSUE THREAD

**Issue by sdumyh** [binary-husky/gpt_academic#88]
![屏幕截图 2023-03-29 154805](https://user-images.githubusercontent.com/87344980/228463960-e1bcff6e-0e3d-439c-b8de-e9743ee638a3.png)
<img width="320" alt="image" src="https://user-images.githubusercontent.com/87344980/228463904-f5aa6ab2-4c50-40ca-88c9-938203615609.png">

**Comment by xiaoliwe** [comment]
一样的问题哦.

**Comment by zzmlwt** [comment]
怎么配的代理呢?

**Comment by xiaoliwe** [comment]
> 能贴下终端的tracetrack吗？

![Screenshot_2023-03-29-17-14-41-573_com.microsoft.emmx-edit.jpg](https://user-images.githubusercontent.com/9930176/228487363-ab96edbb-3c6d-4c56-89fe-9998e477da38.jpg)

目前我这边的提示是这个，程序部署在海外服务器，不存在代理问题

**Comment by binary-husky** [comment]
没有有用的信息，需要看terminal的报错

**Comment by binary-husky** [comment]
#12 目前在huggingface上测试是没问题

**Comment by xiaoliwe** [comment]
@binary-husky log 是放在哪个路径下？

**Comment by sdumyh** [comment]
> #12 目前在huggingface上测试是没问题
我的key也在huggingface上测试没问题，就是在本地一直error
<img width="728" alt="image" src="https://user-images.githubusercontent.com/87344980/228513620-131b0163-4a53-4dc6-ab1c-3d2f63b27768.png">

**Comment by xiaoliwe** [comment]
为何套了一个 *.gradio.live 的网址在里面？

**Comment by jacyhen** [comment]
我是提交后出现：
Json解析不合常规 “error”: { “message”: “You exceeded your current quota, please check your plan and billing details.”, “type”: “insufficient_quota”, “param”: null, “code”: null }}

**Comment by FredYuuu** [comment]
> 能贴下终端的tracetrack吗？

我也有同样的问题，本地运行没问题，但是把程序部署在海外云服务器上使用就会报错 connection error out.

但是同时 terminal 无任何异常显示，如下：

`网络代理状态：未配置。无代理状态下很可能无法访问。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
代理配置 无, 代理所在地：未知，IP查询频率受限
URL http://localhost:1067
Running on local URL:  http://0.0.0.0:1067

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app

`

**Comment by binary-husky** [comment]
@FredYuuu  如果terminal无任何异常显示，那似乎只是gradio的内部bug了。
请尝试升级gradio版本试试。由于没有任何报错，我暂时无法理解这个问题。

**Comment by colin4k** [comment]
我的也是这样，最后发现只要不设置密码就ok，设置了密码就会这样。

**Comment by hupozZZ** [comment]
> ![屏幕截图 2023-03-29 154805](https://user-images.githubusercontent.com/87344980/228463960-e1bcff6e-0e3d-439c-b8de-e9743ee638a3.png) <img alt="image" width="320" src="https://user-images.githubusercontent.com/87344980/228463904-f5aa6ab2-4c50-40ca-88c9-938203615609.png">

请问你这个代理怎么设置的,我用的vpn,然后开海外代理也是连接超时

**Comment by YSAA1** [comment]
> 

你好，我账号密码都没有设置，终端也没用任何报错但是也是这个问题，你是不是只设置了账号没设置密码呢
