### ISSUE TITLE
[Feature]: reverse-proxy based api access.

### ISSUE THREAD

**Issue by hongyi-zhao** [binary-husky/gpt_academic#880]
### Class | 类型

None

### Feature Request | 功能请求

是否可以使用下面的反向代理免费访问 OpenAI API?

https://github.com/transitive-bullshit/chatgpt-api#reverse-proxy

![image](https://github.com/binary-husky/gpt_academic/assets/11155854/c2ec1499-b98e-408e-b213-981931c4126a)

See https://github.com/PawanOsman/ChatGPT/issues/14 for related discussion.

**Comment by binary-husky** [comment]
可以 读config.py

**Comment by hongyi-zhao** [comment]
reverse-proxy 并不是一般的proxy server，没有明白你是什么意思。

**Comment by hongyi-zhao** [comment]
我的问题是：这种方法是否可以绕过API过期（失效）的问题？
