### ISSUE TITLE
[Bug]: Latex插件转化pdf失败

### ISSUE THREAD

**Issue by LUORANCHENG** [binary-husky/gpt_academic#885]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

Latex插件转化pdf失败

### Screen Shot | 有帮助的截图

![2023-06-18_22-02](https://github.com/binary-husky/gpt_academic/assets/80999506/ecc4a4d5-0d0c-4d21-82d7-8ac32ff67683)

这是最后输出的结果
[2023-06-18-13-56-57-result.zip](https://github.com/binary-husky/gpt_academic/files/11781721/2023-06-18-13-56-57-result.zip)

**Comment by Swinden** [comment]
你可以手动编译一下，一点点排除问题

**Comment by Swinden** [comment]
> ### Installation Method | 安装方法与平台
> Docker（Linux）
> 
> ### Version | 版本
> Latest | 最新版
> 
> ### OS | 操作系统
> Docker
> 
> ### Describe the bug | 简述
> Latex插件转化pdf失败
> 
> ### Screen Shot | 有帮助的截图
> ![2023-06-18_22-02](https://user-images.githubusercontent.com/80999506/246669959-ecc4a4d5-0d0c-4d21-82d7-8ac32ff67683.png)
> 
> 这是最后输出的结果 [2023-06-18-13-56-57-result.zip](https://github.com/binary-husky/gpt_academic/files/11781721/2023-06-18-13-56-57-result.zip)
> 
> ### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）
> _No response_
你可以手动编译一下，一点点排除问题

**Comment by Swinden** [comment]
你可以手动编译一下，一点点排除问题

> ### Installation Method | 安装方法与平台
> Docker（Linux）
> 
> ### Version | 版本
> Latest | 最新版
> 
> ### OS | 操作系统
> Docker
> 
> ### Describe the bug | 简述
> Latex插件转化pdf失败
> 
> ### Screen Shot | 有帮助的截图
> ![2023-06-18_22-02](https://user-images.githubusercontent.com/80999506/246669959-ecc4a4d5-0d0c-4d21-82d7-8ac32ff67683.png)
> 
> 这是最后输出的结果 [2023-06-18-13-56-57-result.zip](https://github.com/binary-husky/gpt_academic/files/11781721/2023-06-18-13-56-57-result.zip)
> 
> ### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）
> _No response_





你可以手动编译一下，一点点排除问题

**Comment by binary-husky** [comment]
@LUORANCHENG

**Comment by LUORANCHENG** [comment]
好的，谢谢大佬
