### ISSUE TITLE
[Bug]: 需要更新时输入Y回车后，直接显示更新失败 

### ISSUE THREAD

**Issue by Schodinger** [binary-husky/gpt_academic#886]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

输入Y后显示更新失败

### Screen Shot | 有帮助的截图

![QQ截图20230619151005](https://github.com/binary-husky/gpt_academic/assets/134361663/38ae0d08-5ace-4b92-a807-cc34f8932c66)

**Comment by Esmety** [comment]
重裝就是了

**Comment by binary-husky** [comment]
可能是cn特有的网络不畅，手动下载代码覆盖即可

**Comment by binary-husky** [comment]
效果是等价的
