### ISSUE TITLE
[Bug]: localhost已拒绝连接

### ISSUE THREAD

**Issue by zgq2020** [binary-husky/gpt_academic#888]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

新安装chatgpt academic，按照步骤装好，一直出现localhost 已拒绝连接。尝试过打开FTP服务器、修改host等还是不行

### Screen Shot | 有帮助的截图

![L53IBQVCN$EP %VLK3ZVS65](https://github.com/binary-husky/gpt_academic/assets/61308133/c6f74854-cd52-4cf0-a6d2-f73c1d951545)
![X($0JN4S88UF3RH%TIN3OP1](https://github.com/binary-husky/gpt_academic/assets/61308133/68fe94da-71c8-4f4a-a98e-5c9aa73965b9)

**Comment by inkydragon** [comment]
Chrome 浏览器的安全策略：“如果你的网站需要向 localhost 发出请求，那么你需要将你的网站升级到 HTTPS。”

地址改为 http://127.0.0.1 就行了

想要治本可以参考
- https://stackoverflow.com/questions/25277457/google-chrome-redirecting-localhost-to-https
- [Chrome 安全策略更新-网站访问本地localhost的限制 - 掘金](https://juejin.cn/post/7025252808978858014)
