### ISSUE TITLE
[Feature]: pdf翻译

### ISSUE THREAD

**Issue by shentry** [binary-husky/gpt_academic#899]
### Class | 类型

函数插件

### Feature Request | 功能请求

能够使pdf翻译中的图片以及公式不消失，不改变pdf的公式么？

**Comment by binary-husky** [comment]
支持借助GROBID实现PDF高精度翻译
https://github.com/binary-husky/gpt_academic/commit/ec76d3dcc4c5b8dc514e25a6305f9ff0828623dd
