### ISSUE TITLE
[Feature]: support new THUDM/chatglm2-6b？

### ISSUE THREAD

**Issue by fz68** [binary-husky/gpt_academic#902]
### Class | 类型

None

### Feature Request | 功能请求

[chatglm2-6b](https://huggingface.co/THUDM/chatglm2-6b)

[chatglm2-6b-int4](https://huggingface.co/THUDM/chatglm2-6b-int4)

**Comment by zdevc** [comment]
Replace all instances of 'THUDM/chatglm-6b' in the run() function of request_llm/bridge_chatglm.py with 'THUDM/chatglm2-6b'.
`                if self.chatglm_model is None:
                    self.chatglm_tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)
                    device, = get_conf('LOCAL_MODEL_DEVICE')
                    if device=='cpu':
                        self.chatglm_model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).float()
                    else:
                        self.chatglm_model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).half().cuda()
                    self.chatglm_model = self.chatglm_model.eval()
                    break
                else:
                    break`

**Comment by binary-husky** [comment]
working on it~

**Comment by binary-husky** [comment]
已经这么弄了，我觉得chatglm1没必要保留了，直接与chatglm2对齐了

> Replace all instances of 'THUDM/chatglm-6b' in the run() function of request_llm/bridge_chatglm.py with 'THUDM/chatglm2-6b'.
