### ISSUE TITLE
[Bug]: Latex插件转化pdf失败

### ISSUE THREAD

**Issue by zzcgithub** [binary-husky/gpt_academic#912]
### Installation Method | 安装方法与平台

Huggingface

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

[2023-06-28-06-19-59-2023-06-28-06-19-57-result.zip](https://github.com/binary-husky/gpt_academic/files/11892023/2023-06-28-06-19-59-2023-06-28-06-19-57-result.zip)

### Screen Shot | 有帮助的截图

<img width="799" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/13117136/b61b66e8-30cc-4eac-ae63-a77b3f29f44b">

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/47a103b5-9da9-4234-8efa-9a98d7717317)

这里出现了个罕见的latex命令，导致出错了。怎么稳定的解决这类问题，需要想想
