### ISSUE TITLE
[Bug]:  ArXiv Latex一键翻译（输入arXiv ID）翻译中存在大量未翻译中文，请排查

### ISSUE THREAD

**Issue by zzcgithub** [binary-husky/gpt_academic#913]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

文章地址：https://arxiv.org/abs/2304.02643

在缓存中存在翻译结果，第3页存在大量未翻译文字，见截图。

### Screen Shot | 有帮助的截图

<img width="744" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/13117136/2ff408bc-e154-43b7-b981-4d1638a8634b">

**Comment by binary-husky** [comment]
遇到少数latex命令嵌套时，很可能会导致这种问题。为了整个文章能够顺利编译，目前采用的手段是牺牲局部

**Comment by binary-husky** [comment]
重试有时候可以解决
