### ISSUE TITLE
[Bug]: 在pdf文件翻译好后无法下载整合文件，右侧上传框显示“error”

### ISSUE THREAD

**Issue by Qilely** [binary-husky/gpt_academic#915]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

首先感谢大佬们的工作，但我在使用时出现了下面这个问题。

我的是搭建在一个服务器上的，使用docker搭建，远程访问。在使用pdf翻译功能后无法获取到整理好的文件，右侧文件上传区显示红色error。但去服务器上是可以在gpt日志文件夹里面找到html的整合文件的。且尝试过多个pdf均有此问题。

### Screen Shot | 有帮助的截图

![微信图片_20230629141024](https://github.com/binary-husky/gpt_academic/assets/130070063/5770440b-4ec1-4da9-814e-5072244ad98b)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpt/toolbox.py", line 505, in on_report_generated
    chatbot.append(['报告如何远程获取？', f'报告已经添加到右侧“文件上传区”（可能处于折叠状态），请查收。{file_links}'])
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'

**Comment by binary-husky** [comment]
您好，我刚修复了一个文件上传下载的小bug，但是感觉和这个问题关系不大，但我这里无法复现，请问运行docker的命令用的是哪个呢？

**Comment by Qilely** [comment]
> 您好，我刚修复了一个文件上传下载的小bug，但是感觉和这个问题关系不大，但我这里无法复现，请问运行docker的命令用的是哪个呢？

大佬您好，启用docker我用的是docker run --rm -itd --net=host gpt-academic 或者docker run --rm -it --net=host gpt-academic。因为我想远程端后台运行就用的itd。但这两个命令都不行……

**Comment by Qilely** [comment]
> 您好，我刚修复了一个文件上传下载的小bug，但是感觉和这个问题关系不大，但我这里无法复现，请问运行docker的命令用的是哪个呢？

我更新了一下然后重新建立镜像开启容器，还是同样的报错……

**Comment by Qilely** [comment]
您好，我刚才又更新了一下，发现重新建立镜像后已经可以使用了，感谢大佬们的付出，非常感谢Orz

**Comment by binary-husky** [comment]
支持借助GROBID实现PDF高精度翻译
https://github.com/binary-husky/gpt_academic/commit/ec76d3dcc4c5b8dc514e25a6305f9ff0828623dd
