### ISSUE TITLE
[Bug]: 文件区上传文件不能被读取

### ISSUE THREAD

**Issue by bigaym** [binary-husky/gpt_academic#922]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

使用“解析项目源码”插件时，上传了MvFIF.zip文件，被解析为“private_upload/2023-07-01-11-02-00”，参数填的".m"，但是解析错误“找不到任何文件: private_upload/2023-07-01-11-02-00”

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/97392187/5678db65-cd3c-4fcf-aadc-b84e575bdea6)
![image](https://github.com/binary-husky/gpt_academic/assets/97392187/99af07f3-32a2-403f-9bc9-8831b01547f8)
![image](https://github.com/binary-husky/gpt_academic/assets/97392187/a33818d5-a6c1-4a00-be57-ecfc0ef38a9f)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Successfully extracted zip archive to private_upload/2023-07-01-11-02-00/MvFIF.zip.extract                             

 Traceback (most recent call last):                                                                                       

​	 File "D:\Anaconda3\envs\chatpaper\lib\site-packages\gradio\routes.py", line 422, in run_predict                          

​		 output = await app.get_blocks().process_api(                                                                          

​	File "D:\Anaconda3\envs\chatpaper\lib\site-packages\gradio\blocks.py", line 1326, in process_api                          

​		data = self.postprocess_data(fn_index, result["prediction"], state)                                                   

​	File "D:\Anaconda3\envs\chatpaper\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data                     

​		self.validate_outputs(fn_index, predictions)  # type: ignore                                                          

​	File "D:\Anaconda3\envs\chatpaper\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs                     

​		raise ValueError(                                                                                                   

​	ValueError: An event handler (on_report_generated) didn't receive enough output values (needed: 3, received: 2).        

Wanted outputs:                                                                                                            

​	[state, file, chatbot]                                                                                              

Received outputs:                                                                                                          

​	 [None, [['<div class="markdown-body">我上传了文件，请查收</div>', '<div class="markdown-body"><p>[Local Message] 收 到以下文件: </p>\n<p>private_upload\\2023-07-01-11-02-00  </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip    </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip.extract    </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip.extract\\dataset_preprocessed.mat   </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip.extract\\Example_v2.m   </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip.extract\\LICENSE    </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip.extract\\MvFIF_v7.m </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip.extract\\prefixed_double_filter.mat </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip.extract\\README.md  </p>\n<p>private_upload\\2023-07-01-11-02-00\\MvFIF.zip.extract\\Settings_FIF_v3.m</p>\n<p>调用路径参数已自动修正到: </p>\n<p>private_upload/2023-07-01-11-02-00</p>\n<p>现在您点击任意“红颜色”标识的函数插件时，以上文件将被作为输入参数</p></div>'], ['<div class="markdown-body">解析项目:&nbsp;private_upload/2023-07-01-11-02-00</div>', '<div class="markdown-body"><p>找不到任何文件: private_upload/2023-07-01-11-02-00</p></div>']]]    
[MvFIF.zip](https://github.com/binary-husky/gpt_academic/files/11924200/MvFIF.zip)

**Comment by binary-husky** [comment]
您好，这个bug已经修复了，更新代码即可。
另外您 需要用 *.m，星号代表任意的意思
