### ISSUE TITLE
[Feature]: 连续使用prompt越来越长，有考虑做总结功能吗

### ISSUE THREAD

**Issue by y1max** [binary-husky/gpt_academic#926]
### Class | 类型

None

### Feature Request | 功能请求

历史工程做的比较简单粗暴导致prompt越滚越多；有没有考虑做总结功能

**Comment by binary-husky** [comment]
可以试试gpt-3.5-16k

**Comment by binary-husky** [comment]
目前没有考虑过把总结工程做进底层，
稳定性和严谨性考虑，这里更倾向于把复杂的功能用插件的形式实现
