### ISSUE TITLE
[Bug]: OpenAI拒绝了请求是账号过期了吗？

### ISSUE THREAD

**Issue by jordanxlj** [binary-husky/gpt_academic#928]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

raise RuntimeError("OpenAI拒绝了请求：" + error_msg)
RuntimeError: OpenAI拒绝了请求：{    "error": {        "message": "This key is associated with a deactivated account. If you feel this is an error, contact us through our help center at help.openai.com.",        "type": "invalid_request_error",        "param": null,        "code": "account_deactivated"    }}

### Screen Shot | 有帮助的截图

<img width="1724" alt="image" src="https://github.com/binary-husky/gpt_academic/assets/4532524/dc7aff09-5d91-4d1a-85f3-0fff0898f8f8">

**Comment by binary-husky** [comment]
账号失效了
