### ISSUE TITLE
[Bug]: Linux下，批量总结word文档，报错No module named 'win32com'

### ISSUE THREAD

**Issue by zdevc** [binary-husky/gpt_academic#935]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

Linux环境下，批量总结word文档，报错ModuleNotFoundError: No module named 'win32com'

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/40593221/6f031a82-5726-4356-b069-ce23bc8b44ec)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

Traceback (most recent call last):
  File "./toolbox.py", line 100, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "./crazy_functions/总结word文档.py", line 127, in 总结word文档
    yield from 解析docx(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File "./crazy_functions/总结word文档.py", line 17, in 解析docx
    import win32com.client
ModuleNotFoundError: No module named 'win32com'

**Comment by binary-husky** [comment]
请先将.doc文档转换为.docx文档。

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/67d90518909cb0f623d71138e4fcc4921ab340f4
