### ISSUE TITLE
[Bug]: 提交输入后一直没有输出反应

### ISSUE THREAD

**Issue by AtalsZem** [binary-husky/gpt_academic#936]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

如图所示，代理配置正确，但是提交输入后一直没有输出，望解答，感谢！

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/86402580/b35c1c19-c992-45c8-a8e9-0c3948ec1b35)

**Comment by bittp** [comment]
出现同样的问题

**Comment by jiaka** [comment]
+1

**Comment by xiaohei366** [comment]
+1

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/654bba2c-2f7a-4d1b-827d-5d110f4e7b02)

**Comment by binary-husky** [comment]
@jiaka @xiaohei366 @AtalsZem @bittp pip install fastapi==0.93.0

**Comment by jiaka** [comment]
> @jiaka @xiaohei366 @AtalsZem @bittp pip install fastapi==0.93.0

我换了一个浏览器，还是不行

**Comment by xiaohei366** [comment]
> @jiaka @xiaohei366 @AtalsZem @bittp pip install fastapi==0.93.0

pip后可以了

**Comment by jiaka** [comment]
> @jiaka @xiaohei366 @AtalsZem @bittp pip install fastapi==0.93.0

安装这个可以了

**Comment by binary-husky** [comment]
修正一下，和fastapi没关系，是pydantic的锅
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/71e07629-e144-4535-85a9-9162859096a5)

**Comment by binary-husky** [comment]
https://github.com/tiangolo/fastapi/issues/9710

**Comment by jgxxjg** [comment]
更新后，这个问题顺利解决。
