### ISSUE TITLE
网络代理配置失败

### ISSUE THREAD

**Issue by mumubaibai** [binary-husky/gpt_academic#939]
[PROXY] 网络代理状态：未配置。无代理状态下很可能无法访问OpenAI家族的模型。建议：检查USE_PROXY选项是否修改。
 [API_KEY] 本项目现已支持OpenAI和API2D的api-key。也支持同时填写多个api-key，如API_KEY="openai-key1,openai-key2,api2d-key3"
 [API_KEY] 您既可以在config.py中修改api-key(s)，也可以在问题输入区输入临时的api-key(s)，然后回车键提交后即可生效。
 [API_KEY] 您的 API_KEY 是: sk-sGDUPdS79T6C*** API_KEY 导入成功

`
USE_PROXY = True
if USE_PROXY:
    proxies = {"http": "http://127.0.0.1:7880", "https": "http://127.0.0.1:7880", }
else:
    proxies = None`

不知道哪里出错了
![微信图片_20230708113205](https://github.com/binary-husky/gpt_academic/assets/101308856/f3e59e0c-a7e4-4e86-8530-a83606d03583)

**Comment by binary-husky** [comment]
#1
