### ISSUE TITLE
[Bug]: [Local Message] 远程返回错误

### ISSUE THREAD

**Issue by zangqiourun** [binary-husky/gpt_academic#946]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

[Local Message] 远程返回错误:

Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 174, in predict
    chunk = next(stream_response)
            ^^^^^^^^^^^^^^^^^^^^^
StopIteration

### Screen Shot | 有帮助的截图

![360截图20230713172730759](https://github.com/binary-husky/gpt_academic/assets/130052096/d0c1bcbb-e0dd-4a19-a948-8d4a9a56c614)

**Comment by binary-husky** [comment]
请使用将对话历史保存，然后发一下，方便我们复现

**Comment by zangqiourun** [comment]
> 请使用将对话历史保存，然后发一下，方便我们复现

没有做什么特别操作，就是头一天还正常在用，昨天就不行了，用的你推荐的反向代理，代码为：
API_URL_REDIRECT = {"https://api.openai.com/v1/chat/completions":"https://free.churchless.tech/v1/chat/completions"}
[chatGPT对话历史2023-07-14-22-54-23.zip](https://github.com/binary-husky/gpt_academic/files/12051743/chatGPT.2023-07-14-22-54-23.zip)

**Comment by binary-husky** [comment]
> > 请使用将对话历史保存，然后发一下，方便我们复现
> 
> 没有做什么特别操作，就是头一天还正常在用，昨天就不行了，用的你推荐的反向代理，代码为： API_URL_REDIRECT = {"[https://api.openai.com/v1/chat/completions":"https://free.churchless.tech/v1/chat/completions"}](https://api.openai.com/v1/chat/completions%22:%22https://free.churchless.tech/v1/chat/completions%22%7D) [chatGPT对话历史2023-07-14-22-54-23.zip](https://github.com/binary-husky/gpt_academic/files/12051743/chatGPT.2023-07-14-22-54-23.zip)

首先，我不推荐任何反向代理

其次，里面错误信息写的已经很清楚了
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/3fd24fb3-176d-4dec-9286-8f8332e58e0e)

**Comment by zangqiourun** [comment]
> > > 请使用将对话历史保存，然后发一下，方便我们复现
> > 
> > 
> > 没有做什么特别操作，就是头一天还正常在用，昨天就不行了，用的你推荐的反向代理，代码为： API_URL_REDIRECT = {"[https://api.openai.com/v1/chat/completions":"https://free.churchless.tech/v1/chat/completions"}](https://api.openai.com/v1/chat/completions%22:%22https://free.churchless.tech/v1/chat/completions%22%7D) [chatGPT对话历史2023-07-14-22-54-23.zip](https://github.com/binary-husky/gpt_academic/files/12051743/chatGPT.2023-07-14-22-54-23.zip)
> 
> 首先，我不推荐任何反向代理
> 
> 其次，里面错误信息写的已经很清楚了 ![image](https://user-images.githubusercontent.com/96192199/253724082-3fd24fb3-176d-4dec-9286-8f8332e58e0e.png)

我切换成cl--ash代理后还是不行，这种错误怎么解决啊？换api可以吗？

**Comment by zangqiourun** [comment]
> > > 请使用将对话历史保存，然后发一下，方便我们复现
> > 
> > 
> > 没有做什么特别操作，就是头一天还正常在用，昨天就不行了，用的你推荐的反向代理，代码为： API_URL_REDIRECT = {"[https://api.openai.com/v1/chat/completions":"https://free.churchless.tech/v1/chat/completions"}](https://api.openai.com/v1/chat/completions%22:%22https://free.churchless.tech/v1/chat/completions%22%7D) [chatGPT对话历史2023-07-14-22-54-23.zip](https://github.com/binary-husky/gpt_academic/files/12051743/chatGPT.2023-07-14-22-54-23.zip)
> 
> 首先，我不推荐任何反向代理
> 
> 其次，里面错误信息写的已经很清楚了 ![image](https://user-images.githubusercontent.com/96192199/253724082-3fd24fb3-176d-4dec-9286-8f8332e58e0e.png)

我的账号突然又好了 ，谢谢
