### ISSUE TITLE
[Bug]: json解析异常，api-key没问题

### ISSUE THREAD

**Issue by yjingh** [binary-husky/gpt_academic#947]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Please choose | 请选择

### OS | 操作系统

Please choose | 请选择

### Describe the bug | 简述

修改了config中的API_URL_REDIRECT
输入前几个问题，返回的回答比较简短，都没报错
输入最后一个问题，返回的回答较长，输出到一半，报错
Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 193, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\evo\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\evo\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\evo\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)

### Screen Shot | 有帮助的截图

![4i2Cyt0eK8](https://github.com/binary-husky/gpt_academic/assets/111102456/6485d9d5-e619-4bea-8bf6-da369e77415b)

**Comment by binary-husky** [comment]
请使用将对话历史保存，然后分享一下，方便我们复现

**Comment by yjingh** [comment]
> 请使用将对话历史保存，然后分享一下，方便我们复现

不需要特定的对话，只是输入一个会返回”较长回答“的问题，就会出现这种情况，比如输入”台风是怎样形成的“，然后就会开始输出”台风是一种...“输出到以下长度出现报错：JSON解析不合常规
![0k3DR0Z8Xq](https://github.com/binary-husky/gpt_academic/assets/111102456/376d85ab-9264-4747-afa5-e932fde9adb3)

**Comment by yjingh** [comment]
> 请使用将对话历史保存，然后分享一下，方便我们复现

不需要特定的对话，只是输入一个会返回”较长回答“的问题，就会出现这种情况，比如输入”台风是怎样形成的“，然后就会开始输出”台风是一种...“输出到以下长度出现报错：JSON解析不合常规
![0k3DR0Z8Xq](https://github.com/binary-husky/gpt_academic/assets/111102456/b0a12d1c-806b-4b47-98c7-1c57ed75effb)

然后返回的报错中的JSON为当前答案的后续内容
![Q4qYCOcRdb](https://github.com/binary-husky/gpt_academic/assets/111102456/fdc6d45f-21b4-4f66-a36e-bd8826b697c1)
![798b0506-4211-4f2f-8e13-6ea567afa271](https://github.com/binary-husky/gpt_academic/assets/111102456/39fd8ad2-be33-4eaa-8079-9f30490bea96)

**Comment by yjingh** [comment]
解决了，返回的内容中有内鬼，导致JSON解析错误，报意思报意思
