### ISSUE TITLE
[Bug]: Arxiv翻译/本地论文翻译对mac上latex的支持

### ISSUE THREAD

**Issue by grothen** [binary-husky/gpt_academic#948]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

mac上的latex配置中文比较麻烦，我是texlive，每次需要在tex中加入一段设置字体
`\setCJKfamilyfont{zhfs}   {STFangsong}      [AutoFakeBold={\FakeBoldSize}]
\setCJKfamilyfont{zhhei}  {Heiti SC Light}  [BoldFont={Heiti SC Medium}]
\setCJKfamilyfont{zhkai}  {Kaiti SC}        [BoldFont={Kaiti SC Bold}]
\setCJKfamilyfont{zhsong} {Songti SC Light} [BoldFont={Songti SC Bold}]
\setCJKmainfont[AutoFakeBold={\FakeBoldSize}]{STFangsong}`
有没有办法直接有个选项可以加入这几行？或者其他解决字体问题的办法？

### Screen Shot | 有帮助的截图

![CleanShot 2023-07-14 at 11 57 15](https://github.com/binary-husky/gpt_academic/assets/3252576/90c45901-ac33-4492-8c73-d4f8bd402e75)

**Comment by binary-husky** [comment]
对mac不太清除，

如果是ubuntu的话，一般[这样](https://github.com/binary-husky/gpt_academic/wiki/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8Latex%E7%9B%B8%E5%85%B3%E6%8F%92%E4%BB%B6%EF%BC%88arxiv%E6%96%87%E7%AB%A0%E7%BF%BB%E8%AF%91%EF%BC%89)解决：

```
想办法合法获取以下字体，并复制到Latex的字体目录/usr/local/texlive/2023/texmf-dist/fonts/truetype

MSYHBD.TTC  SIMLI.TTF  msyh.ttc simfang.ttf  simkai.ttf  SIMYOU.TTF  msyhbd.ttc  simhei.ttf   simsun.ttc

使用texhash命令刷新字体，使第四步生效
```

**Comment by binary-husky** [comment]
另外mac上建议使用docker部署，方法如下：

第一步：新建docker-compose.yml文件，找到本项目的docker-compose.yml，复制方案四，修改里面API_kEY等环境变量
第二步：docker-compose up

**Comment by grothen** [comment]
谢谢🙏
