### ISSUE TITLE
[Bug]: 请问如何解决ImportError错误

### ISSUE THREAD

**Issue by Jie-Li-dev** [binary-husky/gpt_academic#952]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

按照指示运行python main.py后出现了以下错误

ImportError: cannot import name 'AutoModel' from 'transformers' (C:\Users\LI\anaconda3\Lib\site-packages\transformers\__init__.py)

请问如何解决？

### Screen Shot | 有帮助的截图

(base) C:\gptacademic\chatgpt_academic>python main.py
 [PROXY] 网络代理状态：已配置。配置信息如下： {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
Neither PyTorch nor TensorFlow >= 2.0 have been found.Models won't be available and only tokenizers, configurationand file/data utilities can be used.
Traceback (most recent call last):
  File "C:\gptacademic\chatgpt_academic\main.py", line 221, in <module>
    main()
  File "C:\gptacademic\chatgpt_academic\main.py", line 6, in main
    from request_llm.bridge_all import predict
  File "C:\gptacademic\chatgpt_academic\request_llm\bridge_all.py", line 19, in <module>
    from .bridge_chatglm import predict_no_ui_long_connection as chatglm_noui
  File "C:\gptacademic\chatgpt_academic\request_llm\bridge_chatglm.py", line 2, in <module>
    from transformers import AutoModel, AutoTokenizer
ImportError: cannot import name 'AutoModel' from 'transformers' (C:\Users\LI\anaconda3\Lib\site-packages\transformers\__init__.py)

**Comment by binary-husky** [comment]
https://github.com/huggingface/transformers/issues/4172
