### ISSUE TITLE
[Bug]: 新版本更新后No module named 'theme.theme'问题

### ISSUE THREAD

**Issue by Wanbi1** [binary-husky/gpt_academic#954]
### Installation Method | 安装方法与平台

Pip Install (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

在pycharm中对代码升级到最新版后运行出现如下报错：
Traceback (most recent call last):
  File "D:\chatgpt_academic\main.py", line 236, in <module>
    main()
  File "D:\chatgpt_academic\main.py", line 17, in main
    from theme.theme import adjust_theme, advanced_css, theme_declaration
ModuleNotFoundError: No module named 'theme.theme'; 'theme' is not a package

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/110647344/1ef14d66-b9bd-4f45-babe-22afc0794dfd)

**Comment by edward1322** [comment]
升级到新版本后，同样遇到这个了这个问题，我把theme文件下的theme.py拷贝到主目录下，会出现这样的错误：“ImportError: cannot import name 'theme_declaration' from 'theme'”，打开theme.py发现并没有定义theme_declaration

**Comment by binary-husky** [comment]
请问是使用哪种方式升级的？

建议通过重新下载-覆盖源代码的方法更新

**Comment by binary-husky** [comment]
删除`theme.py`

**Comment by binary-husky** [comment]
代码更新：重命名theme文件件为themes，解决了旧文件残留theme.py引起的烂摊子

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/fe231f72b66f2d5a7d6e6d49418e9b5d3b52d285

**Comment by edward1322** [comment]
下载更新后的代码，已正常运行，谢谢！

**Comment by Wanbi1** [comment]
> [fe231f7](https://github.com/binary-husky/gpt_academic/commit/fe231f72b66f2d5a7d6e6d49418e9b5d3b52d285)

更新后的代码可以正常运行了，谢谢
