### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KamenRevice** [binary-husky/gpt_academic#958]
### Installation Method | 安装方法与平台

Anaconda (I used latest requirements.txt)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

我的clash一直是随机端口，每次启动都显示不同的端口号，请问我该如何在config.py文件种配置如下端口设置
前提是不固定我的clash代理端口
```
USE_PROXY = True 
if USE_PROXY:     
    proxies = {     
        #          [协议]://  [地址]  :[端口]      
        "http":  "socks5h://localhost:8563",  # 再例如  "http":  "http://127.0.0.1:7890",      
        "https": "socks5h://localhost:8563",  # 再例如  "https": "http://127.0.0.1:7890",     
    }

```

### Screen Shot | 有帮助的截图

![Snipaste_2023-07-17_15-38-32](https://github.com/binary-husky/gpt_academic/assets/36665957/a20b0b29-9bc8-403d-97b9-f8fd253f5323)

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

无

**Comment by robot-2233** [comment]
try to click that button
it would change it to fixed port
