### ISSUE TITLE
[Feature]: 对Texlive进行精准安装

### ISSUE THREAD

**Issue by stucash** [binary-husky/gpt_academic#960]
### Class | 类型

函数插件

### Feature Request | 功能请求

首先非常感谢各位大大制作了这么牛X的工具， 少熬不少夜啊。 

另外就是想请问一下， 目前看到在Linux系统下安装Texlive的话，没有对Texlive安装做出任何要求， 而在Texlive官网上看到，默认安装的话是7+GB。。。

这个。。。请问工具是确实需要整个7+GB的Texlive吗？

Texlive可以进行选择性的安装， 用`--scheme=small` 就会安装BasicTex这一个类组而已; `--no-doc-install`, `--no-src-install` 诚如字面意思, 也能节省不少空间. 

Texlive传送门: https://tug.org/texlive/quickinstall.html 

各位大大能找个时间看看吗?

**Comment by binary-husky** [comment]
谢谢支持，

我对latex的了解也只是半瓶水，是否需要7GB的texlive说实话我也不太清楚，除了论文原文所需要的依赖外，引入中文后，CTex依赖时必需的

您可以尝试一下 --scheme=small 安装，看看对比之下有什么区别。

**Comment by stucash** [comment]
谢谢大佬, 我以为这是团队作品, 原来是大佬一个人做的, 之前说得不准确, 实在是抱歉. 

关于Texlive的话, 我昨天已经装了这个8GB的版本(目前不带参数安装, 大小就是8GB)...

等有空了我来试试看几个不同的安装选项, 有结果了给你反馈反馈.
