### ISSUE TITLE
[Bug]: 输入无法正确渲染markdown

### ISSUE THREAD

**Issue by M1saka10010** [binary-husky/gpt_academic#961]
### Installation Method | 安装方法与平台

Docker-Compose（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

markdown的代码块无法实现，html内容会直接渲染出来。其他的代码也不能渲染出代码块。请问是否能像输出一样渲染？

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/29598885/ef25f847-e6c6-4b3b-8a09-f753fdda8672)

**Comment by binary-husky** [comment]
麻烦提供下复现步骤和prompt？

**Comment by M1saka10010** [comment]
> 
不需要步骤，就只要在markdown的代码块里面放html代码就能复现。不过其实加不加markdown的代码标记没啥区别就是了，直接丢html代码也是一样的效果
