### ISSUE TITLE
[Bug]:  openai的账号已经扣费了，但还是用不了gpt4.

### ISSUE THREAD

**Issue by panxiang126** [binary-husky/gpt_academic#962]
### Installation Method | 安装方法与平台

Docker（Linux）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Linux

### Describe the bug | 简述

调用gpt-4模型时提示没有体验资格。
`[Local Message] Model gpt-4 does not exist. 模型不存在, 或者您没有获得体验资格.`

我的openAI账号7月1号已经扣过费了。
![image](https://github.com/binary-husky/gpt_academic/assets/68883727/1d42841d-ef91-44e0-9bde-73c23832aef9)

openAI不是说，7月6日向所有有成功支付历史的API用户提供了GPT-4 API的访问权限嘛。
![image](https://github.com/binary-husky/gpt_academic/assets/68883727/e6315e2c-5ea2-414a-a369-d3cbfeed0a40)

有没有遇到同样问题的小伙伴。

### Screen Shot | 有帮助的截图

...

### Terminal Traceback & Material to Help Reproduce Bugs | 终端traceback（如有） + 帮助我们复现的测试材料样本（如有）

...

**Comment by hpub** [comment]
记得是要扣费满一美元
