### ISSUE TITLE
能够弹出最终界面，配置和Key都没问题，但是输入对话时出现了错误

### ISSUE THREAD

**Issue by xhlin1230** [binary-husky/gpt_academic#969]
### Installation Method | 安装方法与平台

Docker（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

安装已经完成，也能正常弹出学术优化界面，但是输入内容后弹出报错：（请求帮助）
Traceback (most recent call last):
  File ".\request_llm\bridge_chatgpt.py", line 191, in predict
    if ('data: [DONE]' in chunk_decoded) or (len(json.loads(chunk_decoded[6:])['choices'][0]["delta"]) == 0):
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chat\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chat\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\chat\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Screen Shot | 有帮助的截图

![报错](https://github.com/binary-husky/gpt_academic/assets/139568981/b9f9a42f-3f4b-4fc7-a6ec-11f77e2ae04c)

**Comment by binary-husky** [comment]
截图不完整

**Comment by fancl117** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/135203044/bc7eb788-f878-4327-93d2-0421db3e2121)
国内的转发key，可以用的哦
