### ISSUE TITLE
[Feature]: 能否利用freegpt-webui搭建的服务器进行GPT对话？

### ISSUE THREAD

**Issue by pangafu** [binary-husky/gpt_academic#970]
### Class | 类型

大语言模型

### Feature Request | 功能请求

GITHUB地址
https://github.com/ramonvc/freegpt-webui

作者提供了三个freegpt-webui的chat地址：
https://freegpt-webui.ramonvc.repl.co/chat/
https://huggingface.co/spaces/monra/freegpt-webui
https://freegpt-webui-chimera.ramonvc.repl.co/chat/

经过测试，该项目的GPT-3.5比其他的freegpt项目稍微稳定点，而且不需要任何key的设置
此项目的GPT-4问题比较多，不推荐

**Comment by binary-husky** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/96192199/9775030d-db51-4032-bf55-2af43e349d3e)

测试不行呀

**Comment by binary-husky** [comment]
另外GPT4Free测试也不行，全是 requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

GPT4Free还活着吗，还是因为我代理网络的问题？

**Comment by pangafu** [comment]
GPT-3.5-turbo-16k-0613比较好
GPT-4问题比较多，不推荐

![image](https://github.com/binary-husky/gpt_academic/assets/10149168/764b6e36-6f24-4058-9ad3-947fde4eb0f2)

**Comment by pangafu** [comment]
用这两个地址测试
https://freegpt-webui.ramonvc.repl.co/chat/
https://huggingface.co/spaces/monra/freegpt-webui

最后一个chat服务器属于开发版本，不稳定

**Comment by binary-husky** [comment]
太不稳定了😂
