### ISSUE TITLE
[Bug]: 突然冒出其他人的文档，有一定隐私风险

### ISSUE THREAD

**Issue by tongyx361** [binary-husky/gpt_academic#973]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Docker

### Describe the bug | 简述

突然冒出其他人的文档，即下图中的 [gpt_log/2023-07-20-04-48-53-chatgpt.polish.md](https://academic.chatwithpaper.org/file=/gpt/gpt_log/2023-07-20-04-48-53-chatgpt.polish.md)

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/98524878/39133e91-8f9b-4a70-bb6c-417778305375)

**Comment by binary-husky** [comment]
多人使用请对本项目模块进行裁剪，从而确保安全

**Comment by tongyx361** [comment]
> 多人使用请对本项目模块进行裁剪，从而确保安全

只有我一个人在使用，冒出的文档是我完全不认识的人的文档
