### ISSUE TITLE
[Feature]: 如果只用chatgpt3.5加组件的功能，最低配置是多少GPU、CPU、内存，请给个参考方便购买机器设备。

### ISSUE THREAD

**Issue by maolilai** [binary-husky/gpt_academic#975]
### Class | 类型

None

### Feature Request | 功能请求

[Feature]: 如果只用chatgpt3.5加组件的功能，最低配置是多少GPU、CPU、内存，请给个参考方便购买机器设备。

**Comment by M1saka10010** [comment]
内存大概300M左右（不包latex），cpu别太烂就行了。gpu不需要

**Comment by maolilai** [comment]
收到，谢谢大佬
