### ISSUE TITLE
[Bug]: 代理配置成功，代理所在地查询超时，代理可能无效

### ISSUE THREAD

**Issue by CHONGANDXU** [binary-husky/gpt_academic#978]
### Installation Method | 安装方法与平台

Docker（Windows/Mac）

### Version | 版本

Latest | 最新版

### OS | 操作系统

Mac

### Describe the bug | 简述

按照要求修改代理配置文件`config.py`，基于`Dockerfile`构建之后运行出现，`代理配置成功，代理所在地查询超时，代理可能无效`的警告⚠️，实际运行报错`ConnectionRefusedError: [Errno 111] Connection refused`，请帮帮我哪里配置可能有误
ps.代理服务地址端口配置正确，且运行正常，可以访问外网

### Screen Shot | 有帮助的截图

<img width="921" alt="截屏2023-07-21 21 12 53" src="https://github.com/binary-husky/gpt_academic/assets/97352201/5f54b0b4-a515-4ae6-8360-1b1504683688">

**Comment by binary-husky** [comment]
mac/windows的docker网络配置问题，配置文件的代理地址不能是本地地址，而应该是宿主的ip地址

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/issues/874

**Comment by CHONGANDXU** [comment]
我尝试使用
`docker run --rm -it -e WEB_PORT=50923 -p 127.0.0.1:50923:50923 gpt-academic`
将docker中的端口映射后本地相同端口后，
并且将`config.py`中的`USE_PROXY`变量重新更改为 False ，
尽管 check_proxy 函数检测不到代理，但是本机可以通过 cl**h 走全局代理

**Comment by cisan86** [comment]
good

> mac/windows的docker网络配置问题，配置文件的代理地址不能是本地地址，而应该是宿主的ip地址
