### ISSUE TITLE
[Feature]: 请求说一下如何卸载cpu版本的torch，如何安装gpu版本的torch+cuda

### ISSUE THREAD

**Issue by abel0325** [binary-husky/gpt_academic#984]
### Class | 类型

None

### Feature Request | 功能请求

小白跟着把前面的都弄好了，网上看了一天教程，最后这两个实在是不会，chatglm非常慢，感谢了，4090显卡，

**Comment by abel0325** [comment]
查了issues，已经把配置文件里cpu改成cuda了，仍然无法正常运行报错
  File "D:\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "D:\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
                                 ^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "G:\new\gpt_academic\request_llm\bridge_chatglm.py", line 57, in run
    raise RuntimeError("不能正常加载ChatGLM的参数！")
RuntimeError: 不能正常加载ChatGLM的参数！

应该是没安装cuda和torch的缘故吧。

**Comment by binary-husky** [comment]
如果真的是新手，还是建议用Linux + docker吧，一行代码搞定的事；

有一定的python使用经验可以用Anaconda

**Comment by abel0325** [comment]
感谢回复，电脑没有linux，不了解docker，以后再说这个吧，目前把cuda安装并且添加环境变量了，再安装个pytorch并且添加到环境变量应该就行了。

> 如果真的是新手，还是建议用Linux + docker吧，一行代码搞定的事；
> 
> 有一定的python使用经验可以用Anaconda

**Comment by Wenzhi-Ding** [comment]
安装 PyTorch 的 CUDA 版本参照这个页面：

https://pytorch.org/get-started/locally/

比如你是 Windows 系统加 Anaconda 环境，在命令行运行官网给出的指令即可：

```bash
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```

然后务必安装与 PyTorch 版本所匹配的 CUDA，比如目前（2023年7月）可以用 CUDA 11.8。在搜索引擎搜 CUDA 11.8 Toolkit，就可以找到官方的下载页面。千万不要盲目安装最新版本的 CUDA。

https://developer.nvidia.com/cuda-11-8-0-download-archive

然后把 gpt_academic 目录下的 `config.py` 中的 CPU 参数换成 CUDA 即可。

**Comment by abel0325** [comment]
> 安装 PyTorch 的 CUDA 版本参照这个页面：
> 
> https://pytorch.org/get-started/locally/
> 
> 比如你是 Windows 系统加 Anaconda 环境，在命令行运行官网给出的指令即可：
> 
> ```shell
> conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
> ```
> 
> 然后务必安装与 PyTorch 版本所匹配的 CUDA，比如目前（2023年7月）可以用 CUDA 11.8。在搜索引擎搜 CUDA 11.8 Toolkit，就可以找到官方的下载页面。千万不要盲目安装最新版本的 CUDA。
> 
> https://developer.nvidia.com/cuda-11-8-0-download-archive
> 
> 然后把 gpt_academic 目录下的 `config.py` 中的 CPU 参数换成 CUDA 即可。

感谢，错误可能跟我12.2版本的cuda有关。

**Comment by abel0325** [comment]
我决定重新部署一遍

**Comment by abel0325** [comment]
重装之后，完全解决了之前的问题，驱动程序是12.2版本的，cuda工具包11.8和12.2版本都试了，都可以正常工作。装完后感觉整个人空虚了，装之前不懂annaconda，miniconda，python之间的关系，也不懂pytorch到底怎么装，怎么卸载，会想cuda是不是应该装在anaconda里面这样的问题，很开心自己终于成功部署了第一个项目，最早的时候部署stablediffusion失败，后来部署roop插件失败，导致重装电脑，一直在用大神的整合包，这次终于从github上成功部署了第一个项目，纪念。
