### ISSUE TITLE
[Bug]:  ArXiv Latex一键翻译（输入arXiv ID）一直在对论文进行精细分割，等了两个小时还是在分割

### ISSUE THREAD

**Issue by hanhantie233** [binary-husky/gpt_academic#988]
### Installation Method | 安装方法与平台

Please choose | 请选择

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

为啥啊？

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/130548715/c399ebf3-30d9-4caa-820d-a3a5a0fbe451)

**Comment by binary-husky** [comment]
多少页？arxiv ID？

**Comment by hanhantie233** [comment]
> 多少页？arxiv ID？

18页，2101.09833

**Comment by binary-husky** [comment]
谢谢 查出来一个正则表达式有效率问题 待会修复

**Comment by binary-husky** [comment]
https://github.com/binary-husky/gpt_academic/commit/56bb8b6498c1c9481d54f2e37ecd21c4498226a3

**Comment by binary-husky** [comment]
翻译后的论文

https://ageasga-my.sharepoint.com/:b:/g/personal/fuqingxu_yiteam_tech/EYLE8mAcgbhMq5PVFVSSq0gBP1pz_zjAQmbygN1HLgNkmw?e=femFPt

**Comment by binary-husky** [comment]
```
https://ageasga-my.sharepoint.com/:b:/g/personal/fuqingxu_yiteam_tech/EYLE8mAcgbhMq5PVFVSSq0gBP1pz_zjAQmbygN1HLgNkmw?e=femFPt
```

**Comment by hanhantie233** [comment]
> 谢谢 查出来一个正则表达式有效率问题 待会修复

大佬，牛

**Comment by maolilai** [comment]
binary-husky大佬，我这边 提示 ： 找不到任何.tex文件: private_upload/2023-07-24-19-34-37

是什么错误呢？ 
![image](https://github.com/binary-husky/gpt_academic/assets/61673882/87250db6-f82b-4ea5-9c92-f73f1bda00cd)

**Comment by maolilai** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/61673882/12844bd4-5bc8-43cf-9fa3-e6d75816c3f2)
我的是本地安装的，是这个原因吗

**Comment by hanhantie233** [comment]
> 谢谢 查出来一个正则表达式有效率问题 待会修复

更新完能正常用这个插件吗？
为啥我这一直显示tarfile.py打不开啊？
![image](https://github.com/binary-husky/gpt_academic/assets/130548715/80d6ebb1-f36d-4917-86be-45a8987d98e9)
![image](https://github.com/binary-husky/gpt_academic/assets/130548715/b3050660-2215-4576-8d5c-a469f9526fab)

**Comment by binary-husky** [comment]
id填错地方啦，填输入区@maililai

**Comment by maolilai** [comment]
![image](https://github.com/binary-husky/gpt_academic/assets/61673882/4d2be121-1378-4ce6-96dc-96b112b451fc)
输入id 是这个错误，[binary]能帮忙看看吗？ 感觉是环境路径问题， 但是path也加上了

**Comment by maolilai** [comment]
PATH=/usr/local/texlive/2023/bin/x86_64-linux:$PATH 这种加上了

**Comment by hanhantie233** [comment]
> ![image](https://user-images.githubusercontent.com/61673882/255621272-4d2be121-1378-4ce6-96dc-96b112b451fc.png) 输入id 是这个错误，[binary]能帮忙看看吗？ 感觉是环境路径问题， 但是path也加上了

这个我刚也遇见了，应该是下载的压缩包损坏了，把这个id的下载文件删掉重新下，然后我的解决了

**Comment by maolilai** [comment]
确实是下载的tar文件坏了，我删掉后还是不行，不知道哪里出问题了

**Comment by binary-husky** [comment]
> PATH=/usr/local/texlive/2023/bin/x86_64-linux:$PATH 这种加上了

Linux吗，Linux请直接选择docker-compose方案四
