### ISSUE TITLE
[Feature]: 是否支持不同LLM同时输出结果？

### ISSUE THREAD

**Issue by Gy-Hu-Star** [binary-husky/gpt_academic#989]
### Class | 类型

大语言模型

### Feature Request | 功能请求

你好，请问是否支持多语言模型同时输出结果，并且可以方便对比同一个文档/问题 输出回应的不同？

**Comment by binary-husky** [comment]
支持

https://github.com/binary-husky/gpt_academic/blob/master/crazy_functions/%E8%AF%A2%E9%97%AE%E5%A4%9A%E4%B8%AA%E5%A4%A7%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B.py

**Comment by Gy-Hu-Star** [comment]
谢谢，请问这个要在界面上哪里开启呢？

**Comment by binary-husky** [comment]
下拉菜单
