### ISSUE TITLE
[Feature]: 允许指定基础功能是否发送历史消息

### ISSUE THREAD

**Issue by awwaawwa** [binary-husky/gpt_academic#997]
### Class | 类型

程序主体

### Feature Request | 功能请求

在某些情况下，例如在总结一段文本或解释某段代码时，发送历史消息可能会降低LLM的回复质量，并且还会大幅增加按量计费的花销。对于那些不依赖于历史消息记录的功能，可以选择不发送历史信息，以提高回答质量并降低开销。

**Comment by binary-husky** [comment]
好的！

**Comment by binary-husky** [comment]
做了若干修改

请您测试https://github.com/binary-husky/gpt_academic/tree/enable_clear_history_option这个子分支实现的功能是否和您的建议一致



![image](https://github.com/binary-husky/gpt_academic/assets/96192199/7f9ca42e-d045-49e6-81e4-0f8ec98fe2d2)

**Comment by awwaawwa** [comment]
清空历史后前端仍然可见之前的历史，有无必要加入提示提醒用户？

**Comment by awwaawwa** [comment]
比如这样

```python
def handle_core_functionality(additional_fn, inputs, history, chatbot=None):
    import core_functional
    importlib.reload(core_functional)    # 热更新prompt
    core_functional = core_functional.get_core_functions()
    if "PreProcess" in core_functional[additional_fn]: inputs = core_functional[additional_fn]["PreProcess"](inputs)  # 获取预处理函数（如果有的话）
    inputs = core_functional[additional_fn]["Prefix"] + inputs + core_functional[additional_fn]["Suffix"]
    if core_functional[additional_fn].get("AutoClearHistory", False):
        history = []
        chatbot.append(('本次是否包含历史消息？', "[Local Message] 已清空所有历史消息."))
    return inputs, history
```

`inputs, history = handle_core_functionality(additional_fn, inputs, history, chatbot)`

**Comment by binary-husky** [comment]
功能已经merge到主分支 https://github.com/binary-husky/gpt_academic/commit/109afcf8f6c939cb00159e04ad1ae5f4f719104c
